.*: Assembler messages:
.*:9: Error: unexpected register name `r2' in instruction `if r1>r2'
.*:9: Error: unrecognized instruction `if r1>r2 gotol\+1'
.*:9: Error: expected white space, got 'l\+1'
.*:10: Error: unrecognized instruction `if r1&5 gotol-1'
.*:10: Error: expected white space, got 'l-1'
.*:11: Error: unexpected register name `w2' in instruction `if w1==w2'
.*:11: Error: unrecognized instruction `if w1==w2 gotol\+1'
.*:11: Error: expected white space, got 'l\+1'
