# Copyright 2024-2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require allow_python_tests
require {!is_remote host}

save_vars { env(PYTHONHOME) } {
    setenv PYTHONHOME foo
    clean_restart
}

gdb_test "python print (1)" \
    "Python not initialized"

set output_seen 0
gdb_test_multiple "quit" "" {
    -re ^quit\r\n {
	exp_continue
    }
    eof {
	set output_seen [expr [string length $expect_out(buffer)] != 0]
	pass $gdb_test_name
    }
}
gdb_assert {!$output_seen} "no output after quit"
