/* This file is automatically generated by i386-gen.  Do not edit!  */
/* Copyright (C) 2007-2026 Free Software Foundation, Inc.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

static const char i386_mnemonics[];

#define MN_ud0 0x1
#define MN_prefetcht0 0x5
#define MN_prefetchit0 0x10
#define MN_t2rpntlvwz0 0x1c
#define MN_xsha1 0x28
#define MN_fld1 0x2e
#define MN_ud1 0x33
#define MN_sha1msg1 0x37
#define MN_vsha512msg1 0x40
#define MN_vsm3msg1 0x4c
#define MN_sha256msg1 0x55
#define MN_fprem1 0x60
#define MN_f2xm1 0x67
#define MN_fyl2xp1 0x6d
#define MN_t2rpntlvwz0t1 0x75
#define MN_t2rpntlvwz1t1 0x83
#define MN_tileloaddt1 0x91
#define MN_prefetcht1 0x9d
#define MN_prefetchit1 0xa8
#define MN_pfrcpit1 0xb4
#define MN_pfrsqit1 0xbd
#define MN_int1 0xc6
#define MN_t2rpntlvwz0rst1 0xcb
#define MN_t2rpntlvwz1rst1 0xdb
#define MN_tileloaddrst1 0xeb
#define MN_prefetchwt1 0xf9
#define MN_t2rpntlvwz1 0x105
#define MN_xsha512 0x111
#define MN_vmovdqa32 0x119
#define MN_data32 0x123
#define MN_crc32 0x12a
#define MN_endbr32 0x130
#define MN_addr32 0x138
#define MN_vmovdqu32 0x13f
#define MN_ud2 0x149
#define MN_fldlg2 0x14d
#define MN_xrng2 0x154
#define MN_sha1msg2 0x15a
#define MN_vsha512msg2 0x163
#define MN_vsm3msg2 0x16f
#define MN_sha256msg2 0x178
#define MN_push2 0x183
#define MN_montmul2 0x189
#define MN_sm2 0x192
#define MN_fldln2 0x196
#define MN_pop2 0x19d
#define MN_vsha512rnds2 0x1a2
#define MN_vsm3rnds2 0x1af
#define MN_sha256rnds2 0x1b9
#define MN_prefetcht2 0x1c5
#define MN_pfrcpit2 0x1d0
#define MN_prefetchrst2 0x1d9
#define MN_vbroadcastf32x2 0x1e6
#define MN_vbroadcasti32x2 0x1f6
#define MN_vshuff64x2 0x206
#define MN_vextractf64x2 0x211
#define MN_vinsertf64x2 0x21f
#define MN_vbroadcastf64x2 0x22c
#define MN_vshufi64x2 0x23c
#define MN_vextracti64x2 0x247
#define MN_vinserti64x2 0x255
#define MN_vbroadcasti64x2 0x262
#define MN_sm3 0x272
#define MN_int3 0x276
#define MN_vmovdqa64 0x27b
#define MN_xsavec64 0x285
#define MN_xsave64 (MN_fxsave64 + 1)
#define MN_fxsave64 0x28e
#define MN_endbr64 0x297
#define MN_xrstor64 (MN_fxrstor64 + 1)
#define MN_fxrstor64 0x29f
#define MN_xsaves64 0x2a9
#define MN_xrstors64 0x2b2
#define MN_xsaveopt64 0x2bc
#define MN_vmovdqu64 0x2c7
#define MN_rex64 0x2d1
#define MN_xsha384 0x2d7
#define MN_sm4 0x2df
#define MN_sha1rnds4 0x2e3
#define MN_vsm4rnds4 0x2ed
#define MN_vshuff32x4 0x2f7
#define MN_vextractf32x4 0x302
#define MN_vinsertf32x4 0x310
#define MN_vbroadcastf32x4 0x31d
#define MN_vshufi32x4 0x32d
#define MN_vextracti32x4 0x338
#define MN_vinserti32x4 0x346
#define MN_vbroadcasti32x4 0x353
#define MN_vextractf64x4 0x363
#define MN_vinsertf64x4 0x371
#define MN_vbroadcastf64x4 0x37e
#define MN_vextracti64x4 0x38e
#define MN_vinserti64x4 0x39c
#define MN_vbroadcasti64x4 0x3a9
#define MN_vsm4key4 0x3b9
#define MN_data16 0x3c2
#define MN_vfmsub231bf16 0x3c9
#define MN_vfnmsub231bf16 0x3d7
#define MN_vfmadd231bf16 0x3e6
#define MN_vfnmadd231bf16 0x3f4
#define MN_vfmsub132bf16 0x403
#define MN_vfnmsub132bf16 0x411
#define MN_vfmadd132bf16 0x420
#define MN_vfnmadd132bf16 0x42e
#define MN_vcvtne2ps2bf16 0x43d
#define MN_vcvtneps2bf16 0x44c
#define MN_vfmsub213bf16 0x45a
#define MN_vfnmsub213bf16 0x468
#define MN_vfmadd213bf16 0x477
#define MN_vfnmadd213bf16 0x485
#define MN_vsubbf16 0x494
#define MN_vaddbf16 0x49d
#define MN_vreducebf16 0x4a6
#define MN_vrndscalebf16 0x4b2
#define MN_vscalefbf16 0x4c0
#define MN_vmulbf16 0x4cc
#define MN_vminbf16 0x4d5
#define MN_vrcpbf16 0x4de
#define MN_vcmpbf16 0x4e7
#define MN_vgetexpbf16 0x4f0
#define MN_vcomisbf16 0x4fc
#define MN_vfpclassbf16 0x507
#define MN_vgetmantbf16 0x514
#define MN_vrsqrtbf16 0x521
#define MN_vsqrtbf16 0x52c
#define MN_vdivbf16 0x536
#define MN_vminmaxbf16 0x53f
#define MN_vmaxbf16 0x54b
#define MN_tconjtfp16 0x554
#define MN_addr16 0x55f
#define MN_vmovdqu16 0x566
#define MN_vbmacor16x16x16 0x570
#define MN_vbmacxor16x16x16 0x580
#define MN_xsha256 0x591
#define MN_encodekey256 0x599
#define MN_vperm2f128 0x5a6
#define MN_vextractf128 0x5b1
#define MN_vinsertf128 0x5be
#define MN_vbroadcastf128 0x5ca
#define MN_vperm2i128 0x5d9
#define MN_vextracti128 0x5e4
#define MN_vinserti128 0x5f1
#define MN_vbroadcasti128 0x5fd
#define MN_encodekey128 0x60c
#define MN_vcvt2ph2bf8 0x619
#define MN_vcvtbiasph2bf8 0x625
#define MN_vcvtph2bf8 0x634
#define MN_vcvtbiasps2bf8 0x63f
#define MN_vcvtps2bf8 0x64e
#define MN_vcvtbf42hf8 0x659
#define MN_vcvtbf62hf8 0x665
#define MN_vcvthf62hf8 0x671
#define MN_vcvt2ph2hf8 0x67d
#define MN_vcvtbiasph2hf8 0x689
#define MN_vcvtph2hf8 0x698
#define MN_vcvtrops2hf8 0x6a3
#define MN_vcvtbiasps2hf8 0x6b0
#define MN_vcvtps2hf8 0x6bf
#define MN_vmovdqu8 0x6ca
#define MN_vextractf32x8 0x6d3
#define MN_vinsertf32x8 0x6e1
#define MN_vbroadcastf32x8 0x6ee
#define MN_vextracti32x8 0x6fe
#define MN_vinserti32x8 0x70c
#define MN_vbroadcasti32x8 0x719
#define MN_ud2a 0x729
#define MN_aaa 0x72e
#define MN_daa 0x732
#define MN_ssca 0x736
#define MN_lea 0x73b
#define MN_invlpga 0x73f
#define MN_pusha 0x747
#define MN_ja 0x74d
#define MN_jna 0x750
#define MN_ccmpna 0x754
#define MN_setna 0x75b
#define MN_ctestna 0x761
#define MN_setzuna 0x769
#define MN_cmovna (MN_fcmovna + 1)
#define MN_fcmovna (MN_cfcmovna + 1)
#define MN_cfcmovna 0x771
#define MN_ccmpa 0x77a
#define MN_popa 0x780
#define MN_movntdqa (MN_vmovntdqa + 1)
#define MN_vmovntdqa 0x785
#define MN_movdqa (MN_vmovdqa + 1)
#define MN_vmovdqa 0x78f
#define MN_seta 0x797
#define MN_prefetchnta 0x79c
#define MN_ctesta 0x7a8
#define MN_setzua 0x7af
#define MN_cmova (MN_fcmova + 1)
#define MN_fcmova (MN_cfcmova + 1)
#define MN_cfcmova 0x7b6
#define MN_rex_b 0x7be
#define MN_ud2b 0x7c4
#define MN_vpermi2b 0x7c9
#define MN_vpmovm2b 0x7d2
#define MN_vpermt2b 0x7db
#define MN_movdir64b 0x7e4
#define MN_cmpxchg16b 0x7ee
#define MN_cmpxchg8b 0x7f9
#define MN_vpshab 0x803
#define MN_sbb 0x80a
#define MN_psubb (MN_vpsubb + 1)
#define MN_vpsubb 0x80e
#define MN_xcrypt_ecb 0x815
#define MN_xcryptecb 0x820
#define MN_llwpcb 0x82a
#define MN_slwpcb 0x831
#define MN_kaddb 0x838
#define MN_paddb (MN_vpaddb + 1)
#define MN_vpaddb 0x83e
#define MN_kandb 0x845
#define MN_vpexpandb 0x84b
#define MN_vpmovssdb 0x855
#define MN_vpmovusdb 0x85f
#define MN_vpmovsdb 0x869
#define MN_udb 0x872
#define MN_vpmovdb 0x876
#define MN_vpcomgeb 0x87e
#define MN_vpcomleb 0x887
#define MN_vpcmpnleb 0x890
#define MN_vpcmpleb 0x89a
#define MN_vpcomfalseb 0x8a3
#define MN_vpcomtrueb 0x8af
#define MN_xcrypt_cfb 0x8ba
#define MN_xcryptcfb 0x8c5
#define MN_xcrypt_ofb 0x8cf
#define MN_xcryptofb 0x8da
#define MN_pshufb (MN_vpshufb + 1)
#define MN_vpshufb 0x8e4
#define MN_invlpgb 0x8ec
#define MN_pavgb (MN_vpavgb + 1)
#define MN_vpavgb 0x8f4
#define MN_jb 0x8fb
#define MN_vunpackb 0x8fe
#define MN_pbndkb 0x907
#define MN_pmovmskb (MN_vpmovmskb + 1)
#define MN_vpmovmskb 0x90e
#define MN_vpshlb 0x918
#define MN_kshiftlb 0x91f
#define MN_gf2p8mulb (MN_vgf2p8mulb + 1)
#define MN_vgf2p8mulb 0x928
#define MN_vpblendmb 0x933
#define MN_vptestnmb 0x93d
#define MN_vpcomb 0x947
#define MN_vpshufbitqmb 0x94e
#define MN_vpermb 0x95b
#define MN_vptestmb 0x962
#define MN_kandnb 0x96b
#define MN_psignb (MN_vpsignb + 1)
#define MN_vpsignb 0x972
#define MN_jnb 0x97a
#define MN_ccmpnb 0x97e
#define MN_setnb 0x985
#define MN_ctestnb 0x98b
#define MN_setzunb 0x993
#define MN_cmovnb (MN_fcmovnb + 1)
#define MN_fcmovnb (MN_cfcmovnb + 1)
#define MN_cfcmovnb 0x99b
#define MN_ccmpb 0x9a4
#define MN_vpcmpb 0x9aa
#define MN_vpcomeqb 0x9b1
#define MN_gf2p8affineqb (MN_vgf2p8affineqb + 1)
#define MN_vgf2p8affineqb 0x9ba
#define MN_vpcomneqb 0x9c9
#define MN_vpcmpneqb 0x9d3
#define MN_pcmpeqb (MN_vpcmpeqb + 1)
#define MN_vpcmpeqb 0x9dd
#define MN_vpmovusqb 0x9e6
#define MN_vpmovsqb 0x9f0
#define MN_vpmultishiftqb 0x9f9
#define MN_gf2p8affineinvqb (MN_vgf2p8affineinvqb + 1)
#define MN_vgf2p8affineinvqb 0xa08
#define MN_vpmovqb 0xa1a
#define MN_rex_rb 0xa22
#define MN_korb 0xa29
#define MN_kxnorb 0xa2e
#define MN_kxorb 0xa35
#define MN_pinsrb (MN_vpinsrb + 1)
#define MN_vpinsrb 0xa3b
#define MN_kshiftrb 0xa43
#define MN_pextrb (MN_vpextrb + 1)
#define MN_vpextrb 0xa4c
#define MN_rex_wrb 0xa54
#define MN_pabsb (MN_vpabsb + 1)
#define MN_vpabsb 0xa5c
#define MN_psubsb (MN_vpsubsb + 1)
#define MN_vpsubsb 0xa63
#define MN_paddsb (MN_vpaddsb + 1)
#define MN_vpaddsb 0xa6b
#define MN_pminsb (MN_vpminsb + 1)
#define MN_vpminsb 0xa73
#define MN_vmovrsb 0xa7b
#define MN_vpcompressb 0xa83
#define MN_psubusb (MN_vpsubusb + 1)
#define MN_vpsubusb 0xa8f
#define MN_paddusb (MN_vpaddusb + 1)
#define MN_vpaddusb 0xa98
#define MN_pavgusb 0xaa1
#define MN_movsb 0xaa9
#define MN_pmaxsb (MN_vpmaxsb + 1)
#define MN_vpmaxsb 0xaaf
#define MN_setb 0xab7
#define MN_vpcomgtb 0xabc
#define MN_pcmpgtb (MN_vpcmpgtb + 1)
#define MN_vpcmpgtb 0xac5
#define MN_vpcomltb 0xace
#define MN_vpcmpnltb 0xad7
#define MN_vpcmpltb 0xae1
#define MN_vpopcntb 0xaea
#define MN_knotb 0xaf3
#define MN_vprotb 0xaf9
#define MN_vpbroadcastb 0xb00
#define MN_ctestb 0xb0d
#define MN_ktestb 0xb14
#define MN_kortestb 0xb1b
#define MN_vpcomgeub 0xb24
#define MN_vpcomleub 0xb2e
#define MN_vpcmpnleub 0xb38
#define MN_vpcmpleub 0xb43
#define MN_vpcomfalseub 0xb4d
#define MN_vpcomtrueub 0xb5a
#define MN_vpcomub 0xb66
#define MN_pminub (MN_vpminub + 1)
#define MN_vpminub 0xb6e
#define MN_vpcmpub 0xb76
#define MN_vpcomequb 0xb7e
#define MN_vpcomnequb 0xb88
#define MN_vpcmpnequb 0xb93
#define MN_vpcmpequb 0xb9e
#define MN_sub (MN_fsub + 1)
#define MN_fsub (MN_pfsub + 1)
#define MN_pfsub 0xba8
#define MN_fisub 0xbae
#define MN_vpcomgtub 0xbb4
#define MN_vpcomltub 0xbbe
#define MN_vpcmpnltub 0xbc8
#define MN_vpcmpltub 0xbd3
#define MN_pmaxub (MN_vpmaxub + 1)
#define MN_vpmaxub 0xbdd
#define MN_setzub 0xbe5
#define MN_pblendvb (MN_vpblendvb + 1)
#define MN_vpblendvb 0xbec
#define MN_vbitrevb 0xbf6
#define MN_cmovb (MN_fcmovb + 1)
#define MN_fcmovb (MN_cfcmovb + 1)
#define MN_cfcmovb 0xbff
#define MN_kmovb 0xc07
#define MN_rex_wb 0xc0d
#define MN_clwb 0xc14
#define MN_packsswb (MN_vpacksswb + 1)
#define MN_vpacksswb 0xc19
#define MN_packuswb (MN_vpackuswb + 1)
#define MN_vpackuswb 0xc23
#define MN_vpmovuswb 0xc2d
#define MN_vpmovswb 0xc37
#define MN_vpmovwb 0xc40
#define MN_rex_xb 0xc48
#define MN_rex_rxb 0xc4f
#define MN_rex_wrxb 0xc57
#define MN_rex_wxb 0xc60
#define MN_movzb 0xc68
#define MN_clac 0xc6e
#define MN_stac 0xc73
#define MN_xcrypt_cbc 0xc78
#define MN_xcryptcbc 0xc83
#define MN_pfacc 0xc8d
#define MN_pfnacc 0xc93
#define MN_pfpnacc 0xc9a
#define MN_adc 0xca2
#define MN_dec (MN_aesdec + 3)
#define MN_aesdec (MN_vaesdec + 1)
#define MN_vaesdec 0xca6
#define MN_getsec 0xcae
#define MN_xsavec 0xcb5
#define MN_blcic 0xcbc
#define MN_blsic 0xcc2
#define MN_jc 0xcc8
#define MN_t1mskc 0xccb
#define MN_salc 0xcd2
#define MN_clc 0xcd7
#define MN_cmc 0xcdb
#define MN_aesimc (MN_vaesimc + 1)
#define MN_vaesimc 0xcdf
#define MN_rdpmc 0xce7
#define MN_aesenc (MN_vaesenc + 1)
#define MN_vaesenc 0xced
#define MN_inc 0xcf5
#define MN_jnc 0xcf9
#define MN_ccmpnc 0xcfd
#define MN_setnc 0xd04
#define MN_ctestnc 0xd0a
#define MN_vmfunc 0xd12
#define MN_setzunc 0xd19
#define MN_cmovnc (MN_cfcmovnc + 2)
#define MN_cfcmovnc 0xd21
#define MN_tlbsync 0xd2a
#define MN_ccmpc 0xd32
#define MN_rdtsc 0xd38
#define MN_btc 0xd3e
#define MN_setc 0xd42
#define MN_stc (MN_ctestc + 3)
#define MN_ctestc 0xd47
#define MN_setzuc 0xd4e
#define MN_cmovc (MN_cfcmovc + 2)
#define MN_cfcmovc 0xd55
#define MN_vpermi2d 0xd5d
#define MN_vpmovm2d 0xd66
#define MN_vpermt2d 0xd6f
#define MN_vpbroadcastmw2d 0xd78
#define MN_aad 0xd88
#define MN_vmread 0xd8c
#define MN_rmpread 0xd93
#define MN_vpshad 0xd9b
#define MN_vmload 0xda2
#define MN_psrad (MN_vpsrad + 1)
#define MN_vpsrad 0xda9
#define MN_vphaddbd 0xdb0
#define MN_vphaddubd 0xdb9
#define MN_phsubd (MN_vphsubd + 1)
#define MN_vphsubd 0xdc3
#define MN_psubd (MN_vpsubd + 1)
#define MN_vpsubd 0xdcb
#define MN_pmovsxbd (MN_vpmovsxbd + 1)
#define MN_vpmovsxbd 0xdd2
#define MN_pmovzxbd (MN_vpmovzxbd + 1)
#define MN_vpmovzxbd 0xddc
#define MN_add (MN_aadd + 1)
#define MN_aadd 0xde6
#define MN_fadd (MN_pfadd + 1)
#define MN_pfadd 0xdeb
#define MN_fiadd 0xdf1
#define MN_tileloadd 0xdf7
#define MN_xadd (MN_cmpnaxadd + 5)
#define MN_cmpnaxadd 0xe01
#define MN_cmpaxadd 0xe0b
#define MN_cmpnbxadd 0xe14
#define MN_cmpbxadd 0xe1e
#define MN_cmpncxadd 0xe27
#define MN_cmpcxadd 0xe31
#define MN_cmpnaexadd 0xe3a
#define MN_cmpaexadd 0xe45
#define MN_cmpnbexadd 0xe4f
#define MN_cmpbexadd 0xe5a
#define MN_cmpngexadd 0xe64
#define MN_cmpgexadd 0xe6f
#define MN_cmpnlexadd 0xe79
#define MN_cmplexadd 0xe84
#define MN_cmpnexadd 0xe8e
#define MN_cmpexadd 0xe98
#define MN_cmppexadd 0xea1
#define MN_cmpngxadd 0xeab
#define MN_cmpgxadd 0xeb5
#define MN_cmpnlxadd 0xebe
#define MN_cmplxadd 0xec8
#define MN_cmpnoxadd 0xed1
#define MN_cmpoxadd 0xedb
#define MN_cmppoxadd 0xee4
#define MN_cmpnpxadd 0xeee
#define MN_cmppxadd 0xef8
#define MN_cmpnsxadd 0xf01
#define MN_cmpsxadd 0xf0b
#define MN_cmpnzxadd 0xf14
#define MN_cmpzxadd 0xf1e
#define MN_phaddd (MN_vphaddd + 1)
#define MN_vphaddd 0xf27
#define MN_kaddd 0xf2f
#define MN_paddd (MN_vpaddd + 1)
#define MN_vpaddd 0xf35
#define MN_vpshldd 0xf3c
#define MN_kandd 0xf44
#define MN_vpandd 0xf4a
#define MN_vpexpandd 0xf51
#define MN_vpblendd 0xf5b
#define MN_vpgatherdd 0xf64
#define MN_vpscatterdd 0xf6f
#define MN_vpshrdd 0xf7b
#define MN_vpmacsdd 0xf83
#define MN_vpmacssdd 0xf8c
#define MN_rdseed 0xf96
#define MN_vpcomged 0xf9d
#define MN_vpcomled 0xfa6
#define MN_vpcmpnled 0xfaf
#define MN_vpcmpled 0xfb9
#define MN_tilestored 0xfc2
#define MN_vpcomfalsed 0xfcd
#define MN_ttransposed 0xfd9
#define MN_vpcomtrued 0xfe5
#define MN_pi2fd 0xff0
#define MN_pshufd (MN_vpshufd + 1)
#define MN_vpshufd 0xff6
#define MN_vpternlogd 0xffe
#define MN_pf2id 0x1009
#define MN_invpcid 0x100f
#define MN_rdpid 0x1017
#define MN_invvpid 0x101d
#define MN_cpuid 0x1025
#define MN_rmpchkd 0x102b
#define MN_fbld 0x1033
#define MN_cld 0x1038
#define MN_fld 0x103c
#define MN_shld (MN_vpshld + 2)
#define MN_vpshld 0x1040
#define MN_fild 0x1047
#define MN_pslld (MN_vpslld + 1)
#define MN_vpslld 0x104c
#define MN_pmulld (MN_vpmulld + 1)
#define MN_vpmulld 0x1053
#define MN_vprold 0x105b
#define MN_psrld (MN_vpsrld + 1)
#define MN_vpsrld 0x1062
#define MN_vmptrld 0x1069
#define MN_kshiftld 0x1071
#define MN_enqcmd 0x107a
#define MN_vpblendmd 0x1081
#define MN_vptestnmd 0x108b
#define MN_vpcomd 0x1095
#define MN_vpermd 0x109c
#define MN_vptestmd 0x10a3
#define MN_and (MN_aand + 1)
#define MN_aand 0x10ac
#define MN_pand (MN_vpand + 1)
#define MN_vpand 0x10b1
#define MN_rdrand 0x10b7
#define MN_bnd 0x10be
#define MN_kandnd 0x10c2
#define MN_vpandnd 0x10c9
#define MN_xend 0x10d1
#define MN_valignd 0x10d6
#define MN_psignd (MN_vpsignd + 1)
#define MN_vpsignd 0x10de
#define MN_bound 0x10e6
#define MN_slod 0x10ec
#define MN_vfmaddsub231pd 0x10f1
#define MN_vfmsub231pd 0x1100
#define MN_vfnmsub231pd 0x110c
#define MN_vfmsubadd231pd 0x1119
#define MN_vfmadd231pd 0x1128
#define MN_vfnmadd231pd 0x1134
#define MN_vfmaddsub132pd 0x1141
#define MN_vfmsub132pd 0x1150
#define MN_vfnmsub132pd 0x115c
#define MN_vfmsubadd132pd 0x1169
#define MN_vfmadd132pd 0x1178
#define MN_vfnmadd132pd 0x1184
#define MN_vcvtph2pd 0x1191
#define MN_vpermi2pd 0x119b
#define MN_cvtpi2pd 0x11a5
#define MN_vpermil2pd 0x11ae
#define MN_vexp2pd 0x11b9
#define MN_cvtdq2pd (MN_vcvtdq2pd + 1)
#define MN_vcvtdq2pd 0x11c1
#define MN_vcvtudq2pd 0x11cb
#define MN_vcvtqq2pd 0x11d6
#define MN_vcvtuqq2pd 0x11e0
#define MN_cvtps2pd (MN_vcvtps2pd + 1)
#define MN_vcvtps2pd 0x11eb
#define MN_vpermt2pd 0x11f5
#define MN_vfmaddsub213pd 0x11ff
#define MN_vfmsub213pd 0x120e
#define MN_vfnmsub213pd 0x121a
#define MN_vfmsubadd213pd 0x1227
#define MN_vfmadd213pd 0x1236
#define MN_vfnmadd213pd 0x1242
#define MN_vrcp14pd 0x124f
#define MN_vrsqrt14pd 0x1258
#define MN_vrcp28pd 0x1263
#define MN_vrsqrt28pd 0x126c
#define MN_movapd (MN_vmovapd + 1)
#define MN_vmovapd 0x1277
#define MN_pswapd 0x127f
#define MN_subpd (MN_addsubpd + 3)
#define MN_addsubpd (MN_vfmaddsubpd + 3)
#define MN_vfmaddsubpd 0x1286
#define MN_vaddsubpd 0x1292
#define MN_hsubpd (MN_vhsubpd + 1)
#define MN_vhsubpd 0x129c
#define MN_vfmsubpd 0x12a4
#define MN_vfnmsubpd 0x12ad
#define MN_vsubpd 0x12b7
#define MN_vgatherpf0dpd 0x12be
#define MN_vscatterpf0dpd 0x12cc
#define MN_vgatherpf1dpd 0x12db
#define MN_vscatterpf1dpd 0x12e9
#define MN_addpd (MN_vfmsubaddpd + 6)
#define MN_vfmsubaddpd 0x12f8
#define MN_haddpd (MN_vhaddpd + 1)
#define MN_vhaddpd 0x1304
#define MN_vfmaddpd 0x130c
#define MN_vfnmaddpd 0x1315
#define MN_vaddpd 0x131f
#define MN_andpd (MN_vexpandpd + 4)
#define MN_vexpandpd 0x1326
#define MN_vandpd 0x1330
#define MN_blendpd (MN_vblendpd + 1)
#define MN_vblendpd 0x1337
#define MN_roundpd (MN_vroundpd + 1)
#define MN_vroundpd 0x1340
#define MN_vgatherdpd 0x1349
#define MN_vscatterdpd 0x1354
#define MN_cmpunordpd (MN_vcmpunordpd + 1)
#define MN_vcmpunordpd 0x1360
#define MN_cmpordpd (MN_vcmpordpd + 1)
#define MN_vcmpordpd 0x136c
#define MN_vreducepd 0x1376
#define MN_vrangepd 0x1380
#define MN_vcmpngepd 0x1389
#define MN_vcmpgepd 0x1393
#define MN_vrndscalepd 0x139c
#define MN_cmpnlepd (MN_vcmpnlepd + 1)
#define MN_vcmpnlepd 0x13a8
#define MN_cmplepd (MN_vcmplepd + 1)
#define MN_vcmplepd 0x13b2
#define MN_vcmpfalsepd 0x13bb
#define MN_vcmptruepd 0x13c7
#define MN_vscalefpd 0x13d2
#define MN_shufpd (MN_vshufpd + 1)
#define MN_vshufpd 0x13dc
#define MN_unpckhpd (MN_vunpckhpd + 1)
#define MN_vunpckhpd 0x13e4
#define MN_movhpd (MN_vmovhpd + 1)
#define MN_vmovhpd 0x13ee
#define MN_movmskpd (MN_vmovmskpd + 1)
#define MN_vmovmskpd 0x13f6
#define MN_vpermilpd 0x1400
#define MN_unpcklpd (MN_vunpcklpd + 1)
#define MN_vunpcklpd 0x140a
#define MN_mulpd (MN_vmulpd + 1)
#define MN_vmulpd 0x1414
#define MN_movlpd (MN_vmovlpd + 1)
#define MN_vmovlpd 0x141b
#define MN_vpcmpd 0x1423
#define MN_vblendmpd 0x142a
#define MN_vfixupimmpd 0x1434
#define MN_vpermpd 0x1440
#define MN_andnpd (MN_vandnpd + 1)
#define MN_vandnpd 0x1448
#define MN_minpd (MN_vminpd + 1)
#define MN_vminpd 0x1450
#define MN_dppd (MN_vdppd + 1)
#define MN_vdppd 0x1457
#define MN_cmppd (MN_vcmppd + 1)
#define MN_vcmppd 0x145d
#define MN_vgetexppd 0x1464
#define MN_vgatherpf0qpd 0x146e
#define MN_vscatterpf0qpd 0x147c
#define MN_vgatherpf1qpd 0x148b
#define MN_vscatterpf1qpd 0x1499
#define MN_vcmpunord_qpd 0x14a8
#define MN_vcmpord_qpd 0x14b6
#define MN_cmpneqpd (MN_vcmpneqpd + 1)
#define MN_vcmpneqpd 0x14c2
#define MN_cmpeqpd (MN_vcmpeqpd + 1)
#define MN_vcmpeqpd 0x14cc
#define MN_vcmpge_oqpd 0x14d5
#define MN_vcmple_oqpd 0x14e1
#define MN_vcmpfalse_oqpd 0x14ed
#define MN_vcmpneq_oqpd 0x14fc
#define MN_vcmpeq_oqpd 0x1509
#define MN_vcmpgt_oqpd 0x1515
#define MN_vcmplt_oqpd 0x1521
#define MN_vgatherqpd 0x152d
#define MN_vscatterqpd 0x1538
#define MN_vcmpnge_uqpd 0x1544
#define MN_vcmpnle_uqpd 0x1551
#define MN_vcmptrue_uqpd 0x155e
#define MN_vcmpneq_uqpd 0x156c
#define MN_vcmpeq_uqpd 0x1579
#define MN_vcmpngt_uqpd 0x1585
#define MN_vcmpnlt_uqpd 0x1592
#define MN_orpd (MN_vorpd + 1)
#define MN_vorpd 0x159f
#define MN_xorpd (MN_vxorpd + 1)
#define MN_vxorpd 0x15a5
#define MN_vcmpunord_spd 0x15ac
#define MN_vcmpord_spd 0x15ba
#define MN_vcmpge_ospd 0x15c6
#define MN_vcmple_ospd 0x15d2
#define MN_vcmpfalse_ospd 0x15de
#define MN_vcmpneq_ospd 0x15ed
#define MN_vcmpeq_ospd 0x15fa
#define MN_vcmpgt_ospd 0x1606
#define MN_vcmplt_ospd 0x1612
#define MN_vfpclasspd 0x161e
#define MN_incsspd 0x1629
#define MN_rdsspd 0x1631
#define MN_vcompresspd 0x1638
#define MN_vcmpnge_uspd 0x1644
#define MN_vcmpnle_uspd 0x1651
#define MN_vcmptrue_uspd 0x165e
#define MN_vcmpneq_uspd 0x166c
#define MN_vcmpeq_uspd 0x1679
#define MN_vcmpngt_uspd 0x1685
#define MN_vcmpnlt_uspd 0x1692
#define MN_vcmpngtpd 0x169f
#define MN_vcmpgtpd 0x16a9
#define MN_cmpnltpd (MN_vcmpnltpd + 1)
#define MN_vcmpnltpd 0x16b2
#define MN_cmpltpd (MN_vcmpltpd + 1)
#define MN_vcmpltpd 0x16bc
#define MN_vgetmantpd 0x16c5
#define MN_movntpd (MN_vmovntpd + 1)
#define MN_vmovntpd 0x16d0
#define MN_sqrtpd (MN_vsqrtpd + 1)
#define MN_vsqrtpd 0x16d9
#define MN_vtestpd 0x16e1
#define MN_movupd (MN_vmovupd + 1)
#define MN_vmovupd 0x16e9
#define MN_blendvpd (MN_vblendvpd + 1)
#define MN_vblendvpd 0x16f1
#define MN_divpd (MN_vdivpd + 1)
#define MN_vdivpd 0x16fb
#define MN_vmaskmovpd 0x1702
#define MN_maxpd (MN_vminmaxpd + 4)
#define MN_vminmaxpd 0x170d
#define MN_vmaxpd 0x1717
#define MN_vfrczpd 0x171e
#define MN_vpcomeqd 0x1726
#define MN_vpcomneqd 0x172f
#define MN_vpcmpneqd 0x1739
#define MN_pcmpeqd (MN_vpcmpeqd + 1)
#define MN_vpcmpeqd 0x1743
#define MN_vpgatherqd 0x174c
#define MN_vpscatterqd 0x1757
#define MN_vpmovusqd 0x1763
#define MN_vpmovsqd 0x176d
#define MN_vpmovqd 0x1776
#define MN_shrd 0x177e
#define MN_kord 0x1783
#define MN_kxnord 0x1788
#define MN_vpord 0x178f
#define MN_vprord 0x1795
#define MN_word (MN_aword + 1)
#define MN_aword 0x179c
#define MN_dword (MN_adword + 1)
#define MN_adword 0x17a2
#define MN_kxord 0x17a9
#define MN_vpxord 0x17af
#define MN_pinsrd (MN_vpinsrd + 1)
#define MN_vpinsrd 0x17b6
#define MN_kshiftrd 0x17be
#define MN_pextrd (MN_vpextrd + 1)
#define MN_vpextrd 0x17c7
#define MN_vfmsub231sd 0x17cf
#define MN_vfnmsub231sd 0x17db
#define MN_vfmadd231sd 0x17e8
#define MN_vfnmadd231sd 0x17f4
#define MN_vfmsub132sd 0x1801
#define MN_vfnmsub132sd 0x180d
#define MN_vfmadd132sd 0x181a
#define MN_vfnmadd132sd 0x1826
#define MN_vcvtsh2sd 0x1833
#define MN_cvtsi2sd (MN_vcvtsi2sd + 1)
#define MN_vcvtsi2sd 0x183d
#define MN_vcvtusi2sd 0x1847
#define MN_cvtss2sd (MN_vcvtss2sd + 1)
#define MN_vcvtss2sd 0x1852
#define MN_vfmsub213sd 0x185c
#define MN_vfnmsub213sd 0x1868
#define MN_vfmadd213sd 0x1875
#define MN_vfnmadd213sd 0x1881
#define MN_vrcp14sd 0x188e
#define MN_vrsqrt14sd 0x1897
#define MN_vrcp28sd 0x18a2
#define MN_vrsqrt28sd 0x18ab
#define MN_pabsd (MN_vpabsd + 1)
#define MN_vpabsd 0x18b6
#define MN_subsd (MN_vfmsubsd + 3)
#define MN_vfmsubsd 0x18bd
#define MN_vfnmsubsd 0x18c6
#define MN_vsubsd 0x18d0
#define MN_addsd (MN_vfmaddsd + 3)
#define MN_vfmaddsd 0x18d7
#define MN_vfnmaddsd 0x18e0
#define MN_vaddsd 0x18ea
#define MN_roundsd (MN_vroundsd + 1)
#define MN_vroundsd 0x18f1
#define MN_cmpunordsd (MN_vcmpunordsd + 1)
#define MN_vcmpunordsd 0x18fa
#define MN_cmpordsd (MN_vcmpordsd + 1)
#define MN_vcmpordsd 0x1906
#define MN_vreducesd 0x1910
#define MN_vrangesd 0x191a
#define MN_vcmpngesd 0x1923
#define MN_vcmpgesd 0x192d
#define MN_vrndscalesd 0x1936
#define MN_cmpnlesd (MN_vcmpnlesd + 1)
#define MN_vcmpnlesd 0x1942
#define MN_cmplesd (MN_vcmplesd + 1)
#define MN_vcmplesd 0x194c
#define MN_vcmpfalsesd 0x1955
#define MN_vcmptruesd 0x1961
#define MN_vscalefsd 0x196c
#define MN_comisd (MN_ucomisd + 1)
#define MN_ucomisd (MN_vucomisd + 1)
#define MN_vucomisd 0x1976
#define MN_vcomisd 0x197f
#define MN_mulsd (MN_vmulsd + 1)
#define MN_vmulsd 0x1987
#define MN_vfixupimmsd 0x198e
#define MN_minsd (MN_pminsd + 1)
#define MN_pminsd (MN_vpminsd + 1)
#define MN_vpminsd 0x199a
#define MN_vminsd 0x19a2
#define MN_cmpsd (MN_vcmpsd + 1)
#define MN_vcmpsd 0x19a9
#define MN_vgetexpsd 0x19b0
#define MN_vcmpunord_qsd 0x19ba
#define MN_vcmpord_qsd 0x19c8
#define MN_cmpneqsd (MN_vcmpneqsd + 1)
#define MN_vcmpneqsd 0x19d4
#define MN_cmpeqsd (MN_vcmpeqsd + 1)
#define MN_vcmpeqsd 0x19de
#define MN_vcmpge_oqsd 0x19e7
#define MN_vcmple_oqsd 0x19f3
#define MN_vcmpfalse_oqsd 0x19ff
#define MN_vcmpneq_oqsd 0x1a0e
#define MN_vcmpeq_oqsd 0x1a1b
#define MN_vcmpgt_oqsd 0x1a27
#define MN_vcmplt_oqsd 0x1a33
#define MN_vcmpnge_uqsd 0x1a3f
#define MN_vcmpnle_uqsd 0x1a4c
#define MN_vcmptrue_uqsd 0x1a59
#define MN_vcmpneq_uqsd 0x1a67
#define MN_vcmpeq_uqsd 0x1a74
#define MN_vcmpngt_uqsd 0x1a80
#define MN_vcmpnlt_uqsd 0x1a8d
#define MN_vmovrsd 0x1a9a
#define MN_vcmpunord_ssd 0x1aa2
#define MN_vcmpord_ssd 0x1ab0
#define MN_vpdpbssd 0x1abc
#define MN_tdpbssd 0x1ac5
#define MN_vpcompressd 0x1acd
#define MN_vcmpge_ossd 0x1ad9
#define MN_vcmple_ossd 0x1ae5
#define MN_vcmpfalse_ossd 0x1af1
#define MN_vcmpneq_ossd 0x1b00
#define MN_vcmpeq_ossd 0x1b0d
#define MN_vcmpgt_ossd 0x1b19
#define MN_vcmplt_ossd 0x1b25
#define MN_wrssd 0x1b31
#define MN_vfpclasssd 0x1b37
#define MN_vcmpnge_ussd 0x1b42
#define MN_vcmpnle_ussd 0x1b4f
#define MN_vcmptrue_ussd 0x1b5c
#define MN_vcmpneq_ussd 0x1b6a
#define MN_vcmpeq_ussd 0x1b77
#define MN_vcmpngt_ussd 0x1b83
#define MN_vcmpnlt_ussd 0x1b90
#define MN_wrussd 0x1b9d
#define MN_vp4dpwssd 0x1ba4
#define MN_vpdpwssd 0x1bae
#define MN_vcmpngtsd 0x1bb7
#define MN_vcmpgtsd 0x1bc1
#define MN_cmpnltsd (MN_vcmpnltsd + 1)
#define MN_vcmpnltsd 0x1bca
#define MN_cmpltsd (MN_vcmpltsd + 1)
#define MN_vcmpltsd 0x1bd4
#define MN_vgetmantsd 0x1bdd
#define MN_movntsd 0x1be8
#define MN_sqrtsd (MN_vsqrtsd + 1)
#define MN_vsqrtsd 0x1bf0
#define MN_vbroadcastsd 0x1bf8
#define MN_vpdpbusd 0x1c05
#define MN_tdpbusd 0x1c0e
#define MN_vpdpwusd 0x1c16
#define MN_divsd (MN_vdivsd + 1)
#define MN_vdivsd 0x1c1f
#define MN_movsd (MN_vmovsd + 1)
#define MN_vmovsd 0x1c26
#define MN_maxsd (MN_vminmaxsd + 4)
#define MN_vminmaxsd 0x1c2d
#define MN_pmaxsd (MN_vpmaxsd + 1)
#define MN_vpmaxsd 0x1c37
#define MN_vmaxsd 0x1c3f
#define MN_vucomxsd 0x1c46
#define MN_vcomxsd 0x1c4f
#define MN_vfrczsd 0x1c57
#define MN_vp2intersectd 0x1c5f
#define MN_vpconflictd 0x1c6d
#define MN_vpcomgtd 0x1c79
#define MN_pcmpgtd (MN_vpcmpgtd + 1)
#define MN_vpcmpgtd 0x1c82
#define MN_cltd 0x1c8b
#define MN_vpcomltd 0x1c90
#define MN_vpcmpnltd 0x1c99
#define MN_vpcmpltd 0x1ca3
#define MN_vpopcntd 0x1cac
#define MN_vplzcntd 0x1cb5
#define MN_knotd 0x1cbe
#define MN_vprotd 0x1cc4
#define MN_std (MN_vpbroadcastd + 9)
#define MN_vpbroadcastd 0x1ccb
#define MN_ktestd 0x1cd8
#define MN_kortestd 0x1cdf
#define MN_cwtd 0x1ce8
#define MN_vpcomgeud 0x1ced
#define MN_vpcomleud 0x1cf7
#define MN_vpcmpnleud 0x1d01
#define MN_vpcmpleud 0x1d0c
#define MN_vpcomfalseud 0x1d16
#define MN_vpcomtrueud 0x1d23
#define MN_vpcomud 0x1d2f
#define MN_pminud (MN_vpminud + 1)
#define MN_vpminud 0x1d37
#define MN_vpcmpud 0x1d3f
#define MN_vpcomequd 0x1d47
#define MN_vpcomnequd 0x1d51
#define MN_vpcmpnequd 0x1d5c
#define MN_vpcmpequd 0x1d67
#define MN_vpdpbsud 0x1d71
#define MN_tdpbsud 0x1d7a
#define MN_vpdpwsud 0x1d82
#define MN_vpcomgtud 0x1d8b
#define MN_vpcomltud 0x1d95
#define MN_vpcmpnltud 0x1d9f
#define MN_vpcmpltud 0x1daa
#define MN_vpdpbuud 0x1db4
#define MN_tdpbuud 0x1dbd
#define MN_vpdpwuud 0x1dc5
#define MN_pmaxud (MN_vpmaxud + 1)
#define MN_vpmaxud 0x1dce
#define MN_vpsravd 0x1dd6
#define MN_vpshldvd 0x1dde
#define MN_vpshrdvd 0x1de7
#define MN_vpsllvd 0x1df0
#define MN_vprolvd 0x1df8
#define MN_vpsrlvd 0x1e00
#define MN_invd (MN_wbinvd + 2)
#define MN_wbinvd 0x1e08
#define MN_wbnoinvd 0x1e0f
#define MN_movd (MN_kmovd + 1)
#define MN_kmovd (MN_vpmaskmovd + 5)
#define MN_vpmaskmovd 0x1e18
#define MN_vmovd 0x1e23
#define MN_vprorvd 0x1e29
#define MN_vphsubwd 0x1e31
#define MN_cwd 0x1e3a
#define MN_vphaddwd 0x1e3e
#define MN_pmaddwd (MN_vpmaddwd + 1)
#define MN_vpmaddwd 0x1e47
#define MN_punpckhwd (MN_vpunpckhwd + 1)
#define MN_vpunpckhwd 0x1e50
#define MN_kunpckwd 0x1e5b
#define MN_punpcklwd (MN_vpunpcklwd + 1)
#define MN_vpunpcklwd 0x1e64
#define MN_vpmacswd 0x1e6f
#define MN_vpmadcswd 0x1e78
#define MN_vpmacsswd 0x1e82
#define MN_vpmadcsswd 0x1e8c
#define MN_vphadduwd 0x1e97
#define MN_pmovsxwd (MN_vpmovsxwd + 1)
#define MN_vpmovsxwd 0x1ea1
#define MN_pmovzxwd (MN_vpmovzxwd + 1)
#define MN_vpmovzxwd 0x1eab
#define MN_movsxd 0x1eb5
#define MN_fldl2e 0x1ebc
#define MN_jae 0x1ec3
#define MN_jnae 0x1ec7
#define MN_ccmpnae 0x1ecc
#define MN_setnae 0x1ed4
#define MN_ctestnae 0x1edb
#define MN_setzunae 0x1ee4
#define MN_cmovnae (MN_fcmovnae + 1)
#define MN_fcmovnae (MN_cfcmovnae + 1)
#define MN_cfcmovnae 0x1eed
#define MN_ccmpae 0x1ef7
#define MN_setae 0x1efe
#define MN_ctestae 0x1f04
#define MN_setzuae 0x1f0c
#define MN_cmovae (MN_fcmovae + 1)
#define MN_fcmovae (MN_cfcmovae + 1)
#define MN_cfcmovae 0x1f14
#define MN_jbe 0x1f1d
#define MN_jnbe 0x1f21
#define MN_ccmpnbe 0x1f26
#define MN_setnbe 0x1f2e
#define MN_ctestnbe 0x1f35
#define MN_setzunbe 0x1f3e
#define MN_cmovnbe (MN_fcmovnbe + 1)
#define MN_fcmovnbe (MN_cfcmovnbe + 1)
#define MN_cfcmovnbe 0x1f47
#define MN_ccmpbe 0x1f51
#define MN_setbe 0x1f58
#define MN_ctestbe 0x1f5e
#define MN_setzube 0x1f66
#define MN_movbe (MN_cmovbe + 1)
#define MN_cmovbe (MN_fcmovbe + 1)
#define MN_fcmovbe (MN_cfcmovbe + 1)
#define MN_cfcmovbe 0x1f6e
#define MN_lfence 0x1f77
#define MN_mfence 0x1f7e
#define MN_sfence 0x1f85
#define MN_cwde 0x1f8c
#define MN_ffree 0x1f91
#define MN_jge 0x1f97
#define MN_jnge 0x1f9b
#define MN_ccmpnge 0x1fa0
#define MN_setnge 0x1fa8
#define MN_ctestnge 0x1faf
#define MN_setzunge 0x1fb8
#define MN_cmovnge (MN_cfcmovnge + 2)
#define MN_cfcmovnge 0x1fc1
#define MN_ccmpge 0x1fcb
#define MN_pfcmpge 0x1fd2
#define MN_setge 0x1fda
#define MN_ctestge 0x1fe0
#define MN_setzuge 0x1fe8
#define MN_cmovge (MN_cfcmovge + 2)
#define MN_cfcmovge 0x1ff0
#define MN_je 0x1ff9
#define MN_fscale 0x1ffc
#define MN_jle 0x2003
#define MN_jnle 0x2007
#define MN_ccmpnle 0x200c
#define MN_setnle 0x2014
#define MN_ctestnle 0x201b
#define MN_setzunle 0x2024
#define MN_cmovnle (MN_cfcmovnle + 2)
#define MN_cfcmovnle 0x202d
#define MN_ccmple 0x2037
#define MN_setle 0x203e
#define MN_ctestle 0x2044
#define MN_setzule 0x204c
#define MN_cmovle (MN_cfcmovle + 2)
#define MN_cfcmovle 0x2054
#define MN_vmresume 0x205d
#define MN_jne 0x2066
#define MN_repne 0x206a
#define MN_ccmpne 0x2070
#define MN_loopne 0x2077
#define MN_setne 0x207e
#define MN_ctestne 0x2084
#define MN_setzune 0x208c
#define MN_cmovne (MN_fcmovne + 1)
#define MN_fcmovne (MN_cfcmovne + 1)
#define MN_cfcmovne 0x2094
#define MN_repe 0x209d
#define MN_jpe 0x20a2
#define MN_ccmpe 0x20a6
#define MN_loope 0x20ac
#define MN_setpe 0x20b2
#define MN_setzupe 0x20b8
#define MN_cmovpe (MN_cfcmovpe + 2)
#define MN_cfcmovpe 0x20c0
#define MN_cdqe 0x20c9
#define MN_xacquire 0x20ce
#define MN_xstore 0x20d7
#define MN_rdfsbase 0x20de
#define MN_wrfsbase 0x20e7
#define MN_rdgsbase 0x20f0
#define MN_wrgsbase 0x20f9
#define MN_tilerelease 0x2102
#define MN_xrelease 0x210e
#define MN_pause (MN_tpause + 1)
#define MN_tpause 0x2117
#define MN_pvalidate 0x211e
#define MN_rmpupdate 0x2128
#define MN_sete 0x2132
#define MN_vmwrite 0x2137
#define MN_ptwrite 0x213f
#define MN_cldemote 0x2147
#define MN_cteste 0x2150
#define MN_sha1nexte 0x2157
#define MN_setzue 0x2161
#define MN_leave 0x2168
#define MN_fsave 0x216e
#define MN_vmsave 0x2174
#define MN_fnsave 0x217b
#define MN_xsave (MN_fxsave + 1)
#define MN_fxsave 0x2182
#define MN_cmove (MN_fcmove + 1)
#define MN_fcmove (MN_cfcmove + 1)
#define MN_cfcmove 0x2189
#define MN_serialize 0x2191
#define MN_vmxoff 0x219b
#define MN_lahf 0x21a2
#define MN_sahf 0x21a7
#define MN_pushf 0x21ac
#define MN_ccmpf 0x21b2
#define MN_popf 0x21b8
#define MN_bsf 0x21bd
#define MN_retf 0x21c1
#define MN_ctestf 0x21c6
#define MN_bsrmovf 0x21cd
#define MN_neg 0x21d5
#define MN_ldtilecfg 0x21d9
#define MN_sttilecfg 0x21e3
#define MN_xchg (MN_cmpxchg + 3)
#define MN_cmpxchg 0x21ed
#define MN_pconfig 0x21f5
#define MN_jg 0x21fd
#define MN_jng 0x2200
#define MN_ccmpng 0x2204
#define MN_xstore_rng 0x220b
#define MN_xstorerng 0x2216
#define MN_setng 0x2220
#define MN_ctestng 0x2226
#define MN_setzung 0x222e
#define MN_cmovng (MN_cfcmovng + 2)
#define MN_cfcmovng 0x2236
#define MN_invlpg 0x223f
#define MN_ccmpg 0x2246
#define MN_setg 0x224c
#define MN_ctestg 0x2251
#define MN_setzug 0x2258
#define MN_cmovg (MN_cfcmovg + 2)
#define MN_cfcmovg 0x225f
#define MN_tcvtrowps2bf16h 0x2267
#define MN_vmlaunch 0x2277
#define MN_prefetch 0x2280
#define MN_fxch 0x2289
#define MN_tcvtrowps2phh 0x228e
#define MN_vfmaddsub231ph 0x229c
#define MN_vfmsub231ph 0x22ab
#define MN_vfnmsub231ph 0x22b7
#define MN_vfmsubadd231ph 0x22c4
#define MN_vfmadd231ph 0x22d3
#define MN_vfnmadd231ph 0x22df
#define MN_vfmaddsub132ph 0x22ec
#define MN_vfmsub132ph 0x22fb
#define MN_vfnmsub132ph 0x2307
#define MN_vfmsubadd132ph 0x2314
#define MN_vfmadd132ph 0x2323
#define MN_vfnmadd132ph 0x232f
#define MN_vcvthf82ph 0x233c
#define MN_vcvtpd2ph 0x2347
#define MN_vcvtdq2ph 0x2351
#define MN_vcvtudq2ph 0x235b
#define MN_vcvtqq2ph 0x2366
#define MN_vcvtuqq2ph 0x2370
#define MN_vcvtps2ph 0x237b
#define MN_vcvtw2ph 0x2385
#define MN_vcvtuw2ph 0x238e
#define MN_vfmaddsub213ph 0x2398
#define MN_vfmsub213ph 0x23a7
#define MN_vfnmsub213ph 0x23b3
#define MN_vfmsubadd213ph 0x23c0
#define MN_vfmadd213ph 0x23cf
#define MN_vfnmadd213ph 0x23db
#define MN_vsubph 0x23e8
#define MN_vfcmaddcph 0x23ef
#define MN_vfmaddcph 0x23fa
#define MN_vfcmulcph 0x2404
#define MN_vfmulcph 0x240e
#define MN_vaddph 0x2417
#define MN_vcmpunordph 0x241e
#define MN_vcmpordph 0x242a
#define MN_vreduceph 0x2434
#define MN_vcmpngeph 0x243e
#define MN_vcmpgeph 0x2448
#define MN_vrndscaleph 0x2451
#define MN_vcmpnleph 0x245d
#define MN_vcmpleph 0x2467
#define MN_vcmpfalseph 0x2470
#define MN_vcmptrueph 0x247c
#define MN_vscalefph 0x2487
#define MN_vmulph 0x2491
#define MN_vminph 0x2498
#define MN_vrcpph 0x249f
#define MN_vcmpph 0x24a6
#define MN_vgetexpph 0x24ad
#define MN_vcmpunord_qph 0x24b7
#define MN_vcmpord_qph 0x24c5
#define MN_vcmpneqph 0x24d1
#define MN_vcmpeqph 0x24db
#define MN_vcmpge_oqph 0x24e4
#define MN_vcmple_oqph 0x24f0
#define MN_vcmpfalse_oqph 0x24fc
#define MN_vcmpneq_oqph 0x250b
#define MN_vcmpeq_oqph 0x2518
#define MN_vcmpgt_oqph 0x2524
#define MN_vcmplt_oqph 0x2530
#define MN_vcmpnge_uqph 0x253c
#define MN_vcmpnle_uqph 0x2549
#define MN_vcmptrue_uqph 0x2556
#define MN_vcmpneq_uqph 0x2564
#define MN_vcmpeq_uqph 0x2571
#define MN_vcmpngt_uqph 0x257d
#define MN_vcmpnlt_uqph 0x258a
#define MN_vcmpunord_sph 0x2597
#define MN_vcmpord_sph 0x25a5
#define MN_vcmpge_osph 0x25b1
#define MN_vcmple_osph 0x25bd
#define MN_vcmpfalse_osph 0x25c9
#define MN_vcmpneq_osph 0x25d8
#define MN_vcmpeq_osph 0x25e5
#define MN_vcmpgt_osph 0x25f1
#define MN_vcmplt_osph 0x25fd
#define MN_vfpclassph 0x2609
#define MN_vcmpnge_usph 0x2614
#define MN_vcmpnle_usph 0x2621
#define MN_vcmptrue_usph 0x262e
#define MN_vcmpneq_usph 0x263c
#define MN_vcmpeq_usph 0x2649
#define MN_vcmpngt_usph 0x2655
#define MN_vcmpnlt_usph 0x2662
#define MN_vcmpngtph 0x266f
#define MN_vcmpgtph 0x2679
#define MN_vcmpnltph 0x2682
#define MN_vcmpltph 0x268c
#define MN_vgetmantph 0x2695
#define MN_vrsqrtph 0x26a0
#define MN_vsqrtph 0x26a9
#define MN_vdivph 0x26b1
#define MN_vminmaxph 0x26b8
#define MN_vmaxph 0x26c2
#define MN_vpmacsdqh 0x26c9
#define MN_vpmacssdqh 0x26d3
#define MN_vfmsub231sh 0x26de
#define MN_vfnmsub231sh 0x26ea
#define MN_vfmadd231sh 0x26f7
#define MN_vfnmadd231sh 0x2703
#define MN_vfmsub132sh 0x2710
#define MN_vfnmsub132sh 0x271c
#define MN_vfmadd132sh 0x2729
#define MN_vfnmadd132sh 0x2735
#define MN_vcvtsd2sh 0x2742
#define MN_vcvtsi2sh 0x274c
#define MN_vcvtusi2sh 0x2756
#define MN_vcvtss2sh 0x2761
#define MN_vfmsub213sh 0x276b
#define MN_vfnmsub213sh 0x2777
#define MN_vfmadd213sh 0x2784
#define MN_vfnmadd213sh 0x2790
#define MN_psmash 0x279d
#define MN_vsubsh 0x27a4
#define MN_vfcmaddcsh 0x27ab
#define MN_vfmaddcsh 0x27b6
#define MN_vfcmulcsh 0x27c0
#define MN_vfmulcsh 0x27ca
#define MN_vaddsh 0x27d3
#define MN_vcmpunordsh 0x27da
#define MN_vcmpordsh 0x27e6
#define MN_vreducesh 0x27f0
#define MN_vcmpngesh 0x27fa
#define MN_vcmpgesh 0x2804
#define MN_vrndscalesh 0x280d
#define MN_vcmpnlesh 0x2819
#define MN_vcmplesh 0x2823
#define MN_vcmpfalsesh 0x282c
#define MN_vcmptruesh 0x2838
#define MN_vscalefsh 0x2843
#define MN_vucomish 0x284d
#define MN_vcomish 0x2856
#define MN_vmulsh 0x285e
#define MN_vminsh 0x2865
#define MN_vrcpsh 0x286c
#define MN_vcmpsh 0x2873
#define MN_vgetexpsh 0x287a
#define MN_vcmpunord_qsh 0x2884
#define MN_vcmpord_qsh 0x2892
#define MN_vcmpneqsh 0x289e
#define MN_vcmpeqsh 0x28a8
#define MN_vcmpge_oqsh 0x28b1
#define MN_vcmple_oqsh 0x28bd
#define MN_vcmpfalse_oqsh 0x28c9
#define MN_vcmpneq_oqsh 0x28d8
#define MN_vcmpeq_oqsh 0x28e5
#define MN_vcmpgt_oqsh 0x28f1
#define MN_vcmplt_oqsh 0x28fd
#define MN_vcmpnge_uqsh 0x2909
#define MN_vcmpnle_uqsh 0x2916
#define MN_vcmptrue_uqsh 0x2923
#define MN_vcmpneq_uqsh 0x2931
#define MN_vcmpeq_uqsh 0x293e
#define MN_vcmpngt_uqsh 0x294a
#define MN_vcmpnlt_uqsh 0x2957
#define MN_vcmpunord_ssh 0x2964
#define MN_vcmpord_ssh 0x2972
#define MN_vcmpge_ossh 0x297e
#define MN_vcmple_ossh 0x298a
#define MN_vcmpfalse_ossh 0x2996
#define MN_vcmpneq_ossh 0x29a5
#define MN_vcmpeq_ossh 0x29b2
#define MN_vcmpgt_ossh 0x29be
#define MN_vcmplt_ossh 0x29ca
#define MN_vfpclasssh 0x29d6
#define MN_vcmpnge_ussh 0x29e1
#define MN_vcmpnle_ussh 0x29ee
#define MN_vcmptrue_ussh 0x29fb
#define MN_vcmpneq_ussh 0x2a09
#define MN_vcmpeq_ussh 0x2a16
#define MN_vcmpngt_ussh 0x2a22
#define MN_vcmpnlt_ussh 0x2a2f
#define MN_vcmpngtsh 0x2a3c
#define MN_vcmpgtsh 0x2a46
#define MN_vcmpnltsh 0x2a4f
#define MN_vcmpltsh 0x2a59
#define MN_vgetmantsh 0x2a62
#define MN_vrsqrtsh 0x2a6d
#define MN_vsqrtsh 0x2a76
#define MN_clflush 0x2a7e
#define MN_push 0x2a86
#define MN_vdivsh 0x2a8b
#define MN_vmovsh 0x2a92
#define MN_vminmaxsh 0x2a99
#define MN_vmaxsh 0x2aa3
#define MN_vucomxsh 0x2aaa
#define MN_vcomxsh 0x2ab3
#define MN_bsrmovh 0x2abb
#define MN_blci 0x2ac3
#define MN_clgi 0x2ac8
#define MN_stgi 0x2acd
#define MN_bzhi 0x2ad2
#define MN_cli 0x2ad7
#define MN_fcomi 0x2adb
#define MN_fucomi 0x2ae1
#define MN_feni 0x2ae8
#define MN_fneni 0x2aed
#define MN_cvttpd2pi 0x2af3
#define MN_cvtpd2pi 0x2afd
#define MN_cvttps2pi 0x2b06
#define MN_cvtps2pi 0x2b10
#define MN_fldpi 0x2b19
#define MN_senduipi 0x2b1f
#define MN_fcompi 0x2b28
#define MN_fucompi 0x2b2f
#define MN_movdiri 0x2b37
#define MN_pcmpestri (MN_vpcmpestri + 1)
#define MN_vpcmpestri 0x2b3f
#define MN_pcmpistri (MN_vpcmpistri + 1)
#define MN_vpcmpistri 0x2b4a
#define MN_cvttsd2si (MN_vcvttsd2si + 1)
#define MN_vcvttsd2si 0x2b55
#define MN_cvtsd2si (MN_vcvtsd2si + 1)
#define MN_vcvtsd2si 0x2b60
#define MN_vcvttsh2si 0x2b6a
#define MN_vcvtsh2si 0x2b75
#define MN_cvttss2si (MN_vcvttss2si + 1)
#define MN_vcvttss2si 0x2b7f
#define MN_cvtss2si (MN_vcvtss2si + 1)
#define MN_vcvtss2si 0x2b8a
#define MN_fdisi 0x2b94
#define MN_fndisi 0x2b9a
#define MN_blsi 0x2ba1
#define MN_vcvttsd2usi 0x2ba6
#define MN_vcvtsd2usi 0x2bb2
#define MN_vcvttsh2usi 0x2bbd
#define MN_vcvtsh2usi 0x2bc9
#define MN_vcvttss2usi 0x2bd4
#define MN_vcvtss2usi 0x2be0
#define MN_movnti 0x2beb
#define MN_sti 0x2bf2
#define MN_clui 0x2bf6
#define MN_stui (MN_testui + 2)
#define MN_testui 0x2bfb
#define MN_notrack 0x2c02
#define MN_lock 0x2c0a
#define MN_bndmk 0x2c0f
#define MN_xresldtrk 0x2c15
#define MN_xsusldtrk 0x2c1f
#define MN_blcmsk 0x2c29
#define MN_blsmsk 0x2c30
#define MN_tzmsk 0x2c37
#define MN_tcvtrowps2bf16l 0x2c3d
#define MN_sal 0x2c4d
#define MN_lwpval 0x2c51
#define MN_bndcl 0x2c58
#define MN_rcl 0x2c5e
#define MN_tcvtrowps2phl 0x2c62
#define MN_shl 0x2c70
#define MN_jl 0x2c74
#define MN_aesdec256kl 0x2c77
#define MN_aesenc256kl 0x2c83
#define MN_aesdecwide256kl 0x2c8f
#define MN_aesencwide256kl 0x2c9f
#define MN_aesdec128kl 0x2caf
#define MN_aesenc128kl 0x2cbb
#define MN_aesdecwide128kl 0x2cc7
#define MN_aesencwide128kl 0x2cd7
#define MN_call (MN_tdcall + 2)
#define MN_tdcall 0x2ce7
#define MN_lcall 0x2cee
#define MN_seamcall 0x2cf4
#define MN_vmmcall 0x2cfd
#define MN_vmcall 0x2d05
#define MN_syscall 0x2d0c
#define MN_vzeroall 0x2d14
#define MN_fildll 0x2d1d
#define MN_blcfill 0x2d24
#define MN_blsfill 0x2d2c
#define MN_fistpll 0x2d34
#define MN_fisttpll 0x2d3c
#define MN_jnl 0x2d45
#define MN_ccmpnl 0x2d49
#define MN_setnl 0x2d50
#define MN_ctestnl 0x2d56
#define MN_setzunl 0x2d5e
#define MN_cmovnl (MN_cfcmovnl + 2)
#define MN_cfcmovnl 0x2d66
#define MN_tilemovcol 0x2d6f
#define MN_rol 0x2d7a
#define MN_ccmpl 0x2d7e
#define MN_arpl 0x2d84
#define MN_vpmacsdql 0x2d89
#define MN_vpmacssdql 0x2d93
#define MN_lsl 0x2d9e
#define MN_movsl 0x2da2
#define MN_setl 0x2da8
#define MN_ctestl 0x2dad
#define MN_cwtl 0x2db4
#define MN_mul (MN_fmul + 1)
#define MN_fmul (MN_pfmul + 1)
#define MN_pfmul 0x2db9
#define MN_imul (MN_fimul + 1)
#define MN_fimul 0x2dbf
#define MN_montmul 0x2dc5
#define MN_setzul 0x2dcd
#define MN_cmovl (MN_cfcmovl + 2)
#define MN_cfcmovl 0x2dd4
#define MN_bsrmovl 0x2ddc
#define MN_vpmovb2m 0x2de4
#define MN_vpmovd2m 0x2ded
#define MN_vpmovq2m 0x2df6
#define MN_vpmovw2m 0x2dff
#define MN_aam 0x2e08
#define MN_fxam 0x2e0c
#define MN_fprem 0x2e11
#define MN_fcom 0x2e17
#define MN_ficom 0x2e1c
#define MN_fucom 0x2e22
#define MN_fsetpm 0x2e28
#define MN_fnsetpm 0x2e2f
#define MN_frstpm 0x2e37
#define MN_vpperm 0x2e3e
#define MN_pcmpestrm (MN_vpcmpestrm + 1)
#define MN_vpcmpestrm 0x2e45
#define MN_pcmpistrm (MN_vpcmpistrm + 1)
#define MN_vpcmpistrm 0x2e50
#define MN_rsm 0x2e5b
#define MN_fpatan 0x2e5f
#define MN_fptan 0x2e66
#define MN_bndcn 0x2e6c
#define MN_andn (MN_pandn + 1)
#define MN_pandn (MN_vpandn + 1)
#define MN_vpandn 0x2e72
#define MN_in (MN_xbegin + 4)
#define MN_xbegin 0x2e79
#define MN_pfmin 0x2e80
#define MN_fsin 0x2e86
#define MN_vmxon 0x2e8b
#define MN_vmrun 0x2e91
#define MN_jo 0x2e97
#define MN_jno 0x2e9a
#define MN_ccmpno 0x2e9e
#define MN_setno 0x2ea5
#define MN_ctestno 0x2eab
#define MN_setzuno 0x2eb3
#define MN_cmovno (MN_cfcmovno + 2)
#define MN_cfcmovno 0x2ebb
#define MN_jpo 0x2ec4
#define MN_ccmpo 0x2ec8
#define MN_setpo 0x2ece
#define MN_setzupo 0x2ed4
#define MN_cmovpo (MN_cfcmovpo + 2)
#define MN_cfcmovpo 0x2edc
#define MN_cqo 0x2ee5
#define MN_tilezero 0x2ee9
#define MN_clzero 0x2ef2
#define MN_seto 0x2ef9
#define MN_into 0x2efe
#define MN_cqto 0x2f03
#define MN_ctesto 0x2f08
#define MN_ssto 0x2f0f
#define MN_setzuo 0x2f14
#define MN_cmovo (MN_cfcmovo + 2)
#define MN_cfcmovo 0x2f1b
#define MN_push2p 0x2f23
#define MN_pop2p 0x2f2a
#define MN_bswap 0x2f30
#define MN_fsubp 0x2f36
#define MN_pfrcp 0x2f3c
#define MN_rdtscp 0x2f42
#define MN_faddp 0x2f49
#define MN_pdep 0x2f4f
#define MN_ffreep 0x2f54
#define MN_rep 0x2f5b
#define MN_pushp 0x2f5f
#define MN_fcomip 0x2f65
#define MN_fucomip 0x2f6c
#define MN_jp 0x2f74
#define MN_fmulp 0x2f77
#define MN_cmp (MN_scmp + 1)
#define MN_scmp 0x2f7d
#define MN_jmp (MN_ljmp + 1)
#define MN_ljmp 0x2f82
#define MN_fcomp 0x2f87
#define MN_ficomp 0x2f8d
#define MN_fucomp 0x2f94
#define MN_jnp 0x2f9b
#define MN_setnp 0x2f9f
#define MN_setzunp 0x2fa5
#define MN_cmovnp (MN_cfcmovnp + 2)
#define MN_cfcmovnp 0x2fad
#define MN_nop (MN_fnop + 1)
#define MN_fnop 0x2fb6
#define MN_loop 0x2fbb
#define MN_pop 0x2fc0
#define MN_fcompp 0x2fc4
#define MN_fucompp 0x2fcb
#define MN_popp 0x2fd3
#define MN_fsubrp 0x2fd8
#define MN_fdivrp 0x2fdf
#define MN_rstorssp 0x2fe6
#define MN_saveprevssp 0x2fef
#define MN_setp 0x2ffb
#define MN_fbstp 0x3000
#define MN_fdecstp 0x3006
#define MN_fincstp 0x300e
#define MN_fstp 0x3016
#define MN_fistp 0x301b
#define MN_fisttp 0x3021
#define MN_movddup (MN_vmovddup + 1)
#define MN_vmovddup 0x3028
#define MN_movshdup (MN_vmovshdup + 1)
#define MN_vmovshdup 0x3031
#define MN_movsldup (MN_vmovsldup + 1)
#define MN_vmovsldup 0x303b
#define MN_setzup 0x3045
#define MN_fdivp 0x304c
#define MN_cmovp (MN_cfcmovp + 2)
#define MN_cfcmovp 0x3052
#define MN_xmodexp 0x305a
#define MN_vpbroadcastmb2q 0x3062
#define MN_vpermi2q 0x3072
#define MN_vpmovm2q 0x307b
#define MN_movdq2q 0x3084
#define MN_vpermt2q 0x308c
#define MN_vpshaq 0x3095
#define MN_vpsraq 0x309c
#define MN_vphaddbq 0x30a3
#define MN_vphaddubq 0x30ac
#define MN_psubq (MN_vpsubq + 1)
#define MN_vpsubq 0x30b6
#define MN_pmovsxbq (MN_vpmovsxbq + 1)
#define MN_vpmovsxbq 0x30bd
#define MN_pmovzxbq (MN_vpmovzxbq + 1)
#define MN_vpmovzxbq 0x30c7
#define MN_cvttpd2dq (MN_vcvttpd2dq + 1)
#define MN_vcvttpd2dq 0x30d1
#define MN_cvtpd2dq (MN_vcvtpd2dq + 1)
#define MN_vcvtpd2dq 0x30dc
#define MN_vcvttph2dq 0x30e6
#define MN_vcvtph2dq 0x30f1
#define MN_movq2dq 0x30fb
#define MN_cvttps2dq (MN_vcvttps2dq + 1)
#define MN_vcvttps2dq 0x3103
#define MN_cvtps2dq (MN_vcvtps2dq + 1)
#define MN_vcvtps2dq 0x310e
#define MN_vphsubdq 0x3118
#define MN_cdq 0x3121
#define MN_kaddq 0x3125
#define MN_paddq (MN_vpaddq + 1)
#define MN_vpaddq 0x312b
#define MN_vphadddq 0x3132
#define MN_punpckhdq (MN_vpunpckhdq + 1)
#define MN_vpunpckhdq 0x313b
#define MN_kunpckdq 0x3146
#define MN_vpshldq 0x314f
#define MN_punpckldq (MN_vpunpckldq + 1)
#define MN_vpunpckldq 0x3157
#define MN_pslldq (MN_vpslldq + 1)
#define MN_vpslldq 0x3162
#define MN_psrldq (MN_vpsrldq + 1)
#define MN_vpsrldq 0x316a
#define MN_pmuldq (MN_vpmuldq + 1)
#define MN_vpmuldq 0x3172
#define MN_kandq 0x317a
#define MN_vpandq 0x3180
#define MN_vpexpandq 0x3187
#define MN_punpckhqdq (MN_vpunpckhqdq + 1)
#define MN_vpunpckhqdq 0x3191
#define MN_pclmulhqhqdq (MN_vpclmulhqhqdq + 1)
#define MN_vpclmulhqhqdq 0x319d
#define MN_pclmullqhqdq (MN_vpclmullqhqdq + 1)
#define MN_vpclmullqhqdq 0x31ab
#define MN_punpcklqdq (MN_vpunpcklqdq + 1)
#define MN_vpunpcklqdq 0x31b9
#define MN_pclmulhqlqdq (MN_vpclmulhqlqdq + 1)
#define MN_vpclmulhqlqdq 0x31c5
#define MN_pclmullqlqdq (MN_vpclmullqlqdq + 1)
#define MN_vpclmullqlqdq 0x31d3
#define MN_pclmulqdq (MN_vpclmulqdq + 1)
#define MN_vpclmulqdq 0x31e1
#define MN_vpgatherdq 0x31ec
#define MN_vpscatterdq 0x31f7
#define MN_vpshrdq 0x3203
#define MN_movntdq (MN_vmovntdq + 1)
#define MN_vmovntdq 0x320b
#define MN_vcvttpd2udq 0x3214
#define MN_vcvtpd2udq 0x3220
#define MN_vcvttph2udq 0x322b
#define MN_vcvtph2udq 0x3237
#define MN_vcvttps2udq 0x3242
#define MN_vcvtps2udq 0x324e
#define MN_vphaddudq 0x3259
#define MN_pmuludq (MN_vpmuludq + 1)
#define MN_vpmuludq 0x3263
#define MN_pmovsxdq (MN_vpmovsxdq + 1)
#define MN_vpmovsxdq 0x326c
#define MN_pmovzxdq (MN_vpmovzxdq + 1)
#define MN_vpmovzxdq 0x3276
#define MN_vpcomgeq 0x3280
#define MN_vpcomleq 0x3289
#define MN_vpcmpnleq 0x3292
#define MN_vpcmpleq 0x329c
#define MN_pfcmpeq 0x32a5
#define MN_vpcomfalseq 0x32ad
#define MN_vpcomtrueq 0x32b9
#define MN_vpternlogq 0x32c4
#define MN_vpshlq 0x32cf
#define MN_psllq (MN_vpsllq + 1)
#define MN_vpsllq 0x32d6
#define MN_vpmullq 0x32dd
#define MN_vprolq 0x32e5
#define MN_psrlq (MN_vpsrlq + 1)
#define MN_vpsrlq 0x32ec
#define MN_kshiftlq 0x32f3
#define MN_vpblendmq 0x32fc
#define MN_vptestnmq 0x3306
#define MN_vpcomq 0x3310
#define MN_vpermq 0x3317
#define MN_vptestmq 0x331e
#define MN_kandnq 0x3327
#define MN_vpandnq 0x332e
#define MN_valignq 0x3336
#define MN_vpcmpq 0x333e
#define MN_incsspq 0x3345
#define MN_rdsspq 0x334d
#define MN_vcvttpd2qq 0x3354
#define MN_vcvtpd2qq 0x335f
#define MN_vcvttph2qq 0x3369
#define MN_vcvtph2qq 0x3374
#define MN_vcvttps2qq 0x337e
#define MN_vcvtps2qq 0x3389
#define MN_vpcomeqq 0x3393
#define MN_vpcomneqq 0x339c
#define MN_vpcmpneqq 0x33a6
#define MN_pcmpeqq (MN_vpcmpeqq + 1)
#define MN_vpcmpeqq 0x33b0
#define MN_vpgatherqq 0x33b9
#define MN_vpscatterqq 0x33c4
#define MN_vcvttpd2uqq 0x33d0
#define MN_vcvtpd2uqq 0x33dc
#define MN_vcvttph2uqq 0x33e7
#define MN_vcvtph2uqq 0x33f3
#define MN_vcvttps2uqq 0x33fe
#define MN_vcvtps2uqq 0x340a
#define MN_korq 0x3415
#define MN_kxnorq 0x341a
#define MN_vporq 0x3421
#define MN_vprorq 0x3427
#define MN_kxorq 0x342e
#define MN_vpxorq 0x3434
#define MN_pinsrq (MN_vpinsrq + 1)
#define MN_vpinsrq 0x343b
#define MN_kshiftrq 0x3443
#define MN_extrq (MN_pextrq + 1)
#define MN_pextrq (MN_vpextrq + 1)
#define MN_vpextrq 0x344c
#define MN_vpabsq 0x3454
#define MN_vpminsq 0x345b
#define MN_vmovrsq 0x3463
#define MN_vpcompressq 0x346b
#define MN_wrssq 0x3477
#define MN_wrussq 0x347d
#define MN_vpmaxsq 0x3484
#define MN_vp2intersectq 0x348c
#define MN_vpconflictq 0x349a
#define MN_vpcomgtq 0x34a6
#define MN_pcmpgtq (MN_vpcmpgtq + 1)
#define MN_vpcmpgtq 0x34af
#define MN_cltq 0x34b8
#define MN_vpcomltq 0x34bd
#define MN_vpcmpnltq 0x34c6
#define MN_vpcmpltq 0x34d0
#define MN_vpopcntq 0x34d9
#define MN_vplzcntq 0x34e2
#define MN_movntq 0x34eb
#define MN_knotq 0x34f2
#define MN_vprotq 0x34f8
#define MN_insertq 0x34ff
#define MN_vpbroadcastq 0x3507
#define MN_ktestq 0x3514
#define MN_kortestq 0x351b
#define MN_vpcomgeuq 0x3524
#define MN_vpcomleuq 0x352e
#define MN_vpcmpnleuq 0x3538
#define MN_vpcmpleuq 0x3543
#define MN_vpcomfalseuq 0x354d
#define MN_vpcomtrueuq 0x355a
#define MN_vpmadd52huq 0x3566
#define MN_vpmadd52luq 0x3572
#define MN_vpcomuq 0x357e
#define MN_vpminuq 0x3586
#define MN_vpcmpuq 0x358e
#define MN_vpcomequq 0x3596
#define MN_vpcomnequq 0x35a0
#define MN_vpcmpnequq 0x35ab
#define MN_vpcmpequq 0x35b6
#define MN_vpcomgtuq 0x35c0
#define MN_vpcomltuq 0x35ca
#define MN_vpcmpnltuq 0x35d4
#define MN_vpcmpltuq 0x35df
#define MN_vpmaxuq 0x35e9
#define MN_vpsravq 0x35f1
#define MN_vpshldvq 0x35f9
#define MN_vpshrdvq 0x3602
#define MN_vpsllvq 0x360b
#define MN_vprolvq 0x3613
#define MN_vpsrlvq 0x361b
#define MN_movq (MN_kmovq + 1)
#define MN_kmovq (MN_maskmovq + 3)
#define MN_maskmovq (MN_vpmaskmovq + 2)
#define MN_vpmaskmovq 0x3623
#define MN_vmovq 0x362e
#define MN_vprorvq 0x3634
#define MN_vphaddwq 0x363c
#define MN_vphadduwq 0x3645
#define MN_pmovsxwq (MN_vpmovsxwq + 1)
#define MN_vpmovsxwq 0x364f
#define MN_pmovzxwq (MN_vpmovzxwq + 1)
#define MN_vpmovzxwq 0x3659
#define MN_rex_r 0x3663
#define MN_vmclear 0x3669
#define MN_lar 0x3671
#define MN_sar 0x3675
#define MN_fsubr (MN_pfsubr + 1)
#define MN_pfsubr 0x3679
#define MN_fisubr 0x3680
#define MN_rcr 0x3687
#define MN_vzeroupper 0x368b
#define MN_enter (MN_sysenter + 3)
#define MN_sysenter 0x3696
#define MN_shr 0x369f
#define MN_clr 0x36a3
#define MN_palignr (MN_vpalignr + 1)
#define MN_vpalignr 0x36a7
#define MN_or (MN_aor + 1)
#define MN_aor 0x36b0
#define MN_por (MN_vpor + 1)
#define MN_vpor 0x36b4
#define MN_ror 0x36b9
#define MN_monitor (MN_umonitor + 1)
#define MN_umonitor 0x36bd
#define MN_frstor 0x36c6
#define MN_xrstor (MN_fxrstor + 1)
#define MN_fxrstor 0x36cd
#define MN_xor (MN_axor + 1)
#define MN_axor 0x36d5
#define MN_pxor (MN_vpxor + 1)
#define MN_vpxor 0x36da
#define MN_verr 0x36e0
#define MN_bsr 0x36e5
#define MN_ldmxcsr (MN_vldmxcsr + 1)
#define MN_vldmxcsr 0x36e9
#define MN_stmxcsr (MN_vstmxcsr + 1)
#define MN_vstmxcsr 0x36f2
#define MN_blsr 0x36fb
#define MN_rdmsr (MN_urdmsr + 1)
#define MN_urdmsr 0x3700
#define MN_wrmsr (MN_uwrmsr + 1)
#define MN_uwrmsr 0x3707
#define MN_btr 0x370e
#define MN_xcrypt_ctr 0x3712
#define MN_xcryptctr 0x371d
#define MN_ltr 0x3727
#define MN_str 0x372b
#define MN_bextr 0x372f
#define MN_fdivr 0x3735
#define MN_fidivr 0x373b
#define MN_rex_wr 0x3742
#define MN_vcvtbf82bf4s 0x3749
#define MN_vcvthf82bf4s 0x3756
#define MN_vcvtbf82bf6s 0x3763
#define MN_vcvthf82hf6s 0x3770
#define MN_vcvt2ph2bf8s 0x377d
#define MN_vcvtbiasph2bf8s 0x378a
#define MN_vcvtph2bf8s 0x379a
#define MN_vcvtbiasps2bf8s 0x37a6
#define MN_vcvtps2bf8s 0x37b6
#define MN_vcvt2ph2hf8s 0x37c2
#define MN_vcvtbiasph2hf8s 0x37cf
#define MN_vcvtph2hf8s 0x37df
#define MN_vcvtrops2hf8s 0x37eb
#define MN_vcvtbiasps2hf8s 0x37f9
#define MN_vcvtps2hf8s 0x3809
#define MN_aas 0x3815
#define MN_scas 0x3819
#define MN_das 0x381e
#define MN_fabs 0x3822
#define MN_jmpabs 0x3827
#define MN_movabs 0x382e
#define MN_vcvttbf162ibs 0x3835
#define MN_vcvtbf162ibs 0x3843
#define MN_vcvttph2ibs 0x3850
#define MN_vcvtph2ibs 0x385c
#define MN_vcvttps2ibs 0x3867
#define MN_vcvtps2ibs 0x3873
#define MN_vcvttbf162iubs 0x387e
#define MN_vcvtbf162iubs 0x388d
#define MN_vcvttph2iubs 0x389b
#define MN_vcvtph2iubs 0x38a8
#define MN_vcvttps2iubs 0x38b4
#define MN_vcvtps2iubs 0x38c1
#define MN_cs (MN_blcs + 2)
#define MN_blcs 0x38cd
#define MN_ds (MN_lds + 1)
#define MN_lds 0x38d2
#define MN_enqcmds 0x38d6
#define MN_lods 0x38de
#define MN_vpdpbssds 0x38e3
#define MN_vp4dpwssds 0x38ed
#define MN_vpdpwssds 0x38f8
#define MN_vpdpbusds 0x3902
#define MN_vpdpwusds 0x390c
#define MN_vpdpbsuds 0x3916
#define MN_vpdpwsuds 0x3920
#define MN_vpdpbuuds 0x392a
#define MN_vpdpwuuds 0x3934
#define MN_es (MN_les + 1)
#define MN_les 0x393e
#define MN_xsaves 0x3942
#define MN_fs (MN_lfs + 1)
#define MN_lfs 0x3949
#define MN_gs (MN_lkgs + 2)
#define MN_lkgs 0x394d
#define MN_lgs 0x3952
#define MN_swapgs 0x3956
#define MN_fchs 0x395d
#define MN_vcvttsd2sis 0x3962
#define MN_vcvttss2sis 0x396e
#define MN_vcvttsd2usis 0x397a
#define MN_vcvttss2usis 0x3987
#define MN_js 0x3994
#define MN_encls 0x3997
#define MN_emms (MN_femms + 1)
#define MN_femms 0x399d
#define MN_ins (MN_lwpins + 3)
#define MN_lwpins 0x39a3
#define MN_jns 0x39aa
#define MN_ccmpns 0x39ae
#define MN_wrmsrns 0x39b5
#define MN_setns 0x39bd
#define MN_ctestns 0x39c3
#define MN_setzuns 0x39cb
#define MN_cmovns (MN_cfcmovns + 2)
#define MN_cfcmovns 0x39d3
#define MN_fcos 0x39dc
#define MN_fsincos 0x39e1
#define MN_stos 0x39e9
#define MN_vfmaddsub231ps 0x39ee
#define MN_vfmsub231ps 0x39fd
#define MN_vfnmsub231ps 0x3a09
#define MN_vfmsubadd231ps 0x3a16
#define MN_vfmadd231ps 0x3a25
#define MN_vfnmadd231ps 0x3a31
#define MN_vfmaddsub132ps 0x3a3e
#define MN_vfmsub132ps 0x3a4d
#define MN_vfnmsub132ps 0x3a59
#define MN_vfmsubadd132ps 0x3a66
#define MN_vfmadd132ps 0x3a75
#define MN_vfnmadd132ps 0x3a81
#define MN_tmmultf32ps (MN_ttmmultf32ps + 1)
#define MN_ttmmultf32ps 0x3a8e
#define MN_vcvtneebf162ps 0x3a9b
#define MN_vbcstnebf162ps 0x3aaa
#define MN_vcvtneobf162ps 0x3ab9
#define MN_vcvtbf82ps 0x3ac8
#define MN_vcvthf82ps 0x3ad3
#define MN_cvtpd2ps (MN_vcvtpd2ps + 1)
#define MN_vcvtpd2ps 0x3ade
#define MN_tcvtrowd2ps 0x3ae8
#define MN_vcvtneeph2ps 0x3af4
#define MN_vcvtneoph2ps 0x3b01
#define MN_vcvtph2ps 0x3b0e
#define MN_vbcstnesh2ps 0x3b18
#define MN_vpermi2ps 0x3b25
#define MN_cvtpi2ps 0x3b2f
#define MN_vpermil2ps 0x3b38
#define MN_vexp2ps 0x3b43
#define MN_cvtdq2ps (MN_vcvtdq2ps + 1)
#define MN_vcvtdq2ps 0x3b4b
#define MN_vcvtudq2ps 0x3b55
#define MN_vcvtqq2ps 0x3b60
#define MN_vcvtuqq2ps 0x3b6a
#define MN_vpermt2ps 0x3b75
#define MN_vfmaddsub213ps 0x3b7f
#define MN_vfmsub213ps 0x3b8e
#define MN_vfnmsub213ps 0x3b9a
#define MN_vfmsubadd213ps 0x3ba7
#define MN_vfmadd213ps 0x3bb6
#define MN_vfnmadd213ps 0x3bc2
#define MN_vrcp14ps 0x3bcf
#define MN_vrsqrt14ps 0x3bd8
#define MN_tdpbf16ps (MN_ttdpbf16ps + 1)
#define MN_ttdpbf16ps 0x3be3
#define MN_vdpbf16ps 0x3bee
#define MN_tcmmrlfp16ps (MN_ttcmmrlfp16ps + 1)
#define MN_ttcmmrlfp16ps 0x3bf8
#define MN_tcmmimfp16ps (MN_tconjtcmmimfp16ps + 5)
#define MN_tconjtcmmimfp16ps 0x3c06
#define MN_ttcmmimfp16ps 0x3c18
#define MN_tdpfp16ps (MN_ttdpfp16ps + 1)
#define MN_ttdpfp16ps 0x3c26
#define MN_vrcp28ps 0x3c31
#define MN_vrsqrt28ps 0x3c3a
#define MN_tdphbf8ps 0x3c45
#define MN_tdpbf8ps 0x3c4f
#define MN_tdpbhf8ps 0x3c58
#define MN_tdphf8ps 0x3c62
#define MN_movaps (MN_vmovaps + 1)
#define MN_vmovaps 0x3c6b
#define MN_subps (MN_addsubps + 3)
#define MN_addsubps (MN_vfmaddsubps + 3)
#define MN_vfmaddsubps 0x3c73
#define MN_vaddsubps 0x3c7f
#define MN_hsubps (MN_vhsubps + 1)
#define MN_vhsubps 0x3c89
#define MN_vfmsubps 0x3c91
#define MN_vfnmsubps 0x3c9a
#define MN_vsubps 0x3ca4
#define MN_vgatherpf0dps 0x3cab
#define MN_vscatterpf0dps 0x3cb9
#define MN_vgatherpf1dps 0x3cc8
#define MN_vscatterpf1dps 0x3cd6
#define MN_addps (MN_vfmsubaddps + 6)
#define MN_vfmsubaddps 0x3ce5
#define MN_haddps (MN_vhaddps + 1)
#define MN_vhaddps 0x3cf1
#define MN_v4fmaddps 0x3cf9
#define MN_vfmaddps 0x3d03
#define MN_v4fnmaddps 0x3d0c
#define MN_vfnmaddps 0x3d17
#define MN_vaddps 0x3d21
#define MN_andps (MN_vexpandps + 4)
#define MN_vexpandps 0x3d28
#define MN_vandps 0x3d32
#define MN_blendps (MN_vblendps + 1)
#define MN_vblendps 0x3d39
#define MN_roundps (MN_vroundps + 1)
#define MN_vroundps 0x3d42
#define MN_vgatherdps 0x3d4b
#define MN_vscatterdps 0x3d56
#define MN_cmpunordps (MN_vcmpunordps + 1)
#define MN_vcmpunordps 0x3d62
#define MN_cmpordps (MN_vcmpordps + 1)
#define MN_vcmpordps 0x3d6e
#define MN_vreduceps 0x3d78
#define MN_vrangeps 0x3d82
#define MN_vcmpngeps 0x3d8b
#define MN_vcmpgeps 0x3d95
#define MN_vrndscaleps 0x3d9e
#define MN_cmpnleps (MN_vcmpnleps + 1)
#define MN_vcmpnleps 0x3daa
#define MN_cmpleps (MN_vcmpleps + 1)
#define MN_vcmpleps 0x3db4
#define MN_vcmpfalseps 0x3dbd
#define MN_vcmptrueps 0x3dc9
#define MN_vscalefps 0x3dd4
#define MN_shufps (MN_vshufps + 1)
#define MN_vshufps 0x3dde
#define MN_unpckhps (MN_vunpckhps + 1)
#define MN_vunpckhps 0x3de6
#define MN_movlhps (MN_vmovlhps + 1)
#define MN_vmovlhps 0x3df0
#define MN_vdpphps 0x3df9
#define MN_movhps (MN_vmovhps + 1)
#define MN_vmovhps 0x3e01
#define MN_movmskps (MN_vmovmskps + 1)
#define MN_vmovmskps 0x3e09
#define MN_movhlps (MN_vmovhlps + 1)
#define MN_vmovhlps 0x3e13
#define MN_vpermilps 0x3e1c
#define MN_unpcklps (MN_vunpcklps + 1)
#define MN_vunpcklps 0x3e26
#define MN_mulps (MN_vmulps + 1)
#define MN_vmulps 0x3e30
#define MN_movlps (MN_vmovlps + 1)
#define MN_vmovlps 0x3e37
#define MN_cmps (MN_ccmps + 1)
#define MN_ccmps 0x3e3f
#define MN_vblendmps 0x3e45
#define MN_vfixupimmps 0x3e4f
#define MN_vpermps 0x3e5b
#define MN_andnps (MN_vandnps + 1)
#define MN_vandnps 0x3e63
#define MN_minps (MN_vminps + 1)
#define MN_vminps 0x3e6b
#define MN_seamops 0x3e72
#define MN_rcpps (MN_vrcpps + 1)
#define MN_vrcpps 0x3e7a
#define MN_dpps (MN_vdpps + 1)
#define MN_vdpps 0x3e81
#define MN_cmpps (MN_vcmpps + 1)
#define MN_vcmpps 0x3e87
#define MN_vgetexpps 0x3e8e
#define MN_vgatherpf0qps 0x3e98
#define MN_vscatterpf0qps 0x3ea6
#define MN_vgatherpf1qps 0x3eb5
#define MN_vscatterpf1qps 0x3ec3
#define MN_vcmpunord_qps 0x3ed2
#define MN_vcmpord_qps 0x3ee0
#define MN_cmpneqps (MN_vcmpneqps + 1)
#define MN_vcmpneqps 0x3eec
#define MN_cmpeqps (MN_vcmpeqps + 1)
#define MN_vcmpeqps 0x3ef6
#define MN_vcmpge_oqps 0x3eff
#define MN_vcmple_oqps 0x3f0b
#define MN_vcmpfalse_oqps 0x3f17
#define MN_vcmpneq_oqps 0x3f26
#define MN_vcmpeq_oqps 0x3f33
#define MN_vcmpgt_oqps 0x3f3f
#define MN_vcmplt_oqps 0x3f4b
#define MN_vgatherqps 0x3f57
#define MN_vscatterqps 0x3f62
#define MN_vcmpnge_uqps 0x3f6e
#define MN_vcmpnle_uqps 0x3f7b
#define MN_vcmptrue_uqps 0x3f88
#define MN_vcmpneq_uqps 0x3f96
#define MN_vcmpeq_uqps 0x3fa3
#define MN_vcmpngt_uqps 0x3faf
#define MN_vcmpnlt_uqps 0x3fbc
#define MN_orps (MN_vorps + 1)
#define MN_vorps 0x3fc9
#define MN_xorps (MN_vxorps + 1)
#define MN_vxorps 0x3fcf
#define MN_vcmpunord_sps 0x3fd6
#define MN_vcmpord_sps 0x3fe4
#define MN_vcmpge_osps 0x3ff0
#define MN_vcmple_osps 0x3ffc
#define MN_vcmpfalse_osps 0x4008
#define MN_vcmpneq_osps 0x4017
#define MN_vcmpeq_osps 0x4024
#define MN_vcmpgt_osps 0x4030
#define MN_vcmplt_osps 0x403c
#define MN_vfpclassps 0x4048
#define MN_vcompressps 0x4053
#define MN_vcmpnge_usps 0x405f
#define MN_vcmpnle_usps 0x406c
#define MN_vcmptrue_usps 0x4079
#define MN_vcmpneq_usps 0x4087
#define MN_vcmpeq_usps 0x4094
#define MN_vcmpngt_usps 0x40a0
#define MN_vcmpnlt_usps 0x40ad
#define MN_extractps (MN_vextractps + 1)
#define MN_vextractps 0x40ba
#define MN_vcmpngtps 0x40c5
#define MN_vcmpgtps 0x40cf
#define MN_cmpnltps (MN_vcmpnltps + 1)
#define MN_vcmpnltps 0x40d8
#define MN_cmpltps (MN_vcmpltps + 1)
#define MN_vcmpltps 0x40e2
#define MN_vgetmantps 0x40eb
#define MN_movntps (MN_vmovntps + 1)
#define MN_vmovntps 0x40f6
#define MN_insertps (MN_vinsertps + 1)
#define MN_vinsertps 0x40ff
#define MN_sqrtps (MN_rsqrtps + 1)
#define MN_rsqrtps (MN_vrsqrtps + 1)
#define MN_vrsqrtps 0x4109
#define MN_vsqrtps 0x4112
#define MN_vtestps 0x411a
#define MN_movups (MN_vmovups + 1)
#define MN_vmovups 0x4122
#define MN_blendvps (MN_vblendvps + 1)
#define MN_vblendvps 0x412a
#define MN_divps (MN_vdivps + 1)
#define MN_vdivps 0x4134
#define MN_vmaskmovps 0x413b
#define MN_maxps (MN_vminmaxps + 4)
#define MN_vminmaxps 0x4146
#define MN_vmaxps 0x4150
#define MN_vfrczps 0x4157
#define MN_vcvttpd2dqs 0x415f
#define MN_vcvttps2dqs 0x416b
#define MN_vcvttpd2udqs 0x4177
#define MN_vcvttps2udqs 0x4184
#define MN_vcvttpd2qqs 0x4191
#define MN_vcvttps2qqs 0x419d
#define MN_vcvttpd2uqqs 0x41a9
#define MN_vcvttps2uqqs 0x41b6
#define MN_t2rpntlvwz0rs 0x41c3
#define MN_t2rpntlvwz1rs 0x41d1
#define MN_tileloaddrs 0x41df
#define MN_xrstors 0x41eb
#define MN_movrs 0x41f3
#define MN_ss (MN_vfmsub231ss + 9)
#define MN_vfmsub231ss 0x41f9
#define MN_vfnmsub231ss 0x4205
#define MN_vfmadd231ss 0x4212
#define MN_vfnmadd231ss 0x421e
#define MN_vfmsub132ss 0x422b
#define MN_vfnmsub132ss 0x4237
#define MN_vfmadd132ss 0x4244
#define MN_vfnmadd132ss 0x4250
#define MN_cvtsd2ss (MN_vcvtsd2ss + 1)
#define MN_vcvtsd2ss 0x425d
#define MN_vcvtsh2ss 0x4267
#define MN_cvtsi2ss (MN_vcvtsi2ss + 1)
#define MN_vcvtsi2ss 0x4271
#define MN_vcvtusi2ss 0x427b
#define MN_vfmsub213ss 0x4286
#define MN_vfnmsub213ss 0x4292
#define MN_vfmadd213ss 0x429f
#define MN_vfnmadd213ss 0x42ab
#define MN_vrcp14ss 0x42b8
#define MN_vrsqrt14ss 0x42c1
#define MN_vrcp28ss 0x42cc
#define MN_vrsqrt28ss 0x42d5
#define MN_subss (MN_vfmsubss + 3)
#define MN_vfmsubss 0x42e0
#define MN_vfnmsubss 0x42e9
#define MN_vsubss 0x42f3
#define MN_addss (MN_v4fmaddss + 4)
#define MN_v4fmaddss 0x42fa
#define MN_vfmaddss 0x4304
#define MN_v4fnmaddss 0x430d
#define MN_vfnmaddss 0x4318
#define MN_vaddss 0x4322
#define MN_roundss (MN_vroundss + 1)
#define MN_vroundss 0x4329
#define MN_cmpunordss (MN_vcmpunordss + 1)
#define MN_vcmpunordss 0x4332
#define MN_cmpordss (MN_vcmpordss + 1)
#define MN_vcmpordss 0x433e
#define MN_vreducess 0x4348
#define MN_vrangess 0x4352
#define MN_vcmpngess 0x435b
#define MN_vcmpgess 0x4365
#define MN_vrndscaless 0x436e
#define MN_cmpnless (MN_vcmpnless + 1)
#define MN_vcmpnless 0x437a
#define MN_cmpless (MN_vcmpless + 1)
#define MN_vcmpless 0x4384
#define MN_vcmpfalsess 0x438d
#define MN_vcmptruess 0x4399
#define MN_vscalefss 0x43a4
#define MN_comiss (MN_ucomiss + 1)
#define MN_ucomiss (MN_vucomiss + 1)
#define MN_vucomiss 0x43ae
#define MN_vcomiss 0x43b7
#define MN_lss (MN_mulss + 2)
#define MN_mulss (MN_vmulss + 1)
#define MN_vmulss 0x43bf
#define MN_vfixupimmss 0x43c6
#define MN_minss (MN_vminss + 1)
#define MN_vminss 0x43d2
#define MN_rcpss (MN_vrcpss + 1)
#define MN_vrcpss 0x43d9
#define MN_cmpss (MN_vcmpss + 1)
#define MN_vcmpss 0x43e0
#define MN_vgetexpss 0x43e7
#define MN_vcmpunord_qss 0x43f1
#define MN_vcmpord_qss 0x43ff
#define MN_cmpneqss (MN_vcmpneqss + 1)
#define MN_vcmpneqss 0x440b
#define MN_cmpeqss (MN_vcmpeqss + 1)
#define MN_vcmpeqss 0x4415
#define MN_vcmpge_oqss 0x441e
#define MN_vcmple_oqss 0x442a
#define MN_vcmpfalse_oqss 0x4436
#define MN_vcmpneq_oqss 0x4445
#define MN_vcmpeq_oqss 0x4452
#define MN_vcmpgt_oqss 0x445e
#define MN_vcmplt_oqss 0x446a
#define MN_vcmpnge_uqss 0x4476
#define MN_vcmpnle_uqss 0x4483
#define MN_vcmptrue_uqss 0x4490
#define MN_vcmpneq_uqss 0x449e
#define MN_vcmpeq_uqss 0x44ab
#define MN_vcmpngt_uqss 0x44b7
#define MN_vcmpnlt_uqss 0x44c4
#define MN_vcmpunord_sss 0x44d1
#define MN_vcmpord_sss 0x44df
#define MN_vcmpge_osss 0x44eb
#define MN_vcmple_osss 0x44f7
#define MN_vcmpfalse_osss 0x4503
#define MN_vcmpneq_osss 0x4512
#define MN_vcmpeq_osss 0x451f
#define MN_vcmpgt_osss 0x452b
#define MN_vcmplt_osss 0x4537
#define MN_vfpclassss 0x4543
#define MN_vcmpnge_usss 0x454e
#define MN_vcmpnle_usss 0x455b
#define MN_vcmptrue_usss 0x4568
#define MN_vcmpneq_usss 0x4576
#define MN_vcmpeq_usss 0x4583
#define MN_vcmpngt_usss 0x458f
#define MN_vcmpnlt_usss 0x459c
#define MN_vcmpngtss 0x45a9
#define MN_vcmpgtss 0x45b3
#define MN_cmpnltss (MN_vcmpnltss + 1)
#define MN_vcmpnltss 0x45bc
#define MN_cmpltss (MN_vcmpltss + 1)
#define MN_vcmpltss 0x45c6
#define MN_vgetmantss 0x45cf
#define MN_movntss 0x45da
#define MN_sqrtss (MN_rsqrtss + 1)
#define MN_rsqrtss (MN_vrsqrtss + 1)
#define MN_vrsqrtss 0x45e2
#define MN_vsqrtss 0x45eb
#define MN_vbroadcastss 0x45f3
#define MN_divss (MN_vdivss + 1)
#define MN_vdivss 0x4600
#define MN_movss (MN_vmovss + 1)
#define MN_vmovss 0x4607
#define MN_maxss (MN_vminmaxss + 4)
#define MN_vminmaxss 0x460e
#define MN_vmaxss 0x4618
#define MN_vucomxss 0x461f
#define MN_vcomxss 0x4628
#define MN_vfrczss 0x4630
#define MN_bts 0x4638
#define MN_erets 0x463c
#define MN_sets 0x4642
#define MN_clts 0x4647
#define MN_ctests 0x464c
#define MN_outs 0x4653
#define MN_setzus 0x4658
#define MN_movs (MN_cmovs + 1)
#define MN_cmovs (MN_cfcmovs + 2)
#define MN_cfcmovs 0x465f
#define MN_fldl2t 0x4667
#define MN_xlat 0x466e
#define MN_bt 0x4673
#define MN_fxtract 0x4676
#define MN_lgdt 0x467e
#define MN_sgdt 0x4683
#define MN_lidt 0x4688
#define MN_sidt 0x468d
#define MN_fldt 0x4692
#define MN_lldt 0x4697
#define MN_sldt 0x469c
#define MN_ret (MN_iret + 1)
#define MN_iret (MN_uiret + 1)
#define MN_uiret 0x46a1
#define MN_lret 0x46a7
#define MN_seamret 0x46ac
#define MN_sysret 0x46b4
#define MN_hreset 0x46bb
#define MN_pfcmpgt 0x46c2
#define MN_ht 0x46ca
#define MN_wait (MN_fwait + 1)
#define MN_fwait 0x46cd
#define MN_mwait (MN_umwait + 1)
#define MN_umwait 0x46d3
#define MN_mcommit 0x46da
#define MN_finit 0x46e2
#define MN_skinit 0x46e8
#define MN_fninit 0x46ef
#define MN_bsrinit 0x46f6
#define MN_vmgexit 0x46fe
#define MN_sysexit 0x4706
#define MN_hlt 0x470e
#define MN_popcnt 0x4712
#define MN_lzcnt 0x4719
#define MN_tzcnt 0x471f
#define MN_hnt 0x4725
#define MN_int (MN_frndint + 4)
#define MN_frndint 0x4729
#define MN_not 0x4731
#define MN_invept 0x4735
#define MN_ccmpt 0x473c
#define MN_xsaveopt 0x4742
#define MN_clflushopt 0x474b
#define MN_rmpopt 0x4756
#define MN_fstpt 0x475d
#define MN_xabort 0x4763
#define MN_fsqrt 0x476a
#define MN_pfrsqrt 0x4770
#define MN_aesdeclast (MN_vaesdeclast + 1)
#define MN_vaesdeclast 0x4778
#define MN_aesenclast (MN_vaesenclast + 1)
#define MN_vaesenclast 0x4784
#define MN_test (MN_ptest + 1)
#define MN_ptest (MN_vptest + 1)
#define MN_vptest 0x4790
#define MN_xtest 0x4797
#define MN_fst 0x479d
#define MN_fist 0x47a1
#define MN_rdmsrlist 0x47a6
#define MN_wrmsrlist 0x47b0
#define MN_aeskeygenassist (MN_vaeskeygenassist + 1)
#define MN_vaeskeygenassist 0x47ba
#define MN_vmptrst 0x47cb
#define MN_ftst 0x47d3
#define MN_rmpadjust 0x47d8
#define MN_ctestt 0x47e2
#define MN_out 0x47e9
#define MN_pext 0x47ed
#define MN_bndcu 0x47f2
#define MN_enclu 0x47f8
#define MN_fcmovnu 0x47fe
#define MN_lddqu (MN_vlddqu + 1)
#define MN_vlddqu 0x4806
#define MN_movdqu (MN_maskmovdqu + 4)
#define MN_maskmovdqu (MN_vmaskmovdqu + 1)
#define MN_vmaskmovdqu 0x480d
#define MN_vmovdqu 0x4819
#define MN_rdpkru 0x4821
#define MN_wrpkru 0x4828
#define MN_rdpru 0x482f
#define MN_eretu 0x4835
#define MN_fcmovu 0x483b
#define MN_imulzu 0x4842
#define MN_xgetbv 0x4849
#define MN_xsetbv 0x4850
#define MN_div (MN_fdiv + 1)
#define MN_fdiv 0x4857
#define MN_idiv (MN_fidiv + 1)
#define MN_fidiv 0x485c
#define MN_enclv 0x4862
#define MN_fldenv 0x4868
#define MN_fstenv 0x486f
#define MN_fnstenv 0x4876
#define MN_mov (MN_vpcmov + 3)
#define MN_vpcmov 0x487e
#define MN_bndmov 0x4885
#define MN_smov 0x488c
#define MN_rex_w 0x4891
#define MN_vcvttph2w 0x4897
#define MN_vcvtph2w 0x48a1
#define MN_vpermi2w 0x48aa
#define MN_vpmovm2w 0x48b3
#define MN_vpermt2w 0x48bc
#define MN_vpshaw 0x48c5
#define MN_psraw (MN_vpsraw + 1)
#define MN_vpsraw 0x48cc
#define MN_vphsubbw 0x48d3
#define MN_cbw 0x48dc
#define MN_psadbw (MN_vdbpsadbw + 3)
#define MN_vdbpsadbw 0x48e0
#define MN_mpsadbw (MN_vmpsadbw + 1)
#define MN_vmpsadbw 0x48ea
#define MN_vpsadbw 0x48f3
#define MN_vphaddbw 0x48fb
#define MN_punpckhbw (MN_vpunpckhbw + 1)
#define MN_vpunpckhbw 0x4904
#define MN_kunpckbw 0x490f
#define MN_punpcklbw (MN_vpunpcklbw + 1)
#define MN_vpunpcklbw 0x4918
#define MN_vphaddubw 0x4923
#define MN_phsubw (MN_vphsubw + 1)
#define MN_vphsubw 0x492d
#define MN_psubw (MN_vpsubw + 1)
#define MN_vpsubw 0x4935
#define MN_pmovsxbw (MN_vpmovsxbw + 1)
#define MN_vpmovsxbw 0x493c
#define MN_pmovzxbw (MN_vpmovzxbw + 1)
#define MN_vpmovzxbw 0x4946
#define MN_fldcw 0x4950
#define MN_fstcw 0x4956
#define MN_fnstcw 0x495c
#define MN_phaddw (MN_vphaddw + 1)
#define MN_vphaddw 0x4963
#define MN_kaddw 0x496b
#define MN_paddw (MN_vpaddw + 1)
#define MN_vpaddw 0x4971
#define MN_vpshldw 0x4978
#define MN_kandw 0x4980
#define MN_vpexpandw 0x4986
#define MN_pblendw (MN_vpblendw + 1)
#define MN_vpblendw 0x4990
#define MN_vpshrdw 0x4999
#define MN_packssdw (MN_vpackssdw + 1)
#define MN_vpackssdw 0x49a1
#define MN_packusdw (MN_vpackusdw + 1)
#define MN_vpackusdw 0x49ab
#define MN_vpmovusdw 0x49b5
#define MN_vpmovsdw 0x49bf
#define MN_vpmovdw 0x49c8
#define MN_vpcomgew 0x49d0
#define MN_vpcomlew 0x49d9
#define MN_vpcmpnlew 0x49e2
#define MN_vpcmplew 0x49ec
#define MN_vpcomfalsew 0x49f5
#define MN_vpcomtruew 0x4a01
#define MN_pi2fw 0x4a0c
#define MN_pshufw 0x4a12
#define MN_pavgw (MN_vpavgw + 1)
#define MN_vpavgw 0x4a19
#define MN_prefetchw 0x4a20
#define MN_pshufhw (MN_vpshufhw + 1)
#define MN_vpshufhw 0x4a2a
#define MN_pmulhw (MN_vpmulhw + 1)
#define MN_vpmulhw 0x4a33
#define MN_pf2iw 0x4a3b
#define MN_pshuflw (MN_vpshuflw + 1)
#define MN_vpshuflw 0x4a41
#define MN_vpshlw 0x4a4a
#define MN_psllw (MN_vpsllw + 1)
#define MN_vpsllw 0x4a51
#define MN_pmullw (MN_vpmullw + 1)
#define MN_vpmullw 0x4a58
#define MN_psrlw (MN_vpsrlw + 1)
#define MN_vpsrlw 0x4a60
#define MN_kshiftlw 0x4a67
#define MN_vpblendmw 0x4a70
#define MN_vptestnmw 0x4a7a
#define MN_vpcomw 0x4a84
#define MN_vpermw 0x4a8b
#define MN_vptestmw 0x4a92
#define MN_kandnw 0x4a9b
#define MN_psignw (MN_vpsignw + 1)
#define MN_vpsignw 0x4aa2
#define MN_tilemovrow 0x4aaa
#define MN_vpcmpw 0x4ab5
#define MN_vpcomeqw 0x4abc
#define MN_vpcomneqw 0x4ac5
#define MN_vpcmpneqw 0x4acf
#define MN_pcmpeqw (MN_vpcmpeqw + 1)
#define MN_vpcmpeqw 0x4ad9
#define MN_vpmovusqw 0x4ae2
#define MN_vpmovsqw 0x4aec
#define MN_vpmovqw 0x4af5
#define MN_verw 0x4afd
#define MN_pmulhrw 0x4b02
#define MN_korw 0x4b0a
#define MN_kxnorw 0x4b0f
#define MN_kxorw 0x4b16
#define MN_pinsrw (MN_vpinsrw + 1)
#define MN_vpinsrw 0x4b1c
#define MN_kshiftrw 0x4b24
#define MN_pextrw (MN_vpextrw + 1)
#define MN_vpextrw 0x4b2d
#define MN_pabsw (MN_vpabsw + 1)
#define MN_vpabsw 0x4b35
#define MN_pmaddubsw (MN_vpmaddubsw + 1)
#define MN_vpmaddubsw 0x4b3c
#define MN_phsubsw (MN_vphsubsw + 1)
#define MN_vphsubsw 0x4b47
#define MN_psubsw (MN_vpsubsw + 1)
#define MN_vpsubsw 0x4b50
#define MN_phaddsw (MN_vphaddsw + 1)
#define MN_vphaddsw 0x4b58
#define MN_paddsw (MN_vpaddsw + 1)
#define MN_vpaddsw 0x4b61
#define MN_lmsw 0x4b69
#define MN_smsw 0x4b6e
#define MN_pminsw (MN_vpminsw + 1)
#define MN_vpminsw 0x4b73
#define MN_pmulhrsw (MN_vpmulhrsw + 1)
#define MN_vpmulhrsw 0x4b7b
#define MN_vmovrsw 0x4b85
#define MN_vpcompressw 0x4b8d
#define MN_fstsw 0x4b99
#define MN_fnstsw 0x4b9f
#define MN_psubusw (MN_vpsubusw + 1)
#define MN_vpsubusw 0x4ba6
#define MN_paddusw (MN_vpaddusw + 1)
#define MN_vpaddusw 0x4baf
#define MN_movsw 0x4bb8
#define MN_pmaxsw (MN_vpmaxsw + 1)
#define MN_vpmaxsw 0x4bbe
#define MN_cbtw 0x4bc6
#define MN_vpcomgtw 0x4bcb
#define MN_pcmpgtw (MN_vpcmpgtw + 1)
#define MN_vpcmpgtw 0x4bd4
#define MN_vpcomltw 0x4bdd
#define MN_vpcmpnltw 0x4be6
#define MN_vpcmpltw 0x4bf0
#define MN_vpopcntw 0x4bf9
#define MN_knotw 0x4c02
#define MN_vprotw 0x4c08
#define MN_vpbroadcastw 0x4c0f
#define MN_ktestw 0x4c1c
#define MN_kortestw 0x4c23
#define MN_vcvttph2uw 0x4c2c
#define MN_vcvtph2uw 0x4c37
#define MN_vpcomgeuw 0x4c41
#define MN_vpcomleuw 0x4c4b
#define MN_vpcmpnleuw 0x4c55
#define MN_vpcmpleuw 0x4c60
#define MN_vpcomfalseuw 0x4c6a
#define MN_vpcomtrueuw 0x4c77
#define MN_pmulhuw (MN_vpmulhuw + 1)
#define MN_vpmulhuw 0x4c83
#define MN_vpcomuw 0x4c8c
#define MN_pminuw (MN_vpminuw + 1)
#define MN_vpminuw 0x4c94
#define MN_vpcmpuw 0x4c9c
#define MN_vpcomequw 0x4ca4
#define MN_vpcomnequw 0x4cae
#define MN_vpcmpnequw 0x4cb9
#define MN_vpcmpequw 0x4cc4
#define MN_phminposuw (MN_vphminposuw + 1)
#define MN_vphminposuw 0x4cce
#define MN_vpcomgtuw 0x4cda
#define MN_vpcomltuw 0x4ce4
#define MN_vpcmpnltuw 0x4cee
#define MN_vpcmpltuw 0x4cf9
#define MN_pmaxuw (MN_vpmaxuw + 1)
#define MN_vpmaxuw 0x4d03
#define MN_vpsravw 0x4d0b
#define MN_vpshldvw 0x4d13
#define MN_vpshrdvw 0x4d1c
#define MN_vpsllvw 0x4d25
#define MN_vpsrlvw 0x4d2d
#define MN_kmovw 0x4d35
#define MN_vmovw 0x4d3b
#define MN_vpmacsww 0x4d41
#define MN_vpmacssww 0x4d4a
#define MN_movzw 0x4d54
#define MN_rex_x 0x4d5a
#define MN_fyl2x 0x4d60
#define MN_rex64x 0x4d66
#define MN_vcvtneps2bf16x 0x4d6d
#define MN_vfpclassbf16x 0x4d7c
#define MN_vcvtph2bf8x 0x4d8a
#define MN_vcvtps2bf8x 0x4d96
#define MN_vcvtph2hf8x 0x4da2
#define MN_vcvtrops2hf8x 0x4dae
#define MN_vcvtps2hf8x 0x4dbc
#define MN_pfmax 0x4dc8
#define MN_adcx 0x4dce
#define MN_bndldx 0x4dd3
#define MN_vfpclasspdx 0x4dda
#define MN_fclex 0x4de6
#define MN_fnclex 0x4dec
#define MN_rex 0x4df3
#define MN_vcvtpd2phx 0x4df7
#define MN_vcvtdq2phx 0x4e02
#define MN_vcvtudq2phx 0x4e0d
#define MN_vcvtqq2phx 0x4e19
#define MN_vcvtuqq2phx 0x4e24
#define MN_vcvt2ps2phx 0x4e30
#define MN_vcvtps2phx 0x4e3c
#define MN_vfpclassphx 0x4e47
#define MN_shlx 0x4e53
#define MN_mulx 0x4e58
#define MN_adox 0x4e5d
#define MN_vcvttpd2dqx 0x4e62
#define MN_vcvtpd2dqx 0x4e6e
#define MN_vcvttpd2udqx 0x4e79
#define MN_vcvtpd2udqx 0x4e86
#define MN_rex_rx 0x4e92
#define MN_sarx 0x4e99
#define MN_shrx 0x4e9e
#define MN_rorx 0x4ea3
#define MN_monitorx 0x4ea8
#define MN_rex_wrx 0x4eb1
#define MN_vcvtph2bf8sx 0x4eb9
#define MN_vcvtps2bf8sx 0x4ec6
#define MN_vcvtph2hf8sx 0x4ed3
#define MN_vcvtrops2hf8sx 0x4ee0
#define MN_vcvtps2hf8sx 0x4eef
#define MN_vcvtpd2psx 0x4efc
#define MN_vcvtph2psx 0x4f07
#define MN_vcvtqq2psx 0x4f12
#define MN_vcvtuqq2psx 0x4f1d
#define MN_vfpclasspsx 0x4f29
#define MN_vcvttpd2dqsx 0x4f35
#define MN_vcvttpd2udqsx 0x4f42
#define MN_movsx 0x4f50
#define MN_mwaitx 0x4f56
#define MN_bndstx 0x4f5d
#define MN_rex_wx 0x4f64
#define MN_rexx 0x4f6b
#define MN_vcvtps2phxx 0x4f70
#define MN_movzx 0x4f7c
#define MN_rex64y 0x4f82
#define MN_vcvtneps2bf16y 0x4f89
#define MN_vfpclassbf16y 0x4f98
#define MN_vcvtph2bf8y 0x4fa6
#define MN_vcvtps2bf8y 0x4fb2
#define MN_vcvtph2hf8y 0x4fbe
#define MN_vcvtrops2hf8y 0x4fca
#define MN_vcvtps2hf8y 0x4fd8
#define MN_vfpclasspdy 0x4fe4
#define MN_loadiwkey 0x4ff0
#define MN_vcvtpd2phy 0x4ffa
#define MN_vcvtdq2phy 0x5005
#define MN_vcvtudq2phy 0x5010
#define MN_vcvtqq2phy 0x501c
#define MN_vcvtuqq2phy 0x5027
#define MN_vfpclassphy 0x5033
#define MN_vcvttpd2dqy 0x503f
#define MN_vcvtpd2dqy 0x504b
#define MN_vcvttpd2udqy 0x5056
#define MN_vcvtpd2udqy 0x5063
#define MN_rmpquery 0x506f
#define MN_vcvtph2bf8sy 0x5078
#define MN_vcvtps2bf8sy 0x5085
#define MN_vcvtph2hf8sy 0x5092
#define MN_vcvtrops2hf8sy 0x509f
#define MN_vcvtps2hf8sy 0x50ae
#define MN_clrssbsy 0x50bb
#define MN_setssbsy 0x50c4
#define MN_vcvtpd2psy 0x50cd
#define MN_vcvtqq2psy 0x50d8
#define MN_vcvtuqq2psy 0x50e3
#define MN_vfpclasspsy 0x50ef
#define MN_vcvttpd2dqsy 0x50fb
#define MN_vcvttpd2udqsy 0x5108
#define MN_rex64xy 0x5116
#define MN_rexy 0x511e
#define MN_vcvtps2phxy 0x5123
#define MN_rexxy 0x512f
#define MN_rex64z 0x5135
#define MN_vfpclassbf16z 0x513c
#define MN_vcvtps2bf8z 0x514a
#define MN_vcvtrops2hf8z 0x5156
#define MN_vcvtps2hf8z 0x5164
#define MN_fldz 0x5170
#define MN_vfpclasspdz 0x5175
#define MN_vcvtpd2phz 0x5181
#define MN_vcvtqq2phz 0x518c
#define MN_vcvtuqq2phz 0x5197
#define MN_vfpclassphz 0x51a3
#define MN_jz 0x51af
#define MN_jnz 0x51b2
#define MN_repnz 0x51b6
#define MN_ccmpnz 0x51bc
#define MN_loopnz 0x51c3
#define MN_setnz 0x51ca
#define MN_ctestnz 0x51d0
#define MN_setzunz 0x51d8
#define MN_cmovnz (MN_cfcmovnz + 2)
#define MN_cfcmovnz 0x51e0
#define MN_repz 0x51e9
#define MN_ccmpz 0x51ee
#define MN_loopz 0x51f4
#define MN_vcvtps2bf8sz 0x51fa
#define MN_vcvtrops2hf8sz 0x5207
#define MN_vcvtps2hf8sz 0x5216
#define MN_vfpclasspsz 0x5223
#define MN_setz 0x522f
#define MN_ctestz 0x5234
#define MN_setzuz 0x523b
#define MN_cmovz (MN_cfcmovz + 2)
#define MN_cfcmovz 0x5242
#define MN_rex64xz 0x524a
#define MN_jecxz 0x5252
#define MN_jcxz 0x5258
#define MN_jrcxz 0x525d
#define MN_rexz 0x5263
#define MN_rexxz 0x5268
#define MN_rex64yz 0x526e
#define MN_rex64xyz 0x5276
#define MN_rexyz 0x527f
#define MN_rexxyz 0x5285
#define MN__disp32_ 0x528c
#define MN__rex2_ 0x5295
#define MN__vex2_ 0x529c
#define MN__vex3_ 0x52a3
#define MN__disp16_ 0x52aa
#define MN__disp8_ 0x52b3
#define MN__load_ 0x52bb
#define MN__store_ 0x52c2
#define MN__nooptimize_ 0x52ca
#define MN__nf_ 0x52d7
#define MN__noimm8s_ 0x52dc
#define MN__rex_ 0x52e6
#define MN__evex_ 0x52ec
#define MN__vex_ 0x52f3
#define MN__insn 0x52f9

#define OPREF_4_0 10
#define OPREF_4_4 14
#define OPREF_4_8 18
#define OPREF_4_12 1
#define OPREF_4_16 5
#define OPREF_4_20 22
#define OPREF_4_24 26
#define OPREF_4_28 30
#define OPREF_4_32 34
#define OPREF_4_36 38
#define OPREF_4_40 42
#define OPREF_4_44 46
#define OPREF_4_48 50
#define OPREF_4_52 54
#define OPREF_4_56 58
#define OPREF_4_60 62
#define OPREF_4_64 66
#define OPREF_4_68 70
#define OPREF_4_72 74
#define OPREF_4_76 78
#define OPREF_4_80 82
#define OPREF_4_84 86
#define OPREF_4_88 90
#define OPREF_4_92 94
#define OPREF_4_96 6
#define OPREF_4_100 98
#define OPREF_4_104 102
#define OPREF_4_108 106
#define OPREF_4_112 110
#define OPREF_4_116 114
#define OPREF_4_120 118
#define OPREF_4_124 122
#define OPREF_4_128 126
#define OPREF_4_132 130
#define OPREF_4_136 134
#define OPREF_4_140 138
#define OPREF_4_144 142
#define OPREF_4_148 146
#define OPREF_4_152 150
#define OPREF_4_156 154
#define OPREF_4_160 158
#define OPREF_4_164 162
#define OPREF_3_0 166
#define OPREF_3_3 169
#define OPREF_3_6 172
#define OPREF_3_9 175
#define OPREF_3_12 178
#define OPREF_3_15 181
#define OPREF_3_18 184
#define OPREF_3_21 187
#define OPREF_3_24 190
#define OPREF_3_27 193
#define OPREF_3_30 196
#define OPREF_3_33 199
#define OPREF_3_36 202
#define OPREF_3_39 205
#define OPREF_3_42 10
#define OPREF_3_45 208
#define OPREF_3_48 14
#define OPREF_3_51 106
#define OPREF_3_54 30
#define OPREF_3_57 211
#define OPREF_3_60 214
#define OPREF_3_63 217
#define OPREF_3_66 62
#define OPREF_3_69 78
#define OPREF_3_72 220
#define OPREF_3_75 223
#define OPREF_3_78 226
#define OPREF_3_81 46
#define OPREF_3_84 38
#define OPREF_3_87 229
#define OPREF_3_90 232
#define OPREF_3_93 235
#define OPREF_3_96 238
#define OPREF_3_99 241
#define OPREF_3_102 244
#define OPREF_3_105 247
#define OPREF_3_108 250
#define OPREF_3_111 66
#define OPREF_3_114 70
#define OPREF_3_117 74
#define OPREF_3_120 253
#define OPREF_3_123 2
#define OPREF_3_126 83
#define OPREF_3_129 87
#define OPREF_3_132 31
#define OPREF_3_135 39
#define OPREF_3_138 23
#define OPREF_3_141 27
#define OPREF_3_144 35
#define OPREF_3_147 43
#define OPREF_3_150 256
#define OPREF_3_153 71
#define OPREF_3_156 259
#define OPREF_3_159 262
#define OPREF_3_162 265
#define OPREF_3_165 268
#define OPREF_3_168 99
#define OPREF_3_171 271
#define OPREF_3_174 55
#define OPREF_3_177 151
#define OPREF_3_180 82
#define OPREF_3_183 18
#define OPREF_3_186 86
#define OPREF_3_189 90
#define OPREF_3_192 274
#define OPREF_3_195 264
#define OPREF_3_198 277
#define OPREF_3_201 22
#define OPREF_3_204 26
#define OPREF_3_207 54
#define OPREF_3_210 5
#define OPREF_3_213 143
#define OPREF_3_216 146
#define OPREF_3_219 147
#define OPREF_3_222 280
#define OPREF_3_225 283
#define OPREF_3_228 286
#define OPREF_3_231 289
#define OPREF_3_234 292
#define OPREF_3_237 47
#define OPREF_3_240 295
#define OPREF_3_243 298
#define OPREF_3_246 163
#define OPREF_3_249 131
#define OPREF_3_252 301
#define OPREF_3_255 304
#define OPREF_3_258 307
#define OPREF_3_261 110
#define OPREF_3_264 310
#define OPREF_3_267 313
#define OPREF_3_270 114
#define OPREF_3_273 316
#define OPREF_3_276 319
#define OPREF_3_279 322
#define OPREF_3_282 325
#define OPREF_3_285 328
#define OPREF_3_288 154
#define OPREF_3_291 331
#define OPREF_3_294 334
#define OPREF_3_297 337
#define OPREF_3_300 340
#define OPREF_3_303 343
#define OPREF_3_306 346
#define OPREF_3_309 349
#define OPREF_3_312 352
#define OPREF_3_315 355
#define OPREF_3_318 358
#define OPREF_3_321 361
#define OPREF_3_324 364
#define OPREF_3_327 367
#define OPREF_3_330 370
#define OPREF_3_333 373
#define OPREF_3_336 376
#define OPREF_3_339 379
#define OPREF_3_342 382
#define OPREF_3_345 385
#define OPREF_3_348 388
#define OPREF_3_351 391
#define OPREF_3_354 394
#define OPREF_3_357 155
#define OPREF_3_360 159
#define OPREF_3_363 397
#define OPREF_3_366 400
#define OPREF_3_369 403
#define OPREF_3_372 406
#define OPREF_3_375 409
#define OPREF_3_378 412
#define OPREF_3_381 415
#define OPREF_3_384 418
#define OPREF_3_387 421
#define OPREF_3_390 424
#define OPREF_3_393 427
#define OPREF_3_396 430
#define OPREF_2_0 433
#define OPREF_2_2 435
#define OPREF_2_4 437
#define OPREF_2_6 439
#define OPREF_2_8 441
#define OPREF_2_10 443
#define OPREF_2_12 445
#define OPREF_2_14 447
#define OPREF_2_16 446
#define OPREF_2_18 449
#define OPREF_2_20 451
#define OPREF_2_22 453
#define OPREF_2_24 455
#define OPREF_2_26 457
#define OPREF_2_28 459
#define OPREF_2_30 12
#define OPREF_2_32 461
#define OPREF_2_34 463
#define OPREF_2_36 465
#define OPREF_2_38 467
#define OPREF_2_40 469
#define OPREF_2_42 471
#define OPREF_2_44 188
#define OPREF_2_46 473
#define OPREF_2_48 475
#define OPREF_2_50 477
#define OPREF_2_52 476
#define OPREF_2_54 479
#define OPREF_2_56 481
#define OPREF_2_58 483
#define OPREF_2_60 166
#define OPREF_2_62 178
#define OPREF_2_64 169
#define OPREF_2_66 485
#define OPREF_2_68 172
#define OPREF_2_70 167
#define OPREF_2_72 179
#define OPREF_2_74 487
#define OPREF_2_76 489
#define OPREF_2_78 491
#define OPREF_2_80 493
#define OPREF_2_82 495
#define OPREF_2_84 497
#define OPREF_2_86 499
#define OPREF_2_88 193
#define OPREF_2_90 501
#define OPREF_2_92 196
#define OPREF_2_94 503
#define OPREF_2_96 199
#define OPREF_2_98 505
#define OPREF_2_100 202
#define OPREF_2_102 206
#define OPREF_2_104 507
#define OPREF_2_106 509
#define OPREF_2_108 511
#define OPREF_2_110 513
#define OPREF_2_112 515
#define OPREF_2_114 517
#define OPREF_2_116 519
#define OPREF_2_118 518
#define OPREF_2_120 521
#define OPREF_2_122 523
#define OPREF_2_124 525
#define OPREF_2_126 527
#define OPREF_2_128 176
#define OPREF_2_130 529
#define OPREF_2_132 531
#define OPREF_2_134 533
#define OPREF_2_136 535
#define OPREF_2_138 537
#define OPREF_2_140 71
#define OPREF_2_142 539
#define OPREF_2_144 541
#define OPREF_2_146 543
#define OPREF_2_148 39
#define OPREF_2_150 101
#define OPREF_2_152 75
#define OPREF_2_154 227
#define OPREF_2_156 545
#define OPREF_2_158 47
#define OPREF_2_160 115
#define OPREF_2_162 214
#define OPREF_2_164 547
#define OPREF_2_166 31
#define OPREF_2_168 549
#define OPREF_2_170 551
#define OPREF_2_172 553
#define OPREF_2_174 555
#define OPREF_2_176 557
#define OPREF_2_178 32
#define OPREF_2_180 271
#define OPREF_2_182 289
#define OPREF_2_184 212
#define OPREF_2_186 559
#define OPREF_2_188 561
#define OPREF_2_190 284
#define OPREF_2_192 215
#define OPREF_2_194 558
#define OPREF_2_196 563
#define OPREF_2_198 565
#define OPREF_2_200 567
#define OPREF_2_202 367
#define OPREF_2_204 370
#define OPREF_2_206 569
#define OPREF_2_208 571
#define OPREF_2_210 573
#define OPREF_2_212 575
#define OPREF_2_214 577
#define OPREF_2_216 579
#define OPREF_2_218 131
#define OPREF_2_220 581
#define OPREF_2_222 583
#define OPREF_2_224 585
#define OPREF_2_226 587
#define OPREF_2_228 293
#define OPREF_2_230 285
#define OPREF_2_232 589
#define OPREF_2_234 591
#define OPREF_2_236 593
#define OPREF_2_238 51
#define OPREF_2_240 595
#define OPREF_2_242 597
#define OPREF_2_244 599
#define OPREF_2_246 2
#define OPREF_2_248 23
#define OPREF_2_250 601
#define OPREF_2_252 282
#define OPREF_2_254 603
#define OPREF_2_256 605
#define OPREF_2_258 607
#define OPREF_2_260 609
#define OPREF_2_262 611
#define OPREF_2_264 268
#define OPREF_2_266 55
#define OPREF_2_268 245
#define OPREF_2_270 554
#define OPREF_2_272 59
#define OPREF_2_274 376
#define OPREF_2_276 613
#define OPREF_2_278 266
#define OPREF_2_280 615
#define OPREF_2_282 617
#define OPREF_2_284 619
#define OPREF_2_286 621
#define OPREF_2_288 623
#define OPREF_2_290 139
#define OPREF_2_292 27
#define OPREF_2_294 625
#define OPREF_2_296 627
#define OPREF_2_298 629
#define OPREF_2_300 631
#define OPREF_2_302 633
#define OPREF_2_304 635
#define OPREF_2_306 637
#define OPREF_2_308 639
#define OPREF_2_310 641
#define OPREF_2_312 281
#define OPREF_2_314 643
#define OPREF_2_316 287
#define OPREF_2_318 302
#define OPREF_2_320 229
#define OPREF_2_322 283
#define OPREF_2_324 316
#define OPREF_2_326 645
#define OPREF_2_328 647
#define OPREF_2_330 649
#define OPREF_2_332 651
#define OPREF_2_334 653
#define OPREF_2_336 52
#define OPREF_2_338 655
#define OPREF_2_340 657
#define OPREF_2_342 659
#define OPREF_2_344 661
#define OPREF_2_346 663
#define OPREF_2_348 322
#define OPREF_2_350 155
#define OPREF_2_352 665
#define OPREF_2_354 667
#define OPREF_2_356 669
#define OPREF_2_358 642
#define OPREF_2_360 286
#define OPREF_2_362 671
#define OPREF_2_364 270
#define OPREF_2_366 292
#define OPREF_2_368 673
#define OPREF_2_370 79
#define OPREF_2_372 675
#define OPREF_2_374 588
#define OPREF_2_376 299
#define OPREF_2_378 263
#define OPREF_2_380 622
#define OPREF_2_382 677
#define OPREF_2_384 679
#define OPREF_2_386 681
#define OPREF_2_388 683
#define OPREF_2_390 685
#define OPREF_2_392 687
#define OPREF_2_394 689
#define OPREF_2_396 691
#define OPREF_2_398 693
#define OPREF_2_400 695
#define OPREF_2_402 24
#define OPREF_2_404 697
#define OPREF_2_406 699
#define OPREF_2_408 701
#define OPREF_2_410 410
#define OPREF_2_412 703
#define OPREF_2_414 705
#define OPREF_2_416 707
#define OPREF_2_418 709
#define OPREF_2_420 711
#define OPREF_2_422 713
#define OPREF_2_424 715
#define OPREF_2_426 232
#define OPREF_2_428 717
#define OPREF_2_430 719
#define OPREF_2_432 721
#define OPREF_2_434 723
#define OPREF_2_436 390
#define OPREF_2_438 725
#define OPREF_2_440 727
#define OPREF_2_442 729
#define OPREF_2_444 731
#define OPREF_2_446 733
#define OPREF_2_448 735
#define OPREF_2_450 737
#define OPREF_2_452 678
#define OPREF_2_454 739
#define OPREF_2_456 741
#define OPREF_2_458 743
#define OPREF_2_460 745
#define OPREF_2_462 747
#define OPREF_2_464 749
#define OPREF_2_466 751
#define OPREF_2_468 753
#define OPREF_2_470 755
#define OPREF_2_472 757
#define OPREF_2_474 759
#define OPREF_2_476 761
#define OPREF_2_478 763
#define OPREF_2_480 56
#define OPREF_2_482 765
#define OPREF_2_484 767
#define OPREF_1_0 63
#define OPREF_1_1 482
#define OPREF_1_2 769
#define OPREF_1_3 169
#define OPREF_1_4 508
#define OPREF_1_5 445
#define OPREF_1_6 770
#define OPREF_1_7 771
#define OPREF_1_8 772
#define OPREF_1_9 246
#define OPREF_1_10 0
#define OPREF_1_11 477
#define OPREF_1_12 166
#define OPREF_1_13 438
#define OPREF_1_14 167
#define OPREF_1_15 773
#define OPREF_1_16 774
#define OPREF_1_17 75
#define OPREF_1_18 775
#define OPREF_1_19 776
#define OPREF_1_20 703
#define OPREF_1_21 705
#define OPREF_1_22 777
#define OPREF_1_23 778
#define OPREF_1_24 443
#define OPREF_1_25 779
#define OPREF_1_26 190
#define OPREF_1_27 780
#define OPREF_1_28 461
#define OPREF_1_29 781
#define OPREF_1_30 782
#define OPREF_1_31 517
#define OPREF_1_32 511
#define OPREF_1_33 783
#define OPREF_1_34 179
#define OPREF_1_35 784
#define OPREF_1_36 785
#define OPREF_1_37 11
#define OPREF_1_38 79
#define OPREF_1_39 463
#define OPREF_1_40 531
#define OPREF_1_41 524
#define OPREF_1_42 786
#define OPREF_1_43 787
#define OPREF_1_44 271
#define OPREF_1_45 788
#define OPREF_1_46 479
#define OPREF_1_47 284
#define OPREF_1_48 579
#define OPREF_1_49 375
#define OPREF_1_50 229
#define OPREF_1_51 373
#define OPREF_1_52 71
#define OPREF_1_53 316
#define OPREF_1_54 232
#define OPREF_1_55 380
#define OPREF_1_56 396
#define OPREF_1_57 645
#define OPREF_1_58 789
