/* This file is automatically generated by i386-gen.  Do not edit!  */
/* Copyright (C) 2007-2026 Free Software Foundation, Inc.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

static const char i386_mnemonics[];

#define MN_ud0 0x1
#define MN_prefetcht0 0x5
#define MN_prefetchit0 0x10
#define MN_t2rpntlvwz0 0x1c
#define MN_xsha1 0x28
#define MN_fld1 0x2e
#define MN_ud1 0x33
#define MN_sha1msg1 0x37
#define MN_vsha512msg1 0x40
#define MN_vsm3msg1 0x4c
#define MN_sha256msg1 0x55
#define MN_fprem1 0x60
#define MN_f2xm1 0x67
#define MN_fyl2xp1 0x6d
#define MN_t2rpntlvwz0t1 0x75
#define MN_t2rpntlvwz1t1 0x83
#define MN_tileloaddt1 0x91
#define MN_prefetcht1 0x9d
#define MN_prefetchit1 0xa8
#define MN_pfrcpit1 0xb4
#define MN_pfrsqit1 0xbd
#define MN_int1 0xc6
#define MN_t2rpntlvwz0rst1 0xcb
#define MN_t2rpntlvwz1rst1 0xdb
#define MN_tileloaddrst1 0xeb
#define MN_prefetchwt1 0xf9
#define MN_t2rpntlvwz1 0x105
#define MN_xsha512 0x111
#define MN_vmovdqa32 0x119
#define MN_data32 0x123
#define MN_crc32 0x12a
#define MN_endbr32 0x130
#define MN_addr32 0x138
#define MN_vmovdqu32 0x13f
#define MN_ud2 0x149
#define MN_fldlg2 0x14d
#define MN_xrng2 0x154
#define MN_sha1msg2 0x15a
#define MN_vsha512msg2 0x163
#define MN_vsm3msg2 0x16f
#define MN_sha256msg2 0x178
#define MN_push2 0x183
#define MN_montmul2 0x189
#define MN_sm2 0x192
#define MN_fldln2 0x196
#define MN_pop2 0x19d
#define MN_vsha512rnds2 0x1a2
#define MN_vsm3rnds2 0x1af
#define MN_sha256rnds2 0x1b9
#define MN_prefetcht2 0x1c5
#define MN_pfrcpit2 0x1d0
#define MN_prefetchrst2 0x1d9
#define MN_vbroadcastf32x2 0x1e6
#define MN_vbroadcasti32x2 0x1f6
#define MN_vshuff64x2 0x206
#define MN_vextractf64x2 0x211
#define MN_vinsertf64x2 0x21f
#define MN_vbroadcastf64x2 0x22c
#define MN_vshufi64x2 0x23c
#define MN_vextracti64x2 0x247
#define MN_vinserti64x2 0x255
#define MN_vbroadcasti64x2 0x262
#define MN_sm3 0x272
#define MN_int3 0x276
#define MN_vmovdqa64 0x27b
#define MN_xsavec64 0x285
#define MN_xsave64 (MN_fxsave64 + 1)
#define MN_fxsave64 0x28e
#define MN_endbr64 0x297
#define MN_xrstor64 (MN_fxrstor64 + 1)
#define MN_fxrstor64 0x29f
#define MN_xsaves64 0x2a9
#define MN_xrstors64 0x2b2
#define MN_xsaveopt64 0x2bc
#define MN_vmovdqu64 0x2c7
#define MN_rex64 0x2d1
#define MN_xsha384 0x2d7
#define MN_sm4 0x2df
#define MN_sha1rnds4 0x2e3
#define MN_vsm4rnds4 0x2ed
#define MN_vshuff32x4 0x2f7
#define MN_vextractf32x4 0x302
#define MN_vinsertf32x4 0x310
#define MN_vbroadcastf32x4 0x31d
#define MN_vshufi32x4 0x32d
#define MN_vextracti32x4 0x338
#define MN_vinserti32x4 0x346
#define MN_vbroadcasti32x4 0x353
#define MN_vextractf64x4 0x363
#define MN_vinsertf64x4 0x371
#define MN_vbroadcastf64x4 0x37e
#define MN_vextracti64x4 0x38e
#define MN_vinserti64x4 0x39c
#define MN_vbroadcasti64x4 0x3a9
#define MN_vsm4key4 0x3b9
#define MN_data16 0x3c2
#define MN_vfmsub231bf16 0x3c9
#define MN_vfnmsub231bf16 0x3d7
#define MN_vfmadd231bf16 0x3e6
#define MN_vfnmadd231bf16 0x3f4
#define MN_vfmsub132bf16 0x403
#define MN_vfnmsub132bf16 0x411
#define MN_vfmadd132bf16 0x420
#define MN_vfnmadd132bf16 0x42e
#define MN_vcvtne2ps2bf16 0x43d
#define MN_vcvtneps2bf16 0x44c
#define MN_vfmsub213bf16 0x45a
#define MN_vfnmsub213bf16 0x468
#define MN_vfmadd213bf16 0x477
#define MN_vfnmadd213bf16 0x485
#define MN_vsubbf16 0x494
#define MN_vaddbf16 0x49d
#define MN_vreducebf16 0x4a6
#define MN_vrndscalebf16 0x4b2
#define MN_vscalefbf16 0x4c0
#define MN_vmulbf16 0x4cc
#define MN_vminbf16 0x4d5
#define MN_vrcpbf16 0x4de
#define MN_vcmpbf16 0x4e7
#define MN_vgetexpbf16 0x4f0
#define MN_vcomisbf16 0x4fc
#define MN_vfpclassbf16 0x507
#define MN_vgetmantbf16 0x514
#define MN_vrsqrtbf16 0x521
#define MN_vsqrtbf16 0x52c
#define MN_vdivbf16 0x536
#define MN_vminmaxbf16 0x53f
#define MN_vmaxbf16 0x54b
#define MN_tconjtfp16 0x554
#define MN_addr16 0x55f
#define MN_vmovdqu16 0x566
#define MN_vbmacor16x16x16 0x570
#define MN_vbmacxor16x16x16 0x580
#define MN_xsha256 0x591
#define MN_encodekey256 0x599
#define MN_vperm2f128 0x5a6
#define MN_vextractf128 0x5b1
#define MN_vinsertf128 0x5be
#define MN_vbroadcastf128 0x5ca
#define MN_vperm2i128 0x5d9
#define MN_vextracti128 0x5e4
#define MN_vinserti128 0x5f1
#define MN_vbroadcasti128 0x5fd
#define MN_encodekey128 0x60c
#define MN_vcvt2ph2bf8 0x619
#define MN_vcvtbiasph2bf8 0x625
#define MN_vcvtph2bf8 0x634
#define MN_vcvtbiasps2bf8 0x63f
#define MN_vcvtps2bf8 0x64e
#define MN_vcvtbf42hf8 0x659
#define MN_vcvtbf62hf8 0x665
#define MN_vcvthf62hf8 0x671
#define MN_vcvt2ph2hf8 0x67d
#define MN_vcvtbiasph2hf8 0x689
#define MN_vcvtph2hf8 0x698
#define MN_vcvtrops2hf8 0x6a3
#define MN_vcvtbiasps2hf8 0x6b0
#define MN_vcvtps2hf8 0x6bf
#define MN_vmovdqu8 0x6ca
#define MN_vextractf32x8 0x6d3
#define MN_vinsertf32x8 0x6e1
#define MN_vbroadcastf32x8 0x6ee
#define MN_vextracti32x8 0x6fe
#define MN_vinserti32x8 0x70c
#define MN_vbroadcasti32x8 0x719
#define MN_ud2a 0x729
#define MN_aaa 0x72e
#define MN_daa 0x732
#define MN_ssca 0x736
#define MN_lea 0x73b
#define MN_invlpga 0x73f
#define MN_pusha 0x747
#define MN_ja 0x74d
#define MN_jna 0x750
#define MN_ccmpna 0x754
#define MN_setna 0x75b
#define MN_ctestna 0x761
#define MN_setzuna 0x769
#define MN_cmovna (MN_fcmovna + 1)
#define MN_fcmovna (MN_cfcmovna + 1)
#define MN_cfcmovna 0x771
#define MN_ccmpa 0x77a
#define MN_popa 0x780
#define MN_movntdqa (MN_vmovntdqa + 1)
#define MN_vmovntdqa 0x785
#define MN_movdqa (MN_vmovdqa + 1)
#define MN_vmovdqa 0x78f
#define MN_seta 0x797
#define MN_prefetchnta 0x79c
#define MN_ctesta 0x7a8
#define MN_setzua 0x7af
#define MN_cmova (MN_fcmova + 1)
#define MN_fcmova (MN_cfcmova + 1)
#define MN_cfcmova 0x7b6
#define MN_rex_b 0x7be
#define MN_ud2b 0x7c4
#define MN_vpermi2b 0x7c9
#define MN_vpmovm2b 0x7d2
#define MN_vpermt2b 0x7db
#define MN_movdir64b 0x7e4
#define MN_cmpxchg16b 0x7ee
#define MN_cmpxchg8b 0x7f9
#define MN_vpshab 0x803
#define MN_sbb 0x80a
#define MN_psubb (MN_vpsubb + 1)
#define MN_vpsubb 0x80e
#define MN_xcrypt_ecb 0x815
#define MN_xcryptecb 0x820
#define MN_llwpcb 0x82a
#define MN_slwpcb 0x831
#define MN_kaddb 0x838
#define MN_paddb (MN_vpaddb + 1)
#define MN_vpaddb 0x83e
#define MN_kandb 0x845
#define MN_vpexpandb 0x84b
#define MN_vpmovssdb 0x855
#define MN_vpmovusdb 0x85f
#define MN_vpmovsdb 0x869
#define MN_udb 0x872
#define MN_vpmovdb 0x876
#define MN_vpcomgeb 0x87e
#define MN_vpcomleb 0x887
#define MN_vpcmpnleb 0x890
#define MN_vpcmpleb 0x89a
#define MN_vpcomfalseb 0x8a3
#define MN_vpcomtrueb 0x8af
#define MN_xcrypt_cfb 0x8ba
#define MN_xcryptcfb 0x8c5
#define MN_xcrypt_ofb 0x8cf
#define MN_xcryptofb 0x8da
#define MN_pshufb (MN_vpshufb + 1)
#define MN_vpshufb 0x8e4
#define MN_invlpgb 0x8ec
#define MN_pavgb (MN_vpavgb + 1)
#define MN_vpavgb 0x8f4
#define MN_jb 0x8fb
#define MN_vunpackb 0x8fe
#define MN_pbndkb 0x907
#define MN_pmovmskb (MN_vpmovmskb + 1)
#define MN_vpmovmskb 0x90e
#define MN_vpshlb 0x918
#define MN_kshiftlb 0x91f
#define MN_gf2p8mulb (MN_vgf2p8mulb + 1)
#define MN_vgf2p8mulb 0x928
#define MN_vpblendmb 0x933
#define MN_vptestnmb 0x93d
#define MN_vpcomb 0x947
#define MN_vpshufbitqmb 0x94e
#define MN_vpermb 0x95b
#define MN_vptestmb 0x962
#define MN_kandnb 0x96b
#define MN_psignb (MN_vpsignb + 1)
#define MN_vpsignb 0x972
#define MN_jnb 0x97a
#define MN_ccmpnb 0x97e
#define MN_setnb 0x985
#define MN_ctestnb 0x98b
#define MN_setzunb 0x993
#define MN_cmovnb (MN_fcmovnb + 1)
#define MN_fcmovnb (MN_cfcmovnb + 1)
#define MN_cfcmovnb 0x99b
#define MN_ccmpb 0x9a4
#define MN_vpcmpb 0x9aa
#define MN_vpcomeqb 0x9b1
#define MN_gf2p8affineqb (MN_vgf2p8affineqb + 1)
#define MN_vgf2p8affineqb 0x9ba
#define MN_vpcomneqb 0x9c9
#define MN_vpcmpneqb 0x9d3
#define MN_pcmpeqb (MN_vpcmpeqb + 1)
#define MN_vpcmpeqb 0x9dd
#define MN_vpmovusqb 0x9e6
#define MN_vpmovsqb 0x9f0
#define MN_vpmultishiftqb 0x9f9
#define MN_gf2p8affineinvqb (MN_vgf2p8affineinvqb + 1)
#define MN_vgf2p8affineinvqb 0xa08
#define MN_vpmovqb 0xa1a
#define MN_rex_rb 0xa22
#define MN_korb 0xa29
#define MN_kxnorb 0xa2e
#define MN_kxorb 0xa35
#define MN_pinsrb (MN_vpinsrb + 1)
#define MN_vpinsrb 0xa3b
#define MN_kshiftrb 0xa43
#define MN_pextrb (MN_vpextrb + 1)
#define MN_vpextrb 0xa4c
#define MN_rex_wrb 0xa54
#define MN_pabsb (MN_vpabsb + 1)
#define MN_vpabsb 0xa5c
#define MN_psubsb (MN_vpsubsb + 1)
#define MN_vpsubsb 0xa63
#define MN_paddsb (MN_vpaddsb + 1)
#define MN_vpaddsb 0xa6b
#define MN_pminsb (MN_vpminsb + 1)
#define MN_vpminsb 0xa73
#define MN_vmovrsb 0xa7b
#define MN_vpcompressb 0xa83
#define MN_psubusb (MN_vpsubusb + 1)
#define MN_vpsubusb 0xa8f
#define MN_paddusb (MN_vpaddusb + 1)
#define MN_vpaddusb 0xa98
#define MN_pavgusb 0xaa1
#define MN_movsb 0xaa9
#define MN_pmaxsb (MN_vpmaxsb + 1)
#define MN_vpmaxsb 0xaaf
#define MN_setb 0xab7
#define MN_vpcomgtb 0xabc
#define MN_pcmpgtb (MN_vpcmpgtb + 1)
#define MN_vpcmpgtb 0xac5
#define MN_vpcomltb 0xace
#define MN_vpcmpnltb 0xad7
#define MN_vpcmpltb 0xae1
#define MN_vpopcntb 0xaea
#define MN_knotb 0xaf3
#define MN_vprotb 0xaf9
#define MN_vpbroadcastb 0xb00
#define MN_ctestb 0xb0d
#define MN_ktestb 0xb14
#define MN_kortestb 0xb1b
#define MN_vpcomgeub 0xb24
#define MN_vpcomleub 0xb2e
#define MN_vpcmpnleub 0xb38
#define MN_vpcmpleub 0xb43
#define MN_vpcomfalseub 0xb4d
#define MN_vpcomtrueub 0xb5a
#define MN_vpcomub 0xb66
#define MN_pminub (MN_vpminub + 1)
#define MN_vpminub 0xb6e
#define MN_vpcmpub 0xb76
#define MN_vpcomequb 0xb7e
#define MN_vpcomnequb 0xb88
#define MN_vpcmpnequb 0xb93
#define MN_vpcmpequb 0xb9e
#define MN_sub (MN_fsub + 1)
#define MN_fsub (MN_pfsub + 1)
#define MN_pfsub 0xba8
#define MN_fisub 0xbae
#define MN_vpcomgtub 0xbb4
#define MN_vpcomltub 0xbbe
#define MN_vpcmpnltub 0xbc8
#define MN_vpcmpltub 0xbd3
#define MN_pmaxub (MN_vpmaxub + 1)
#define MN_vpmaxub 0xbdd
#define MN_setzub 0xbe5
#define MN_pblendvb (MN_vpblendvb + 1)
#define MN_vpblendvb 0xbec
#define MN_vbitrevb 0xbf6
#define MN_cmovb (MN_fcmovb + 1)
#define MN_fcmovb (MN_cfcmovb + 1)
#define MN_cfcmovb 0xbff
#define MN_kmovb 0xc07
#define MN_rex_wb 0xc0d
#define MN_clwb 0xc14
#define MN_packsswb (MN_vpacksswb + 1)
#define MN_vpacksswb 0xc19
#define MN_packuswb (MN_vpackuswb + 1)
#define MN_vpackuswb 0xc23
#define MN_vpmovuswb 0xc2d
#define MN_vpmovswb 0xc37
#define MN_vpmovwb 0xc40
#define MN_rex_xb 0xc48
#define MN_rex_rxb 0xc4f
#define MN_rex_wrxb 0xc57
#define MN_rex_wxb 0xc60
#define MN_movzb 0xc68
#define MN_clac 0xc6e
#define MN_stac 0xc73
#define MN_xcrypt_cbc 0xc78
#define MN_xcryptcbc 0xc83
#define MN_pfacc 0xc8d
#define MN_pfnacc 0xc93
#define MN_pfpnacc 0xc9a
#define MN_adc 0xca2
#define MN_dec (MN_aesdec + 3)
#define MN_aesdec (MN_vaesdec + 1)
#define MN_vaesdec 0xca6
#define MN_getsec 0xcae
#define MN_xsavec 0xcb5
#define MN_blcic 0xcbc
#define MN_blsic 0xcc2
#define MN_jc 0xcc8
#define MN_t1mskc 0xccb
#define MN_salc 0xcd2
#define MN_clc 0xcd7
#define MN_cmc 0xcdb
#define MN_aesimc (MN_vaesimc + 1)
#define MN_vaesimc 0xcdf
#define MN_rdpmc 0xce7
#define MN_aesenc (MN_vaesenc + 1)
#define MN_vaesenc 0xced
#define MN_inc 0xcf5
#define MN_jnc 0xcf9
#define MN_ccmpnc 0xcfd
#define MN_setnc 0xd04
#define MN_ctestnc 0xd0a
#define MN_vmfunc 0xd12
#define MN_setzunc 0xd19
#define MN_cmovnc (MN_cfcmovnc + 2)
#define MN_cfcmovnc 0xd21
#define MN_tlbsync 0xd2a
#define MN_ccmpc 0xd32
#define MN_rdtsc 0xd38
#define MN_btc 0xd3e
#define MN_setc 0xd42
#define MN_stc (MN_ctestc + 3)
#define MN_ctestc 0xd47
#define MN_setzuc 0xd4e
#define MN_cmovc (MN_cfcmovc + 2)
#define MN_cfcmovc 0xd55
#define MN_vpermi2d 0xd5d
#define MN_vpmovm2d 0xd66
#define MN_vpermt2d 0xd6f
#define MN_vpbroadcastmw2d 0xd78
#define MN_aad 0xd88
#define MN_vmread 0xd8c
#define MN_rmpread 0xd93
#define MN_vpshad 0xd9b
#define MN_vmload 0xda2
#define MN_psrad (MN_vpsrad + 1)
#define MN_vpsrad 0xda9
#define MN_vphaddbd 0xdb0
#define MN_vphaddubd 0xdb9
#define MN_phsubd (MN_vphsubd + 1)
#define MN_vphsubd 0xdc3
#define MN_psubd (MN_vpsubd + 1)
#define MN_vpsubd 0xdcb
#define MN_pmovsxbd (MN_vpmovsxbd + 1)
#define MN_vpmovsxbd 0xdd2
#define MN_pmovzxbd (MN_vpmovzxbd + 1)
#define MN_vpmovzxbd 0xddc
#define MN_add (MN_aadd + 1)
#define MN_aadd 0xde6
#define MN_fadd (MN_pfadd + 1)
#define MN_pfadd 0xdeb
#define MN_fiadd 0xdf1
#define MN_tileloadd 0xdf7
#define MN_xadd (MN_cmpnaxadd + 5)
#define MN_cmpnaxadd 0xe01
#define MN_cmpaxadd 0xe0b
#define MN_cmpnbxadd 0xe14
#define MN_cmpbxadd 0xe1e
#define MN_cmpncxadd 0xe27
#define MN_cmpcxadd 0xe31
#define MN_cmpnaexadd 0xe3a
#define MN_cmpaexadd 0xe45
#define MN_cmpnbexadd 0xe4f
#define MN_cmpbexadd 0xe5a
#define MN_cmpngexadd 0xe64
#define MN_cmpgexadd 0xe6f
#define MN_cmpnlexadd 0xe79
#define MN_cmplexadd 0xe84
#define MN_cmpnexadd 0xe8e
#define MN_cmpexadd 0xe98
#define MN_cmppexadd 0xea1
#define MN_cmpngxadd 0xeab
#define MN_cmpgxadd 0xeb5
#define MN_cmpnlxadd 0xebe
#define MN_cmplxadd 0xec8
#define MN_cmpnoxadd 0xed1
#define MN_cmpoxadd 0xedb
#define MN_cmppoxadd 0xee4
#define MN_cmpnpxadd 0xeee
#define MN_cmppxadd 0xef8
#define MN_cmpnsxadd 0xf01
#define MN_cmpsxadd 0xf0b
#define MN_cmpnzxadd 0xf14
#define MN_cmpzxadd 0xf1e
#define MN_phaddd (MN_vphaddd + 1)
#define MN_vphaddd 0xf27
#define MN_kaddd 0xf2f
#define MN_paddd (MN_vpaddd + 1)
#define MN_vpaddd 0xf35
#define MN_vpshldd 0xf3c
#define MN_kandd 0xf44
#define MN_vpandd 0xf4a
#define MN_vpexpandd 0xf51
#define MN_vpblendd 0xf5b
#define MN_vpgatherdd 0xf64
#define MN_vpscatterdd 0xf6f
#define MN_vpshrdd 0xf7b
#define MN_vpmacsdd 0xf83
#define MN_vpmacssdd 0xf8c
#define MN_rdseed 0xf96
#define MN_vpcomged 0xf9d
#define MN_vpcomled 0xfa6
#define MN_vpcmpnled 0xfaf
#define MN_vpcmpled 0xfb9
#define MN_tilestored 0xfc2
#define MN_vpcomfalsed 0xfcd
#define MN_ttransposed 0xfd9
#define MN_vpcomtrued 0xfe5
#define MN_pi2fd 0xff0
#define MN_pshufd (MN_vpshufd + 1)
#define MN_vpshufd 0xff6
#define MN_vpternlogd 0xffe
#define MN_pf2id 0x1009
#define MN_invpcid 0x100f
#define MN_rdpid 0x1017
#define MN_invvpid 0x101d
#define MN_cpuid 0x1025
#define MN_rmpchkd 0x102b
#define MN_fbld 0x1033
#define MN_cld 0x1038
#define MN_fld 0x103c
#define MN_shld (MN_vpshld + 2)
#define MN_vpshld 0x1040
#define MN_fild 0x1047
#define MN_pslld (MN_vpslld + 1)
#define MN_vpslld 0x104c
#define MN_pmulld (MN_vpmulld + 1)
#define MN_vpmulld 0x1053
#define MN_vprold 0x105b
#define MN_psrld (MN_vpsrld + 1)
#define MN_vpsrld 0x1062
#define MN_vmptrld 0x1069
#define MN_kshiftld 0x1071
#define MN_enqcmd 0x107a
#define MN_vpblendmd 0x1081
#define MN_vptestnmd 0x108b
#define MN_vpcomd 0x1095
#define MN_vpermd 0x109c
#define MN_vptestmd 0x10a3
#define MN_and (MN_aand + 1)
#define MN_aand 0x10ac
#define MN_pand (MN_vpand + 1)
#define MN_vpand 0x10b1
#define MN_rdrand 0x10b7
#define MN_bnd 0x10be
#define MN_kandnd 0x10c2
#define MN_vpandnd 0x10c9
#define MN_xend 0x10d1
#define MN_valignd 0x10d6
#define MN_psignd (MN_vpsignd + 1)
#define MN_vpsignd 0x10de
#define MN_bound 0x10e6
#define MN_slod 0x10ec
#define MN_vfmaddsub231pd 0x10f1
#define MN_vfmsub231pd 0x1100
#define MN_vfnmsub231pd 0x110c
#define MN_vfmsubadd231pd 0x1119
#define MN_vfmadd231pd 0x1128
#define MN_vfnmadd231pd 0x1134
#define MN_vfmaddsub132pd 0x1141
#define MN_vfmsub132pd 0x1150
#define MN_vfnmsub132pd 0x115c
#define MN_vfmsubadd132pd 0x1169
#define MN_vfmadd132pd 0x1178
#define MN_vfnmadd132pd 0x1184
#define MN_vcvtph2pd 0x1191
#define MN_vpermi2pd 0x119b
#define MN_cvtpi2pd 0x11a5
#define MN_vpermil2pd 0x11ae
#define MN_vexp2pd 0x11b9
#define MN_cvtdq2pd (MN_vcvtdq2pd + 1)
#define MN_vcvtdq2pd 0x11c1
#define MN_vcvtudq2pd 0x11cb
#define MN_vcvtqq2pd 0x11d6
#define MN_vcvtuqq2pd 0x11e0
#define MN_cvtps2pd (MN_vcvtps2pd + 1)
#define MN_vcvtps2pd 0x11eb
#define MN_vpermt2pd 0x11f5
#define MN_vfmaddsub213pd 0x11ff
#define MN_vfmsub213pd 0x120e
#define MN_vfnmsub213pd 0x121a
#define MN_vfmsubadd213pd 0x1227
#define MN_vfmadd213pd 0x1236
#define MN_vfnmadd213pd 0x1242
#define MN_vrcp14pd 0x124f
#define MN_vrsqrt14pd 0x1258
#define MN_vrcp28pd 0x1263
#define MN_vrsqrt28pd 0x126c
#define MN_movapd (MN_vmovapd + 1)
#define MN_vmovapd 0x1277
#define MN_pswapd 0x127f
#define MN_subpd (MN_addsubpd + 3)
#define MN_addsubpd (MN_vfmaddsubpd + 3)
#define MN_vfmaddsubpd 0x1286
#define MN_vaddsubpd 0x1292
#define MN_hsubpd (MN_vhsubpd + 1)
#define MN_vhsubpd 0x129c
#define MN_vfmsubpd 0x12a4
#define MN_vfnmsubpd 0x12ad
#define MN_vsubpd 0x12b7
#define MN_vgatherpf0dpd 0x12be
#define MN_vscatterpf0dpd 0x12cc
#define MN_vgatherpf1dpd 0x12db
#define MN_vscatterpf1dpd 0x12e9
#define MN_addpd (MN_vfmsubaddpd + 6)
#define MN_vfmsubaddpd 0x12f8
#define MN_haddpd (MN_vhaddpd + 1)
#define MN_vhaddpd 0x1304
#define MN_vfmaddpd 0x130c
#define MN_vfnmaddpd 0x1315
#define MN_vaddpd 0x131f
#define MN_andpd (MN_vexpandpd + 4)
#define MN_vexpandpd 0x1326
#define MN_vandpd 0x1330
#define MN_blendpd (MN_vblendpd + 1)
#define MN_vblendpd 0x1337
#define MN_roundpd (MN_vroundpd + 1)
#define MN_vroundpd 0x1340
#define MN_vgatherdpd 0x1349
#define MN_vscatterdpd 0x1354
#define MN_cmpunordpd (MN_vcmpunordpd + 1)
#define MN_vcmpunordpd 0x1360
#define MN_cmpordpd (MN_vcmpordpd + 1)
#define MN_vcmpordpd 0x136c
#define MN_vreducepd 0x1376
#define MN_vrangepd 0x1380
#define MN_vcmpngepd 0x1389
#define MN_vcmpgepd 0x1393
#define MN_vrndscalepd 0x139c
#define MN_cmpnlepd (MN_vcmpnlepd + 1)
#define MN_vcmpnlepd 0x13a8
#define MN_cmplepd (MN_vcmplepd + 1)
#define MN_vcmplepd 0x13b2
#define MN_vcmpfalsepd 0x13bb
#define MN_vcmptruepd 0x13c7
#define MN_vscalefpd 0x13d2
#define MN_shufpd (MN_vshufpd + 1)
#define MN_vshufpd 0x13dc
#define MN_unpckhpd (MN_vunpckhpd + 1)
#define MN_vunpckhpd 0x13e4
#define MN_movhpd (MN_vmovhpd + 1)
#define MN_vmovhpd 0x13ee
#define MN_movmskpd (MN_vmovmskpd + 1)
#define MN_vmovmskpd 0x13f6
#define MN_vpermilpd 0x1400
#define MN_unpcklpd (MN_vunpcklpd + 1)
#define MN_vunpcklpd 0x140a
#define MN_mulpd (MN_vmulpd + 1)
#define MN_vmulpd 0x1414
#define MN_movlpd (MN_vmovlpd + 1)
#define MN_vmovlpd 0x141b
#define MN_vpcmpd 0x1423
#define MN_vblendmpd 0x142a
#define MN_vfixupimmpd 0x1434
#define MN_vpermpd 0x1440
#define MN_andnpd (MN_vandnpd + 1)
#define MN_vandnpd 0x1448
#define MN_minpd (MN_vminpd + 1)
#define MN_vminpd 0x1450
#define MN_dppd (MN_vdppd + 1)
#define MN_vdppd 0x1457
#define MN_cmppd (MN_vcmppd + 1)
#define MN_vcmppd 0x145d
#define MN_vgetexppd 0x1464
#define MN_vgatherpf0qpd 0x146e
#define MN_vscatterpf0qpd 0x147c
#define MN_vgatherpf1qpd 0x148b
#define MN_vscatterpf1qpd 0x1499
#define MN_vcmpunord_qpd 0x14a8
#define MN_vcmpord_qpd 0x14b6
#define MN_cmpneqpd (MN_vcmpneqpd + 1)
#define MN_vcmpneqpd 0x14c2
#define MN_cmpeqpd (MN_vcmpeqpd + 1)
#define MN_vcmpeqpd 0x14cc
#define MN_vcmpge_oqpd 0x14d5
#define MN_vcmple_oqpd 0x14e1
#define MN_vcmpfalse_oqpd 0x14ed
#define MN_vcmpneq_oqpd 0x14fc
#define MN_vcmpeq_oqpd 0x1509
#define MN_vcmpgt_oqpd 0x1515
#define MN_vcmplt_oqpd 0x1521
#define MN_vgatherqpd 0x152d
#define MN_vscatterqpd 0x1538
#define MN_vcmpnge_uqpd 0x1544
#define MN_vcmpnle_uqpd 0x1551
#define MN_vcmptrue_uqpd 0x155e
#define MN_vcmpneq_uqpd 0x156c
#define MN_vcmpeq_uqpd 0x1579
#define MN_vcmpngt_uqpd 0x1585
#define MN_vcmpnlt_uqpd 0x1592
#define MN_orpd (MN_vorpd + 1)
#define MN_vorpd 0x159f
#define MN_xorpd (MN_vxorpd + 1)
#define MN_vxorpd 0x15a5
#define MN_vcmpunord_spd 0x15ac
#define MN_vcmpord_spd 0x15ba
#define MN_vcmpge_ospd 0x15c6
#define MN_vcmple_ospd 0x15d2
#define MN_vcmpfalse_ospd 0x15de
#define MN_vcmpneq_ospd 0x15ed
#define MN_vcmpeq_ospd 0x15fa
#define MN_vcmpgt_ospd 0x1606
#define MN_vcmplt_ospd 0x1612
#define MN_vfpclasspd 0x161e
#define MN_incsspd 0x1629
#define MN_rdsspd 0x1631
#define MN_vcompresspd 0x1638
#define MN_vcmpnge_uspd 0x1644
#define MN_vcmpnle_uspd 0x1651
#define MN_vcmptrue_uspd 0x165e
#define MN_vcmpneq_uspd 0x166c
#define MN_vcmpeq_uspd 0x1679
#define MN_vcmpngt_uspd 0x1685
#define MN_vcmpnlt_uspd 0x1692
#define MN_vcmpngtpd 0x169f
#define MN_vcmpgtpd 0x16a9
#define MN_cmpnltpd (MN_vcmpnltpd + 1)
#define MN_vcmpnltpd 0x16b2
#define MN_cmpltpd (MN_vcmpltpd + 1)
#define MN_vcmpltpd 0x16bc
#define MN_vgetmantpd 0x16c5
#define MN_movntpd (MN_vmovntpd + 1)
#define MN_vmovntpd 0x16d0
#define MN_sqrtpd (MN_vsqrtpd + 1)
#define MN_vsqrtpd 0x16d9
#define MN_vtestpd 0x16e1
#define MN_movupd (MN_vmovupd + 1)
#define MN_vmovupd 0x16e9
#define MN_blendvpd (MN_vblendvpd + 1)
#define MN_vblendvpd 0x16f1
#define MN_divpd (MN_vdivpd + 1)
#define MN_vdivpd 0x16fb
#define MN_vmaskmovpd 0x1702
#define MN_maxpd (MN_vminmaxpd + 4)
#define MN_vminmaxpd 0x170d
#define MN_vmaxpd 0x1717
#define MN_vfrczpd 0x171e
#define MN_vpcomeqd 0x1726
#define MN_vpcomneqd 0x172f
#define MN_vpcmpneqd 0x1739
#define MN_pcmpeqd (MN_vpcmpeqd + 1)
#define MN_vpcmpeqd 0x1743
#define MN_vpgatherqd 0x174c
#define MN_vpscatterqd 0x1757
#define MN_vpmovusqd 0x1763
#define MN_vpmovsqd 0x176d
#define MN_vpmovqd 0x1776
#define MN_shrd 0x177e
#define MN_kord 0x1783
#define MN_kxnord 0x1788
#define MN_vpord 0x178f
#define MN_vprord 0x1795
#define MN_word (MN_aword + 1)
#define MN_aword 0x179c
#define MN_dword (MN_adword + 1)
#define MN_adword 0x17a2
#define MN_kxord 0x17a9
#define MN_vpxord 0x17af
#define MN_pinsrd (MN_vpinsrd + 1)
#define MN_vpinsrd 0x17b6
#define MN_kshiftrd 0x17be
#define MN_pextrd (MN_vpextrd + 1)
#define MN_vpextrd 0x17c7
#define MN_vfmsub231sd 0x17cf
#define MN_vfnmsub231sd 0x17db
#define MN_vfmadd231sd 0x17e8
#define MN_vfnmadd231sd 0x17f4
#define MN_vfmsub132sd 0x1801
#define MN_vfnmsub132sd 0x180d
#define MN_vfmadd132sd 0x181a
#define MN_vfnmadd132sd 0x1826
#define MN_vcvtsh2sd 0x1833
#define MN_cvtsi2sd (MN_vcvtsi2sd + 1)
#define MN_vcvtsi2sd 0x183d
#define MN_vcvtusi2sd 0x1847
#define MN_cvtss2sd (MN_vcvtss2sd + 1)
#define MN_vcvtss2sd 0x1852
#define MN_vfmsub213sd 0x185c
#define MN_vfnmsub213sd 0x1868
#define MN_vfmadd213sd 0x1875
#define MN_vfnmadd213sd 0x1881
#define MN_vrcp14sd 0x188e
#define MN_vrsqrt14sd 0x1897
#define MN_vrcp28sd 0x18a2
#define MN_vrsqrt28sd 0x18ab
#define MN_pabsd (MN_vpabsd + 1)
#define MN_vpabsd 0x18b6
#define MN_subsd (MN_vfmsubsd + 3)
#define MN_vfmsubsd 0x18bd
#define MN_vfnmsubsd 0x18c6
#define MN_vsubsd 0x18d0
#define MN_addsd (MN_vfmaddsd + 3)
#define MN_vfmaddsd 0x18d7
#define MN_vfnmaddsd 0x18e0
#define MN_vaddsd 0x18ea
#define MN_roundsd (MN_vroundsd + 1)
#define MN_vroundsd 0x18f1
#define MN_cmpunordsd (MN_vcmpunordsd + 1)
#define MN_vcmpunordsd 0x18fa
#define MN_cmpordsd (MN_vcmpordsd + 1)
#define MN_vcmpordsd 0x1906
#define MN_vreducesd 0x1910
#define MN_vrangesd 0x191a
#define MN_vcmpngesd 0x1923
#define MN_vcmpgesd 0x192d
#define MN_vrndscalesd 0x1936
#define MN_cmpnlesd (MN_vcmpnlesd + 1)
#define MN_vcmpnlesd 0x1942
#define MN_cmplesd (MN_vcmplesd + 1)
#define MN_vcmplesd 0x194c
#define MN_vcmpfalsesd 0x1955
#define MN_vcmptruesd 0x1961
#define MN_vscalefsd 0x196c
#define MN_comisd (MN_ucomisd + 1)
#define MN_ucomisd (MN_vucomisd + 1)
#define MN_vucomisd 0x1976
#define MN_vcomisd 0x197f
#define MN_mulsd (MN_vmulsd + 1)
#define MN_vmulsd 0x1987
#define MN_vfixupimmsd 0x198e
#define MN_minsd (MN_pminsd + 1)
#define MN_pminsd (MN_vpminsd + 1)
#define MN_vpminsd 0x199a
#define MN_vminsd 0x19a2
#define MN_cmpsd (MN_vcmpsd + 1)
#define MN_vcmpsd 0x19a9
#define MN_vgetexpsd 0x19b0
#define MN_vcmpunord_qsd 0x19ba
#define MN_vcmpord_qsd 0x19c8
#define MN_cmpneqsd (MN_vcmpneqsd + 1)
#define MN_vcmpneqsd 0x19d4
#define MN_cmpeqsd (MN_vcmpeqsd + 1)
#define MN_vcmpeqsd 0x19de
#define MN_vcmpge_oqsd 0x19e7
#define MN_vcmple_oqsd 0x19f3
#define MN_vcmpfalse_oqsd 0x19ff
#define MN_vcmpneq_oqsd 0x1a0e
#define MN_vcmpeq_oqsd 0x1a1b
#define MN_vcmpgt_oqsd 0x1a27
#define MN_vcmplt_oqsd 0x1a33
#define MN_vcmpnge_uqsd 0x1a3f
#define MN_vcmpnle_uqsd 0x1a4c
#define MN_vcmptrue_uqsd 0x1a59
#define MN_vcmpneq_uqsd 0x1a67
#define MN_vcmpeq_uqsd 0x1a74
#define MN_vcmpngt_uqsd 0x1a80
#define MN_vcmpnlt_uqsd 0x1a8d
#define MN_vmovrsd 0x1a9a
#define MN_vcmpunord_ssd 0x1aa2
#define MN_vcmpord_ssd 0x1ab0
#define MN_top4bssd 0x1abc
#define MN_vpdpbssd 0x1ac5
#define MN_tdpbssd 0x1ace
#define MN_vpcompressd 0x1ad6
#define MN_vcmpge_ossd 0x1ae2
#define MN_vcmple_ossd 0x1aee
#define MN_vcmpfalse_ossd 0x1afa
#define MN_vcmpneq_ossd 0x1b09
#define MN_vcmpeq_ossd 0x1b16
#define MN_vcmpgt_ossd 0x1b22
#define MN_vcmplt_ossd 0x1b2e
#define MN_wrssd 0x1b3a
#define MN_vfpclasssd 0x1b40
#define MN_vcmpnge_ussd 0x1b4b
#define MN_vcmpnle_ussd 0x1b58
#define MN_vcmptrue_ussd 0x1b65
#define MN_vcmpneq_ussd 0x1b73
#define MN_vcmpeq_ussd 0x1b80
#define MN_vcmpngt_ussd 0x1b8c
#define MN_vcmpnlt_ussd 0x1b99
#define MN_wrussd 0x1ba6
#define MN_vp4dpwssd 0x1bad
#define MN_vpdpwssd 0x1bb7
#define MN_vcmpngtsd 0x1bc0
#define MN_vcmpgtsd 0x1bca
#define MN_cmpnltsd (MN_vcmpnltsd + 1)
#define MN_vcmpnltsd 0x1bd3
#define MN_cmpltsd (MN_vcmpltsd + 1)
#define MN_vcmpltsd 0x1bdd
#define MN_vgetmantsd 0x1be6
#define MN_movntsd 0x1bf1
#define MN_sqrtsd (MN_vsqrtsd + 1)
#define MN_vsqrtsd 0x1bf9
#define MN_vbroadcastsd 0x1c01
#define MN_top4busd 0x1c0e
#define MN_vpdpbusd 0x1c17
#define MN_tdpbusd 0x1c20
#define MN_vpdpwusd 0x1c28
#define MN_divsd (MN_vdivsd + 1)
#define MN_vdivsd 0x1c31
#define MN_movsd (MN_vmovsd + 1)
#define MN_vmovsd 0x1c38
#define MN_maxsd (MN_vminmaxsd + 4)
#define MN_vminmaxsd 0x1c3f
#define MN_pmaxsd (MN_vpmaxsd + 1)
#define MN_vpmaxsd 0x1c49
#define MN_vmaxsd 0x1c51
#define MN_vucomxsd 0x1c58
#define MN_vcomxsd 0x1c61
#define MN_vfrczsd 0x1c69
#define MN_vp2intersectd 0x1c71
#define MN_vpconflictd 0x1c7f
#define MN_vpcomgtd 0x1c8b
#define MN_pcmpgtd (MN_vpcmpgtd + 1)
#define MN_vpcmpgtd 0x1c94
#define MN_cltd 0x1c9d
#define MN_vpcomltd 0x1ca2
#define MN_vpcmpnltd 0x1cab
#define MN_vpcmpltd 0x1cb5
#define MN_vpopcntd 0x1cbe
#define MN_vplzcntd 0x1cc7
#define MN_knotd 0x1cd0
#define MN_vprotd 0x1cd6
#define MN_std (MN_vpbroadcastd + 9)
#define MN_vpbroadcastd 0x1cdd
#define MN_ktestd 0x1cea
#define MN_kortestd 0x1cf1
#define MN_cwtd 0x1cfa
#define MN_vpcomgeud 0x1cff
#define MN_vpcomleud 0x1d09
#define MN_vpcmpnleud 0x1d13
#define MN_vpcmpleud 0x1d1e
#define MN_vpcomfalseud 0x1d28
#define MN_vpcomtrueud 0x1d35
#define MN_vpcomud 0x1d41
#define MN_pminud (MN_vpminud + 1)
#define MN_vpminud 0x1d49
#define MN_vpcmpud 0x1d51
#define MN_vpcomequd 0x1d59
#define MN_vpcomnequd 0x1d63
#define MN_vpcmpnequd 0x1d6e
#define MN_vpcmpequd 0x1d79
#define MN_top4bsud 0x1d83
#define MN_vpdpbsud 0x1d8c
#define MN_tdpbsud 0x1d95
#define MN_vpdpwsud 0x1d9d
#define MN_vpcomgtud 0x1da6
#define MN_vpcomltud 0x1db0
#define MN_vpcmpnltud 0x1dba
#define MN_vpcmpltud 0x1dc5
#define MN_top4buud 0x1dcf
#define MN_vpdpbuud 0x1dd8
#define MN_tdpbuud 0x1de1
#define MN_vpdpwuud 0x1de9
#define MN_pmaxud (MN_vpmaxud + 1)
#define MN_vpmaxud 0x1df2
#define MN_vpsravd 0x1dfa
#define MN_vpshldvd 0x1e02
#define MN_vpshrdvd 0x1e0b
#define MN_vpsllvd 0x1e14
#define MN_vprolvd 0x1e1c
#define MN_vpsrlvd 0x1e24
#define MN_invd (MN_wbinvd + 2)
#define MN_wbinvd 0x1e2c
#define MN_wbnoinvd 0x1e33
#define MN_movd (MN_kmovd + 1)
#define MN_kmovd (MN_vpmaskmovd + 5)
#define MN_vpmaskmovd 0x1e3c
#define MN_vmovd 0x1e47
#define MN_vprorvd 0x1e4d
#define MN_vphsubwd 0x1e55
#define MN_cwd 0x1e5e
#define MN_vphaddwd 0x1e62
#define MN_pmaddwd (MN_vpmaddwd + 1)
#define MN_vpmaddwd 0x1e6b
#define MN_punpckhwd (MN_vpunpckhwd + 1)
#define MN_vpunpckhwd 0x1e74
#define MN_kunpckwd 0x1e7f
#define MN_punpcklwd (MN_vpunpcklwd + 1)
#define MN_vpunpcklwd 0x1e88
#define MN_vpmacswd 0x1e93
#define MN_vpmadcswd 0x1e9c
#define MN_vpmacsswd 0x1ea6
#define MN_vpmadcsswd 0x1eb0
#define MN_vphadduwd 0x1ebb
#define MN_pmovsxwd (MN_vpmovsxwd + 1)
#define MN_vpmovsxwd 0x1ec5
#define MN_pmovzxwd (MN_vpmovzxwd + 1)
#define MN_vpmovzxwd 0x1ecf
#define MN_movsxd 0x1ed9
#define MN_fldl2e 0x1ee0
#define MN_jae 0x1ee7
#define MN_jnae 0x1eeb
#define MN_ccmpnae 0x1ef0
#define MN_setnae 0x1ef8
#define MN_ctestnae 0x1eff
#define MN_setzunae 0x1f08
#define MN_cmovnae (MN_fcmovnae + 1)
#define MN_fcmovnae (MN_cfcmovnae + 1)
#define MN_cfcmovnae 0x1f11
#define MN_ccmpae 0x1f1b
#define MN_setae 0x1f22
#define MN_ctestae 0x1f28
#define MN_setzuae 0x1f30
#define MN_cmovae (MN_fcmovae + 1)
#define MN_fcmovae (MN_cfcmovae + 1)
#define MN_cfcmovae 0x1f38
#define MN_jbe 0x1f41
#define MN_jnbe 0x1f45
#define MN_ccmpnbe 0x1f4a
#define MN_setnbe 0x1f52
#define MN_ctestnbe 0x1f59
#define MN_setzunbe 0x1f62
#define MN_cmovnbe (MN_fcmovnbe + 1)
#define MN_fcmovnbe (MN_cfcmovnbe + 1)
#define MN_cfcmovnbe 0x1f6b
#define MN_ccmpbe 0x1f75
#define MN_setbe 0x1f7c
#define MN_ctestbe 0x1f82
#define MN_setzube 0x1f8a
#define MN_movbe (MN_cmovbe + 1)
#define MN_cmovbe (MN_fcmovbe + 1)
#define MN_fcmovbe (MN_cfcmovbe + 1)
#define MN_cfcmovbe 0x1f92
#define MN_lfence 0x1f9b
#define MN_mfence 0x1fa2
#define MN_sfence 0x1fa9
#define MN_cwde 0x1fb0
#define MN_ffree 0x1fb5
#define MN_jge 0x1fbb
#define MN_jnge 0x1fbf
#define MN_ccmpnge 0x1fc4
#define MN_setnge 0x1fcc
#define MN_ctestnge 0x1fd3
#define MN_setzunge 0x1fdc
#define MN_cmovnge (MN_cfcmovnge + 2)
#define MN_cfcmovnge 0x1fe5
#define MN_ccmpge 0x1fef
#define MN_pfcmpge 0x1ff6
#define MN_setge 0x1ffe
#define MN_ctestge 0x2004
#define MN_setzuge 0x200c
#define MN_cmovge (MN_cfcmovge + 2)
#define MN_cfcmovge 0x2014
#define MN_je 0x201d
#define MN_fscale 0x2020
#define MN_jle 0x2027
#define MN_jnle 0x202b
#define MN_ccmpnle 0x2030
#define MN_setnle 0x2038
#define MN_ctestnle 0x203f
#define MN_setzunle 0x2048
#define MN_cmovnle (MN_cfcmovnle + 2)
#define MN_cfcmovnle 0x2051
#define MN_ccmple 0x205b
#define MN_setle 0x2062
#define MN_ctestle 0x2068
#define MN_setzule 0x2070
#define MN_cmovle (MN_cfcmovle + 2)
#define MN_cfcmovle 0x2078
#define MN_vmresume 0x2081
#define MN_jne 0x208a
#define MN_repne 0x208e
#define MN_ccmpne 0x2094
#define MN_loopne 0x209b
#define MN_setne 0x20a2
#define MN_ctestne 0x20a8
#define MN_setzune 0x20b0
#define MN_cmovne (MN_fcmovne + 1)
#define MN_fcmovne (MN_cfcmovne + 1)
#define MN_cfcmovne 0x20b8
#define MN_repe 0x20c1
#define MN_jpe 0x20c6
#define MN_ccmpe 0x20ca
#define MN_loope 0x20d0
#define MN_setpe 0x20d6
#define MN_setzupe 0x20dc
#define MN_cmovpe (MN_cfcmovpe + 2)
#define MN_cfcmovpe 0x20e4
#define MN_cdqe 0x20ed
#define MN_xacquire 0x20f2
#define MN_xstore 0x20fb
#define MN_rdfsbase 0x2102
#define MN_wrfsbase 0x210b
#define MN_rdgsbase 0x2114
#define MN_wrgsbase 0x211d
#define MN_tilerelease 0x2126
#define MN_xrelease 0x2132
#define MN_pause (MN_tpause + 1)
#define MN_tpause 0x213b
#define MN_pvalidate 0x2142
#define MN_rmpupdate 0x214c
#define MN_sete 0x2156
#define MN_vmwrite 0x215b
#define MN_ptwrite 0x2163
#define MN_cldemote 0x216b
#define MN_cteste 0x2174
#define MN_sha1nexte 0x217b
#define MN_setzue 0x2185
#define MN_leave 0x218c
#define MN_fsave 0x2192
#define MN_vmsave 0x2198
#define MN_fnsave 0x219f
#define MN_xsave (MN_fxsave + 1)
#define MN_fxsave 0x21a6
#define MN_cmove (MN_fcmove + 1)
#define MN_fcmove (MN_cfcmove + 1)
#define MN_cfcmove 0x21ad
#define MN_serialize 0x21b5
#define MN_vmxoff 0x21bf
#define MN_lahf 0x21c6
#define MN_sahf 0x21cb
#define MN_pushf 0x21d0
#define MN_ccmpf 0x21d6
#define MN_popf 0x21dc
#define MN_bsf 0x21e1
#define MN_retf 0x21e5
#define MN_ctestf 0x21ea
#define MN_bsrmovf 0x21f1
#define MN_neg 0x21f9
#define MN_ldtilecfg 0x21fd
#define MN_sttilecfg 0x2207
#define MN_xchg (MN_cmpxchg + 3)
#define MN_cmpxchg 0x2211
#define MN_pconfig 0x2219
#define MN_jg 0x2221
#define MN_jng 0x2224
#define MN_ccmpng 0x2228
#define MN_xstore_rng 0x222f
#define MN_xstorerng 0x223a
#define MN_setng 0x2244
#define MN_ctestng 0x224a
#define MN_setzung 0x2252
#define MN_cmovng (MN_cfcmovng + 2)
#define MN_cfcmovng 0x225a
#define MN_invlpg 0x2263
#define MN_ccmpg 0x226a
#define MN_setg 0x2270
#define MN_ctestg 0x2275
#define MN_setzug 0x227c
#define MN_cmovg (MN_cfcmovg + 2)
#define MN_cfcmovg 0x2283
#define MN_tcvtrowps2bf16h 0x228b
#define MN_vmlaunch 0x229b
#define MN_prefetch 0x22a4
#define MN_fxch 0x22ad
#define MN_tcvtrowps2phh 0x22b2
#define MN_vfmaddsub231ph 0x22c0
#define MN_vfmsub231ph 0x22cf
#define MN_vfnmsub231ph 0x22db
#define MN_vfmsubadd231ph 0x22e8
#define MN_vfmadd231ph 0x22f7
#define MN_vfnmadd231ph 0x2303
#define MN_vfmaddsub132ph 0x2310
#define MN_vfmsub132ph 0x231f
#define MN_vfnmsub132ph 0x232b
#define MN_vfmsubadd132ph 0x2338
#define MN_vfmadd132ph 0x2347
#define MN_vfnmadd132ph 0x2353
#define MN_vcvthf82ph 0x2360
#define MN_vcvtpd2ph 0x236b
#define MN_vcvtdq2ph 0x2375
#define MN_vcvtudq2ph 0x237f
#define MN_vcvtqq2ph 0x238a
#define MN_vcvtuqq2ph 0x2394
#define MN_vcvtps2ph 0x239f
#define MN_vcvtw2ph 0x23a9
#define MN_vcvtuw2ph 0x23b2
#define MN_vfmaddsub213ph 0x23bc
#define MN_vfmsub213ph 0x23cb
#define MN_vfnmsub213ph 0x23d7
#define MN_vfmsubadd213ph 0x23e4
#define MN_vfmadd213ph 0x23f3
#define MN_vfnmadd213ph 0x23ff
#define MN_vsubph 0x240c
#define MN_vfcmaddcph 0x2413
#define MN_vfmaddcph 0x241e
#define MN_vfcmulcph 0x2428
#define MN_vfmulcph 0x2432
#define MN_vaddph 0x243b
#define MN_vcmpunordph 0x2442
#define MN_vcmpordph 0x244e
#define MN_vreduceph 0x2458
#define MN_vcmpngeph 0x2462
#define MN_vcmpgeph 0x246c
#define MN_vrndscaleph 0x2475
#define MN_vcmpnleph 0x2481
#define MN_vcmpleph 0x248b
#define MN_vcmpfalseph 0x2494
#define MN_vcmptrueph 0x24a0
#define MN_vscalefph 0x24ab
#define MN_vmulph 0x24b5
#define MN_vminph 0x24bc
#define MN_vrcpph 0x24c3
#define MN_vcmpph 0x24ca
#define MN_vgetexpph 0x24d1
#define MN_vcmpunord_qph 0x24db
#define MN_vcmpord_qph 0x24e9
#define MN_vcmpneqph 0x24f5
#define MN_vcmpeqph 0x24ff
#define MN_vcmpge_oqph 0x2508
#define MN_vcmple_oqph 0x2514
#define MN_vcmpfalse_oqph 0x2520
#define MN_vcmpneq_oqph 0x252f
#define MN_vcmpeq_oqph 0x253c
#define MN_vcmpgt_oqph 0x2548
#define MN_vcmplt_oqph 0x2554
#define MN_vcmpnge_uqph 0x2560
#define MN_vcmpnle_uqph 0x256d
#define MN_vcmptrue_uqph 0x257a
#define MN_vcmpneq_uqph 0x2588
#define MN_vcmpeq_uqph 0x2595
#define MN_vcmpngt_uqph 0x25a1
#define MN_vcmpnlt_uqph 0x25ae
#define MN_vcmpunord_sph 0x25bb
#define MN_vcmpord_sph 0x25c9
#define MN_vcmpge_osph 0x25d5
#define MN_vcmple_osph 0x25e1
#define MN_vcmpfalse_osph 0x25ed
#define MN_vcmpneq_osph 0x25fc
#define MN_vcmpeq_osph 0x2609
#define MN_vcmpgt_osph 0x2615
#define MN_vcmplt_osph 0x2621
#define MN_vfpclassph 0x262d
#define MN_vcmpnge_usph 0x2638
#define MN_vcmpnle_usph 0x2645
#define MN_vcmptrue_usph 0x2652
#define MN_vcmpneq_usph 0x2660
#define MN_vcmpeq_usph 0x266d
#define MN_vcmpngt_usph 0x2679
#define MN_vcmpnlt_usph 0x2686
#define MN_vcmpngtph 0x2693
#define MN_vcmpgtph 0x269d
#define MN_vcmpnltph 0x26a6
#define MN_vcmpltph 0x26b0
#define MN_vgetmantph 0x26b9
#define MN_vrsqrtph 0x26c4
#define MN_vsqrtph 0x26cd
#define MN_vdivph 0x26d5
#define MN_vminmaxph 0x26dc
#define MN_vmaxph 0x26e6
#define MN_vpmacsdqh 0x26ed
#define MN_vpmacssdqh 0x26f7
#define MN_vfmsub231sh 0x2702
#define MN_vfnmsub231sh 0x270e
#define MN_vfmadd231sh 0x271b
#define MN_vfnmadd231sh 0x2727
#define MN_vfmsub132sh 0x2734
#define MN_vfnmsub132sh 0x2740
#define MN_vfmadd132sh 0x274d
#define MN_vfnmadd132sh 0x2759
#define MN_vcvtsd2sh 0x2766
#define MN_vcvtsi2sh 0x2770
#define MN_vcvtusi2sh 0x277a
#define MN_vcvtss2sh 0x2785
#define MN_vfmsub213sh 0x278f
#define MN_vfnmsub213sh 0x279b
#define MN_vfmadd213sh 0x27a8
#define MN_vfnmadd213sh 0x27b4
#define MN_psmash 0x27c1
#define MN_vsubsh 0x27c8
#define MN_vfcmaddcsh 0x27cf
#define MN_vfmaddcsh 0x27da
#define MN_vfcmulcsh 0x27e4
#define MN_vfmulcsh 0x27ee
#define MN_vaddsh 0x27f7
#define MN_vcmpunordsh 0x27fe
#define MN_vcmpordsh 0x280a
#define MN_vreducesh 0x2814
#define MN_vcmpngesh 0x281e
#define MN_vcmpgesh 0x2828
#define MN_vrndscalesh 0x2831
#define MN_vcmpnlesh 0x283d
#define MN_vcmplesh 0x2847
#define MN_vcmpfalsesh 0x2850
#define MN_vcmptruesh 0x285c
#define MN_vscalefsh 0x2867
#define MN_vucomish 0x2871
#define MN_vcomish 0x287a
#define MN_vmulsh 0x2882
#define MN_vminsh 0x2889
#define MN_vrcpsh 0x2890
#define MN_vcmpsh 0x2897
#define MN_vgetexpsh 0x289e
#define MN_vcmpunord_qsh 0x28a8
#define MN_vcmpord_qsh 0x28b6
#define MN_vcmpneqsh 0x28c2
#define MN_vcmpeqsh 0x28cc
#define MN_vcmpge_oqsh 0x28d5
#define MN_vcmple_oqsh 0x28e1
#define MN_vcmpfalse_oqsh 0x28ed
#define MN_vcmpneq_oqsh 0x28fc
#define MN_vcmpeq_oqsh 0x2909
#define MN_vcmpgt_oqsh 0x2915
#define MN_vcmplt_oqsh 0x2921
#define MN_vcmpnge_uqsh 0x292d
#define MN_vcmpnle_uqsh 0x293a
#define MN_vcmptrue_uqsh 0x2947
#define MN_vcmpneq_uqsh 0x2955
#define MN_vcmpeq_uqsh 0x2962
#define MN_vcmpngt_uqsh 0x296e
#define MN_vcmpnlt_uqsh 0x297b
#define MN_vcmpunord_ssh 0x2988
#define MN_vcmpord_ssh 0x2996
#define MN_vcmpge_ossh 0x29a2
#define MN_vcmple_ossh 0x29ae
#define MN_vcmpfalse_ossh 0x29ba
#define MN_vcmpneq_ossh 0x29c9
#define MN_vcmpeq_ossh 0x29d6
#define MN_vcmpgt_ossh 0x29e2
#define MN_vcmplt_ossh 0x29ee
#define MN_vfpclasssh 0x29fa
#define MN_vcmpnge_ussh 0x2a05
#define MN_vcmpnle_ussh 0x2a12
#define MN_vcmptrue_ussh 0x2a1f
#define MN_vcmpneq_ussh 0x2a2d
#define MN_vcmpeq_ussh 0x2a3a
#define MN_vcmpngt_ussh 0x2a46
#define MN_vcmpnlt_ussh 0x2a53
#define MN_vcmpngtsh 0x2a60
#define MN_vcmpgtsh 0x2a6a
#define MN_vcmpnltsh 0x2a73
#define MN_vcmpltsh 0x2a7d
#define MN_vgetmantsh 0x2a86
#define MN_vrsqrtsh 0x2a91
#define MN_vsqrtsh 0x2a9a
#define MN_clflush 0x2aa2
#define MN_push 0x2aaa
#define MN_vdivsh 0x2aaf
#define MN_vmovsh 0x2ab6
#define MN_vminmaxsh 0x2abd
#define MN_vmaxsh 0x2ac7
#define MN_vucomxsh 0x2ace
#define MN_vcomxsh 0x2ad7
#define MN_bsrmovh 0x2adf
#define MN_blci 0x2ae7
#define MN_clgi 0x2aec
#define MN_stgi 0x2af1
#define MN_bzhi 0x2af6
#define MN_cli 0x2afb
#define MN_fcomi 0x2aff
#define MN_fucomi 0x2b05
#define MN_feni 0x2b0c
#define MN_fneni 0x2b11
#define MN_cvttpd2pi 0x2b17
#define MN_cvtpd2pi 0x2b21
#define MN_cvttps2pi 0x2b2a
#define MN_cvtps2pi 0x2b34
#define MN_fldpi 0x2b3d
#define MN_senduipi 0x2b43
#define MN_fcompi 0x2b4c
#define MN_fucompi 0x2b53
#define MN_movdiri 0x2b5b
#define MN_pcmpestri (MN_vpcmpestri + 1)
#define MN_vpcmpestri 0x2b63
#define MN_pcmpistri (MN_vpcmpistri + 1)
#define MN_vpcmpistri 0x2b6e
#define MN_cvttsd2si (MN_vcvttsd2si + 1)
#define MN_vcvttsd2si 0x2b79
#define MN_cvtsd2si (MN_vcvtsd2si + 1)
#define MN_vcvtsd2si 0x2b84
#define MN_vcvttsh2si 0x2b8e
#define MN_vcvtsh2si 0x2b99
#define MN_cvttss2si (MN_vcvttss2si + 1)
#define MN_vcvttss2si 0x2ba3
#define MN_cvtss2si (MN_vcvtss2si + 1)
#define MN_vcvtss2si 0x2bae
#define MN_fdisi 0x2bb8
#define MN_fndisi 0x2bbe
#define MN_blsi 0x2bc5
#define MN_vcvttsd2usi 0x2bca
#define MN_vcvtsd2usi 0x2bd6
#define MN_vcvttsh2usi 0x2be1
#define MN_vcvtsh2usi 0x2bed
#define MN_vcvttss2usi 0x2bf8
#define MN_vcvtss2usi 0x2c04
#define MN_movnti 0x2c0f
#define MN_sti 0x2c16
#define MN_clui 0x2c1a
#define MN_stui (MN_testui + 2)
#define MN_testui 0x2c1f
#define MN_notrack 0x2c26
#define MN_lock 0x2c2e
#define MN_bndmk 0x2c33
#define MN_xresldtrk 0x2c39
#define MN_xsusldtrk 0x2c43
#define MN_blcmsk 0x2c4d
#define MN_blsmsk 0x2c54
#define MN_tzmsk 0x2c5b
#define MN_tcvtrowps2bf16l 0x2c61
#define MN_sal 0x2c71
#define MN_lwpval 0x2c75
#define MN_bndcl 0x2c7c
#define MN_rcl 0x2c82
#define MN_tcvtrowps2phl 0x2c86
#define MN_shl 0x2c94
#define MN_jl 0x2c98
#define MN_aesdec256kl 0x2c9b
#define MN_aesenc256kl 0x2ca7
#define MN_aesdecwide256kl 0x2cb3
#define MN_aesencwide256kl 0x2cc3
#define MN_aesdec128kl 0x2cd3
#define MN_aesenc128kl 0x2cdf
#define MN_aesdecwide128kl 0x2ceb
#define MN_aesencwide128kl 0x2cfb
#define MN_call (MN_tdcall + 2)
#define MN_tdcall 0x2d0b
#define MN_lcall 0x2d12
#define MN_seamcall 0x2d18
#define MN_vmmcall 0x2d21
#define MN_vmcall 0x2d29
#define MN_syscall 0x2d30
#define MN_vzeroall 0x2d38
#define MN_fildll 0x2d41
#define MN_blcfill 0x2d48
#define MN_blsfill 0x2d50
#define MN_fistpll 0x2d58
#define MN_fisttpll 0x2d60
#define MN_jnl 0x2d69
#define MN_ccmpnl 0x2d6d
#define MN_setnl 0x2d74
#define MN_ctestnl 0x2d7a
#define MN_setzunl 0x2d82
#define MN_cmovnl (MN_cfcmovnl + 2)
#define MN_cfcmovnl 0x2d8a
#define MN_tilemovcol 0x2d93
#define MN_rol 0x2d9e
#define MN_ccmpl 0x2da2
#define MN_arpl 0x2da8
#define MN_vpmacsdql 0x2dad
#define MN_vpmacssdql 0x2db7
#define MN_lsl 0x2dc2
#define MN_movsl 0x2dc6
#define MN_setl 0x2dcc
#define MN_ctestl 0x2dd1
#define MN_cwtl 0x2dd8
#define MN_mul (MN_fmul + 1)
#define MN_fmul (MN_pfmul + 1)
#define MN_pfmul 0x2ddd
#define MN_imul (MN_fimul + 1)
#define MN_fimul 0x2de3
#define MN_montmul 0x2de9
#define MN_setzul 0x2df1
#define MN_cmovl (MN_cfcmovl + 2)
#define MN_cfcmovl 0x2df8
#define MN_bsrmovl 0x2e00
#define MN_vpmovb2m 0x2e08
#define MN_vpmovd2m 0x2e11
#define MN_vpmovq2m 0x2e1a
#define MN_vpmovw2m 0x2e23
#define MN_aam 0x2e2c
#define MN_fxam 0x2e30
#define MN_fprem 0x2e35
#define MN_fcom 0x2e3b
#define MN_ficom 0x2e40
#define MN_fucom 0x2e46
#define MN_fsetpm 0x2e4c
#define MN_fnsetpm 0x2e53
#define MN_frstpm 0x2e5b
#define MN_vpperm 0x2e62
#define MN_pcmpestrm (MN_vpcmpestrm + 1)
#define MN_vpcmpestrm 0x2e69
#define MN_pcmpistrm (MN_vpcmpistrm + 1)
#define MN_vpcmpistrm 0x2e74
#define MN_rsm 0x2e7f
#define MN_fpatan 0x2e83
#define MN_fptan 0x2e8a
#define MN_bndcn 0x2e90
#define MN_andn (MN_pandn + 1)
#define MN_pandn (MN_vpandn + 1)
#define MN_vpandn 0x2e96
#define MN_in (MN_xbegin + 4)
#define MN_xbegin 0x2e9d
#define MN_pfmin 0x2ea4
#define MN_fsin 0x2eaa
#define MN_vmxon 0x2eaf
#define MN_vmrun 0x2eb5
#define MN_jo 0x2ebb
#define MN_jno 0x2ebe
#define MN_ccmpno 0x2ec2
#define MN_setno 0x2ec9
#define MN_ctestno 0x2ecf
#define MN_setzuno 0x2ed7
#define MN_cmovno (MN_cfcmovno + 2)
#define MN_cfcmovno 0x2edf
#define MN_jpo 0x2ee8
#define MN_ccmpo 0x2eec
#define MN_setpo 0x2ef2
#define MN_setzupo 0x2ef8
#define MN_cmovpo (MN_cfcmovpo + 2)
#define MN_cfcmovpo 0x2f00
#define MN_cqo 0x2f09
#define MN_tilezero 0x2f0d
#define MN_clzero 0x2f16
#define MN_seto 0x2f1d
#define MN_into 0x2f22
#define MN_cqto 0x2f27
#define MN_ctesto 0x2f2c
#define MN_ssto 0x2f33
#define MN_setzuo 0x2f38
#define MN_cmovo (MN_cfcmovo + 2)
#define MN_cfcmovo 0x2f3f
#define MN_push2p 0x2f47
#define MN_pop2p 0x2f4e
#define MN_bswap 0x2f54
#define MN_fsubp 0x2f5a
#define MN_pfrcp 0x2f60
#define MN_rdtscp 0x2f66
#define MN_faddp 0x2f6d
#define MN_pdep 0x2f73
#define MN_ffreep 0x2f78
#define MN_rep 0x2f7f
#define MN_pushp 0x2f83
#define MN_fcomip 0x2f89
#define MN_fucomip 0x2f90
#define MN_jp 0x2f98
#define MN_fmulp 0x2f9b
#define MN_cmp (MN_scmp + 1)
#define MN_scmp 0x2fa1
#define MN_jmp (MN_ljmp + 1)
#define MN_ljmp 0x2fa6
#define MN_fcomp 0x2fab
#define MN_ficomp 0x2fb1
#define MN_fucomp 0x2fb8
#define MN_jnp 0x2fbf
#define MN_setnp 0x2fc3
#define MN_setzunp 0x2fc9
#define MN_cmovnp (MN_cfcmovnp + 2)
#define MN_cfcmovnp 0x2fd1
#define MN_nop (MN_fnop + 1)
#define MN_fnop 0x2fda
#define MN_loop 0x2fdf
#define MN_pop 0x2fe4
#define MN_fcompp 0x2fe8
#define MN_fucompp 0x2fef
#define MN_popp 0x2ff7
#define MN_fsubrp 0x2ffc
#define MN_fdivrp 0x3003
#define MN_rstorssp 0x300a
#define MN_saveprevssp 0x3013
#define MN_setp 0x301f
#define MN_fbstp 0x3024
#define MN_fdecstp 0x302a
#define MN_fincstp 0x3032
#define MN_fstp 0x303a
#define MN_fistp 0x303f
#define MN_fisttp 0x3045
#define MN_movddup (MN_vmovddup + 1)
#define MN_vmovddup 0x304c
#define MN_movshdup (MN_vmovshdup + 1)
#define MN_vmovshdup 0x3055
#define MN_movsldup (MN_vmovsldup + 1)
#define MN_vmovsldup 0x305f
#define MN_setzup 0x3069
#define MN_fdivp 0x3070
#define MN_cmovp (MN_cfcmovp + 2)
#define MN_cfcmovp 0x3076
#define MN_xmodexp 0x307e
#define MN_vpbroadcastmb2q 0x3086
#define MN_vpermi2q 0x3096
#define MN_vpmovm2q 0x309f
#define MN_movdq2q 0x30a8
#define MN_vpermt2q 0x30b0
#define MN_vpshaq 0x30b9
#define MN_vpsraq 0x30c0
#define MN_vphaddbq 0x30c7
#define MN_vphaddubq 0x30d0
#define MN_psubq (MN_vpsubq + 1)
#define MN_vpsubq 0x30da
#define MN_pmovsxbq (MN_vpmovsxbq + 1)
#define MN_vpmovsxbq 0x30e1
#define MN_pmovzxbq (MN_vpmovzxbq + 1)
#define MN_vpmovzxbq 0x30eb
#define MN_cvttpd2dq (MN_vcvttpd2dq + 1)
#define MN_vcvttpd2dq 0x30f5
#define MN_cvtpd2dq (MN_vcvtpd2dq + 1)
#define MN_vcvtpd2dq 0x3100
#define MN_vcvttph2dq 0x310a
#define MN_vcvtph2dq 0x3115
#define MN_movq2dq 0x311f
#define MN_cvttps2dq (MN_vcvttps2dq + 1)
#define MN_vcvttps2dq 0x3127
#define MN_cvtps2dq (MN_vcvtps2dq + 1)
#define MN_vcvtps2dq 0x3132
#define MN_vphsubdq 0x313c
#define MN_cdq 0x3145
#define MN_kaddq 0x3149
#define MN_paddq (MN_vpaddq + 1)
#define MN_vpaddq 0x314f
#define MN_vphadddq 0x3156
#define MN_punpckhdq (MN_vpunpckhdq + 1)
#define MN_vpunpckhdq 0x315f
#define MN_kunpckdq 0x316a
#define MN_vpshldq 0x3173
#define MN_punpckldq (MN_vpunpckldq + 1)
#define MN_vpunpckldq 0x317b
#define MN_pslldq (MN_vpslldq + 1)
#define MN_vpslldq 0x3186
#define MN_psrldq (MN_vpsrldq + 1)
#define MN_vpsrldq 0x318e
#define MN_pmuldq (MN_vpmuldq + 1)
#define MN_vpmuldq 0x3196
#define MN_kandq 0x319e
#define MN_vpandq 0x31a4
#define MN_vpexpandq 0x31ab
#define MN_punpckhqdq (MN_vpunpckhqdq + 1)
#define MN_vpunpckhqdq 0x31b5
#define MN_pclmulhqhqdq (MN_vpclmulhqhqdq + 1)
#define MN_vpclmulhqhqdq 0x31c1
#define MN_pclmullqhqdq (MN_vpclmullqhqdq + 1)
#define MN_vpclmullqhqdq 0x31cf
#define MN_punpcklqdq (MN_vpunpcklqdq + 1)
#define MN_vpunpcklqdq 0x31dd
#define MN_pclmulhqlqdq (MN_vpclmulhqlqdq + 1)
#define MN_vpclmulhqlqdq 0x31e9
#define MN_pclmullqlqdq (MN_vpclmullqlqdq + 1)
#define MN_vpclmullqlqdq 0x31f7
#define MN_pclmulqdq (MN_vpclmulqdq + 1)
#define MN_vpclmulqdq 0x3205
#define MN_vpgatherdq 0x3210
#define MN_vpscatterdq 0x321b
#define MN_vpshrdq 0x3227
#define MN_movntdq (MN_vmovntdq + 1)
#define MN_vmovntdq 0x322f
#define MN_vcvttpd2udq 0x3238
#define MN_vcvtpd2udq 0x3244
#define MN_vcvttph2udq 0x324f
#define MN_vcvtph2udq 0x325b
#define MN_vcvttps2udq 0x3266
#define MN_vcvtps2udq 0x3272
#define MN_vphaddudq 0x327d
#define MN_pmuludq (MN_vpmuludq + 1)
#define MN_vpmuludq 0x3287
#define MN_pmovsxdq (MN_vpmovsxdq + 1)
#define MN_vpmovsxdq 0x3290
#define MN_pmovzxdq (MN_vpmovzxdq + 1)
#define MN_vpmovzxdq 0x329a
#define MN_vpcomgeq 0x32a4
#define MN_vpcomleq 0x32ad
#define MN_vpcmpnleq 0x32b6
#define MN_vpcmpleq 0x32c0
#define MN_pfcmpeq 0x32c9
#define MN_vpcomfalseq 0x32d1
#define MN_vpcomtrueq 0x32dd
#define MN_vpternlogq 0x32e8
#define MN_vpshlq 0x32f3
#define MN_psllq (MN_vpsllq + 1)
#define MN_vpsllq 0x32fa
#define MN_vpmullq 0x3301
#define MN_vprolq 0x3309
#define MN_psrlq (MN_vpsrlq + 1)
#define MN_vpsrlq 0x3310
#define MN_kshiftlq 0x3317
#define MN_vpblendmq 0x3320
#define MN_vptestnmq 0x332a
#define MN_vpcomq 0x3334
#define MN_vpermq 0x333b
#define MN_vptestmq 0x3342
#define MN_kandnq 0x334b
#define MN_vpandnq 0x3352
#define MN_valignq 0x335a
#define MN_vpcmpq 0x3362
#define MN_incsspq 0x3369
#define MN_rdsspq 0x3371
#define MN_vcvttpd2qq 0x3378
#define MN_vcvtpd2qq 0x3383
#define MN_vcvttph2qq 0x338d
#define MN_vcvtph2qq 0x3398
#define MN_vcvttps2qq 0x33a2
#define MN_vcvtps2qq 0x33ad
#define MN_vpcomeqq 0x33b7
#define MN_vpcomneqq 0x33c0
#define MN_vpcmpneqq 0x33ca
#define MN_pcmpeqq (MN_vpcmpeqq + 1)
#define MN_vpcmpeqq 0x33d4
#define MN_vpgatherqq 0x33dd
#define MN_vpscatterqq 0x33e8
#define MN_vcvttpd2uqq 0x33f4
#define MN_vcvtpd2uqq 0x3400
#define MN_vcvttph2uqq 0x340b
#define MN_vcvtph2uqq 0x3417
#define MN_vcvttps2uqq 0x3422
#define MN_vcvtps2uqq 0x342e
#define MN_korq 0x3439
#define MN_kxnorq 0x343e
#define MN_vporq 0x3445
#define MN_vprorq 0x344b
#define MN_kxorq 0x3452
#define MN_vpxorq 0x3458
#define MN_pinsrq (MN_vpinsrq + 1)
#define MN_vpinsrq 0x345f
#define MN_kshiftrq 0x3467
#define MN_extrq (MN_pextrq + 1)
#define MN_pextrq (MN_vpextrq + 1)
#define MN_vpextrq 0x3470
#define MN_vpabsq 0x3478
#define MN_vpminsq 0x347f
#define MN_vmovrsq 0x3487
#define MN_vpcompressq 0x348f
#define MN_wrssq 0x349b
#define MN_wrussq 0x34a1
#define MN_vpmaxsq 0x34a8
#define MN_vp2intersectq 0x34b0
#define MN_vpconflictq 0x34be
#define MN_vpcomgtq 0x34ca
#define MN_pcmpgtq (MN_vpcmpgtq + 1)
#define MN_vpcmpgtq 0x34d3
#define MN_cltq 0x34dc
#define MN_vpcomltq 0x34e1
#define MN_vpcmpnltq 0x34ea
#define MN_vpcmpltq 0x34f4
#define MN_vpopcntq 0x34fd
#define MN_vplzcntq 0x3506
#define MN_movntq 0x350f
#define MN_knotq 0x3516
#define MN_vprotq 0x351c
#define MN_insertq 0x3523
#define MN_vpbroadcastq 0x352b
#define MN_ktestq 0x3538
#define MN_kortestq 0x353f
#define MN_vpcomgeuq 0x3548
#define MN_vpcomleuq 0x3552
#define MN_vpcmpnleuq 0x355c
#define MN_vpcmpleuq 0x3567
#define MN_vpcomfalseuq 0x3571
#define MN_vpcomtrueuq 0x357e
#define MN_vpmadd52huq 0x358a
#define MN_vpmadd52luq 0x3596
#define MN_vpcomuq 0x35a2
#define MN_vpminuq 0x35aa
#define MN_vpcmpuq 0x35b2
#define MN_vpcomequq 0x35ba
#define MN_vpcomnequq 0x35c4
#define MN_vpcmpnequq 0x35cf
#define MN_vpcmpequq 0x35da
#define MN_vpcomgtuq 0x35e4
#define MN_vpcomltuq 0x35ee
#define MN_vpcmpnltuq 0x35f8
#define MN_vpcmpltuq 0x3603
#define MN_vpmaxuq 0x360d
#define MN_vpsravq 0x3615
#define MN_vpshldvq 0x361d
#define MN_vpshrdvq 0x3626
#define MN_vpsllvq 0x362f
#define MN_vprolvq 0x3637
#define MN_vpsrlvq 0x363f
#define MN_movq (MN_kmovq + 1)
#define MN_kmovq (MN_maskmovq + 3)
#define MN_maskmovq (MN_vpmaskmovq + 2)
#define MN_vpmaskmovq 0x3647
#define MN_vmovq 0x3652
#define MN_vprorvq 0x3658
#define MN_vphaddwq 0x3660
#define MN_vphadduwq 0x3669
#define MN_pmovsxwq (MN_vpmovsxwq + 1)
#define MN_vpmovsxwq 0x3673
#define MN_pmovzxwq (MN_vpmovzxwq + 1)
#define MN_vpmovzxwq 0x367d
#define MN_rex_r 0x3687
#define MN_vmclear 0x368d
#define MN_lar 0x3695
#define MN_sar 0x3699
#define MN_fsubr (MN_pfsubr + 1)
#define MN_pfsubr 0x369d
#define MN_fisubr 0x36a4
#define MN_rcr 0x36ab
#define MN_vzeroupper 0x36af
#define MN_enter (MN_sysenter + 3)
#define MN_sysenter 0x36ba
#define MN_shr 0x36c3
#define MN_clr 0x36c7
#define MN_palignr (MN_vpalignr + 1)
#define MN_vpalignr 0x36cb
#define MN_or (MN_aor + 1)
#define MN_aor 0x36d4
#define MN_por (MN_vpor + 1)
#define MN_vpor 0x36d8
#define MN_ror 0x36dd
#define MN_monitor (MN_umonitor + 1)
#define MN_umonitor 0x36e1
#define MN_frstor 0x36ea
#define MN_xrstor (MN_fxrstor + 1)
#define MN_fxrstor 0x36f1
#define MN_xor (MN_axor + 1)
#define MN_axor 0x36f9
#define MN_pxor (MN_vpxor + 1)
#define MN_vpxor 0x36fe
#define MN_verr 0x3704
#define MN_bsr 0x3709
#define MN_ldmxcsr (MN_vldmxcsr + 1)
#define MN_vldmxcsr 0x370d
#define MN_stmxcsr (MN_vstmxcsr + 1)
#define MN_vstmxcsr 0x3716
#define MN_blsr 0x371f
#define MN_rdmsr (MN_urdmsr + 1)
#define MN_urdmsr 0x3724
#define MN_wrmsr (MN_uwrmsr + 1)
#define MN_uwrmsr 0x372b
#define MN_btr 0x3732
#define MN_xcrypt_ctr 0x3736
#define MN_xcryptctr 0x3741
#define MN_ltr 0x374b
#define MN_str 0x374f
#define MN_bextr 0x3753
#define MN_fdivr 0x3759
#define MN_fidivr 0x375f
#define MN_rex_wr 0x3766
#define MN_vcvtbf82bf4s 0x376d
#define MN_vcvthf82bf4s 0x377a
#define MN_vcvtbf82bf6s 0x3787
#define MN_vcvthf82hf6s 0x3794
#define MN_vcvt2ph2bf8s 0x37a1
#define MN_vcvtbiasph2bf8s 0x37ae
#define MN_vcvtph2bf8s 0x37be
#define MN_vcvtbiasps2bf8s 0x37ca
#define MN_vcvtps2bf8s 0x37da
#define MN_vcvt2ph2hf8s 0x37e6
#define MN_vcvtbiasph2hf8s 0x37f3
#define MN_vcvtph2hf8s 0x3803
#define MN_vcvtrops2hf8s 0x380f
#define MN_vcvtbiasps2hf8s 0x381d
#define MN_vcvtps2hf8s 0x382d
#define MN_aas 0x3839
#define MN_scas 0x383d
#define MN_das 0x3842
#define MN_fabs 0x3846
#define MN_jmpabs 0x384b
#define MN_movabs 0x3852
#define MN_vcvttbf162ibs 0x3859
#define MN_vcvtbf162ibs 0x3867
#define MN_vcvttph2ibs 0x3874
#define MN_vcvtph2ibs 0x3880
#define MN_vcvttps2ibs 0x388b
#define MN_vcvtps2ibs 0x3897
#define MN_vcvttbf162iubs 0x38a2
#define MN_vcvtbf162iubs 0x38b1
#define MN_vcvttph2iubs 0x38bf
#define MN_vcvtph2iubs 0x38cc
#define MN_vcvttps2iubs 0x38d8
#define MN_vcvtps2iubs 0x38e5
#define MN_cs (MN_blcs + 2)
#define MN_blcs 0x38f1
#define MN_ds (MN_lds + 1)
#define MN_lds 0x38f6
#define MN_enqcmds 0x38fa
#define MN_lods 0x3902
#define MN_vpdpbssds 0x3907
#define MN_vp4dpwssds 0x3911
#define MN_vpdpwssds 0x391c
#define MN_vpdpbusds 0x3926
#define MN_vpdpwusds 0x3930
#define MN_vpdpbsuds 0x393a
#define MN_vpdpwsuds 0x3944
#define MN_vpdpbuuds 0x394e
#define MN_vpdpwuuds 0x3958
#define MN_es (MN_les + 1)
#define MN_les 0x3962
#define MN_xsaves 0x3966
#define MN_fs (MN_lfs + 1)
#define MN_lfs 0x396d
#define MN_gs (MN_lkgs + 2)
#define MN_lkgs 0x3971
#define MN_lgs 0x3976
#define MN_swapgs 0x397a
#define MN_fchs 0x3981
#define MN_vcvttsd2sis 0x3986
#define MN_vcvttss2sis 0x3992
#define MN_vcvttsd2usis 0x399e
#define MN_vcvttss2usis 0x39ab
#define MN_js 0x39b8
#define MN_encls 0x39bb
#define MN_emms (MN_femms + 1)
#define MN_femms 0x39c1
#define MN_ins (MN_lwpins + 3)
#define MN_lwpins 0x39c7
#define MN_jns 0x39ce
#define MN_ccmpns 0x39d2
#define MN_wrmsrns 0x39d9
#define MN_setns 0x39e1
#define MN_ctestns 0x39e7
#define MN_setzuns 0x39ef
#define MN_cmovns (MN_cfcmovns + 2)
#define MN_cfcmovns 0x39f7
#define MN_fcos 0x3a00
#define MN_fsincos 0x3a05
#define MN_stos 0x3a0d
#define MN_vfmaddsub231ps 0x3a12
#define MN_vfmsub231ps 0x3a21
#define MN_vfnmsub231ps 0x3a2d
#define MN_vfmsubadd231ps 0x3a3a
#define MN_vfmadd231ps 0x3a49
#define MN_vfnmadd231ps 0x3a55
#define MN_vfmaddsub132ps 0x3a62
#define MN_vfmsub132ps 0x3a71
#define MN_vfnmsub132ps 0x3a7d
#define MN_vfmsubadd132ps 0x3a8a
#define MN_vfmadd132ps 0x3a99
#define MN_vfnmadd132ps 0x3aa5
#define MN_tmmultf32ps (MN_ttmmultf32ps + 1)
#define MN_ttmmultf32ps 0x3ab2
#define MN_vcvtneebf162ps 0x3abf
#define MN_vbcstnebf162ps 0x3ace
#define MN_vcvtneobf162ps 0x3add
#define MN_vcvtbf82ps 0x3aec
#define MN_vcvthf82ps 0x3af7
#define MN_cvtpd2ps (MN_vcvtpd2ps + 1)
#define MN_vcvtpd2ps 0x3b02
#define MN_tcvtrowd2ps 0x3b0c
#define MN_vcvtneeph2ps 0x3b18
#define MN_vcvtneoph2ps 0x3b25
#define MN_vcvtph2ps 0x3b32
#define MN_vbcstnesh2ps 0x3b3c
#define MN_vpermi2ps 0x3b49
#define MN_cvtpi2ps 0x3b53
#define MN_vpermil2ps 0x3b5c
#define MN_vexp2ps 0x3b67
#define MN_cvtdq2ps (MN_vcvtdq2ps + 1)
#define MN_vcvtdq2ps 0x3b6f
#define MN_vcvtudq2ps 0x3b79
#define MN_vcvtqq2ps 0x3b84
#define MN_vcvtuqq2ps 0x3b8e
#define MN_vpermt2ps 0x3b99
#define MN_vfmaddsub213ps 0x3ba3
#define MN_vfmsub213ps 0x3bb2
#define MN_vfnmsub213ps 0x3bbe
#define MN_vfmsubadd213ps 0x3bcb
#define MN_vfmadd213ps 0x3bda
#define MN_vfnmadd213ps 0x3be6
#define MN_vrcp14ps 0x3bf3
#define MN_vrsqrt14ps 0x3bfc
#define MN_top2bf16ps 0x3c07
#define MN_tdpbf16ps (MN_ttdpbf16ps + 1)
#define MN_ttdpbf16ps 0x3c12
#define MN_vdpbf16ps 0x3c1d
#define MN_tcmmrlfp16ps (MN_ttcmmrlfp16ps + 1)
#define MN_ttcmmrlfp16ps 0x3c27
#define MN_tcmmimfp16ps (MN_tconjtcmmimfp16ps + 5)
#define MN_tconjtcmmimfp16ps 0x3c35
#define MN_ttcmmimfp16ps 0x3c47
#define MN_tdpfp16ps (MN_ttdpfp16ps + 1)
#define MN_ttdpfp16ps 0x3c55
#define MN_vrcp28ps 0x3c60
#define MN_vrsqrt28ps 0x3c69
#define MN_tdphbf8ps 0x3c74
#define MN_top4mxhbf8ps 0x3c7e
#define MN_tdpbf8ps 0x3c8b
#define MN_top4mxbf8ps 0x3c94
#define MN_tdpbhf8ps 0x3ca0
#define MN_top4mxbhf8ps 0x3caa
#define MN_tdphf8ps 0x3cb7
#define MN_top4mxhf8ps 0x3cc0
#define MN_movaps (MN_vmovaps + 1)
#define MN_vmovaps 0x3ccc
#define MN_subps (MN_addsubps + 3)
#define MN_addsubps (MN_vfmaddsubps + 3)
#define MN_vfmaddsubps 0x3cd4
#define MN_vaddsubps 0x3ce0
#define MN_hsubps (MN_vhsubps + 1)
#define MN_vhsubps 0x3cea
#define MN_vfmsubps 0x3cf2
#define MN_vfnmsubps 0x3cfb
#define MN_vsubps 0x3d05
#define MN_vgatherpf0dps 0x3d0c
#define MN_vscatterpf0dps 0x3d1a
#define MN_vgatherpf1dps 0x3d29
#define MN_vscatterpf1dps 0x3d37
#define MN_addps (MN_vfmsubaddps + 6)
#define MN_vfmsubaddps 0x3d46
#define MN_haddps (MN_vhaddps + 1)
#define MN_vhaddps 0x3d52
#define MN_v4fmaddps 0x3d5a
#define MN_vfmaddps 0x3d64
#define MN_v4fnmaddps 0x3d6d
#define MN_vfnmaddps 0x3d78
#define MN_vaddps 0x3d82
#define MN_andps (MN_vexpandps + 4)
#define MN_vexpandps 0x3d89
#define MN_vandps 0x3d93
#define MN_blendps (MN_vblendps + 1)
#define MN_vblendps 0x3d9a
#define MN_roundps (MN_vroundps + 1)
#define MN_vroundps 0x3da3
#define MN_vgatherdps 0x3dac
#define MN_vscatterdps 0x3db7
#define MN_cmpunordps (MN_vcmpunordps + 1)
#define MN_vcmpunordps 0x3dc3
#define MN_cmpordps (MN_vcmpordps + 1)
#define MN_vcmpordps 0x3dcf
#define MN_vreduceps 0x3dd9
#define MN_vrangeps 0x3de3
#define MN_vcmpngeps 0x3dec
#define MN_vcmpgeps 0x3df6
#define MN_vrndscaleps 0x3dff
#define MN_cmpnleps (MN_vcmpnleps + 1)
#define MN_vcmpnleps 0x3e0b
#define MN_cmpleps (MN_vcmpleps + 1)
#define MN_vcmpleps 0x3e15
#define MN_vcmpfalseps 0x3e1e
#define MN_vcmptrueps 0x3e2a
#define MN_vscalefps 0x3e35
#define MN_shufps (MN_vshufps + 1)
#define MN_vshufps 0x3e3f
#define MN_unpckhps (MN_vunpckhps + 1)
#define MN_vunpckhps 0x3e47
#define MN_movlhps (MN_vmovlhps + 1)
#define MN_vmovlhps 0x3e51
#define MN_vdpphps 0x3e5a
#define MN_movhps (MN_vmovhps + 1)
#define MN_vmovhps 0x3e62
#define MN_movmskps (MN_vmovmskps + 1)
#define MN_vmovmskps 0x3e6a
#define MN_movhlps (MN_vmovhlps + 1)
#define MN_vmovhlps 0x3e74
#define MN_vpermilps 0x3e7d
#define MN_unpcklps (MN_vunpcklps + 1)
#define MN_vunpcklps 0x3e87
#define MN_mulps (MN_vmulps + 1)
#define MN_vmulps 0x3e91
#define MN_movlps (MN_vmovlps + 1)
#define MN_vmovlps 0x3e98
#define MN_cmps (MN_ccmps + 1)
#define MN_ccmps 0x3ea0
#define MN_vblendmps 0x3ea6
#define MN_vfixupimmps 0x3eb0
#define MN_vpermps 0x3ebc
#define MN_andnps (MN_vandnps + 1)
#define MN_vandnps 0x3ec4
#define MN_minps (MN_vminps + 1)
#define MN_vminps 0x3ecc
#define MN_seamops 0x3ed3
#define MN_rcpps (MN_vrcpps + 1)
#define MN_vrcpps 0x3edb
#define MN_dpps (MN_vdpps + 1)
#define MN_vdpps 0x3ee2
#define MN_cmpps (MN_vcmpps + 1)
#define MN_vcmpps 0x3ee8
#define MN_vgetexpps 0x3eef
#define MN_vgatherpf0qps 0x3ef9
#define MN_vscatterpf0qps 0x3f07
#define MN_vgatherpf1qps 0x3f16
#define MN_vscatterpf1qps 0x3f24
#define MN_vcmpunord_qps 0x3f33
#define MN_vcmpord_qps 0x3f41
#define MN_cmpneqps (MN_vcmpneqps + 1)
#define MN_vcmpneqps 0x3f4d
#define MN_cmpeqps (MN_vcmpeqps + 1)
#define MN_vcmpeqps 0x3f57
#define MN_vcmpge_oqps 0x3f60
#define MN_vcmple_oqps 0x3f6c
#define MN_vcmpfalse_oqps 0x3f78
#define MN_vcmpneq_oqps 0x3f87
#define MN_vcmpeq_oqps 0x3f94
#define MN_vcmpgt_oqps 0x3fa0
#define MN_vcmplt_oqps 0x3fac
#define MN_vgatherqps 0x3fb8
#define MN_vscatterqps 0x3fc3
#define MN_vcmpnge_uqps 0x3fcf
#define MN_vcmpnle_uqps 0x3fdc
#define MN_vcmptrue_uqps 0x3fe9
#define MN_vcmpneq_uqps 0x3ff7
#define MN_vcmpeq_uqps 0x4004
#define MN_vcmpngt_uqps 0x4010
#define MN_vcmpnlt_uqps 0x401d
#define MN_orps (MN_vorps + 1)
#define MN_vorps 0x402a
#define MN_xorps (MN_vxorps + 1)
#define MN_vxorps 0x4030
#define MN_vcmpunord_sps 0x4037
#define MN_vcmpord_sps 0x4045
#define MN_vcmpge_osps 0x4051
#define MN_vcmple_osps 0x405d
#define MN_vcmpfalse_osps 0x4069
#define MN_vcmpneq_osps 0x4078
#define MN_vcmpeq_osps 0x4085
#define MN_vcmpgt_osps 0x4091
#define MN_vcmplt_osps 0x409d
#define MN_vfpclassps 0x40a9
#define MN_top4mxbssps 0x40b4
#define MN_vcompressps 0x40c0
#define MN_vcmpnge_usps 0x40cc
#define MN_vcmpnle_usps 0x40d9
#define MN_vcmptrue_usps 0x40e6
#define MN_vcmpneq_usps 0x40f4
#define MN_vcmpeq_usps 0x4101
#define MN_vcmpngt_usps 0x410d
#define MN_vcmpnlt_usps 0x411a
#define MN_extractps (MN_vextractps + 1)
#define MN_vextractps 0x4127
#define MN_vcmpngtps 0x4132
#define MN_vcmpgtps 0x413c
#define MN_cmpnltps (MN_vcmpnltps + 1)
#define MN_vcmpnltps 0x4145
#define MN_cmpltps (MN_vcmpltps + 1)
#define MN_vcmpltps 0x414f
#define MN_vgetmantps 0x4158
#define MN_movntps (MN_vmovntps + 1)
#define MN_vmovntps 0x4163
#define MN_insertps (MN_vinsertps + 1)
#define MN_vinsertps 0x416c
#define MN_sqrtps (MN_rsqrtps + 1)
#define MN_rsqrtps (MN_vrsqrtps + 1)
#define MN_vrsqrtps 0x4176
#define MN_vsqrtps 0x417f
#define MN_vtestps 0x4187
#define MN_movups (MN_vmovups + 1)
#define MN_vmovups 0x418f
#define MN_blendvps (MN_vblendvps + 1)
#define MN_vblendvps 0x4197
#define MN_divps (MN_vdivps + 1)
#define MN_vdivps 0x41a1
#define MN_vmaskmovps 0x41a8
#define MN_maxps (MN_vminmaxps + 4)
#define MN_vminmaxps 0x41b3
#define MN_vmaxps 0x41bd
#define MN_vfrczps 0x41c4
#define MN_vcvttpd2dqs 0x41cc
#define MN_vcvttps2dqs 0x41d8
#define MN_vcvttpd2udqs 0x41e4
#define MN_vcvttps2udqs 0x41f1
#define MN_vcvttpd2qqs 0x41fe
#define MN_vcvttps2qqs 0x420a
#define MN_vcvttpd2uqqs 0x4216
#define MN_vcvttps2uqqs 0x4223
#define MN_t2rpntlvwz0rs 0x4230
#define MN_t2rpntlvwz1rs 0x423e
#define MN_tileloaddrs 0x424c
#define MN_xrstors 0x4258
#define MN_movrs 0x4260
#define MN_ss (MN_vfmsub231ss + 9)
#define MN_vfmsub231ss 0x4266
#define MN_vfnmsub231ss 0x4272
#define MN_vfmadd231ss 0x427f
#define MN_vfnmadd231ss 0x428b
#define MN_vfmsub132ss 0x4298
#define MN_vfnmsub132ss 0x42a4
#define MN_vfmadd132ss 0x42b1
#define MN_vfnmadd132ss 0x42bd
#define MN_cvtsd2ss (MN_vcvtsd2ss + 1)
#define MN_vcvtsd2ss 0x42ca
#define MN_vcvtsh2ss 0x42d4
#define MN_cvtsi2ss (MN_vcvtsi2ss + 1)
#define MN_vcvtsi2ss 0x42de
#define MN_vcvtusi2ss 0x42e8
#define MN_vfmsub213ss 0x42f3
#define MN_vfnmsub213ss 0x42ff
#define MN_vfmadd213ss 0x430c
#define MN_vfnmadd213ss 0x4318
#define MN_vrcp14ss 0x4325
#define MN_vrsqrt14ss 0x432e
#define MN_vrcp28ss 0x4339
#define MN_vrsqrt28ss 0x4342
#define MN_subss (MN_vfmsubss + 3)
#define MN_vfmsubss 0x434d
#define MN_vfnmsubss 0x4356
#define MN_vsubss 0x4360
#define MN_addss (MN_v4fmaddss + 4)
#define MN_v4fmaddss 0x4367
#define MN_vfmaddss 0x4371
#define MN_v4fnmaddss 0x437a
#define MN_vfnmaddss 0x4385
#define MN_vaddss 0x438f
#define MN_roundss (MN_vroundss + 1)
#define MN_vroundss 0x4396
#define MN_cmpunordss (MN_vcmpunordss + 1)
#define MN_vcmpunordss 0x439f
#define MN_cmpordss (MN_vcmpordss + 1)
#define MN_vcmpordss 0x43ab
#define MN_vreducess 0x43b5
#define MN_vrangess 0x43bf
#define MN_vcmpngess 0x43c8
#define MN_vcmpgess 0x43d2
#define MN_vrndscaless 0x43db
#define MN_cmpnless (MN_vcmpnless + 1)
#define MN_vcmpnless 0x43e7
#define MN_cmpless (MN_vcmpless + 1)
#define MN_vcmpless 0x43f1
#define MN_vcmpfalsess 0x43fa
#define MN_vcmptruess 0x4406
#define MN_vscalefss 0x4411
#define MN_comiss (MN_ucomiss + 1)
#define MN_ucomiss (MN_vucomiss + 1)
#define MN_vucomiss 0x441b
#define MN_vcomiss 0x4424
#define MN_lss (MN_mulss + 2)
#define MN_mulss (MN_vmulss + 1)
#define MN_vmulss 0x442c
#define MN_vfixupimmss 0x4433
#define MN_minss (MN_vminss + 1)
#define MN_vminss 0x443f
#define MN_rcpss (MN_vrcpss + 1)
#define MN_vrcpss 0x4446
#define MN_cmpss (MN_vcmpss + 1)
#define MN_vcmpss 0x444d
#define MN_vgetexpss 0x4454
#define MN_vcmpunord_qss 0x445e
#define MN_vcmpord_qss 0x446c
#define MN_cmpneqss (MN_vcmpneqss + 1)
#define MN_vcmpneqss 0x4478
#define MN_cmpeqss (MN_vcmpeqss + 1)
#define MN_vcmpeqss 0x4482
#define MN_vcmpge_oqss 0x448b
#define MN_vcmple_oqss 0x4497
#define MN_vcmpfalse_oqss 0x44a3
#define MN_vcmpneq_oqss 0x44b2
#define MN_vcmpeq_oqss 0x44bf
#define MN_vcmpgt_oqss 0x44cb
#define MN_vcmplt_oqss 0x44d7
#define MN_vcmpnge_uqss 0x44e3
#define MN_vcmpnle_uqss 0x44f0
#define MN_vcmptrue_uqss 0x44fd
#define MN_vcmpneq_uqss 0x450b
#define MN_vcmpeq_uqss 0x4518
#define MN_vcmpngt_uqss 0x4524
#define MN_vcmpnlt_uqss 0x4531
#define MN_vcmpunord_sss 0x453e
#define MN_vcmpord_sss 0x454c
#define MN_vcmpge_osss 0x4558
#define MN_vcmple_osss 0x4564
#define MN_vcmpfalse_osss 0x4570
#define MN_vcmpneq_osss 0x457f
#define MN_vcmpeq_osss 0x458c
#define MN_vcmpgt_osss 0x4598
#define MN_vcmplt_osss 0x45a4
#define MN_vfpclassss 0x45b0
#define MN_vcmpnge_usss 0x45bb
#define MN_vcmpnle_usss 0x45c8
#define MN_vcmptrue_usss 0x45d5
#define MN_vcmpneq_usss 0x45e3
#define MN_vcmpeq_usss 0x45f0
#define MN_vcmpngt_usss 0x45fc
#define MN_vcmpnlt_usss 0x4609
#define MN_vcmpngtss 0x4616
#define MN_vcmpgtss 0x4620
#define MN_cmpnltss (MN_vcmpnltss + 1)
#define MN_vcmpnltss 0x4629
#define MN_cmpltss (MN_vcmpltss + 1)
#define MN_vcmpltss 0x4633
#define MN_vgetmantss 0x463c
#define MN_movntss 0x4647
#define MN_sqrtss (MN_rsqrtss + 1)
#define MN_rsqrtss (MN_vrsqrtss + 1)
#define MN_vrsqrtss 0x464f
#define MN_vsqrtss 0x4658
#define MN_vbroadcastss 0x4660
#define MN_divss (MN_vdivss + 1)
#define MN_vdivss 0x466d
#define MN_movss (MN_vmovss + 1)
#define MN_vmovss 0x4674
#define MN_maxss (MN_vminmaxss + 4)
#define MN_vminmaxss 0x467b
#define MN_vmaxss 0x4685
#define MN_vucomxss 0x468c
#define MN_vcomxss 0x4695
#define MN_vfrczss 0x469d
#define MN_bts 0x46a5
#define MN_erets 0x46a9
#define MN_sets 0x46af
#define MN_clts 0x46b4
#define MN_ctests 0x46b9
#define MN_outs 0x46c0
#define MN_setzus 0x46c5
#define MN_movs (MN_cmovs + 1)
#define MN_cmovs (MN_cfcmovs + 2)
#define MN_cfcmovs 0x46cc
#define MN_fldl2t 0x46d4
#define MN_xlat 0x46db
#define MN_bt 0x46e0
#define MN_fxtract 0x46e3
#define MN_lgdt 0x46eb
#define MN_sgdt 0x46f0
#define MN_lidt 0x46f5
#define MN_sidt 0x46fa
#define MN_fldt 0x46ff
#define MN_lldt 0x4704
#define MN_sldt 0x4709
#define MN_ret (MN_iret + 1)
#define MN_iret (MN_uiret + 1)
#define MN_uiret 0x470e
#define MN_lret 0x4714
#define MN_seamret 0x4719
#define MN_sysret 0x4721
#define MN_hreset 0x4728
#define MN_pfcmpgt 0x472f
#define MN_ht 0x4737
#define MN_wait (MN_fwait + 1)
#define MN_fwait 0x473a
#define MN_mwait (MN_umwait + 1)
#define MN_umwait 0x4740
#define MN_mcommit 0x4747
#define MN_finit 0x474f
#define MN_skinit 0x4755
#define MN_fninit 0x475c
#define MN_bsrinit 0x4763
#define MN_vmgexit 0x476b
#define MN_sysexit 0x4773
#define MN_hlt 0x477b
#define MN_popcnt 0x477f
#define MN_lzcnt 0x4786
#define MN_tzcnt 0x478c
#define MN_hnt 0x4792
#define MN_int (MN_frndint + 4)
#define MN_frndint 0x4796
#define MN_not 0x479e
#define MN_invept 0x47a2
#define MN_ccmpt 0x47a9
#define MN_xsaveopt 0x47af
#define MN_clflushopt 0x47b8
#define MN_rmpopt 0x47c3
#define MN_fstpt 0x47ca
#define MN_xabort 0x47d0
#define MN_fsqrt 0x47d7
#define MN_pfrsqrt 0x47dd
#define MN_aesdeclast (MN_vaesdeclast + 1)
#define MN_vaesdeclast 0x47e5
#define MN_aesenclast (MN_vaesenclast + 1)
#define MN_vaesenclast 0x47f1
#define MN_test (MN_ptest + 1)
#define MN_ptest (MN_vptest + 1)
#define MN_vptest 0x47fd
#define MN_xtest 0x4804
#define MN_fst 0x480a
#define MN_fist 0x480e
#define MN_rdmsrlist 0x4813
#define MN_wrmsrlist 0x481d
#define MN_aeskeygenassist (MN_vaeskeygenassist + 1)
#define MN_vaeskeygenassist 0x4827
#define MN_vmptrst 0x4838
#define MN_ftst 0x4840
#define MN_rmpadjust 0x4845
#define MN_ctestt 0x484f
#define MN_out 0x4856
#define MN_pext 0x485a
#define MN_bndcu 0x485f
#define MN_enclu 0x4865
#define MN_fcmovnu 0x486b
#define MN_lddqu (MN_vlddqu + 1)
#define MN_vlddqu 0x4873
#define MN_movdqu (MN_maskmovdqu + 4)
#define MN_maskmovdqu (MN_vmaskmovdqu + 1)
#define MN_vmaskmovdqu 0x487a
#define MN_vmovdqu 0x4886
#define MN_rdpkru 0x488e
#define MN_wrpkru 0x4895
#define MN_rdpru 0x489c
#define MN_eretu 0x48a2
#define MN_fcmovu 0x48a8
#define MN_imulzu 0x48af
#define MN_xgetbv 0x48b6
#define MN_xsetbv 0x48bd
#define MN_div (MN_fdiv + 1)
#define MN_fdiv 0x48c4
#define MN_idiv (MN_fidiv + 1)
#define MN_fidiv 0x48c9
#define MN_enclv 0x48cf
#define MN_fldenv 0x48d5
#define MN_fstenv 0x48dc
#define MN_fnstenv 0x48e3
#define MN_mov (MN_vpcmov + 3)
#define MN_vpcmov 0x48eb
#define MN_bndmov 0x48f2
#define MN_smov 0x48f9
#define MN_rex_w 0x48fe
#define MN_vcvttph2w 0x4904
#define MN_vcvtph2w 0x490e
#define MN_vpermi2w 0x4917
#define MN_vpmovm2w 0x4920
#define MN_vpermt2w 0x4929
#define MN_vpshaw 0x4932
#define MN_psraw (MN_vpsraw + 1)
#define MN_vpsraw 0x4939
#define MN_vphsubbw 0x4940
#define MN_cbw 0x4949
#define MN_psadbw (MN_vdbpsadbw + 3)
#define MN_vdbpsadbw 0x494d
#define MN_mpsadbw (MN_vmpsadbw + 1)
#define MN_vmpsadbw 0x4957
#define MN_vpsadbw 0x4960
#define MN_vphaddbw 0x4968
#define MN_punpckhbw (MN_vpunpckhbw + 1)
#define MN_vpunpckhbw 0x4971
#define MN_kunpckbw 0x497c
#define MN_punpcklbw (MN_vpunpcklbw + 1)
#define MN_vpunpcklbw 0x4985
#define MN_vphaddubw 0x4990
#define MN_phsubw (MN_vphsubw + 1)
#define MN_vphsubw 0x499a
#define MN_psubw (MN_vpsubw + 1)
#define MN_vpsubw 0x49a2
#define MN_pmovsxbw (MN_vpmovsxbw + 1)
#define MN_vpmovsxbw 0x49a9
#define MN_pmovzxbw (MN_vpmovzxbw + 1)
#define MN_vpmovzxbw 0x49b3
#define MN_fldcw 0x49bd
#define MN_fstcw 0x49c3
#define MN_fnstcw 0x49c9
#define MN_phaddw (MN_vphaddw + 1)
#define MN_vphaddw 0x49d0
#define MN_kaddw 0x49d8
#define MN_paddw (MN_vpaddw + 1)
#define MN_vpaddw 0x49de
#define MN_vpshldw 0x49e5
#define MN_kandw 0x49ed
#define MN_vpexpandw 0x49f3
#define MN_pblendw (MN_vpblendw + 1)
#define MN_vpblendw 0x49fd
#define MN_vpshrdw 0x4a06
#define MN_packssdw (MN_vpackssdw + 1)
#define MN_vpackssdw 0x4a0e
#define MN_packusdw (MN_vpackusdw + 1)
#define MN_vpackusdw 0x4a18
#define MN_vpmovusdw 0x4a22
#define MN_vpmovsdw 0x4a2c
#define MN_vpmovdw 0x4a35
#define MN_vpcomgew 0x4a3d
#define MN_vpcomlew 0x4a46
#define MN_vpcmpnlew 0x4a4f
#define MN_vpcmplew 0x4a59
#define MN_vpcomfalsew 0x4a62
#define MN_vpcomtruew 0x4a6e
#define MN_pi2fw 0x4a79
#define MN_pshufw 0x4a7f
#define MN_pavgw (MN_vpavgw + 1)
#define MN_vpavgw 0x4a86
#define MN_prefetchw 0x4a8d
#define MN_pshufhw (MN_vpshufhw + 1)
#define MN_vpshufhw 0x4a97
#define MN_pmulhw (MN_vpmulhw + 1)
#define MN_vpmulhw 0x4aa0
#define MN_pf2iw 0x4aa8
#define MN_pshuflw (MN_vpshuflw + 1)
#define MN_vpshuflw 0x4aae
#define MN_vpshlw 0x4ab7
#define MN_psllw (MN_vpsllw + 1)
#define MN_vpsllw 0x4abe
#define MN_pmullw (MN_vpmullw + 1)
#define MN_vpmullw 0x4ac5
#define MN_psrlw (MN_vpsrlw + 1)
#define MN_vpsrlw 0x4acd
#define MN_kshiftlw 0x4ad4
#define MN_vpblendmw 0x4add
#define MN_vptestnmw 0x4ae7
#define MN_vpcomw 0x4af1
#define MN_vpermw 0x4af8
#define MN_vptestmw 0x4aff
#define MN_kandnw 0x4b08
#define MN_psignw (MN_vpsignw + 1)
#define MN_vpsignw 0x4b0f
#define MN_tilemovrow 0x4b17
#define MN_vpcmpw 0x4b22
#define MN_vpcomeqw 0x4b29
#define MN_vpcomneqw 0x4b32
#define MN_vpcmpneqw 0x4b3c
#define MN_pcmpeqw (MN_vpcmpeqw + 1)
#define MN_vpcmpeqw 0x4b46
#define MN_vpmovusqw 0x4b4f
#define MN_vpmovsqw 0x4b59
#define MN_vpmovqw 0x4b62
#define MN_verw 0x4b6a
#define MN_pmulhrw 0x4b6f
#define MN_korw 0x4b77
#define MN_kxnorw 0x4b7c
#define MN_kxorw 0x4b83
#define MN_pinsrw (MN_vpinsrw + 1)
#define MN_vpinsrw 0x4b89
#define MN_kshiftrw 0x4b91
#define MN_pextrw (MN_vpextrw + 1)
#define MN_vpextrw 0x4b9a
#define MN_pabsw (MN_vpabsw + 1)
#define MN_vpabsw 0x4ba2
#define MN_pmaddubsw (MN_vpmaddubsw + 1)
#define MN_vpmaddubsw 0x4ba9
#define MN_phsubsw (MN_vphsubsw + 1)
#define MN_vphsubsw 0x4bb4
#define MN_psubsw (MN_vpsubsw + 1)
#define MN_vpsubsw 0x4bbd
#define MN_phaddsw (MN_vphaddsw + 1)
#define MN_vphaddsw 0x4bc5
#define MN_paddsw (MN_vpaddsw + 1)
#define MN_vpaddsw 0x4bce
#define MN_lmsw 0x4bd6
#define MN_smsw 0x4bdb
#define MN_pminsw (MN_vpminsw + 1)
#define MN_vpminsw 0x4be0
#define MN_pmulhrsw (MN_vpmulhrsw + 1)
#define MN_vpmulhrsw 0x4be8
#define MN_vmovrsw 0x4bf2
#define MN_vpcompressw 0x4bfa
#define MN_fstsw 0x4c06
#define MN_fnstsw 0x4c0c
#define MN_psubusw (MN_vpsubusw + 1)
#define MN_vpsubusw 0x4c13
#define MN_paddusw (MN_vpaddusw + 1)
#define MN_vpaddusw 0x4c1c
#define MN_movsw 0x4c25
#define MN_pmaxsw (MN_vpmaxsw + 1)
#define MN_vpmaxsw 0x4c2b
#define MN_cbtw 0x4c33
#define MN_vpcomgtw 0x4c38
#define MN_pcmpgtw (MN_vpcmpgtw + 1)
#define MN_vpcmpgtw 0x4c41
#define MN_vpcomltw 0x4c4a
#define MN_vpcmpnltw 0x4c53
#define MN_vpcmpltw 0x4c5d
#define MN_vpopcntw 0x4c66
#define MN_knotw 0x4c6f
#define MN_vprotw 0x4c75
#define MN_vpbroadcastw 0x4c7c
#define MN_ktestw 0x4c89
#define MN_kortestw 0x4c90
#define MN_vcvttph2uw 0x4c99
#define MN_vcvtph2uw 0x4ca4
#define MN_vpcomgeuw 0x4cae
#define MN_vpcomleuw 0x4cb8
#define MN_vpcmpnleuw 0x4cc2
#define MN_vpcmpleuw 0x4ccd
#define MN_vpcomfalseuw 0x4cd7
#define MN_vpcomtrueuw 0x4ce4
#define MN_pmulhuw (MN_vpmulhuw + 1)
#define MN_vpmulhuw 0x4cf0
#define MN_vpcomuw 0x4cf9
#define MN_pminuw (MN_vpminuw + 1)
#define MN_vpminuw 0x4d01
#define MN_vpcmpuw 0x4d09
#define MN_vpcomequw 0x4d11
#define MN_vpcomnequw 0x4d1b
#define MN_vpcmpnequw 0x4d26
#define MN_vpcmpequw 0x4d31
#define MN_phminposuw (MN_vphminposuw + 1)
#define MN_vphminposuw 0x4d3b
#define MN_vpcomgtuw 0x4d47
#define MN_vpcomltuw 0x4d51
#define MN_vpcmpnltuw 0x4d5b
#define MN_vpcmpltuw 0x4d66
#define MN_pmaxuw (MN_vpmaxuw + 1)
#define MN_vpmaxuw 0x4d70
#define MN_vpsravw 0x4d78
#define MN_vpshldvw 0x4d80
#define MN_vpshrdvw 0x4d89
#define MN_vpsllvw 0x4d92
#define MN_vpsrlvw 0x4d9a
#define MN_kmovw 0x4da2
#define MN_vmovw 0x4da8
#define MN_vpmacsww 0x4dae
#define MN_vpmacssww 0x4db7
#define MN_movzw 0x4dc1
#define MN_rex_x 0x4dc7
#define MN_fyl2x 0x4dcd
#define MN_rex64x 0x4dd3
#define MN_vcvtneps2bf16x 0x4dda
#define MN_vfpclassbf16x 0x4de9
#define MN_vcvtph2bf8x 0x4df7
#define MN_vcvtps2bf8x 0x4e03
#define MN_vcvtph2hf8x 0x4e0f
#define MN_vcvtrops2hf8x 0x4e1b
#define MN_vcvtps2hf8x 0x4e29
#define MN_pfmax 0x4e35
#define MN_adcx 0x4e3b
#define MN_bndldx 0x4e40
#define MN_vfpclasspdx 0x4e47
#define MN_fclex 0x4e53
#define MN_fnclex 0x4e59
#define MN_rex 0x4e60
#define MN_vcvtpd2phx 0x4e64
#define MN_vcvtdq2phx 0x4e6f
#define MN_vcvtudq2phx 0x4e7a
#define MN_vcvtqq2phx 0x4e86
#define MN_vcvtuqq2phx 0x4e91
#define MN_vcvt2ps2phx 0x4e9d
#define MN_vcvtps2phx 0x4ea9
#define MN_vfpclassphx 0x4eb4
#define MN_shlx 0x4ec0
#define MN_mulx 0x4ec5
#define MN_adox 0x4eca
#define MN_vcvttpd2dqx 0x4ecf
#define MN_vcvtpd2dqx 0x4edb
#define MN_vcvttpd2udqx 0x4ee6
#define MN_vcvtpd2udqx 0x4ef3
#define MN_rex_rx 0x4eff
#define MN_sarx 0x4f06
#define MN_shrx 0x4f0b
#define MN_rorx 0x4f10
#define MN_monitorx 0x4f15
#define MN_rex_wrx 0x4f1e
#define MN_vcvtph2bf8sx 0x4f26
#define MN_vcvtps2bf8sx 0x4f33
#define MN_vcvtph2hf8sx 0x4f40
#define MN_vcvtrops2hf8sx 0x4f4d
#define MN_vcvtps2hf8sx 0x4f5c
#define MN_vcvtpd2psx 0x4f69
#define MN_vcvtph2psx 0x4f74
#define MN_vcvtqq2psx 0x4f7f
#define MN_vcvtuqq2psx 0x4f8a
#define MN_vfpclasspsx 0x4f96
#define MN_vcvttpd2dqsx 0x4fa2
#define MN_vcvttpd2udqsx 0x4faf
#define MN_movsx 0x4fbd
#define MN_mwaitx 0x4fc3
#define MN_bndstx 0x4fca
#define MN_rex_wx 0x4fd1
#define MN_rexx 0x4fd8
#define MN_vcvtps2phxx 0x4fdd
#define MN_movzx 0x4fe9
#define MN_rex64y 0x4fef
#define MN_vcvtneps2bf16y 0x4ff6
#define MN_vfpclassbf16y 0x5005
#define MN_vcvtph2bf8y 0x5013
#define MN_vcvtps2bf8y 0x501f
#define MN_vcvtph2hf8y 0x502b
#define MN_vcvtrops2hf8y 0x5037
#define MN_vcvtps2hf8y 0x5045
#define MN_vfpclasspdy 0x5051
#define MN_loadiwkey 0x505d
#define MN_vcvtpd2phy 0x5067
#define MN_vcvtdq2phy 0x5072
#define MN_vcvtudq2phy 0x507d
#define MN_vcvtqq2phy 0x5089
#define MN_vcvtuqq2phy 0x5094
#define MN_vfpclassphy 0x50a0
#define MN_vcvttpd2dqy 0x50ac
#define MN_vcvtpd2dqy 0x50b8
#define MN_vcvttpd2udqy 0x50c3
#define MN_vcvtpd2udqy 0x50d0
#define MN_rmpquery 0x50dc
#define MN_vcvtph2bf8sy 0x50e5
#define MN_vcvtps2bf8sy 0x50f2
#define MN_vcvtph2hf8sy 0x50ff
#define MN_vcvtrops2hf8sy 0x510c
#define MN_vcvtps2hf8sy 0x511b
#define MN_clrssbsy 0x5128
#define MN_setssbsy 0x5131
#define MN_vcvtpd2psy 0x513a
#define MN_vcvtqq2psy 0x5145
#define MN_vcvtuqq2psy 0x5150
#define MN_vfpclasspsy 0x515c
#define MN_vcvttpd2dqsy 0x5168
#define MN_vcvttpd2udqsy 0x5175
#define MN_rex64xy 0x5183
#define MN_rexy 0x518b
#define MN_vcvtps2phxy 0x5190
#define MN_rexxy 0x519c
#define MN_rex64z 0x51a2
#define MN_vfpclassbf16z 0x51a9
#define MN_vcvtps2bf8z 0x51b7
#define MN_vcvtrops2hf8z 0x51c3
#define MN_vcvtps2hf8z 0x51d1
#define MN_fldz 0x51dd
#define MN_vfpclasspdz 0x51e2
#define MN_vcvtpd2phz 0x51ee
#define MN_vcvtqq2phz 0x51f9
#define MN_vcvtuqq2phz 0x5204
#define MN_vfpclassphz 0x5210
#define MN_jz 0x521c
#define MN_jnz 0x521f
#define MN_repnz 0x5223
#define MN_ccmpnz 0x5229
#define MN_loopnz 0x5230
#define MN_setnz 0x5237
#define MN_ctestnz 0x523d
#define MN_setzunz 0x5245
#define MN_cmovnz (MN_cfcmovnz + 2)
#define MN_cfcmovnz 0x524d
#define MN_repz 0x5256
#define MN_ccmpz 0x525b
#define MN_loopz 0x5261
#define MN_vcvtps2bf8sz 0x5267
#define MN_vcvtrops2hf8sz 0x5274
#define MN_vcvtps2hf8sz 0x5283
#define MN_vfpclasspsz 0x5290
#define MN_setz 0x529c
#define MN_ctestz 0x52a1
#define MN_setzuz 0x52a8
#define MN_cmovz (MN_cfcmovz + 2)
#define MN_cfcmovz 0x52af
#define MN_rex64xz 0x52b7
#define MN_jecxz 0x52bf
#define MN_jcxz 0x52c5
#define MN_jrcxz 0x52ca
#define MN_rexz 0x52d0
#define MN_rexxz 0x52d5
#define MN_rex64yz 0x52db
#define MN_rex64xyz 0x52e3
#define MN_rexyz 0x52ec
#define MN_rexxyz 0x52f2
#define MN__disp32_ 0x52f9
#define MN__rex2_ 0x5302
#define MN__vex2_ 0x5309
#define MN__vex3_ 0x5310
#define MN__disp16_ 0x5317
#define MN__disp8_ 0x5320
#define MN__load_ 0x5328
#define MN__store_ 0x532f
#define MN__nooptimize_ 0x5337
#define MN__nf_ 0x5344
#define MN__noimm8s_ 0x5349
#define MN__rex_ 0x5353
#define MN__evex_ 0x5359
#define MN__vex_ 0x5360
#define MN__insn 0x5366

#define OPREF_4_0 10
#define OPREF_4_4 14
#define OPREF_4_8 18
#define OPREF_4_12 1
#define OPREF_4_16 5
#define OPREF_4_20 22
#define OPREF_4_24 26
#define OPREF_4_28 30
#define OPREF_4_32 34
#define OPREF_4_36 38
#define OPREF_4_40 42
#define OPREF_4_44 46
#define OPREF_4_48 50
#define OPREF_4_52 54
#define OPREF_4_56 58
#define OPREF_4_60 62
#define OPREF_4_64 66
#define OPREF_4_68 70
#define OPREF_4_72 74
#define OPREF_4_76 78
#define OPREF_4_80 82
#define OPREF_4_84 86
#define OPREF_4_88 90
#define OPREF_4_92 94
#define OPREF_4_96 6
#define OPREF_4_100 98
#define OPREF_4_104 102
#define OPREF_4_108 106
#define OPREF_4_112 110
#define OPREF_4_116 114
#define OPREF_4_120 118
#define OPREF_4_124 122
#define OPREF_4_128 126
#define OPREF_4_132 130
#define OPREF_4_136 134
#define OPREF_4_140 138
#define OPREF_4_144 142
#define OPREF_4_148 146
#define OPREF_4_152 150
#define OPREF_4_156 154
#define OPREF_4_160 158
#define OPREF_4_164 162
#define OPREF_4_168 166
#define OPREF_3_0 170
#define OPREF_3_3 173
#define OPREF_3_6 176
#define OPREF_3_9 179
#define OPREF_3_12 182
#define OPREF_3_15 185
#define OPREF_3_18 188
#define OPREF_3_21 191
#define OPREF_3_24 194
#define OPREF_3_27 197
#define OPREF_3_30 200
#define OPREF_3_33 203
#define OPREF_3_36 206
#define OPREF_3_39 209
#define OPREF_3_42 10
#define OPREF_3_45 212
#define OPREF_3_48 14
#define OPREF_3_51 106
#define OPREF_3_54 30
#define OPREF_3_57 215
#define OPREF_3_60 218
#define OPREF_3_63 221
#define OPREF_3_66 62
#define OPREF_3_69 78
#define OPREF_3_72 224
#define OPREF_3_75 227
#define OPREF_3_78 230
#define OPREF_3_81 46
#define OPREF_3_84 38
#define OPREF_3_87 233
#define OPREF_3_90 236
#define OPREF_3_93 239
#define OPREF_3_96 242
#define OPREF_3_99 245
#define OPREF_3_102 248
#define OPREF_3_105 251
#define OPREF_3_108 254
#define OPREF_3_111 66
#define OPREF_3_114 70
#define OPREF_3_117 74
#define OPREF_3_120 257
#define OPREF_3_123 2
#define OPREF_3_126 83
#define OPREF_3_129 87
#define OPREF_3_132 31
#define OPREF_3_135 39
#define OPREF_3_138 23
#define OPREF_3_141 27
#define OPREF_3_144 35
#define OPREF_3_147 43
#define OPREF_3_150 260
#define OPREF_3_153 71
#define OPREF_3_156 263
#define OPREF_3_159 266
#define OPREF_3_162 269
#define OPREF_3_165 272
#define OPREF_3_168 99
#define OPREF_3_171 275
#define OPREF_3_174 55
#define OPREF_3_177 151
#define OPREF_3_180 82
#define OPREF_3_183 18
#define OPREF_3_186 86
#define OPREF_3_189 90
#define OPREF_3_192 278
#define OPREF_3_195 268
#define OPREF_3_198 281
#define OPREF_3_201 22
#define OPREF_3_204 26
#define OPREF_3_207 54
#define OPREF_3_210 5
#define OPREF_3_213 143
#define OPREF_3_216 146
#define OPREF_3_219 147
#define OPREF_3_222 284
#define OPREF_3_225 287
#define OPREF_3_228 290
#define OPREF_3_231 293
#define OPREF_3_234 296
#define OPREF_3_237 47
#define OPREF_3_240 299
#define OPREF_3_243 302
#define OPREF_3_246 167
#define OPREF_3_249 131
#define OPREF_3_252 305
#define OPREF_3_255 308
#define OPREF_3_258 311
#define OPREF_3_261 110
#define OPREF_3_264 314
#define OPREF_3_267 317
#define OPREF_3_270 114
#define OPREF_3_273 320
#define OPREF_3_276 323
#define OPREF_3_279 326
#define OPREF_3_282 329
#define OPREF_3_285 332
#define OPREF_3_288 158
#define OPREF_3_291 335
#define OPREF_3_294 338
#define OPREF_3_297 341
#define OPREF_3_300 344
#define OPREF_3_303 347
#define OPREF_3_306 350
#define OPREF_3_309 353
#define OPREF_3_312 356
#define OPREF_3_315 359
#define OPREF_3_318 362
#define OPREF_3_321 365
#define OPREF_3_324 368
#define OPREF_3_327 371
#define OPREF_3_330 374
#define OPREF_3_333 377
#define OPREF_3_336 380
#define OPREF_3_339 383
#define OPREF_3_342 386
#define OPREF_3_345 389
#define OPREF_3_348 392
#define OPREF_3_351 395
#define OPREF_3_354 398
#define OPREF_3_357 155
#define OPREF_3_360 159
#define OPREF_3_363 163
#define OPREF_3_366 401
#define OPREF_3_369 404
#define OPREF_3_372 407
#define OPREF_3_375 410
#define OPREF_3_378 413
#define OPREF_3_381 416
#define OPREF_3_384 419
#define OPREF_3_387 422
#define OPREF_3_390 425
#define OPREF_3_393 428
#define OPREF_3_396 431
#define OPREF_3_399 434
#define OPREF_2_0 437
#define OPREF_2_2 439
#define OPREF_2_4 441
#define OPREF_2_6 443
#define OPREF_2_8 445
#define OPREF_2_10 447
#define OPREF_2_12 449
#define OPREF_2_14 451
#define OPREF_2_16 450
#define OPREF_2_18 453
#define OPREF_2_20 455
#define OPREF_2_22 457
#define OPREF_2_24 459
#define OPREF_2_26 461
#define OPREF_2_28 463
#define OPREF_2_30 12
#define OPREF_2_32 465
#define OPREF_2_34 467
#define OPREF_2_36 469
#define OPREF_2_38 471
#define OPREF_2_40 473
#define OPREF_2_42 475
#define OPREF_2_44 192
#define OPREF_2_46 477
#define OPREF_2_48 479
#define OPREF_2_50 481
#define OPREF_2_52 480
#define OPREF_2_54 483
#define OPREF_2_56 485
#define OPREF_2_58 487
#define OPREF_2_60 170
#define OPREF_2_62 182
#define OPREF_2_64 173
#define OPREF_2_66 489
#define OPREF_2_68 176
#define OPREF_2_70 171
#define OPREF_2_72 183
#define OPREF_2_74 491
#define OPREF_2_76 493
#define OPREF_2_78 495
#define OPREF_2_80 497
#define OPREF_2_82 499
#define OPREF_2_84 501
#define OPREF_2_86 503
#define OPREF_2_88 197
#define OPREF_2_90 505
#define OPREF_2_92 200
#define OPREF_2_94 507
#define OPREF_2_96 203
#define OPREF_2_98 509
#define OPREF_2_100 206
#define OPREF_2_102 210
#define OPREF_2_104 511
#define OPREF_2_106 513
#define OPREF_2_108 515
#define OPREF_2_110 517
#define OPREF_2_112 519
#define OPREF_2_114 521
#define OPREF_2_116 523
#define OPREF_2_118 522
#define OPREF_2_120 525
#define OPREF_2_122 527
#define OPREF_2_124 529
#define OPREF_2_126 531
#define OPREF_2_128 180
#define OPREF_2_130 533
#define OPREF_2_132 535
#define OPREF_2_134 537
#define OPREF_2_136 539
#define OPREF_2_138 541
#define OPREF_2_140 71
#define OPREF_2_142 543
#define OPREF_2_144 545
#define OPREF_2_146 547
#define OPREF_2_148 39
#define OPREF_2_150 101
#define OPREF_2_152 75
#define OPREF_2_154 231
#define OPREF_2_156 549
#define OPREF_2_158 47
#define OPREF_2_160 115
#define OPREF_2_162 218
#define OPREF_2_164 551
#define OPREF_2_166 31
#define OPREF_2_168 553
#define OPREF_2_170 555
#define OPREF_2_172 557
#define OPREF_2_174 559
#define OPREF_2_176 561
#define OPREF_2_178 32
#define OPREF_2_180 275
#define OPREF_2_182 293
#define OPREF_2_184 216
#define OPREF_2_186 563
#define OPREF_2_188 565
#define OPREF_2_190 288
#define OPREF_2_192 219
#define OPREF_2_194 562
#define OPREF_2_196 567
#define OPREF_2_198 569
#define OPREF_2_200 571
#define OPREF_2_202 371
#define OPREF_2_204 374
#define OPREF_2_206 573
#define OPREF_2_208 575
#define OPREF_2_210 577
#define OPREF_2_212 579
#define OPREF_2_214 581
#define OPREF_2_216 583
#define OPREF_2_218 131
#define OPREF_2_220 585
#define OPREF_2_222 587
#define OPREF_2_224 589
#define OPREF_2_226 591
#define OPREF_2_228 297
#define OPREF_2_230 289
#define OPREF_2_232 593
#define OPREF_2_234 595
#define OPREF_2_236 597
#define OPREF_2_238 51
#define OPREF_2_240 599
#define OPREF_2_242 601
#define OPREF_2_244 603
#define OPREF_2_246 2
#define OPREF_2_248 23
#define OPREF_2_250 605
#define OPREF_2_252 286
#define OPREF_2_254 607
#define OPREF_2_256 609
#define OPREF_2_258 611
#define OPREF_2_260 613
#define OPREF_2_262 615
#define OPREF_2_264 272
#define OPREF_2_266 55
#define OPREF_2_268 249
#define OPREF_2_270 558
#define OPREF_2_272 59
#define OPREF_2_274 380
#define OPREF_2_276 617
#define OPREF_2_278 270
#define OPREF_2_280 619
#define OPREF_2_282 621
#define OPREF_2_284 623
#define OPREF_2_286 625
#define OPREF_2_288 627
#define OPREF_2_290 139
#define OPREF_2_292 27
#define OPREF_2_294 629
#define OPREF_2_296 631
#define OPREF_2_298 633
#define OPREF_2_300 635
#define OPREF_2_302 637
#define OPREF_2_304 639
#define OPREF_2_306 641
#define OPREF_2_308 643
#define OPREF_2_310 645
#define OPREF_2_312 285
#define OPREF_2_314 647
#define OPREF_2_316 291
#define OPREF_2_318 306
#define OPREF_2_320 233
#define OPREF_2_322 287
#define OPREF_2_324 320
#define OPREF_2_326 649
#define OPREF_2_328 651
#define OPREF_2_330 653
#define OPREF_2_332 655
#define OPREF_2_334 657
#define OPREF_2_336 52
#define OPREF_2_338 659
#define OPREF_2_340 661
#define OPREF_2_342 663
#define OPREF_2_344 665
#define OPREF_2_346 667
#define OPREF_2_348 326
#define OPREF_2_350 159
#define OPREF_2_352 669
#define OPREF_2_354 671
#define OPREF_2_356 673
#define OPREF_2_358 646
#define OPREF_2_360 290
#define OPREF_2_362 675
#define OPREF_2_364 274
#define OPREF_2_366 296
#define OPREF_2_368 677
#define OPREF_2_370 79
#define OPREF_2_372 679
#define OPREF_2_374 592
#define OPREF_2_376 303
#define OPREF_2_378 267
#define OPREF_2_380 626
#define OPREF_2_382 681
#define OPREF_2_384 683
#define OPREF_2_386 685
#define OPREF_2_388 687
#define OPREF_2_390 689
#define OPREF_2_392 691
#define OPREF_2_394 693
#define OPREF_2_396 695
#define OPREF_2_398 697
#define OPREF_2_400 699
#define OPREF_2_402 24
#define OPREF_2_404 701
#define OPREF_2_406 703
#define OPREF_2_408 705
#define OPREF_2_410 414
#define OPREF_2_412 707
#define OPREF_2_414 709
#define OPREF_2_416 711
#define OPREF_2_418 713
#define OPREF_2_420 715
#define OPREF_2_422 717
#define OPREF_2_424 719
#define OPREF_2_426 236
#define OPREF_2_428 721
#define OPREF_2_430 723
#define OPREF_2_432 725
#define OPREF_2_434 727
#define OPREF_2_436 394
#define OPREF_2_438 729
#define OPREF_2_440 731
#define OPREF_2_442 733
#define OPREF_2_444 735
#define OPREF_2_446 737
#define OPREF_2_448 739
#define OPREF_2_450 741
#define OPREF_2_452 682
#define OPREF_2_454 743
#define OPREF_2_456 745
#define OPREF_2_458 747
#define OPREF_2_460 749
#define OPREF_2_462 751
#define OPREF_2_464 753
#define OPREF_2_466 755
#define OPREF_2_468 757
#define OPREF_2_470 759
#define OPREF_2_472 761
#define OPREF_2_474 763
#define OPREF_2_476 765
#define OPREF_2_478 767
#define OPREF_2_480 56
#define OPREF_2_482 769
#define OPREF_2_484 771
#define OPREF_1_0 63
#define OPREF_1_1 486
#define OPREF_1_2 773
#define OPREF_1_3 173
#define OPREF_1_4 512
#define OPREF_1_5 449
#define OPREF_1_6 774
#define OPREF_1_7 775
#define OPREF_1_8 776
#define OPREF_1_9 250
#define OPREF_1_10 0
#define OPREF_1_11 481
#define OPREF_1_12 170
#define OPREF_1_13 442
#define OPREF_1_14 171
#define OPREF_1_15 777
#define OPREF_1_16 778
#define OPREF_1_17 75
#define OPREF_1_18 779
#define OPREF_1_19 780
#define OPREF_1_20 707
#define OPREF_1_21 709
#define OPREF_1_22 781
#define OPREF_1_23 782
#define OPREF_1_24 447
#define OPREF_1_25 783
#define OPREF_1_26 194
#define OPREF_1_27 784
#define OPREF_1_28 465
#define OPREF_1_29 785
#define OPREF_1_30 786
#define OPREF_1_31 521
#define OPREF_1_32 515
#define OPREF_1_33 787
#define OPREF_1_34 183
#define OPREF_1_35 788
#define OPREF_1_36 789
#define OPREF_1_37 11
#define OPREF_1_38 79
#define OPREF_1_39 467
#define OPREF_1_40 535
#define OPREF_1_41 528
#define OPREF_1_42 790
#define OPREF_1_43 791
#define OPREF_1_44 275
#define OPREF_1_45 792
#define OPREF_1_46 483
#define OPREF_1_47 288
#define OPREF_1_48 583
#define OPREF_1_49 379
#define OPREF_1_50 233
#define OPREF_1_51 377
#define OPREF_1_52 71
#define OPREF_1_53 320
#define OPREF_1_54 236
#define OPREF_1_55 157
#define OPREF_1_56 400
#define OPREF_1_57 649
#define OPREF_1_58 793
