/* This file is automatically generated by i386-gen.  Do not edit!  */
/* Copyright (C) 2007-2026 Free Software Foundation, Inc.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

static const char i386_mnemonics[];

#define MN_ud0 0x1
#define MN_prefetcht0 0x5
#define MN_prefetchit0 0x10
#define MN_t2rpntlvwz0 0x1c
#define MN_xsha1 0x28
#define MN_fld1 0x2e
#define MN_ud1 0x33
#define MN_sha1msg1 0x37
#define MN_vsha512msg1 0x40
#define MN_vsm3msg1 0x4c
#define MN_sha256msg1 0x55
#define MN_fprem1 0x60
#define MN_f2xm1 0x67
#define MN_fyl2xp1 0x6d
#define MN_t2rpntlvwz0t1 0x75
#define MN_t2rpntlvwz1t1 0x83
#define MN_tileloaddt1 0x91
#define MN_prefetcht1 0x9d
#define MN_prefetchit1 0xa8
#define MN_pfrcpit1 0xb4
#define MN_pfrsqit1 0xbd
#define MN_int1 0xc6
#define MN_t2rpntlvwz0rst1 0xcb
#define MN_t2rpntlvwz1rst1 0xdb
#define MN_tileloaddrst1 0xeb
#define MN_prefetchwt1 0xf9
#define MN_t2rpntlvwz1 0x105
#define MN_xsha512 0x111
#define MN_vmovdqa32 0x119
#define MN_data32 0x123
#define MN_crc32 0x12a
#define MN_endbr32 0x130
#define MN_addr32 0x138
#define MN_vmovdqu32 0x13f
#define MN_ud2 0x149
#define MN_fldlg2 0x14d
#define MN_xrng2 0x154
#define MN_sha1msg2 0x15a
#define MN_vsha512msg2 0x163
#define MN_vsm3msg2 0x16f
#define MN_sha256msg2 0x178
#define MN_push2 0x183
#define MN_montmul2 0x189
#define MN_sm2 0x192
#define MN_fldln2 0x196
#define MN_pop2 0x19d
#define MN_vsha512rnds2 0x1a2
#define MN_vsm3rnds2 0x1af
#define MN_sha256rnds2 0x1b9
#define MN_prefetcht2 0x1c5
#define MN_pfrcpit2 0x1d0
#define MN_prefetchrst2 0x1d9
#define MN_vbroadcastf32x2 0x1e6
#define MN_vbroadcasti32x2 0x1f6
#define MN_vshuff64x2 0x206
#define MN_vextractf64x2 0x211
#define MN_vinsertf64x2 0x21f
#define MN_vbroadcastf64x2 0x22c
#define MN_vshufi64x2 0x23c
#define MN_vextracti64x2 0x247
#define MN_vinserti64x2 0x255
#define MN_vbroadcasti64x2 0x262
#define MN_sm3 0x272
#define MN_int3 0x276
#define MN_vmovdqa64 0x27b
#define MN_xsavec64 0x285
#define MN_xsave64 (MN_fxsave64 + 1)
#define MN_fxsave64 0x28e
#define MN_endbr64 0x297
#define MN_xrstor64 (MN_fxrstor64 + 1)
#define MN_fxrstor64 0x29f
#define MN_xsaves64 0x2a9
#define MN_xrstors64 0x2b2
#define MN_xsaveopt64 0x2bc
#define MN_vmovdqu64 0x2c7
#define MN_rex64 0x2d1
#define MN_xsha384 0x2d7
#define MN_sm4 0x2df
#define MN_sha1rnds4 0x2e3
#define MN_vsm4rnds4 0x2ed
#define MN_vshuff32x4 0x2f7
#define MN_vextractf32x4 0x302
#define MN_vinsertf32x4 0x310
#define MN_vbroadcastf32x4 0x31d
#define MN_vshufi32x4 0x32d
#define MN_vextracti32x4 0x338
#define MN_vinserti32x4 0x346
#define MN_vbroadcasti32x4 0x353
#define MN_vextractf64x4 0x363
#define MN_vinsertf64x4 0x371
#define MN_vbroadcastf64x4 0x37e
#define MN_vextracti64x4 0x38e
#define MN_vinserti64x4 0x39c
#define MN_vbroadcasti64x4 0x3a9
#define MN_vsm4key4 0x3b9
#define MN_data16 0x3c2
#define MN_vfmsub231bf16 0x3c9
#define MN_vfnmsub231bf16 0x3d7
#define MN_vfmadd231bf16 0x3e6
#define MN_vfnmadd231bf16 0x3f4
#define MN_vfmsub132bf16 0x403
#define MN_vfnmsub132bf16 0x411
#define MN_vfmadd132bf16 0x420
#define MN_vfnmadd132bf16 0x42e
#define MN_vcvtne2ps2bf16 0x43d
#define MN_vcvtneps2bf16 0x44c
#define MN_vfmsub213bf16 0x45a
#define MN_vfnmsub213bf16 0x468
#define MN_vfmadd213bf16 0x477
#define MN_vfnmadd213bf16 0x485
#define MN_vsubbf16 0x494
#define MN_vaddbf16 0x49d
#define MN_vreducebf16 0x4a6
#define MN_vrndscalebf16 0x4b2
#define MN_vscalefbf16 0x4c0
#define MN_vmulbf16 0x4cc
#define MN_vminbf16 0x4d5
#define MN_vrcpbf16 0x4de
#define MN_vcmpbf16 0x4e7
#define MN_vgetexpbf16 0x4f0
#define MN_vcomisbf16 0x4fc
#define MN_vfpclassbf16 0x507
#define MN_vgetmantbf16 0x514
#define MN_vrsqrtbf16 0x521
#define MN_vsqrtbf16 0x52c
#define MN_vdivbf16 0x536
#define MN_vminmaxbf16 0x53f
#define MN_vmaxbf16 0x54b
#define MN_tconjtfp16 0x554
#define MN_addr16 0x55f
#define MN_vmovdqu16 0x566
#define MN_vbmacor16x16x16 0x570
#define MN_vbmacxor16x16x16 0x580
#define MN_xsha256 0x591
#define MN_encodekey256 0x599
#define MN_vperm2f128 0x5a6
#define MN_vextractf128 0x5b1
#define MN_vinsertf128 0x5be
#define MN_vbroadcastf128 0x5ca
#define MN_vperm2i128 0x5d9
#define MN_vextracti128 0x5e4
#define MN_vinserti128 0x5f1
#define MN_vbroadcasti128 0x5fd
#define MN_encodekey128 0x60c
#define MN_vcvt2ph2bf8 0x619
#define MN_vcvtbiasph2bf8 0x625
#define MN_vcvtph2bf8 0x634
#define MN_vcvtbiasps2bf8 0x63f
#define MN_vcvtps2bf8 0x64e
#define MN_vcvtbf42hf8 0x659
#define MN_vcvtbf62hf8 0x665
#define MN_vcvthf62hf8 0x671
#define MN_vcvt2ph2hf8 0x67d
#define MN_vcvtbiasph2hf8 0x689
#define MN_vcvtph2hf8 0x698
#define MN_vcvtrops2hf8 0x6a3
#define MN_vcvtbiasps2hf8 0x6b0
#define MN_vcvtps2hf8 0x6bf
#define MN_vmovdqu8 0x6ca
#define MN_vextractf32x8 0x6d3
#define MN_vinsertf32x8 0x6e1
#define MN_vbroadcastf32x8 0x6ee
#define MN_vextracti32x8 0x6fe
#define MN_vinserti32x8 0x70c
#define MN_vbroadcasti32x8 0x719
#define MN_ud2a 0x729
#define MN_aaa 0x72e
#define MN_daa 0x732
#define MN_ssca 0x736
#define MN_lea 0x73b
#define MN_invlpga 0x73f
#define MN_pusha 0x747
#define MN_ja 0x74d
#define MN_jna 0x750
#define MN_ccmpna 0x754
#define MN_setna 0x75b
#define MN_ctestna 0x761
#define MN_setzuna 0x769
#define MN_cmovna (MN_fcmovna + 1)
#define MN_fcmovna (MN_cfcmovna + 1)
#define MN_cfcmovna 0x771
#define MN_ccmpa 0x77a
#define MN_popa 0x780
#define MN_movntdqa (MN_vmovntdqa + 1)
#define MN_vmovntdqa 0x785
#define MN_movdqa (MN_vmovdqa + 1)
#define MN_vmovdqa 0x78f
#define MN_seta 0x797
#define MN_prefetchnta 0x79c
#define MN_ctesta 0x7a8
#define MN_setzua 0x7af
#define MN_cmova (MN_fcmova + 1)
#define MN_fcmova (MN_cfcmova + 1)
#define MN_cfcmova 0x7b6
#define MN_rex_b 0x7be
#define MN_ud2b 0x7c4
#define MN_vpermi2b 0x7c9
#define MN_vpmovm2b 0x7d2
#define MN_vpermt2b 0x7db
#define MN_movdir64b 0x7e4
#define MN_cmpxchg16b 0x7ee
#define MN_cmpxchg8b 0x7f9
#define MN_vpshab 0x803
#define MN_sbb 0x80a
#define MN_psubb (MN_vpsubb + 1)
#define MN_vpsubb 0x80e
#define MN_xcrypt_ecb 0x815
#define MN_xcryptecb 0x820
#define MN_llwpcb 0x82a
#define MN_slwpcb 0x831
#define MN_kaddb 0x838
#define MN_paddb (MN_vpaddb + 1)
#define MN_vpaddb 0x83e
#define MN_kandb 0x845
#define MN_vpexpandb 0x84b
#define MN_vpmovssdb 0x855
#define MN_vpmovusdb 0x85f
#define MN_vpmovsdb 0x869
#define MN_udb 0x872
#define MN_vpmovdb 0x876
#define MN_vpcomgeb 0x87e
#define MN_vpcomleb 0x887
#define MN_vpcmpnleb 0x890
#define MN_vpcmpleb 0x89a
#define MN_vpcomfalseb 0x8a3
#define MN_vpcomtrueb 0x8af
#define MN_xcrypt_cfb 0x8ba
#define MN_xcryptcfb 0x8c5
#define MN_xcrypt_ofb 0x8cf
#define MN_xcryptofb 0x8da
#define MN_pshufb (MN_vpshufb + 1)
#define MN_vpshufb 0x8e4
#define MN_invlpgb 0x8ec
#define MN_pavgb (MN_vpavgb + 1)
#define MN_vpavgb 0x8f4
#define MN_jb 0x8fb
#define MN_vunpackb 0x8fe
#define MN_pbndkb 0x907
#define MN_pmovmskb (MN_vpmovmskb + 1)
#define MN_vpmovmskb 0x90e
#define MN_vpshlb 0x918
#define MN_kshiftlb 0x91f
#define MN_gf2p8mulb (MN_vgf2p8mulb + 1)
#define MN_vgf2p8mulb 0x928
#define MN_vpblendmb 0x933
#define MN_vptestnmb 0x93d
#define MN_vpcomb 0x947
#define MN_vpshufbitqmb 0x94e
#define MN_vpermb 0x95b
#define MN_vptestmb 0x962
#define MN_kandnb 0x96b
#define MN_psignb (MN_vpsignb + 1)
#define MN_vpsignb 0x972
#define MN_jnb 0x97a
#define MN_ccmpnb 0x97e
#define MN_setnb 0x985
#define MN_ctestnb 0x98b
#define MN_setzunb 0x993
#define MN_cmovnb (MN_fcmovnb + 1)
#define MN_fcmovnb (MN_cfcmovnb + 1)
#define MN_cfcmovnb 0x99b
#define MN_ccmpb 0x9a4
#define MN_vpcmpb 0x9aa
#define MN_vpcomeqb 0x9b1
#define MN_gf2p8affineqb (MN_vgf2p8affineqb + 1)
#define MN_vgf2p8affineqb 0x9ba
#define MN_vpcomneqb 0x9c9
#define MN_vpcmpneqb 0x9d3
#define MN_pcmpeqb (MN_vpcmpeqb + 1)
#define MN_vpcmpeqb 0x9dd
#define MN_vpmovusqb 0x9e6
#define MN_vpmovsqb 0x9f0
#define MN_vpmultishiftqb 0x9f9
#define MN_gf2p8affineinvqb (MN_vgf2p8affineinvqb + 1)
#define MN_vgf2p8affineinvqb 0xa08
#define MN_vpmovqb 0xa1a
#define MN_rex_rb 0xa22
#define MN_korb 0xa29
#define MN_kxnorb 0xa2e
#define MN_kxorb 0xa35
#define MN_pinsrb (MN_vpinsrb + 1)
#define MN_vpinsrb 0xa3b
#define MN_kshiftrb 0xa43
#define MN_pextrb (MN_vpextrb + 1)
#define MN_vpextrb 0xa4c
#define MN_rex_wrb 0xa54
#define MN_pabsb (MN_vpabsb + 1)
#define MN_vpabsb 0xa5c
#define MN_psubsb (MN_vpsubsb + 1)
#define MN_vpsubsb 0xa63
#define MN_paddsb (MN_vpaddsb + 1)
#define MN_vpaddsb 0xa6b
#define MN_pminsb (MN_vpminsb + 1)
#define MN_vpminsb 0xa73
#define MN_vmovrsb 0xa7b
#define MN_vpcompressb 0xa83
#define MN_psubusb (MN_vpsubusb + 1)
#define MN_vpsubusb 0xa8f
#define MN_paddusb (MN_vpaddusb + 1)
#define MN_vpaddusb 0xa98
#define MN_pavgusb 0xaa1
#define MN_movsb 0xaa9
#define MN_pmaxsb (MN_vpmaxsb + 1)
#define MN_vpmaxsb 0xaaf
#define MN_setb 0xab7
#define MN_vpcomgtb 0xabc
#define MN_pcmpgtb (MN_vpcmpgtb + 1)
#define MN_vpcmpgtb 0xac5
#define MN_vpcomltb 0xace
#define MN_vpcmpnltb 0xad7
#define MN_vpcmpltb 0xae1
#define MN_vpopcntb 0xaea
#define MN_knotb 0xaf3
#define MN_vprotb 0xaf9
#define MN_vpbroadcastb 0xb00
#define MN_ctestb 0xb0d
#define MN_ktestb 0xb14
#define MN_kortestb 0xb1b
#define MN_vpcomgeub 0xb24
#define MN_vpcomleub 0xb2e
#define MN_vpcmpnleub 0xb38
#define MN_vpcmpleub 0xb43
#define MN_vpcomfalseub 0xb4d
#define MN_vpcomtrueub 0xb5a
#define MN_vpcomub 0xb66
#define MN_pminub (MN_vpminub + 1)
#define MN_vpminub 0xb6e
#define MN_vpcmpub 0xb76
#define MN_vpcomequb 0xb7e
#define MN_vpcomnequb 0xb88
#define MN_vpcmpnequb 0xb93
#define MN_vpcmpequb 0xb9e
#define MN_sub (MN_fsub + 1)
#define MN_fsub (MN_pfsub + 1)
#define MN_pfsub 0xba8
#define MN_fisub 0xbae
#define MN_vpcomgtub 0xbb4
#define MN_vpcomltub 0xbbe
#define MN_vpcmpnltub 0xbc8
#define MN_vpcmpltub 0xbd3
#define MN_pmaxub (MN_vpmaxub + 1)
#define MN_vpmaxub 0xbdd
#define MN_setzub 0xbe5
#define MN_pblendvb (MN_vpblendvb + 1)
#define MN_vpblendvb 0xbec
#define MN_vbitrevb 0xbf6
#define MN_cmovb (MN_fcmovb + 1)
#define MN_fcmovb (MN_cfcmovb + 1)
#define MN_cfcmovb 0xbff
#define MN_kmovb 0xc07
#define MN_rex_wb 0xc0d
#define MN_clwb 0xc14
#define MN_packsswb (MN_vpacksswb + 1)
#define MN_vpacksswb 0xc19
#define MN_packuswb (MN_vpackuswb + 1)
#define MN_vpackuswb 0xc23
#define MN_vpmovuswb 0xc2d
#define MN_vpmovswb 0xc37
#define MN_vpmovwb 0xc40
#define MN_rex_xb 0xc48
#define MN_rex_rxb 0xc4f
#define MN_rex_wrxb 0xc57
#define MN_rex_wxb 0xc60
#define MN_movzb 0xc68
#define MN_clac 0xc6e
#define MN_stac 0xc73
#define MN_xcrypt_cbc 0xc78
#define MN_xcryptcbc 0xc83
#define MN_pfacc 0xc8d
#define MN_pfnacc 0xc93
#define MN_pfpnacc 0xc9a
#define MN_adc 0xca2
#define MN_dec (MN_aesdec + 3)
#define MN_aesdec (MN_vaesdec + 1)
#define MN_vaesdec 0xca6
#define MN_getsec 0xcae
#define MN_xsavec 0xcb5
#define MN_blcic 0xcbc
#define MN_blsic 0xcc2
#define MN_jc 0xcc8
#define MN_t1mskc 0xccb
#define MN_salc 0xcd2
#define MN_clc 0xcd7
#define MN_cmc 0xcdb
#define MN_aesimc (MN_vaesimc + 1)
#define MN_vaesimc 0xcdf
#define MN_rdpmc 0xce7
#define MN_aesenc (MN_vaesenc + 1)
#define MN_vaesenc 0xced
#define MN_inc 0xcf5
#define MN_jnc 0xcf9
#define MN_ccmpnc 0xcfd
#define MN_setnc 0xd04
#define MN_ctestnc 0xd0a
#define MN_vmfunc 0xd12
#define MN_setzunc 0xd19
#define MN_cmovnc (MN_cfcmovnc + 2)
#define MN_cfcmovnc 0xd21
#define MN_tlbsync 0xd2a
#define MN_ccmpc 0xd32
#define MN_rdtsc 0xd38
#define MN_btc 0xd3e
#define MN_setc 0xd42
#define MN_stc (MN_ctestc + 3)
#define MN_ctestc 0xd47
#define MN_setzuc 0xd4e
#define MN_cmovc (MN_cfcmovc + 2)
#define MN_cfcmovc 0xd55
#define MN_vpermi2d 0xd5d
#define MN_vpmovm2d 0xd66
#define MN_vpermt2d 0xd6f
#define MN_vpbroadcastmw2d 0xd78
#define MN_aad 0xd88
#define MN_vmread 0xd8c
#define MN_rmpread 0xd93
#define MN_vpshad 0xd9b
#define MN_vmload 0xda2
#define MN_psrad (MN_vpsrad + 1)
#define MN_vpsrad 0xda9
#define MN_vphaddbd 0xdb0
#define MN_vphaddubd 0xdb9
#define MN_phsubd (MN_vphsubd + 1)
#define MN_vphsubd 0xdc3
#define MN_psubd (MN_vpsubd + 1)
#define MN_vpsubd 0xdcb
#define MN_pmovsxbd (MN_vpmovsxbd + 1)
#define MN_vpmovsxbd 0xdd2
#define MN_pmovzxbd (MN_vpmovzxbd + 1)
#define MN_vpmovzxbd 0xddc
#define MN_add (MN_aadd + 1)
#define MN_aadd 0xde6
#define MN_fadd (MN_pfadd + 1)
#define MN_pfadd 0xdeb
#define MN_fiadd 0xdf1
#define MN_tileloadd 0xdf7
#define MN_xadd (MN_cmpnaxadd + 5)
#define MN_cmpnaxadd 0xe01
#define MN_cmpaxadd 0xe0b
#define MN_cmpnbxadd 0xe14
#define MN_cmpbxadd 0xe1e
#define MN_cmpncxadd 0xe27
#define MN_cmpcxadd 0xe31
#define MN_cmpnaexadd 0xe3a
#define MN_cmpaexadd 0xe45
#define MN_cmpnbexadd 0xe4f
#define MN_cmpbexadd 0xe5a
#define MN_cmpngexadd 0xe64
#define MN_cmpgexadd 0xe6f
#define MN_cmpnlexadd 0xe79
#define MN_cmplexadd 0xe84
#define MN_cmpnexadd 0xe8e
#define MN_cmpexadd 0xe98
#define MN_cmppexadd 0xea1
#define MN_cmpngxadd 0xeab
#define MN_cmpgxadd 0xeb5
#define MN_cmpnlxadd 0xebe
#define MN_cmplxadd 0xec8
#define MN_cmpnoxadd 0xed1
#define MN_cmpoxadd 0xedb
#define MN_cmppoxadd 0xee4
#define MN_cmpnpxadd 0xeee
#define MN_cmppxadd 0xef8
#define MN_cmpnsxadd 0xf01
#define MN_cmpsxadd 0xf0b
#define MN_cmpnzxadd 0xf14
#define MN_cmpzxadd 0xf1e
#define MN_phaddd (MN_vphaddd + 1)
#define MN_vphaddd 0xf27
#define MN_kaddd 0xf2f
#define MN_paddd (MN_vpaddd + 1)
#define MN_vpaddd 0xf35
#define MN_vpshldd 0xf3c
#define MN_kandd 0xf44
#define MN_vpandd 0xf4a
#define MN_vpexpandd 0xf51
#define MN_vpblendd 0xf5b
#define MN_vpgatherdd 0xf64
#define MN_vpscatterdd 0xf6f
#define MN_vpshrdd 0xf7b
#define MN_vpmacsdd 0xf83
#define MN_vpmacssdd 0xf8c
#define MN_rdseed 0xf96
#define MN_vpcomged 0xf9d
#define MN_vpcomled 0xfa6
#define MN_vpcmpnled 0xfaf
#define MN_vpcmpled 0xfb9
#define MN_tilestored 0xfc2
#define MN_vpcomfalsed 0xfcd
#define MN_ttransposed 0xfd9
#define MN_vpcomtrued 0xfe5
#define MN_pi2fd 0xff0
#define MN_pshufd (MN_vpshufd + 1)
#define MN_vpshufd 0xff6
#define MN_vpternlogd 0xffe
#define MN_pf2id 0x1009
#define MN_invpcid 0x100f
#define MN_rdpid 0x1017
#define MN_invvpid 0x101d
#define MN_cpuid 0x1025
#define MN_fbld 0x102b
#define MN_cld 0x1030
#define MN_fld 0x1034
#define MN_shld (MN_vpshld + 2)
#define MN_vpshld 0x1038
#define MN_fild 0x103f
#define MN_pslld (MN_vpslld + 1)
#define MN_vpslld 0x1044
#define MN_pmulld (MN_vpmulld + 1)
#define MN_vpmulld 0x104b
#define MN_vprold 0x1053
#define MN_psrld (MN_vpsrld + 1)
#define MN_vpsrld 0x105a
#define MN_vmptrld 0x1061
#define MN_kshiftld 0x1069
#define MN_enqcmd 0x1072
#define MN_vpblendmd 0x1079
#define MN_vptestnmd 0x1083
#define MN_vpcomd 0x108d
#define MN_vpermd 0x1094
#define MN_vptestmd 0x109b
#define MN_and (MN_aand + 1)
#define MN_aand 0x10a4
#define MN_pand (MN_vpand + 1)
#define MN_vpand 0x10a9
#define MN_rdrand 0x10af
#define MN_bnd 0x10b6
#define MN_kandnd 0x10ba
#define MN_vpandnd 0x10c1
#define MN_xend 0x10c9
#define MN_valignd 0x10ce
#define MN_psignd (MN_vpsignd + 1)
#define MN_vpsignd 0x10d6
#define MN_bound 0x10de
#define MN_slod 0x10e4
#define MN_vfmaddsub231pd 0x10e9
#define MN_vfmsub231pd 0x10f8
#define MN_vfnmsub231pd 0x1104
#define MN_vfmsubadd231pd 0x1111
#define MN_vfmadd231pd 0x1120
#define MN_vfnmadd231pd 0x112c
#define MN_vfmaddsub132pd 0x1139
#define MN_vfmsub132pd 0x1148
#define MN_vfnmsub132pd 0x1154
#define MN_vfmsubadd132pd 0x1161
#define MN_vfmadd132pd 0x1170
#define MN_vfnmadd132pd 0x117c
#define MN_vcvtph2pd 0x1189
#define MN_vpermi2pd 0x1193
#define MN_cvtpi2pd 0x119d
#define MN_vpermil2pd 0x11a6
#define MN_vexp2pd 0x11b1
#define MN_cvtdq2pd (MN_vcvtdq2pd + 1)
#define MN_vcvtdq2pd 0x11b9
#define MN_vcvtudq2pd 0x11c3
#define MN_vcvtqq2pd 0x11ce
#define MN_vcvtuqq2pd 0x11d8
#define MN_cvtps2pd (MN_vcvtps2pd + 1)
#define MN_vcvtps2pd 0x11e3
#define MN_vpermt2pd 0x11ed
#define MN_vfmaddsub213pd 0x11f7
#define MN_vfmsub213pd 0x1206
#define MN_vfnmsub213pd 0x1212
#define MN_vfmsubadd213pd 0x121f
#define MN_vfmadd213pd 0x122e
#define MN_vfnmadd213pd 0x123a
#define MN_vrcp14pd 0x1247
#define MN_vrsqrt14pd 0x1250
#define MN_vrcp28pd 0x125b
#define MN_vrsqrt28pd 0x1264
#define MN_movapd (MN_vmovapd + 1)
#define MN_vmovapd 0x126f
#define MN_pswapd 0x1277
#define MN_subpd (MN_addsubpd + 3)
#define MN_addsubpd (MN_vfmaddsubpd + 3)
#define MN_vfmaddsubpd 0x127e
#define MN_vaddsubpd 0x128a
#define MN_hsubpd (MN_vhsubpd + 1)
#define MN_vhsubpd 0x1294
#define MN_vfmsubpd 0x129c
#define MN_vfnmsubpd 0x12a5
#define MN_vsubpd 0x12af
#define MN_vgatherpf0dpd 0x12b6
#define MN_vscatterpf0dpd 0x12c4
#define MN_vgatherpf1dpd 0x12d3
#define MN_vscatterpf1dpd 0x12e1
#define MN_addpd (MN_vfmsubaddpd + 6)
#define MN_vfmsubaddpd 0x12f0
#define MN_haddpd (MN_vhaddpd + 1)
#define MN_vhaddpd 0x12fc
#define MN_vfmaddpd 0x1304
#define MN_vfnmaddpd 0x130d
#define MN_vaddpd 0x1317
#define MN_andpd (MN_vexpandpd + 4)
#define MN_vexpandpd 0x131e
#define MN_vandpd 0x1328
#define MN_blendpd (MN_vblendpd + 1)
#define MN_vblendpd 0x132f
#define MN_roundpd (MN_vroundpd + 1)
#define MN_vroundpd 0x1338
#define MN_vgatherdpd 0x1341
#define MN_vscatterdpd 0x134c
#define MN_cmpunordpd (MN_vcmpunordpd + 1)
#define MN_vcmpunordpd 0x1358
#define MN_cmpordpd (MN_vcmpordpd + 1)
#define MN_vcmpordpd 0x1364
#define MN_vreducepd 0x136e
#define MN_vrangepd 0x1378
#define MN_vcmpngepd 0x1381
#define MN_vcmpgepd 0x138b
#define MN_vrndscalepd 0x1394
#define MN_cmpnlepd (MN_vcmpnlepd + 1)
#define MN_vcmpnlepd 0x13a0
#define MN_cmplepd (MN_vcmplepd + 1)
#define MN_vcmplepd 0x13aa
#define MN_vcmpfalsepd 0x13b3
#define MN_vcmptruepd 0x13bf
#define MN_vscalefpd 0x13ca
#define MN_shufpd (MN_vshufpd + 1)
#define MN_vshufpd 0x13d4
#define MN_unpckhpd (MN_vunpckhpd + 1)
#define MN_vunpckhpd 0x13dc
#define MN_movhpd (MN_vmovhpd + 1)
#define MN_vmovhpd 0x13e6
#define MN_movmskpd (MN_vmovmskpd + 1)
#define MN_vmovmskpd 0x13ee
#define MN_vpermilpd 0x13f8
#define MN_unpcklpd (MN_vunpcklpd + 1)
#define MN_vunpcklpd 0x1402
#define MN_mulpd (MN_vmulpd + 1)
#define MN_vmulpd 0x140c
#define MN_movlpd (MN_vmovlpd + 1)
#define MN_vmovlpd 0x1413
#define MN_vpcmpd 0x141b
#define MN_vblendmpd 0x1422
#define MN_vfixupimmpd 0x142c
#define MN_vpermpd 0x1438
#define MN_andnpd (MN_vandnpd + 1)
#define MN_vandnpd 0x1440
#define MN_minpd (MN_vminpd + 1)
#define MN_vminpd 0x1448
#define MN_dppd (MN_vdppd + 1)
#define MN_vdppd 0x144f
#define MN_cmppd (MN_vcmppd + 1)
#define MN_vcmppd 0x1455
#define MN_vgetexppd 0x145c
#define MN_vgatherpf0qpd 0x1466
#define MN_vscatterpf0qpd 0x1474
#define MN_vgatherpf1qpd 0x1483
#define MN_vscatterpf1qpd 0x1491
#define MN_vcmpunord_qpd 0x14a0
#define MN_vcmpord_qpd 0x14ae
#define MN_cmpneqpd (MN_vcmpneqpd + 1)
#define MN_vcmpneqpd 0x14ba
#define MN_cmpeqpd (MN_vcmpeqpd + 1)
#define MN_vcmpeqpd 0x14c4
#define MN_vcmpge_oqpd 0x14cd
#define MN_vcmple_oqpd 0x14d9
#define MN_vcmpfalse_oqpd 0x14e5
#define MN_vcmpneq_oqpd 0x14f4
#define MN_vcmpeq_oqpd 0x1501
#define MN_vcmpgt_oqpd 0x150d
#define MN_vcmplt_oqpd 0x1519
#define MN_vgatherqpd 0x1525
#define MN_vscatterqpd 0x1530
#define MN_vcmpnge_uqpd 0x153c
#define MN_vcmpnle_uqpd 0x1549
#define MN_vcmptrue_uqpd 0x1556
#define MN_vcmpneq_uqpd 0x1564
#define MN_vcmpeq_uqpd 0x1571
#define MN_vcmpngt_uqpd 0x157d
#define MN_vcmpnlt_uqpd 0x158a
#define MN_orpd (MN_vorpd + 1)
#define MN_vorpd 0x1597
#define MN_xorpd (MN_vxorpd + 1)
#define MN_vxorpd 0x159d
#define MN_vcmpunord_spd 0x15a4
#define MN_vcmpord_spd 0x15b2
#define MN_vcmpge_ospd 0x15be
#define MN_vcmple_ospd 0x15ca
#define MN_vcmpfalse_ospd 0x15d6
#define MN_vcmpneq_ospd 0x15e5
#define MN_vcmpeq_ospd 0x15f2
#define MN_vcmpgt_ospd 0x15fe
#define MN_vcmplt_ospd 0x160a
#define MN_vfpclasspd 0x1616
#define MN_incsspd 0x1621
#define MN_rdsspd 0x1629
#define MN_vcompresspd 0x1630
#define MN_vcmpnge_uspd 0x163c
#define MN_vcmpnle_uspd 0x1649
#define MN_vcmptrue_uspd 0x1656
#define MN_vcmpneq_uspd 0x1664
#define MN_vcmpeq_uspd 0x1671
#define MN_vcmpngt_uspd 0x167d
#define MN_vcmpnlt_uspd 0x168a
#define MN_vcmpngtpd 0x1697
#define MN_vcmpgtpd 0x16a1
#define MN_cmpnltpd (MN_vcmpnltpd + 1)
#define MN_vcmpnltpd 0x16aa
#define MN_cmpltpd (MN_vcmpltpd + 1)
#define MN_vcmpltpd 0x16b4
#define MN_vgetmantpd 0x16bd
#define MN_movntpd (MN_vmovntpd + 1)
#define MN_vmovntpd 0x16c8
#define MN_sqrtpd (MN_vsqrtpd + 1)
#define MN_vsqrtpd 0x16d1
#define MN_vtestpd 0x16d9
#define MN_movupd (MN_vmovupd + 1)
#define MN_vmovupd 0x16e1
#define MN_blendvpd (MN_vblendvpd + 1)
#define MN_vblendvpd 0x16e9
#define MN_divpd (MN_vdivpd + 1)
#define MN_vdivpd 0x16f3
#define MN_vmaskmovpd 0x16fa
#define MN_maxpd (MN_vminmaxpd + 4)
#define MN_vminmaxpd 0x1705
#define MN_vmaxpd 0x170f
#define MN_vfrczpd 0x1716
#define MN_vpcomeqd 0x171e
#define MN_vpcomneqd 0x1727
#define MN_vpcmpneqd 0x1731
#define MN_pcmpeqd (MN_vpcmpeqd + 1)
#define MN_vpcmpeqd 0x173b
#define MN_vpgatherqd 0x1744
#define MN_vpscatterqd 0x174f
#define MN_vpmovusqd 0x175b
#define MN_vpmovsqd 0x1765
#define MN_vpmovqd 0x176e
#define MN_shrd 0x1776
#define MN_kord 0x177b
#define MN_kxnord 0x1780
#define MN_vpord 0x1787
#define MN_vprord 0x178d
#define MN_word (MN_aword + 1)
#define MN_aword 0x1794
#define MN_dword (MN_adword + 1)
#define MN_adword 0x179a
#define MN_kxord 0x17a1
#define MN_vpxord 0x17a7
#define MN_pinsrd (MN_vpinsrd + 1)
#define MN_vpinsrd 0x17ae
#define MN_kshiftrd 0x17b6
#define MN_pextrd (MN_vpextrd + 1)
#define MN_vpextrd 0x17bf
#define MN_vfmsub231sd 0x17c7
#define MN_vfnmsub231sd 0x17d3
#define MN_vfmadd231sd 0x17e0
#define MN_vfnmadd231sd 0x17ec
#define MN_vfmsub132sd 0x17f9
#define MN_vfnmsub132sd 0x1805
#define MN_vfmadd132sd 0x1812
#define MN_vfnmadd132sd 0x181e
#define MN_vcvtsh2sd 0x182b
#define MN_cvtsi2sd (MN_vcvtsi2sd + 1)
#define MN_vcvtsi2sd 0x1835
#define MN_vcvtusi2sd 0x183f
#define MN_cvtss2sd (MN_vcvtss2sd + 1)
#define MN_vcvtss2sd 0x184a
#define MN_vfmsub213sd 0x1854
#define MN_vfnmsub213sd 0x1860
#define MN_vfmadd213sd 0x186d
#define MN_vfnmadd213sd 0x1879
#define MN_vrcp14sd 0x1886
#define MN_vrsqrt14sd 0x188f
#define MN_vrcp28sd 0x189a
#define MN_vrsqrt28sd 0x18a3
#define MN_pabsd (MN_vpabsd + 1)
#define MN_vpabsd 0x18ae
#define MN_subsd (MN_vfmsubsd + 3)
#define MN_vfmsubsd 0x18b5
#define MN_vfnmsubsd 0x18be
#define MN_vsubsd 0x18c8
#define MN_addsd (MN_vfmaddsd + 3)
#define MN_vfmaddsd 0x18cf
#define MN_vfnmaddsd 0x18d8
#define MN_vaddsd 0x18e2
#define MN_roundsd (MN_vroundsd + 1)
#define MN_vroundsd 0x18e9
#define MN_cmpunordsd (MN_vcmpunordsd + 1)
#define MN_vcmpunordsd 0x18f2
#define MN_cmpordsd (MN_vcmpordsd + 1)
#define MN_vcmpordsd 0x18fe
#define MN_vreducesd 0x1908
#define MN_vrangesd 0x1912
#define MN_vcmpngesd 0x191b
#define MN_vcmpgesd 0x1925
#define MN_vrndscalesd 0x192e
#define MN_cmpnlesd (MN_vcmpnlesd + 1)
#define MN_vcmpnlesd 0x193a
#define MN_cmplesd (MN_vcmplesd + 1)
#define MN_vcmplesd 0x1944
#define MN_vcmpfalsesd 0x194d
#define MN_vcmptruesd 0x1959
#define MN_vscalefsd 0x1964
#define MN_comisd (MN_ucomisd + 1)
#define MN_ucomisd (MN_vucomisd + 1)
#define MN_vucomisd 0x196e
#define MN_vcomisd 0x1977
#define MN_mulsd (MN_vmulsd + 1)
#define MN_vmulsd 0x197f
#define MN_vfixupimmsd 0x1986
#define MN_minsd (MN_pminsd + 1)
#define MN_pminsd (MN_vpminsd + 1)
#define MN_vpminsd 0x1992
#define MN_vminsd 0x199a
#define MN_cmpsd (MN_vcmpsd + 1)
#define MN_vcmpsd 0x19a1
#define MN_vgetexpsd 0x19a8
#define MN_vcmpunord_qsd 0x19b2
#define MN_vcmpord_qsd 0x19c0
#define MN_cmpneqsd (MN_vcmpneqsd + 1)
#define MN_vcmpneqsd 0x19cc
#define MN_cmpeqsd (MN_vcmpeqsd + 1)
#define MN_vcmpeqsd 0x19d6
#define MN_vcmpge_oqsd 0x19df
#define MN_vcmple_oqsd 0x19eb
#define MN_vcmpfalse_oqsd 0x19f7
#define MN_vcmpneq_oqsd 0x1a06
#define MN_vcmpeq_oqsd 0x1a13
#define MN_vcmpgt_oqsd 0x1a1f
#define MN_vcmplt_oqsd 0x1a2b
#define MN_vcmpnge_uqsd 0x1a37
#define MN_vcmpnle_uqsd 0x1a44
#define MN_vcmptrue_uqsd 0x1a51
#define MN_vcmpneq_uqsd 0x1a5f
#define MN_vcmpeq_uqsd 0x1a6c
#define MN_vcmpngt_uqsd 0x1a78
#define MN_vcmpnlt_uqsd 0x1a85
#define MN_vmovrsd 0x1a92
#define MN_vcmpunord_ssd 0x1a9a
#define MN_vcmpord_ssd 0x1aa8
#define MN_vpdpbssd 0x1ab4
#define MN_tdpbssd 0x1abd
#define MN_vpcompressd 0x1ac5
#define MN_vcmpge_ossd 0x1ad1
#define MN_vcmple_ossd 0x1add
#define MN_vcmpfalse_ossd 0x1ae9
#define MN_vcmpneq_ossd 0x1af8
#define MN_vcmpeq_ossd 0x1b05
#define MN_vcmpgt_ossd 0x1b11
#define MN_vcmplt_ossd 0x1b1d
#define MN_wrssd 0x1b29
#define MN_vfpclasssd 0x1b2f
#define MN_vcmpnge_ussd 0x1b3a
#define MN_vcmpnle_ussd 0x1b47
#define MN_vcmptrue_ussd 0x1b54
#define MN_vcmpneq_ussd 0x1b62
#define MN_vcmpeq_ussd 0x1b6f
#define MN_vcmpngt_ussd 0x1b7b
#define MN_vcmpnlt_ussd 0x1b88
#define MN_wrussd 0x1b95
#define MN_vp4dpwssd 0x1b9c
#define MN_vpdpwssd 0x1ba6
#define MN_vcmpngtsd 0x1baf
#define MN_vcmpgtsd 0x1bb9
#define MN_cmpnltsd (MN_vcmpnltsd + 1)
#define MN_vcmpnltsd 0x1bc2
#define MN_cmpltsd (MN_vcmpltsd + 1)
#define MN_vcmpltsd 0x1bcc
#define MN_vgetmantsd 0x1bd5
#define MN_movntsd 0x1be0
#define MN_sqrtsd (MN_vsqrtsd + 1)
#define MN_vsqrtsd 0x1be8
#define MN_vbroadcastsd 0x1bf0
#define MN_vpdpbusd 0x1bfd
#define MN_tdpbusd 0x1c06
#define MN_vpdpwusd 0x1c0e
#define MN_divsd (MN_vdivsd + 1)
#define MN_vdivsd 0x1c17
#define MN_movsd (MN_vmovsd + 1)
#define MN_vmovsd 0x1c1e
#define MN_maxsd (MN_vminmaxsd + 4)
#define MN_vminmaxsd 0x1c25
#define MN_pmaxsd (MN_vpmaxsd + 1)
#define MN_vpmaxsd 0x1c2f
#define MN_vmaxsd 0x1c37
#define MN_vucomxsd 0x1c3e
#define MN_vcomxsd 0x1c47
#define MN_vfrczsd 0x1c4f
#define MN_vp2intersectd 0x1c57
#define MN_vpconflictd 0x1c65
#define MN_vpcomgtd 0x1c71
#define MN_pcmpgtd (MN_vpcmpgtd + 1)
#define MN_vpcmpgtd 0x1c7a
#define MN_cltd 0x1c83
#define MN_vpcomltd 0x1c88
#define MN_vpcmpnltd 0x1c91
#define MN_vpcmpltd 0x1c9b
#define MN_vpopcntd 0x1ca4
#define MN_vplzcntd 0x1cad
#define MN_knotd 0x1cb6
#define MN_vprotd 0x1cbc
#define MN_std (MN_vpbroadcastd + 9)
#define MN_vpbroadcastd 0x1cc3
#define MN_ktestd 0x1cd0
#define MN_kortestd 0x1cd7
#define MN_cwtd 0x1ce0
#define MN_vpcomgeud 0x1ce5
#define MN_vpcomleud 0x1cef
#define MN_vpcmpnleud 0x1cf9
#define MN_vpcmpleud 0x1d04
#define MN_vpcomfalseud 0x1d0e
#define MN_vpcomtrueud 0x1d1b
#define MN_vpcomud 0x1d27
#define MN_pminud (MN_vpminud + 1)
#define MN_vpminud 0x1d2f
#define MN_vpcmpud 0x1d37
#define MN_vpcomequd 0x1d3f
#define MN_vpcomnequd 0x1d49
#define MN_vpcmpnequd 0x1d54
#define MN_vpcmpequd 0x1d5f
#define MN_vpdpbsud 0x1d69
#define MN_tdpbsud 0x1d72
#define MN_vpdpwsud 0x1d7a
#define MN_vpcomgtud 0x1d83
#define MN_vpcomltud 0x1d8d
#define MN_vpcmpnltud 0x1d97
#define MN_vpcmpltud 0x1da2
#define MN_vpdpbuud 0x1dac
#define MN_tdpbuud 0x1db5
#define MN_vpdpwuud 0x1dbd
#define MN_pmaxud (MN_vpmaxud + 1)
#define MN_vpmaxud 0x1dc6
#define MN_vpsravd 0x1dce
#define MN_vpshldvd 0x1dd6
#define MN_vpshrdvd 0x1ddf
#define MN_vpsllvd 0x1de8
#define MN_vprolvd 0x1df0
#define MN_vpsrlvd 0x1df8
#define MN_invd (MN_wbinvd + 2)
#define MN_wbinvd 0x1e00
#define MN_wbnoinvd 0x1e07
#define MN_movd (MN_kmovd + 1)
#define MN_kmovd (MN_vpmaskmovd + 5)
#define MN_vpmaskmovd 0x1e10
#define MN_vmovd 0x1e1b
#define MN_vprorvd 0x1e21
#define MN_vphsubwd 0x1e29
#define MN_cwd 0x1e32
#define MN_vphaddwd 0x1e36
#define MN_pmaddwd (MN_vpmaddwd + 1)
#define MN_vpmaddwd 0x1e3f
#define MN_punpckhwd (MN_vpunpckhwd + 1)
#define MN_vpunpckhwd 0x1e48
#define MN_kunpckwd 0x1e53
#define MN_punpcklwd (MN_vpunpcklwd + 1)
#define MN_vpunpcklwd 0x1e5c
#define MN_vpmacswd 0x1e67
#define MN_vpmadcswd 0x1e70
#define MN_vpmacsswd 0x1e7a
#define MN_vpmadcsswd 0x1e84
#define MN_vphadduwd 0x1e8f
#define MN_pmovsxwd (MN_vpmovsxwd + 1)
#define MN_vpmovsxwd 0x1e99
#define MN_pmovzxwd (MN_vpmovzxwd + 1)
#define MN_vpmovzxwd 0x1ea3
#define MN_movsxd 0x1ead
#define MN_fldl2e 0x1eb4
#define MN_jae 0x1ebb
#define MN_jnae 0x1ebf
#define MN_ccmpnae 0x1ec4
#define MN_setnae 0x1ecc
#define MN_ctestnae 0x1ed3
#define MN_setzunae 0x1edc
#define MN_cmovnae (MN_fcmovnae + 1)
#define MN_fcmovnae (MN_cfcmovnae + 1)
#define MN_cfcmovnae 0x1ee5
#define MN_ccmpae 0x1eef
#define MN_setae 0x1ef6
#define MN_ctestae 0x1efc
#define MN_setzuae 0x1f04
#define MN_cmovae (MN_fcmovae + 1)
#define MN_fcmovae (MN_cfcmovae + 1)
#define MN_cfcmovae 0x1f0c
#define MN_jbe 0x1f15
#define MN_jnbe 0x1f19
#define MN_ccmpnbe 0x1f1e
#define MN_setnbe 0x1f26
#define MN_ctestnbe 0x1f2d
#define MN_setzunbe 0x1f36
#define MN_cmovnbe (MN_fcmovnbe + 1)
#define MN_fcmovnbe (MN_cfcmovnbe + 1)
#define MN_cfcmovnbe 0x1f3f
#define MN_ccmpbe 0x1f49
#define MN_setbe 0x1f50
#define MN_ctestbe 0x1f56
#define MN_setzube 0x1f5e
#define MN_movbe (MN_cmovbe + 1)
#define MN_cmovbe (MN_fcmovbe + 1)
#define MN_fcmovbe (MN_cfcmovbe + 1)
#define MN_cfcmovbe 0x1f66
#define MN_lfence 0x1f6f
#define MN_mfence 0x1f76
#define MN_sfence 0x1f7d
#define MN_cwde 0x1f84
#define MN_ffree 0x1f89
#define MN_jge 0x1f8f
#define MN_jnge 0x1f93
#define MN_ccmpnge 0x1f98
#define MN_setnge 0x1fa0
#define MN_ctestnge 0x1fa7
#define MN_setzunge 0x1fb0
#define MN_cmovnge (MN_cfcmovnge + 2)
#define MN_cfcmovnge 0x1fb9
#define MN_ccmpge 0x1fc3
#define MN_pfcmpge 0x1fca
#define MN_setge 0x1fd2
#define MN_ctestge 0x1fd8
#define MN_setzuge 0x1fe0
#define MN_cmovge (MN_cfcmovge + 2)
#define MN_cfcmovge 0x1fe8
#define MN_je 0x1ff1
#define MN_fscale 0x1ff4
#define MN_jle 0x1ffb
#define MN_jnle 0x1fff
#define MN_ccmpnle 0x2004
#define MN_setnle 0x200c
#define MN_ctestnle 0x2013
#define MN_setzunle 0x201c
#define MN_cmovnle (MN_cfcmovnle + 2)
#define MN_cfcmovnle 0x2025
#define MN_ccmple 0x202f
#define MN_setle 0x2036
#define MN_ctestle 0x203c
#define MN_setzule 0x2044
#define MN_cmovle (MN_cfcmovle + 2)
#define MN_cfcmovle 0x204c
#define MN_vmresume 0x2055
#define MN_jne 0x205e
#define MN_repne 0x2062
#define MN_ccmpne 0x2068
#define MN_loopne 0x206f
#define MN_setne 0x2076
#define MN_ctestne 0x207c
#define MN_setzune 0x2084
#define MN_cmovne (MN_fcmovne + 1)
#define MN_fcmovne (MN_cfcmovne + 1)
#define MN_cfcmovne 0x208c
#define MN_repe 0x2095
#define MN_jpe 0x209a
#define MN_ccmpe 0x209e
#define MN_loope 0x20a4
#define MN_setpe 0x20aa
#define MN_setzupe 0x20b0
#define MN_cmovpe (MN_cfcmovpe + 2)
#define MN_cfcmovpe 0x20b8
#define MN_cdqe 0x20c1
#define MN_xacquire 0x20c6
#define MN_xstore 0x20cf
#define MN_rdfsbase 0x20d6
#define MN_wrfsbase 0x20df
#define MN_rdgsbase 0x20e8
#define MN_wrgsbase 0x20f1
#define MN_tilerelease 0x20fa
#define MN_xrelease 0x2106
#define MN_pause (MN_tpause + 1)
#define MN_tpause 0x210f
#define MN_pvalidate 0x2116
#define MN_rmpupdate 0x2120
#define MN_sete 0x212a
#define MN_vmwrite 0x212f
#define MN_ptwrite 0x2137
#define MN_cldemote 0x213f
#define MN_cteste 0x2148
#define MN_sha1nexte 0x214f
#define MN_setzue 0x2159
#define MN_leave 0x2160
#define MN_fsave 0x2166
#define MN_vmsave 0x216c
#define MN_fnsave 0x2173
#define MN_xsave (MN_fxsave + 1)
#define MN_fxsave 0x217a
#define MN_cmove (MN_fcmove + 1)
#define MN_fcmove (MN_cfcmove + 1)
#define MN_cfcmove 0x2181
#define MN_serialize 0x2189
#define MN_vmxoff 0x2193
#define MN_lahf 0x219a
#define MN_sahf 0x219f
#define MN_pushf 0x21a4
#define MN_ccmpf 0x21aa
#define MN_popf 0x21b0
#define MN_bsf 0x21b5
#define MN_retf 0x21b9
#define MN_ctestf 0x21be
#define MN_neg 0x21c5
#define MN_ldtilecfg 0x21c9
#define MN_sttilecfg 0x21d3
#define MN_xchg (MN_cmpxchg + 3)
#define MN_cmpxchg 0x21dd
#define MN_pconfig 0x21e5
#define MN_jg 0x21ed
#define MN_jng 0x21f0
#define MN_ccmpng 0x21f4
#define MN_xstore_rng 0x21fb
#define MN_xstorerng 0x2206
#define MN_setng 0x2210
#define MN_ctestng 0x2216
#define MN_setzung 0x221e
#define MN_cmovng (MN_cfcmovng + 2)
#define MN_cfcmovng 0x2226
#define MN_invlpg 0x222f
#define MN_ccmpg 0x2236
#define MN_setg 0x223c
#define MN_ctestg 0x2241
#define MN_setzug 0x2248
#define MN_cmovg (MN_cfcmovg + 2)
#define MN_cfcmovg 0x224f
#define MN_tcvtrowps2bf16h 0x2257
#define MN_vmlaunch 0x2267
#define MN_prefetch 0x2270
#define MN_fxch 0x2279
#define MN_tcvtrowps2phh 0x227e
#define MN_vfmaddsub231ph 0x228c
#define MN_vfmsub231ph 0x229b
#define MN_vfnmsub231ph 0x22a7
#define MN_vfmsubadd231ph 0x22b4
#define MN_vfmadd231ph 0x22c3
#define MN_vfnmadd231ph 0x22cf
#define MN_vfmaddsub132ph 0x22dc
#define MN_vfmsub132ph 0x22eb
#define MN_vfnmsub132ph 0x22f7
#define MN_vfmsubadd132ph 0x2304
#define MN_vfmadd132ph 0x2313
#define MN_vfnmadd132ph 0x231f
#define MN_vcvthf82ph 0x232c
#define MN_vcvtpd2ph 0x2337
#define MN_vcvtdq2ph 0x2341
#define MN_vcvtudq2ph 0x234b
#define MN_vcvtqq2ph 0x2356
#define MN_vcvtuqq2ph 0x2360
#define MN_vcvtps2ph 0x236b
#define MN_vcvtw2ph 0x2375
#define MN_vcvtuw2ph 0x237e
#define MN_vfmaddsub213ph 0x2388
#define MN_vfmsub213ph 0x2397
#define MN_vfnmsub213ph 0x23a3
#define MN_vfmsubadd213ph 0x23b0
#define MN_vfmadd213ph 0x23bf
#define MN_vfnmadd213ph 0x23cb
#define MN_vsubph 0x23d8
#define MN_vfcmaddcph 0x23df
#define MN_vfmaddcph 0x23ea
#define MN_vfcmulcph 0x23f4
#define MN_vfmulcph 0x23fe
#define MN_vaddph 0x2407
#define MN_vcmpunordph 0x240e
#define MN_vcmpordph 0x241a
#define MN_vreduceph 0x2424
#define MN_vcmpngeph 0x242e
#define MN_vcmpgeph 0x2438
#define MN_vrndscaleph 0x2441
#define MN_vcmpnleph 0x244d
#define MN_vcmpleph 0x2457
#define MN_vcmpfalseph 0x2460
#define MN_vcmptrueph 0x246c
#define MN_vscalefph 0x2477
#define MN_vmulph 0x2481
#define MN_vminph 0x2488
#define MN_vrcpph 0x248f
#define MN_vcmpph 0x2496
#define MN_vgetexpph 0x249d
#define MN_vcmpunord_qph 0x24a7
#define MN_vcmpord_qph 0x24b5
#define MN_vcmpneqph 0x24c1
#define MN_vcmpeqph 0x24cb
#define MN_vcmpge_oqph 0x24d4
#define MN_vcmple_oqph 0x24e0
#define MN_vcmpfalse_oqph 0x24ec
#define MN_vcmpneq_oqph 0x24fb
#define MN_vcmpeq_oqph 0x2508
#define MN_vcmpgt_oqph 0x2514
#define MN_vcmplt_oqph 0x2520
#define MN_vcmpnge_uqph 0x252c
#define MN_vcmpnle_uqph 0x2539
#define MN_vcmptrue_uqph 0x2546
#define MN_vcmpneq_uqph 0x2554
#define MN_vcmpeq_uqph 0x2561
#define MN_vcmpngt_uqph 0x256d
#define MN_vcmpnlt_uqph 0x257a
#define MN_vcmpunord_sph 0x2587
#define MN_vcmpord_sph 0x2595
#define MN_vcmpge_osph 0x25a1
#define MN_vcmple_osph 0x25ad
#define MN_vcmpfalse_osph 0x25b9
#define MN_vcmpneq_osph 0x25c8
#define MN_vcmpeq_osph 0x25d5
#define MN_vcmpgt_osph 0x25e1
#define MN_vcmplt_osph 0x25ed
#define MN_vfpclassph 0x25f9
#define MN_vcmpnge_usph 0x2604
#define MN_vcmpnle_usph 0x2611
#define MN_vcmptrue_usph 0x261e
#define MN_vcmpneq_usph 0x262c
#define MN_vcmpeq_usph 0x2639
#define MN_vcmpngt_usph 0x2645
#define MN_vcmpnlt_usph 0x2652
#define MN_vcmpngtph 0x265f
#define MN_vcmpgtph 0x2669
#define MN_vcmpnltph 0x2672
#define MN_vcmpltph 0x267c
#define MN_vgetmantph 0x2685
#define MN_vrsqrtph 0x2690
#define MN_vsqrtph 0x2699
#define MN_vdivph 0x26a1
#define MN_vminmaxph 0x26a8
#define MN_vmaxph 0x26b2
#define MN_vpmacsdqh 0x26b9
#define MN_vpmacssdqh 0x26c3
#define MN_vfmsub231sh 0x26ce
#define MN_vfnmsub231sh 0x26da
#define MN_vfmadd231sh 0x26e7
#define MN_vfnmadd231sh 0x26f3
#define MN_vfmsub132sh 0x2700
#define MN_vfnmsub132sh 0x270c
#define MN_vfmadd132sh 0x2719
#define MN_vfnmadd132sh 0x2725
#define MN_vcvtsd2sh 0x2732
#define MN_vcvtsi2sh 0x273c
#define MN_vcvtusi2sh 0x2746
#define MN_vcvtss2sh 0x2751
#define MN_vfmsub213sh 0x275b
#define MN_vfnmsub213sh 0x2767
#define MN_vfmadd213sh 0x2774
#define MN_vfnmadd213sh 0x2780
#define MN_psmash 0x278d
#define MN_vsubsh 0x2794
#define MN_vfcmaddcsh 0x279b
#define MN_vfmaddcsh 0x27a6
#define MN_vfcmulcsh 0x27b0
#define MN_vfmulcsh 0x27ba
#define MN_vaddsh 0x27c3
#define MN_vcmpunordsh 0x27ca
#define MN_vcmpordsh 0x27d6
#define MN_vreducesh 0x27e0
#define MN_vcmpngesh 0x27ea
#define MN_vcmpgesh 0x27f4
#define MN_vrndscalesh 0x27fd
#define MN_vcmpnlesh 0x2809
#define MN_vcmplesh 0x2813
#define MN_vcmpfalsesh 0x281c
#define MN_vcmptruesh 0x2828
#define MN_vscalefsh 0x2833
#define MN_vucomish 0x283d
#define MN_vcomish 0x2846
#define MN_vmulsh 0x284e
#define MN_vminsh 0x2855
#define MN_vrcpsh 0x285c
#define MN_vcmpsh 0x2863
#define MN_vgetexpsh 0x286a
#define MN_vcmpunord_qsh 0x2874
#define MN_vcmpord_qsh 0x2882
#define MN_vcmpneqsh 0x288e
#define MN_vcmpeqsh 0x2898
#define MN_vcmpge_oqsh 0x28a1
#define MN_vcmple_oqsh 0x28ad
#define MN_vcmpfalse_oqsh 0x28b9
#define MN_vcmpneq_oqsh 0x28c8
#define MN_vcmpeq_oqsh 0x28d5
#define MN_vcmpgt_oqsh 0x28e1
#define MN_vcmplt_oqsh 0x28ed
#define MN_vcmpnge_uqsh 0x28f9
#define MN_vcmpnle_uqsh 0x2906
#define MN_vcmptrue_uqsh 0x2913
#define MN_vcmpneq_uqsh 0x2921
#define MN_vcmpeq_uqsh 0x292e
#define MN_vcmpngt_uqsh 0x293a
#define MN_vcmpnlt_uqsh 0x2947
#define MN_vcmpunord_ssh 0x2954
#define MN_vcmpord_ssh 0x2962
#define MN_vcmpge_ossh 0x296e
#define MN_vcmple_ossh 0x297a
#define MN_vcmpfalse_ossh 0x2986
#define MN_vcmpneq_ossh 0x2995
#define MN_vcmpeq_ossh 0x29a2
#define MN_vcmpgt_ossh 0x29ae
#define MN_vcmplt_ossh 0x29ba
#define MN_vfpclasssh 0x29c6
#define MN_vcmpnge_ussh 0x29d1
#define MN_vcmpnle_ussh 0x29de
#define MN_vcmptrue_ussh 0x29eb
#define MN_vcmpneq_ussh 0x29f9
#define MN_vcmpeq_ussh 0x2a06
#define MN_vcmpngt_ussh 0x2a12
#define MN_vcmpnlt_ussh 0x2a1f
#define MN_vcmpngtsh 0x2a2c
#define MN_vcmpgtsh 0x2a36
#define MN_vcmpnltsh 0x2a3f
#define MN_vcmpltsh 0x2a49
#define MN_vgetmantsh 0x2a52
#define MN_vrsqrtsh 0x2a5d
#define MN_vsqrtsh 0x2a66
#define MN_clflush 0x2a6e
#define MN_push 0x2a76
#define MN_vdivsh 0x2a7b
#define MN_vmovsh 0x2a82
#define MN_vminmaxsh 0x2a89
#define MN_vmaxsh 0x2a93
#define MN_vucomxsh 0x2a9a
#define MN_vcomxsh 0x2aa3
#define MN_blci 0x2aab
#define MN_clgi 0x2ab0
#define MN_stgi 0x2ab5
#define MN_bzhi 0x2aba
#define MN_cli 0x2abf
#define MN_fcomi 0x2ac3
#define MN_fucomi 0x2ac9
#define MN_feni 0x2ad0
#define MN_fneni 0x2ad5
#define MN_cvttpd2pi 0x2adb
#define MN_cvtpd2pi 0x2ae5
#define MN_cvttps2pi 0x2aee
#define MN_cvtps2pi 0x2af8
#define MN_fldpi 0x2b01
#define MN_senduipi 0x2b07
#define MN_fcompi 0x2b10
#define MN_fucompi 0x2b17
#define MN_movdiri 0x2b1f
#define MN_pcmpestri (MN_vpcmpestri + 1)
#define MN_vpcmpestri 0x2b27
#define MN_pcmpistri (MN_vpcmpistri + 1)
#define MN_vpcmpistri 0x2b32
#define MN_cvttsd2si (MN_vcvttsd2si + 1)
#define MN_vcvttsd2si 0x2b3d
#define MN_cvtsd2si (MN_vcvtsd2si + 1)
#define MN_vcvtsd2si 0x2b48
#define MN_vcvttsh2si 0x2b52
#define MN_vcvtsh2si 0x2b5d
#define MN_cvttss2si (MN_vcvttss2si + 1)
#define MN_vcvttss2si 0x2b67
#define MN_cvtss2si (MN_vcvtss2si + 1)
#define MN_vcvtss2si 0x2b72
#define MN_fdisi 0x2b7c
#define MN_fndisi 0x2b82
#define MN_blsi 0x2b89
#define MN_vcvttsd2usi 0x2b8e
#define MN_vcvtsd2usi 0x2b9a
#define MN_vcvttsh2usi 0x2ba5
#define MN_vcvtsh2usi 0x2bb1
#define MN_vcvttss2usi 0x2bbc
#define MN_vcvtss2usi 0x2bc8
#define MN_movnti 0x2bd3
#define MN_sti 0x2bda
#define MN_clui 0x2bde
#define MN_stui (MN_testui + 2)
#define MN_testui 0x2be3
#define MN_notrack 0x2bea
#define MN_lock 0x2bf2
#define MN_bndmk 0x2bf7
#define MN_xresldtrk 0x2bfd
#define MN_xsusldtrk 0x2c07
#define MN_blcmsk 0x2c11
#define MN_blsmsk 0x2c18
#define MN_tzmsk 0x2c1f
#define MN_tcvtrowps2bf16l 0x2c25
#define MN_sal 0x2c35
#define MN_lwpval 0x2c39
#define MN_bndcl 0x2c40
#define MN_rcl 0x2c46
#define MN_tcvtrowps2phl 0x2c4a
#define MN_shl 0x2c58
#define MN_jl 0x2c5c
#define MN_aesdec256kl 0x2c5f
#define MN_aesenc256kl 0x2c6b
#define MN_aesdecwide256kl 0x2c77
#define MN_aesencwide256kl 0x2c87
#define MN_aesdec128kl 0x2c97
#define MN_aesenc128kl 0x2ca3
#define MN_aesdecwide128kl 0x2caf
#define MN_aesencwide128kl 0x2cbf
#define MN_call (MN_tdcall + 2)
#define MN_tdcall 0x2ccf
#define MN_lcall 0x2cd6
#define MN_seamcall 0x2cdc
#define MN_vmmcall 0x2ce5
#define MN_vmcall 0x2ced
#define MN_syscall 0x2cf4
#define MN_vzeroall 0x2cfc
#define MN_fildll 0x2d05
#define MN_blcfill 0x2d0c
#define MN_blsfill 0x2d14
#define MN_fistpll 0x2d1c
#define MN_fisttpll 0x2d24
#define MN_jnl 0x2d2d
#define MN_ccmpnl 0x2d31
#define MN_setnl 0x2d38
#define MN_ctestnl 0x2d3e
#define MN_setzunl 0x2d46
#define MN_cmovnl (MN_cfcmovnl + 2)
#define MN_cfcmovnl 0x2d4e
#define MN_rol 0x2d57
#define MN_ccmpl 0x2d5b
#define MN_arpl 0x2d61
#define MN_vpmacsdql 0x2d66
#define MN_vpmacssdql 0x2d70
#define MN_lsl 0x2d7b
#define MN_movsl 0x2d7f
#define MN_setl 0x2d85
#define MN_ctestl 0x2d8a
#define MN_cwtl 0x2d91
#define MN_mul (MN_fmul + 1)
#define MN_fmul (MN_pfmul + 1)
#define MN_pfmul 0x2d96
#define MN_imul (MN_fimul + 1)
#define MN_fimul 0x2d9c
#define MN_montmul 0x2da2
#define MN_setzul 0x2daa
#define MN_cmovl (MN_cfcmovl + 2)
#define MN_cfcmovl 0x2db1
#define MN_vpmovb2m 0x2db9
#define MN_vpmovd2m 0x2dc2
#define MN_vpmovq2m 0x2dcb
#define MN_vpmovw2m 0x2dd4
#define MN_aam 0x2ddd
#define MN_fxam 0x2de1
#define MN_fprem 0x2de6
#define MN_fcom 0x2dec
#define MN_ficom 0x2df1
#define MN_fucom 0x2df7
#define MN_fsetpm 0x2dfd
#define MN_fnsetpm 0x2e04
#define MN_frstpm 0x2e0c
#define MN_vpperm 0x2e13
#define MN_pcmpestrm (MN_vpcmpestrm + 1)
#define MN_vpcmpestrm 0x2e1a
#define MN_pcmpistrm (MN_vpcmpistrm + 1)
#define MN_vpcmpistrm 0x2e25
#define MN_rsm 0x2e30
#define MN_fpatan 0x2e34
#define MN_fptan 0x2e3b
#define MN_bndcn 0x2e41
#define MN_andn (MN_pandn + 1)
#define MN_pandn (MN_vpandn + 1)
#define MN_vpandn 0x2e47
#define MN_in (MN_xbegin + 4)
#define MN_xbegin 0x2e4e
#define MN_pfmin 0x2e55
#define MN_fsin 0x2e5b
#define MN_vmxon 0x2e60
#define MN_vmrun 0x2e66
#define MN_jo 0x2e6c
#define MN_jno 0x2e6f
#define MN_ccmpno 0x2e73
#define MN_setno 0x2e7a
#define MN_ctestno 0x2e80
#define MN_setzuno 0x2e88
#define MN_cmovno (MN_cfcmovno + 2)
#define MN_cfcmovno 0x2e90
#define MN_jpo 0x2e99
#define MN_ccmpo 0x2e9d
#define MN_setpo 0x2ea3
#define MN_setzupo 0x2ea9
#define MN_cmovpo (MN_cfcmovpo + 2)
#define MN_cfcmovpo 0x2eb1
#define MN_cqo 0x2eba
#define MN_tilezero 0x2ebe
#define MN_clzero 0x2ec7
#define MN_seto 0x2ece
#define MN_into 0x2ed3
#define MN_cqto 0x2ed8
#define MN_ctesto 0x2edd
#define MN_ssto 0x2ee4
#define MN_setzuo 0x2ee9
#define MN_cmovo (MN_cfcmovo + 2)
#define MN_cfcmovo 0x2ef0
#define MN_push2p 0x2ef8
#define MN_pop2p 0x2eff
#define MN_bswap 0x2f05
#define MN_fsubp 0x2f0b
#define MN_pfrcp 0x2f11
#define MN_rdtscp 0x2f17
#define MN_faddp 0x2f1e
#define MN_pdep 0x2f24
#define MN_ffreep 0x2f29
#define MN_rep 0x2f30
#define MN_pushp 0x2f34
#define MN_fcomip 0x2f3a
#define MN_fucomip 0x2f41
#define MN_jp 0x2f49
#define MN_fmulp 0x2f4c
#define MN_cmp (MN_scmp + 1)
#define MN_scmp 0x2f52
#define MN_jmp (MN_ljmp + 1)
#define MN_ljmp 0x2f57
#define MN_fcomp 0x2f5c
#define MN_ficomp 0x2f62
#define MN_fucomp 0x2f69
#define MN_jnp 0x2f70
#define MN_setnp 0x2f74
#define MN_setzunp 0x2f7a
#define MN_cmovnp (MN_cfcmovnp + 2)
#define MN_cfcmovnp 0x2f82
#define MN_nop (MN_fnop + 1)
#define MN_fnop 0x2f8b
#define MN_loop 0x2f90
#define MN_pop 0x2f95
#define MN_fcompp 0x2f99
#define MN_fucompp 0x2fa0
#define MN_popp 0x2fa8
#define MN_fsubrp 0x2fad
#define MN_fdivrp 0x2fb4
#define MN_rstorssp 0x2fbb
#define MN_saveprevssp 0x2fc4
#define MN_setp 0x2fd0
#define MN_fbstp 0x2fd5
#define MN_fdecstp 0x2fdb
#define MN_fincstp 0x2fe3
#define MN_fstp 0x2feb
#define MN_fistp 0x2ff0
#define MN_fisttp 0x2ff6
#define MN_movddup (MN_vmovddup + 1)
#define MN_vmovddup 0x2ffd
#define MN_movshdup (MN_vmovshdup + 1)
#define MN_vmovshdup 0x3006
#define MN_movsldup (MN_vmovsldup + 1)
#define MN_vmovsldup 0x3010
#define MN_setzup 0x301a
#define MN_fdivp 0x3021
#define MN_cmovp (MN_cfcmovp + 2)
#define MN_cfcmovp 0x3027
#define MN_xmodexp 0x302f
#define MN_vpbroadcastmb2q 0x3037
#define MN_vpermi2q 0x3047
#define MN_vpmovm2q 0x3050
#define MN_movdq2q 0x3059
#define MN_vpermt2q 0x3061
#define MN_vpshaq 0x306a
#define MN_vpsraq 0x3071
#define MN_vphaddbq 0x3078
#define MN_vphaddubq 0x3081
#define MN_psubq (MN_vpsubq + 1)
#define MN_vpsubq 0x308b
#define MN_pmovsxbq (MN_vpmovsxbq + 1)
#define MN_vpmovsxbq 0x3092
#define MN_pmovzxbq (MN_vpmovzxbq + 1)
#define MN_vpmovzxbq 0x309c
#define MN_cvttpd2dq (MN_vcvttpd2dq + 1)
#define MN_vcvttpd2dq 0x30a6
#define MN_cvtpd2dq (MN_vcvtpd2dq + 1)
#define MN_vcvtpd2dq 0x30b1
#define MN_vcvttph2dq 0x30bb
#define MN_vcvtph2dq 0x30c6
#define MN_movq2dq 0x30d0
#define MN_cvttps2dq (MN_vcvttps2dq + 1)
#define MN_vcvttps2dq 0x30d8
#define MN_cvtps2dq (MN_vcvtps2dq + 1)
#define MN_vcvtps2dq 0x30e3
#define MN_vphsubdq 0x30ed
#define MN_cdq 0x30f6
#define MN_kaddq 0x30fa
#define MN_paddq (MN_vpaddq + 1)
#define MN_vpaddq 0x3100
#define MN_vphadddq 0x3107
#define MN_punpckhdq (MN_vpunpckhdq + 1)
#define MN_vpunpckhdq 0x3110
#define MN_kunpckdq 0x311b
#define MN_vpshldq 0x3124
#define MN_punpckldq (MN_vpunpckldq + 1)
#define MN_vpunpckldq 0x312c
#define MN_pslldq (MN_vpslldq + 1)
#define MN_vpslldq 0x3137
#define MN_psrldq (MN_vpsrldq + 1)
#define MN_vpsrldq 0x313f
#define MN_pmuldq (MN_vpmuldq + 1)
#define MN_vpmuldq 0x3147
#define MN_kandq 0x314f
#define MN_vpandq 0x3155
#define MN_vpexpandq 0x315c
#define MN_punpckhqdq (MN_vpunpckhqdq + 1)
#define MN_vpunpckhqdq 0x3166
#define MN_pclmulhqhqdq (MN_vpclmulhqhqdq + 1)
#define MN_vpclmulhqhqdq 0x3172
#define MN_pclmullqhqdq (MN_vpclmullqhqdq + 1)
#define MN_vpclmullqhqdq 0x3180
#define MN_punpcklqdq (MN_vpunpcklqdq + 1)
#define MN_vpunpcklqdq 0x318e
#define MN_pclmulhqlqdq (MN_vpclmulhqlqdq + 1)
#define MN_vpclmulhqlqdq 0x319a
#define MN_pclmullqlqdq (MN_vpclmullqlqdq + 1)
#define MN_vpclmullqlqdq 0x31a8
#define MN_pclmulqdq (MN_vpclmulqdq + 1)
#define MN_vpclmulqdq 0x31b6
#define MN_vpgatherdq 0x31c1
#define MN_vpscatterdq 0x31cc
#define MN_vpshrdq 0x31d8
#define MN_movntdq (MN_vmovntdq + 1)
#define MN_vmovntdq 0x31e0
#define MN_vcvttpd2udq 0x31e9
#define MN_vcvtpd2udq 0x31f5
#define MN_vcvttph2udq 0x3200
#define MN_vcvtph2udq 0x320c
#define MN_vcvttps2udq 0x3217
#define MN_vcvtps2udq 0x3223
#define MN_vphaddudq 0x322e
#define MN_pmuludq (MN_vpmuludq + 1)
#define MN_vpmuludq 0x3238
#define MN_pmovsxdq (MN_vpmovsxdq + 1)
#define MN_vpmovsxdq 0x3241
#define MN_pmovzxdq (MN_vpmovzxdq + 1)
#define MN_vpmovzxdq 0x324b
#define MN_vpcomgeq 0x3255
#define MN_vpcomleq 0x325e
#define MN_vpcmpnleq 0x3267
#define MN_vpcmpleq 0x3271
#define MN_pfcmpeq 0x327a
#define MN_vpcomfalseq 0x3282
#define MN_vpcomtrueq 0x328e
#define MN_vpternlogq 0x3299
#define MN_vpshlq 0x32a4
#define MN_psllq (MN_vpsllq + 1)
#define MN_vpsllq 0x32ab
#define MN_vpmullq 0x32b2
#define MN_vprolq 0x32ba
#define MN_psrlq (MN_vpsrlq + 1)
#define MN_vpsrlq 0x32c1
#define MN_kshiftlq 0x32c8
#define MN_vpblendmq 0x32d1
#define MN_vptestnmq 0x32db
#define MN_vpcomq 0x32e5
#define MN_vpermq 0x32ec
#define MN_vptestmq 0x32f3
#define MN_kandnq 0x32fc
#define MN_vpandnq 0x3303
#define MN_valignq 0x330b
#define MN_vpcmpq 0x3313
#define MN_incsspq 0x331a
#define MN_rdsspq 0x3322
#define MN_vcvttpd2qq 0x3329
#define MN_vcvtpd2qq 0x3334
#define MN_vcvttph2qq 0x333e
#define MN_vcvtph2qq 0x3349
#define MN_vcvttps2qq 0x3353
#define MN_vcvtps2qq 0x335e
#define MN_vpcomeqq 0x3368
#define MN_vpcomneqq 0x3371
#define MN_vpcmpneqq 0x337b
#define MN_pcmpeqq (MN_vpcmpeqq + 1)
#define MN_vpcmpeqq 0x3385
#define MN_vpgatherqq 0x338e
#define MN_vpscatterqq 0x3399
#define MN_vcvttpd2uqq 0x33a5
#define MN_vcvtpd2uqq 0x33b1
#define MN_vcvttph2uqq 0x33bc
#define MN_vcvtph2uqq 0x33c8
#define MN_vcvttps2uqq 0x33d3
#define MN_vcvtps2uqq 0x33df
#define MN_korq 0x33ea
#define MN_kxnorq 0x33ef
#define MN_vporq 0x33f6
#define MN_vprorq 0x33fc
#define MN_kxorq 0x3403
#define MN_vpxorq 0x3409
#define MN_pinsrq (MN_vpinsrq + 1)
#define MN_vpinsrq 0x3410
#define MN_kshiftrq 0x3418
#define MN_extrq (MN_pextrq + 1)
#define MN_pextrq (MN_vpextrq + 1)
#define MN_vpextrq 0x3421
#define MN_vpabsq 0x3429
#define MN_vpminsq 0x3430
#define MN_vmovrsq 0x3438
#define MN_vpcompressq 0x3440
#define MN_wrssq 0x344c
#define MN_wrussq 0x3452
#define MN_vpmaxsq 0x3459
#define MN_vp2intersectq 0x3461
#define MN_vpconflictq 0x346f
#define MN_vpcomgtq 0x347b
#define MN_pcmpgtq (MN_vpcmpgtq + 1)
#define MN_vpcmpgtq 0x3484
#define MN_cltq 0x348d
#define MN_vpcomltq 0x3492
#define MN_vpcmpnltq 0x349b
#define MN_vpcmpltq 0x34a5
#define MN_vpopcntq 0x34ae
#define MN_vplzcntq 0x34b7
#define MN_movntq 0x34c0
#define MN_knotq 0x34c7
#define MN_vprotq 0x34cd
#define MN_insertq 0x34d4
#define MN_vpbroadcastq 0x34dc
#define MN_ktestq 0x34e9
#define MN_kortestq 0x34f0
#define MN_vpcomgeuq 0x34f9
#define MN_vpcomleuq 0x3503
#define MN_vpcmpnleuq 0x350d
#define MN_vpcmpleuq 0x3518
#define MN_vpcomfalseuq 0x3522
#define MN_vpcomtrueuq 0x352f
#define MN_vpmadd52huq 0x353b
#define MN_vpmadd52luq 0x3547
#define MN_vpcomuq 0x3553
#define MN_vpminuq 0x355b
#define MN_vpcmpuq 0x3563
#define MN_vpcomequq 0x356b
#define MN_vpcomnequq 0x3575
#define MN_vpcmpnequq 0x3580
#define MN_vpcmpequq 0x358b
#define MN_vpcomgtuq 0x3595
#define MN_vpcomltuq 0x359f
#define MN_vpcmpnltuq 0x35a9
#define MN_vpcmpltuq 0x35b4
#define MN_vpmaxuq 0x35be
#define MN_vpsravq 0x35c6
#define MN_vpshldvq 0x35ce
#define MN_vpshrdvq 0x35d7
#define MN_vpsllvq 0x35e0
#define MN_vprolvq 0x35e8
#define MN_vpsrlvq 0x35f0
#define MN_movq (MN_kmovq + 1)
#define MN_kmovq (MN_maskmovq + 3)
#define MN_maskmovq (MN_vpmaskmovq + 2)
#define MN_vpmaskmovq 0x35f8
#define MN_vmovq 0x3603
#define MN_vprorvq 0x3609
#define MN_vphaddwq 0x3611
#define MN_vphadduwq 0x361a
#define MN_pmovsxwq (MN_vpmovsxwq + 1)
#define MN_vpmovsxwq 0x3624
#define MN_pmovzxwq (MN_vpmovzxwq + 1)
#define MN_vpmovzxwq 0x362e
#define MN_rex_r 0x3638
#define MN_vmclear 0x363e
#define MN_lar 0x3646
#define MN_sar 0x364a
#define MN_fsubr (MN_pfsubr + 1)
#define MN_pfsubr 0x364e
#define MN_fisubr 0x3655
#define MN_rcr 0x365c
#define MN_vzeroupper 0x3660
#define MN_enter (MN_sysenter + 3)
#define MN_sysenter 0x366b
#define MN_shr 0x3674
#define MN_clr 0x3678
#define MN_palignr (MN_vpalignr + 1)
#define MN_vpalignr 0x367c
#define MN_or (MN_aor + 1)
#define MN_aor 0x3685
#define MN_por (MN_vpor + 1)
#define MN_vpor 0x3689
#define MN_ror 0x368e
#define MN_monitor (MN_umonitor + 1)
#define MN_umonitor 0x3692
#define MN_frstor 0x369b
#define MN_xrstor (MN_fxrstor + 1)
#define MN_fxrstor 0x36a2
#define MN_xor (MN_axor + 1)
#define MN_axor 0x36aa
#define MN_pxor (MN_vpxor + 1)
#define MN_vpxor 0x36af
#define MN_verr 0x36b5
#define MN_bsr 0x36ba
#define MN_ldmxcsr (MN_vldmxcsr + 1)
#define MN_vldmxcsr 0x36be
#define MN_stmxcsr (MN_vstmxcsr + 1)
#define MN_vstmxcsr 0x36c7
#define MN_blsr 0x36d0
#define MN_rdmsr (MN_urdmsr + 1)
#define MN_urdmsr 0x36d5
#define MN_wrmsr (MN_uwrmsr + 1)
#define MN_uwrmsr 0x36dc
#define MN_btr 0x36e3
#define MN_xcrypt_ctr 0x36e7
#define MN_xcryptctr 0x36f2
#define MN_ltr 0x36fc
#define MN_str 0x3700
#define MN_bextr 0x3704
#define MN_fdivr 0x370a
#define MN_fidivr 0x3710
#define MN_rex_wr 0x3717
#define MN_vcvtbf82bf4s 0x371e
#define MN_vcvthf82bf4s 0x372b
#define MN_vcvtbf82bf6s 0x3738
#define MN_vcvthf82hf6s 0x3745
#define MN_vcvt2ph2bf8s 0x3752
#define MN_vcvtbiasph2bf8s 0x375f
#define MN_vcvtph2bf8s 0x376f
#define MN_vcvtbiasps2bf8s 0x377b
#define MN_vcvtps2bf8s 0x378b
#define MN_vcvt2ph2hf8s 0x3797
#define MN_vcvtbiasph2hf8s 0x37a4
#define MN_vcvtph2hf8s 0x37b4
#define MN_vcvtrops2hf8s 0x37c0
#define MN_vcvtbiasps2hf8s 0x37ce
#define MN_vcvtps2hf8s 0x37de
#define MN_aas 0x37ea
#define MN_scas 0x37ee
#define MN_das 0x37f3
#define MN_fabs 0x37f7
#define MN_jmpabs 0x37fc
#define MN_movabs 0x3803
#define MN_vcvttbf162ibs 0x380a
#define MN_vcvtbf162ibs 0x3818
#define MN_vcvttph2ibs 0x3825
#define MN_vcvtph2ibs 0x3831
#define MN_vcvttps2ibs 0x383c
#define MN_vcvtps2ibs 0x3848
#define MN_vcvttbf162iubs 0x3853
#define MN_vcvtbf162iubs 0x3862
#define MN_vcvttph2iubs 0x3870
#define MN_vcvtph2iubs 0x387d
#define MN_vcvttps2iubs 0x3889
#define MN_vcvtps2iubs 0x3896
#define MN_cs (MN_blcs + 2)
#define MN_blcs 0x38a2
#define MN_ds (MN_lds + 1)
#define MN_lds 0x38a7
#define MN_enqcmds 0x38ab
#define MN_lods 0x38b3
#define MN_vpdpbssds 0x38b8
#define MN_vp4dpwssds 0x38c2
#define MN_vpdpwssds 0x38cd
#define MN_vpdpbusds 0x38d7
#define MN_vpdpwusds 0x38e1
#define MN_vpdpbsuds 0x38eb
#define MN_vpdpwsuds 0x38f5
#define MN_vpdpbuuds 0x38ff
#define MN_vpdpwuuds 0x3909
#define MN_es (MN_les + 1)
#define MN_les 0x3913
#define MN_xsaves 0x3917
#define MN_fs (MN_lfs + 1)
#define MN_lfs 0x391e
#define MN_gs (MN_lkgs + 2)
#define MN_lkgs 0x3922
#define MN_lgs 0x3927
#define MN_swapgs 0x392b
#define MN_fchs 0x3932
#define MN_vcvttsd2sis 0x3937
#define MN_vcvttss2sis 0x3943
#define MN_vcvttsd2usis 0x394f
#define MN_vcvttss2usis 0x395c
#define MN_js 0x3969
#define MN_encls 0x396c
#define MN_emms (MN_femms + 1)
#define MN_femms 0x3972
#define MN_ins (MN_lwpins + 3)
#define MN_lwpins 0x3978
#define MN_jns 0x397f
#define MN_ccmpns 0x3983
#define MN_wrmsrns 0x398a
#define MN_setns 0x3992
#define MN_ctestns 0x3998
#define MN_setzuns 0x39a0
#define MN_cmovns (MN_cfcmovns + 2)
#define MN_cfcmovns 0x39a8
#define MN_fcos 0x39b1
#define MN_fsincos 0x39b6
#define MN_stos 0x39be
#define MN_vfmaddsub231ps 0x39c3
#define MN_vfmsub231ps 0x39d2
#define MN_vfnmsub231ps 0x39de
#define MN_vfmsubadd231ps 0x39eb
#define MN_vfmadd231ps 0x39fa
#define MN_vfnmadd231ps 0x3a06
#define MN_vfmaddsub132ps 0x3a13
#define MN_vfmsub132ps 0x3a22
#define MN_vfnmsub132ps 0x3a2e
#define MN_vfmsubadd132ps 0x3a3b
#define MN_vfmadd132ps 0x3a4a
#define MN_vfnmadd132ps 0x3a56
#define MN_tmmultf32ps (MN_ttmmultf32ps + 1)
#define MN_ttmmultf32ps 0x3a63
#define MN_vcvtneebf162ps 0x3a70
#define MN_vbcstnebf162ps 0x3a7f
#define MN_vcvtneobf162ps 0x3a8e
#define MN_vcvtbf82ps 0x3a9d
#define MN_vcvthf82ps 0x3aa8
#define MN_cvtpd2ps (MN_vcvtpd2ps + 1)
#define MN_vcvtpd2ps 0x3ab3
#define MN_tcvtrowd2ps 0x3abd
#define MN_vcvtneeph2ps 0x3ac9
#define MN_vcvtneoph2ps 0x3ad6
#define MN_vcvtph2ps 0x3ae3
#define MN_vbcstnesh2ps 0x3aed
#define MN_vpermi2ps 0x3afa
#define MN_cvtpi2ps 0x3b04
#define MN_vpermil2ps 0x3b0d
#define MN_vexp2ps 0x3b18
#define MN_cvtdq2ps (MN_vcvtdq2ps + 1)
#define MN_vcvtdq2ps 0x3b20
#define MN_vcvtudq2ps 0x3b2a
#define MN_vcvtqq2ps 0x3b35
#define MN_vcvtuqq2ps 0x3b3f
#define MN_vpermt2ps 0x3b4a
#define MN_vfmaddsub213ps 0x3b54
#define MN_vfmsub213ps 0x3b63
#define MN_vfnmsub213ps 0x3b6f
#define MN_vfmsubadd213ps 0x3b7c
#define MN_vfmadd213ps 0x3b8b
#define MN_vfnmadd213ps 0x3b97
#define MN_vrcp14ps 0x3ba4
#define MN_vrsqrt14ps 0x3bad
#define MN_tdpbf16ps (MN_ttdpbf16ps + 1)
#define MN_ttdpbf16ps 0x3bb8
#define MN_vdpbf16ps 0x3bc3
#define MN_tcmmrlfp16ps (MN_ttcmmrlfp16ps + 1)
#define MN_ttcmmrlfp16ps 0x3bcd
#define MN_tcmmimfp16ps (MN_tconjtcmmimfp16ps + 5)
#define MN_tconjtcmmimfp16ps 0x3bdb
#define MN_ttcmmimfp16ps 0x3bed
#define MN_tdpfp16ps (MN_ttdpfp16ps + 1)
#define MN_ttdpfp16ps 0x3bfb
#define MN_vrcp28ps 0x3c06
#define MN_vrsqrt28ps 0x3c0f
#define MN_tdphbf8ps 0x3c1a
#define MN_tdpbf8ps 0x3c24
#define MN_tdpbhf8ps 0x3c2d
#define MN_tdphf8ps 0x3c37
#define MN_movaps (MN_vmovaps + 1)
#define MN_vmovaps 0x3c40
#define MN_subps (MN_addsubps + 3)
#define MN_addsubps (MN_vfmaddsubps + 3)
#define MN_vfmaddsubps 0x3c48
#define MN_vaddsubps 0x3c54
#define MN_hsubps (MN_vhsubps + 1)
#define MN_vhsubps 0x3c5e
#define MN_vfmsubps 0x3c66
#define MN_vfnmsubps 0x3c6f
#define MN_vsubps 0x3c79
#define MN_vgatherpf0dps 0x3c80
#define MN_vscatterpf0dps 0x3c8e
#define MN_vgatherpf1dps 0x3c9d
#define MN_vscatterpf1dps 0x3cab
#define MN_addps (MN_vfmsubaddps + 6)
#define MN_vfmsubaddps 0x3cba
#define MN_haddps (MN_vhaddps + 1)
#define MN_vhaddps 0x3cc6
#define MN_v4fmaddps 0x3cce
#define MN_vfmaddps 0x3cd8
#define MN_v4fnmaddps 0x3ce1
#define MN_vfnmaddps 0x3cec
#define MN_vaddps 0x3cf6
#define MN_andps (MN_vexpandps + 4)
#define MN_vexpandps 0x3cfd
#define MN_vandps 0x3d07
#define MN_blendps (MN_vblendps + 1)
#define MN_vblendps 0x3d0e
#define MN_roundps (MN_vroundps + 1)
#define MN_vroundps 0x3d17
#define MN_vgatherdps 0x3d20
#define MN_vscatterdps 0x3d2b
#define MN_cmpunordps (MN_vcmpunordps + 1)
#define MN_vcmpunordps 0x3d37
#define MN_cmpordps (MN_vcmpordps + 1)
#define MN_vcmpordps 0x3d43
#define MN_vreduceps 0x3d4d
#define MN_vrangeps 0x3d57
#define MN_vcmpngeps 0x3d60
#define MN_vcmpgeps 0x3d6a
#define MN_vrndscaleps 0x3d73
#define MN_cmpnleps (MN_vcmpnleps + 1)
#define MN_vcmpnleps 0x3d7f
#define MN_cmpleps (MN_vcmpleps + 1)
#define MN_vcmpleps 0x3d89
#define MN_vcmpfalseps 0x3d92
#define MN_vcmptrueps 0x3d9e
#define MN_vscalefps 0x3da9
#define MN_shufps (MN_vshufps + 1)
#define MN_vshufps 0x3db3
#define MN_unpckhps (MN_vunpckhps + 1)
#define MN_vunpckhps 0x3dbb
#define MN_movlhps (MN_vmovlhps + 1)
#define MN_vmovlhps 0x3dc5
#define MN_vdpphps 0x3dce
#define MN_movhps (MN_vmovhps + 1)
#define MN_vmovhps 0x3dd6
#define MN_movmskps (MN_vmovmskps + 1)
#define MN_vmovmskps 0x3dde
#define MN_movhlps (MN_vmovhlps + 1)
#define MN_vmovhlps 0x3de8
#define MN_vpermilps 0x3df1
#define MN_unpcklps (MN_vunpcklps + 1)
#define MN_vunpcklps 0x3dfb
#define MN_mulps (MN_vmulps + 1)
#define MN_vmulps 0x3e05
#define MN_movlps (MN_vmovlps + 1)
#define MN_vmovlps 0x3e0c
#define MN_cmps (MN_ccmps + 1)
#define MN_ccmps 0x3e14
#define MN_vblendmps 0x3e1a
#define MN_vfixupimmps 0x3e24
#define MN_vpermps 0x3e30
#define MN_andnps (MN_vandnps + 1)
#define MN_vandnps 0x3e38
#define MN_minps (MN_vminps + 1)
#define MN_vminps 0x3e40
#define MN_seamops 0x3e47
#define MN_rcpps (MN_vrcpps + 1)
#define MN_vrcpps 0x3e4f
#define MN_dpps (MN_vdpps + 1)
#define MN_vdpps 0x3e56
#define MN_cmpps (MN_vcmpps + 1)
#define MN_vcmpps 0x3e5c
#define MN_vgetexpps 0x3e63
#define MN_vgatherpf0qps 0x3e6d
#define MN_vscatterpf0qps 0x3e7b
#define MN_vgatherpf1qps 0x3e8a
#define MN_vscatterpf1qps 0x3e98
#define MN_vcmpunord_qps 0x3ea7
#define MN_vcmpord_qps 0x3eb5
#define MN_cmpneqps (MN_vcmpneqps + 1)
#define MN_vcmpneqps 0x3ec1
#define MN_cmpeqps (MN_vcmpeqps + 1)
#define MN_vcmpeqps 0x3ecb
#define MN_vcmpge_oqps 0x3ed4
#define MN_vcmple_oqps 0x3ee0
#define MN_vcmpfalse_oqps 0x3eec
#define MN_vcmpneq_oqps 0x3efb
#define MN_vcmpeq_oqps 0x3f08
#define MN_vcmpgt_oqps 0x3f14
#define MN_vcmplt_oqps 0x3f20
#define MN_vgatherqps 0x3f2c
#define MN_vscatterqps 0x3f37
#define MN_vcmpnge_uqps 0x3f43
#define MN_vcmpnle_uqps 0x3f50
#define MN_vcmptrue_uqps 0x3f5d
#define MN_vcmpneq_uqps 0x3f6b
#define MN_vcmpeq_uqps 0x3f78
#define MN_vcmpngt_uqps 0x3f84
#define MN_vcmpnlt_uqps 0x3f91
#define MN_orps (MN_vorps + 1)
#define MN_vorps 0x3f9e
#define MN_xorps (MN_vxorps + 1)
#define MN_vxorps 0x3fa4
#define MN_vcmpunord_sps 0x3fab
#define MN_vcmpord_sps 0x3fb9
#define MN_vcmpge_osps 0x3fc5
#define MN_vcmple_osps 0x3fd1
#define MN_vcmpfalse_osps 0x3fdd
#define MN_vcmpneq_osps 0x3fec
#define MN_vcmpeq_osps 0x3ff9
#define MN_vcmpgt_osps 0x4005
#define MN_vcmplt_osps 0x4011
#define MN_vfpclassps 0x401d
#define MN_vcompressps 0x4028
#define MN_vcmpnge_usps 0x4034
#define MN_vcmpnle_usps 0x4041
#define MN_vcmptrue_usps 0x404e
#define MN_vcmpneq_usps 0x405c
#define MN_vcmpeq_usps 0x4069
#define MN_vcmpngt_usps 0x4075
#define MN_vcmpnlt_usps 0x4082
#define MN_extractps (MN_vextractps + 1)
#define MN_vextractps 0x408f
#define MN_vcmpngtps 0x409a
#define MN_vcmpgtps 0x40a4
#define MN_cmpnltps (MN_vcmpnltps + 1)
#define MN_vcmpnltps 0x40ad
#define MN_cmpltps (MN_vcmpltps + 1)
#define MN_vcmpltps 0x40b7
#define MN_vgetmantps 0x40c0
#define MN_movntps (MN_vmovntps + 1)
#define MN_vmovntps 0x40cb
#define MN_insertps (MN_vinsertps + 1)
#define MN_vinsertps 0x40d4
#define MN_sqrtps (MN_rsqrtps + 1)
#define MN_rsqrtps (MN_vrsqrtps + 1)
#define MN_vrsqrtps 0x40de
#define MN_vsqrtps 0x40e7
#define MN_vtestps 0x40ef
#define MN_movups (MN_vmovups + 1)
#define MN_vmovups 0x40f7
#define MN_blendvps (MN_vblendvps + 1)
#define MN_vblendvps 0x40ff
#define MN_divps (MN_vdivps + 1)
#define MN_vdivps 0x4109
#define MN_vmaskmovps 0x4110
#define MN_maxps (MN_vminmaxps + 4)
#define MN_vminmaxps 0x411b
#define MN_vmaxps 0x4125
#define MN_vfrczps 0x412c
#define MN_vcvttpd2dqs 0x4134
#define MN_vcvttps2dqs 0x4140
#define MN_vcvttpd2udqs 0x414c
#define MN_vcvttps2udqs 0x4159
#define MN_vcvttpd2qqs 0x4166
#define MN_vcvttps2qqs 0x4172
#define MN_vcvttpd2uqqs 0x417e
#define MN_vcvttps2uqqs 0x418b
#define MN_t2rpntlvwz0rs 0x4198
#define MN_t2rpntlvwz1rs 0x41a6
#define MN_tileloaddrs 0x41b4
#define MN_xrstors 0x41c0
#define MN_movrs 0x41c8
#define MN_ss (MN_vfmsub231ss + 9)
#define MN_vfmsub231ss 0x41ce
#define MN_vfnmsub231ss 0x41da
#define MN_vfmadd231ss 0x41e7
#define MN_vfnmadd231ss 0x41f3
#define MN_vfmsub132ss 0x4200
#define MN_vfnmsub132ss 0x420c
#define MN_vfmadd132ss 0x4219
#define MN_vfnmadd132ss 0x4225
#define MN_cvtsd2ss (MN_vcvtsd2ss + 1)
#define MN_vcvtsd2ss 0x4232
#define MN_vcvtsh2ss 0x423c
#define MN_cvtsi2ss (MN_vcvtsi2ss + 1)
#define MN_vcvtsi2ss 0x4246
#define MN_vcvtusi2ss 0x4250
#define MN_vfmsub213ss 0x425b
#define MN_vfnmsub213ss 0x4267
#define MN_vfmadd213ss 0x4274
#define MN_vfnmadd213ss 0x4280
#define MN_vrcp14ss 0x428d
#define MN_vrsqrt14ss 0x4296
#define MN_vrcp28ss 0x42a1
#define MN_vrsqrt28ss 0x42aa
#define MN_subss (MN_vfmsubss + 3)
#define MN_vfmsubss 0x42b5
#define MN_vfnmsubss 0x42be
#define MN_vsubss 0x42c8
#define MN_addss (MN_v4fmaddss + 4)
#define MN_v4fmaddss 0x42cf
#define MN_vfmaddss 0x42d9
#define MN_v4fnmaddss 0x42e2
#define MN_vfnmaddss 0x42ed
#define MN_vaddss 0x42f7
#define MN_roundss (MN_vroundss + 1)
#define MN_vroundss 0x42fe
#define MN_cmpunordss (MN_vcmpunordss + 1)
#define MN_vcmpunordss 0x4307
#define MN_cmpordss (MN_vcmpordss + 1)
#define MN_vcmpordss 0x4313
#define MN_vreducess 0x431d
#define MN_vrangess 0x4327
#define MN_vcmpngess 0x4330
#define MN_vcmpgess 0x433a
#define MN_vrndscaless 0x4343
#define MN_cmpnless (MN_vcmpnless + 1)
#define MN_vcmpnless 0x434f
#define MN_cmpless (MN_vcmpless + 1)
#define MN_vcmpless 0x4359
#define MN_vcmpfalsess 0x4362
#define MN_vcmptruess 0x436e
#define MN_vscalefss 0x4379
#define MN_comiss (MN_ucomiss + 1)
#define MN_ucomiss (MN_vucomiss + 1)
#define MN_vucomiss 0x4383
#define MN_vcomiss 0x438c
#define MN_lss (MN_mulss + 2)
#define MN_mulss (MN_vmulss + 1)
#define MN_vmulss 0x4394
#define MN_vfixupimmss 0x439b
#define MN_minss (MN_vminss + 1)
#define MN_vminss 0x43a7
#define MN_rcpss (MN_vrcpss + 1)
#define MN_vrcpss 0x43ae
#define MN_cmpss (MN_vcmpss + 1)
#define MN_vcmpss 0x43b5
#define MN_vgetexpss 0x43bc
#define MN_vcmpunord_qss 0x43c6
#define MN_vcmpord_qss 0x43d4
#define MN_cmpneqss (MN_vcmpneqss + 1)
#define MN_vcmpneqss 0x43e0
#define MN_cmpeqss (MN_vcmpeqss + 1)
#define MN_vcmpeqss 0x43ea
#define MN_vcmpge_oqss 0x43f3
#define MN_vcmple_oqss 0x43ff
#define MN_vcmpfalse_oqss 0x440b
#define MN_vcmpneq_oqss 0x441a
#define MN_vcmpeq_oqss 0x4427
#define MN_vcmpgt_oqss 0x4433
#define MN_vcmplt_oqss 0x443f
#define MN_vcmpnge_uqss 0x444b
#define MN_vcmpnle_uqss 0x4458
#define MN_vcmptrue_uqss 0x4465
#define MN_vcmpneq_uqss 0x4473
#define MN_vcmpeq_uqss 0x4480
#define MN_vcmpngt_uqss 0x448c
#define MN_vcmpnlt_uqss 0x4499
#define MN_vcmpunord_sss 0x44a6
#define MN_vcmpord_sss 0x44b4
#define MN_vcmpge_osss 0x44c0
#define MN_vcmple_osss 0x44cc
#define MN_vcmpfalse_osss 0x44d8
#define MN_vcmpneq_osss 0x44e7
#define MN_vcmpeq_osss 0x44f4
#define MN_vcmpgt_osss 0x4500
#define MN_vcmplt_osss 0x450c
#define MN_vfpclassss 0x4518
#define MN_vcmpnge_usss 0x4523
#define MN_vcmpnle_usss 0x4530
#define MN_vcmptrue_usss 0x453d
#define MN_vcmpneq_usss 0x454b
#define MN_vcmpeq_usss 0x4558
#define MN_vcmpngt_usss 0x4564
#define MN_vcmpnlt_usss 0x4571
#define MN_vcmpngtss 0x457e
#define MN_vcmpgtss 0x4588
#define MN_cmpnltss (MN_vcmpnltss + 1)
#define MN_vcmpnltss 0x4591
#define MN_cmpltss (MN_vcmpltss + 1)
#define MN_vcmpltss 0x459b
#define MN_vgetmantss 0x45a4
#define MN_movntss 0x45af
#define MN_sqrtss (MN_rsqrtss + 1)
#define MN_rsqrtss (MN_vrsqrtss + 1)
#define MN_vrsqrtss 0x45b7
#define MN_vsqrtss 0x45c0
#define MN_vbroadcastss 0x45c8
#define MN_divss (MN_vdivss + 1)
#define MN_vdivss 0x45d5
#define MN_movss (MN_vmovss + 1)
#define MN_vmovss 0x45dc
#define MN_maxss (MN_vminmaxss + 4)
#define MN_vminmaxss 0x45e3
#define MN_vmaxss 0x45ed
#define MN_vucomxss 0x45f4
#define MN_vcomxss 0x45fd
#define MN_vfrczss 0x4605
#define MN_bts 0x460d
#define MN_erets 0x4611
#define MN_sets 0x4617
#define MN_clts 0x461c
#define MN_ctests 0x4621
#define MN_outs 0x4628
#define MN_setzus 0x462d
#define MN_movs (MN_cmovs + 1)
#define MN_cmovs (MN_cfcmovs + 2)
#define MN_cfcmovs 0x4634
#define MN_fldl2t 0x463c
#define MN_xlat 0x4643
#define MN_bt 0x4648
#define MN_fxtract 0x464b
#define MN_lgdt 0x4653
#define MN_sgdt 0x4658
#define MN_lidt 0x465d
#define MN_sidt 0x4662
#define MN_fldt 0x4667
#define MN_lldt 0x466c
#define MN_sldt 0x4671
#define MN_ret (MN_iret + 1)
#define MN_iret (MN_uiret + 1)
#define MN_uiret 0x4676
#define MN_lret 0x467c
#define MN_seamret 0x4681
#define MN_sysret 0x4689
#define MN_hreset 0x4690
#define MN_pfcmpgt 0x4697
#define MN_ht 0x469f
#define MN_wait (MN_fwait + 1)
#define MN_fwait 0x46a2
#define MN_mwait (MN_umwait + 1)
#define MN_umwait 0x46a8
#define MN_mcommit 0x46af
#define MN_finit 0x46b7
#define MN_skinit 0x46bd
#define MN_fninit 0x46c4
#define MN_vmgexit 0x46cb
#define MN_sysexit 0x46d3
#define MN_hlt 0x46db
#define MN_popcnt 0x46df
#define MN_lzcnt 0x46e6
#define MN_tzcnt 0x46ec
#define MN_hnt 0x46f2
#define MN_int (MN_frndint + 4)
#define MN_frndint 0x46f6
#define MN_not 0x46fe
#define MN_invept 0x4702
#define MN_ccmpt 0x4709
#define MN_xsaveopt 0x470f
#define MN_clflushopt 0x4718
#define MN_fstpt 0x4723
#define MN_xabort 0x4729
#define MN_fsqrt 0x4730
#define MN_pfrsqrt 0x4736
#define MN_aesdeclast (MN_vaesdeclast + 1)
#define MN_vaesdeclast 0x473e
#define MN_aesenclast (MN_vaesenclast + 1)
#define MN_vaesenclast 0x474a
#define MN_test (MN_ptest + 1)
#define MN_ptest (MN_vptest + 1)
#define MN_vptest 0x4756
#define MN_xtest 0x475d
#define MN_fst 0x4763
#define MN_fist 0x4767
#define MN_rdmsrlist 0x476c
#define MN_wrmsrlist 0x4776
#define MN_aeskeygenassist (MN_vaeskeygenassist + 1)
#define MN_vaeskeygenassist 0x4780
#define MN_vmptrst 0x4791
#define MN_ftst 0x4799
#define MN_rmpadjust 0x479e
#define MN_ctestt 0x47a8
#define MN_out 0x47af
#define MN_pext 0x47b3
#define MN_bndcu 0x47b8
#define MN_enclu 0x47be
#define MN_fcmovnu 0x47c4
#define MN_lddqu (MN_vlddqu + 1)
#define MN_vlddqu 0x47cc
#define MN_movdqu (MN_maskmovdqu + 4)
#define MN_maskmovdqu (MN_vmaskmovdqu + 1)
#define MN_vmaskmovdqu 0x47d3
#define MN_vmovdqu 0x47df
#define MN_rdpkru 0x47e7
#define MN_wrpkru 0x47ee
#define MN_rdpru 0x47f5
#define MN_eretu 0x47fb
#define MN_fcmovu 0x4801
#define MN_imulzu 0x4808
#define MN_xgetbv 0x480f
#define MN_xsetbv 0x4816
#define MN_div (MN_fdiv + 1)
#define MN_fdiv 0x481d
#define MN_idiv (MN_fidiv + 1)
#define MN_fidiv 0x4822
#define MN_enclv 0x4828
#define MN_fldenv 0x482e
#define MN_fstenv 0x4835
#define MN_fnstenv 0x483c
#define MN_mov (MN_vpcmov + 3)
#define MN_vpcmov 0x4844
#define MN_bndmov 0x484b
#define MN_smov 0x4852
#define MN_rex_w 0x4857
#define MN_vcvttph2w 0x485d
#define MN_vcvtph2w 0x4867
#define MN_vpermi2w 0x4870
#define MN_vpmovm2w 0x4879
#define MN_vpermt2w 0x4882
#define MN_vpshaw 0x488b
#define MN_psraw (MN_vpsraw + 1)
#define MN_vpsraw 0x4892
#define MN_vphsubbw 0x4899
#define MN_cbw 0x48a2
#define MN_psadbw (MN_vdbpsadbw + 3)
#define MN_vdbpsadbw 0x48a6
#define MN_mpsadbw (MN_vmpsadbw + 1)
#define MN_vmpsadbw 0x48b0
#define MN_vpsadbw 0x48b9
#define MN_vphaddbw 0x48c1
#define MN_punpckhbw (MN_vpunpckhbw + 1)
#define MN_vpunpckhbw 0x48ca
#define MN_kunpckbw 0x48d5
#define MN_punpcklbw (MN_vpunpcklbw + 1)
#define MN_vpunpcklbw 0x48de
#define MN_vphaddubw 0x48e9
#define MN_phsubw (MN_vphsubw + 1)
#define MN_vphsubw 0x48f3
#define MN_psubw (MN_vpsubw + 1)
#define MN_vpsubw 0x48fb
#define MN_pmovsxbw (MN_vpmovsxbw + 1)
#define MN_vpmovsxbw 0x4902
#define MN_pmovzxbw (MN_vpmovzxbw + 1)
#define MN_vpmovzxbw 0x490c
#define MN_fldcw 0x4916
#define MN_fstcw 0x491c
#define MN_fnstcw 0x4922
#define MN_phaddw (MN_vphaddw + 1)
#define MN_vphaddw 0x4929
#define MN_kaddw 0x4931
#define MN_paddw (MN_vpaddw + 1)
#define MN_vpaddw 0x4937
#define MN_vpshldw 0x493e
#define MN_kandw 0x4946
#define MN_vpexpandw 0x494c
#define MN_pblendw (MN_vpblendw + 1)
#define MN_vpblendw 0x4956
#define MN_vpshrdw 0x495f
#define MN_packssdw (MN_vpackssdw + 1)
#define MN_vpackssdw 0x4967
#define MN_packusdw (MN_vpackusdw + 1)
#define MN_vpackusdw 0x4971
#define MN_vpmovusdw 0x497b
#define MN_vpmovsdw 0x4985
#define MN_vpmovdw 0x498e
#define MN_vpcomgew 0x4996
#define MN_vpcomlew 0x499f
#define MN_vpcmpnlew 0x49a8
#define MN_vpcmplew 0x49b2
#define MN_vpcomfalsew 0x49bb
#define MN_vpcomtruew 0x49c7
#define MN_pi2fw 0x49d2
#define MN_pshufw 0x49d8
#define MN_pavgw (MN_vpavgw + 1)
#define MN_vpavgw 0x49df
#define MN_prefetchw 0x49e6
#define MN_pshufhw (MN_vpshufhw + 1)
#define MN_vpshufhw 0x49f0
#define MN_pmulhw (MN_vpmulhw + 1)
#define MN_vpmulhw 0x49f9
#define MN_pf2iw 0x4a01
#define MN_pshuflw (MN_vpshuflw + 1)
#define MN_vpshuflw 0x4a07
#define MN_vpshlw 0x4a10
#define MN_psllw (MN_vpsllw + 1)
#define MN_vpsllw 0x4a17
#define MN_pmullw (MN_vpmullw + 1)
#define MN_vpmullw 0x4a1e
#define MN_psrlw (MN_vpsrlw + 1)
#define MN_vpsrlw 0x4a26
#define MN_kshiftlw 0x4a2d
#define MN_vpblendmw 0x4a36
#define MN_vptestnmw 0x4a40
#define MN_vpcomw 0x4a4a
#define MN_vpermw 0x4a51
#define MN_vptestmw 0x4a58
#define MN_kandnw 0x4a61
#define MN_psignw (MN_vpsignw + 1)
#define MN_vpsignw 0x4a68
#define MN_tilemovrow 0x4a70
#define MN_vpcmpw 0x4a7b
#define MN_vpcomeqw 0x4a82
#define MN_vpcomneqw 0x4a8b
#define MN_vpcmpneqw 0x4a95
#define MN_pcmpeqw (MN_vpcmpeqw + 1)
#define MN_vpcmpeqw 0x4a9f
#define MN_vpmovusqw 0x4aa8
#define MN_vpmovsqw 0x4ab2
#define MN_vpmovqw 0x4abb
#define MN_verw 0x4ac3
#define MN_pmulhrw 0x4ac8
#define MN_korw 0x4ad0
#define MN_kxnorw 0x4ad5
#define MN_kxorw 0x4adc
#define MN_pinsrw (MN_vpinsrw + 1)
#define MN_vpinsrw 0x4ae2
#define MN_kshiftrw 0x4aea
#define MN_pextrw (MN_vpextrw + 1)
#define MN_vpextrw 0x4af3
#define MN_pabsw (MN_vpabsw + 1)
#define MN_vpabsw 0x4afb
#define MN_pmaddubsw (MN_vpmaddubsw + 1)
#define MN_vpmaddubsw 0x4b02
#define MN_phsubsw (MN_vphsubsw + 1)
#define MN_vphsubsw 0x4b0d
#define MN_psubsw (MN_vpsubsw + 1)
#define MN_vpsubsw 0x4b16
#define MN_phaddsw (MN_vphaddsw + 1)
#define MN_vphaddsw 0x4b1e
#define MN_paddsw (MN_vpaddsw + 1)
#define MN_vpaddsw 0x4b27
#define MN_lmsw 0x4b2f
#define MN_smsw 0x4b34
#define MN_pminsw (MN_vpminsw + 1)
#define MN_vpminsw 0x4b39
#define MN_pmulhrsw (MN_vpmulhrsw + 1)
#define MN_vpmulhrsw 0x4b41
#define MN_vmovrsw 0x4b4b
#define MN_vpcompressw 0x4b53
#define MN_fstsw 0x4b5f
#define MN_fnstsw 0x4b65
#define MN_psubusw (MN_vpsubusw + 1)
#define MN_vpsubusw 0x4b6c
#define MN_paddusw (MN_vpaddusw + 1)
#define MN_vpaddusw 0x4b75
#define MN_movsw 0x4b7e
#define MN_pmaxsw (MN_vpmaxsw + 1)
#define MN_vpmaxsw 0x4b84
#define MN_cbtw 0x4b8c
#define MN_vpcomgtw 0x4b91
#define MN_pcmpgtw (MN_vpcmpgtw + 1)
#define MN_vpcmpgtw 0x4b9a
#define MN_vpcomltw 0x4ba3
#define MN_vpcmpnltw 0x4bac
#define MN_vpcmpltw 0x4bb6
#define MN_vpopcntw 0x4bbf
#define MN_knotw 0x4bc8
#define MN_vprotw 0x4bce
#define MN_vpbroadcastw 0x4bd5
#define MN_ktestw 0x4be2
#define MN_kortestw 0x4be9
#define MN_vcvttph2uw 0x4bf2
#define MN_vcvtph2uw 0x4bfd
#define MN_vpcomgeuw 0x4c07
#define MN_vpcomleuw 0x4c11
#define MN_vpcmpnleuw 0x4c1b
#define MN_vpcmpleuw 0x4c26
#define MN_vpcomfalseuw 0x4c30
#define MN_vpcomtrueuw 0x4c3d
#define MN_pmulhuw (MN_vpmulhuw + 1)
#define MN_vpmulhuw 0x4c49
#define MN_vpcomuw 0x4c52
#define MN_pminuw (MN_vpminuw + 1)
#define MN_vpminuw 0x4c5a
#define MN_vpcmpuw 0x4c62
#define MN_vpcomequw 0x4c6a
#define MN_vpcomnequw 0x4c74
#define MN_vpcmpnequw 0x4c7f
#define MN_vpcmpequw 0x4c8a
#define MN_phminposuw (MN_vphminposuw + 1)
#define MN_vphminposuw 0x4c94
#define MN_vpcomgtuw 0x4ca0
#define MN_vpcomltuw 0x4caa
#define MN_vpcmpnltuw 0x4cb4
#define MN_vpcmpltuw 0x4cbf
#define MN_pmaxuw (MN_vpmaxuw + 1)
#define MN_vpmaxuw 0x4cc9
#define MN_vpsravw 0x4cd1
#define MN_vpshldvw 0x4cd9
#define MN_vpshrdvw 0x4ce2
#define MN_vpsllvw 0x4ceb
#define MN_vpsrlvw 0x4cf3
#define MN_kmovw 0x4cfb
#define MN_vmovw 0x4d01
#define MN_vpmacsww 0x4d07
#define MN_vpmacssww 0x4d10
#define MN_movzw 0x4d1a
#define MN_rex_x 0x4d20
#define MN_fyl2x 0x4d26
#define MN_rex64x 0x4d2c
#define MN_vcvtneps2bf16x 0x4d33
#define MN_vfpclassbf16x 0x4d42
#define MN_vcvtph2bf8x 0x4d50
#define MN_vcvtps2bf8x 0x4d5c
#define MN_vcvtph2hf8x 0x4d68
#define MN_vcvtrops2hf8x 0x4d74
#define MN_vcvtps2hf8x 0x4d82
#define MN_pfmax 0x4d8e
#define MN_adcx 0x4d94
#define MN_bndldx 0x4d99
#define MN_vfpclasspdx 0x4da0
#define MN_fclex 0x4dac
#define MN_fnclex 0x4db2
#define MN_rex 0x4db9
#define MN_vcvtpd2phx 0x4dbd
#define MN_vcvtdq2phx 0x4dc8
#define MN_vcvtudq2phx 0x4dd3
#define MN_vcvtqq2phx 0x4ddf
#define MN_vcvtuqq2phx 0x4dea
#define MN_vcvt2ps2phx 0x4df6
#define MN_vcvtps2phx 0x4e02
#define MN_vfpclassphx 0x4e0d
#define MN_shlx 0x4e19
#define MN_mulx 0x4e1e
#define MN_adox 0x4e23
#define MN_vcvttpd2dqx 0x4e28
#define MN_vcvtpd2dqx 0x4e34
#define MN_vcvttpd2udqx 0x4e3f
#define MN_vcvtpd2udqx 0x4e4c
#define MN_rex_rx 0x4e58
#define MN_sarx 0x4e5f
#define MN_shrx 0x4e64
#define MN_rorx 0x4e69
#define MN_monitorx 0x4e6e
#define MN_rex_wrx 0x4e77
#define MN_vcvtph2bf8sx 0x4e7f
#define MN_vcvtps2bf8sx 0x4e8c
#define MN_vcvtph2hf8sx 0x4e99
#define MN_vcvtrops2hf8sx 0x4ea6
#define MN_vcvtps2hf8sx 0x4eb5
#define MN_vcvtpd2psx 0x4ec2
#define MN_vcvtph2psx 0x4ecd
#define MN_vcvtqq2psx 0x4ed8
#define MN_vcvtuqq2psx 0x4ee3
#define MN_vfpclasspsx 0x4eef
#define MN_vcvttpd2dqsx 0x4efb
#define MN_vcvttpd2udqsx 0x4f08
#define MN_movsx 0x4f16
#define MN_mwaitx 0x4f1c
#define MN_bndstx 0x4f23
#define MN_rex_wx 0x4f2a
#define MN_rexx 0x4f31
#define MN_vcvtps2phxx 0x4f36
#define MN_movzx 0x4f42
#define MN_rex64y 0x4f48
#define MN_vcvtneps2bf16y 0x4f4f
#define MN_vfpclassbf16y 0x4f5e
#define MN_vcvtph2bf8y 0x4f6c
#define MN_vcvtps2bf8y 0x4f78
#define MN_vcvtph2hf8y 0x4f84
#define MN_vcvtrops2hf8y 0x4f90
#define MN_vcvtps2hf8y 0x4f9e
#define MN_vfpclasspdy 0x4faa
#define MN_loadiwkey 0x4fb6
#define MN_vcvtpd2phy 0x4fc0
#define MN_vcvtdq2phy 0x4fcb
#define MN_vcvtudq2phy 0x4fd6
#define MN_vcvtqq2phy 0x4fe2
#define MN_vcvtuqq2phy 0x4fed
#define MN_vfpclassphy 0x4ff9
#define MN_vcvttpd2dqy 0x5005
#define MN_vcvtpd2dqy 0x5011
#define MN_vcvttpd2udqy 0x501c
#define MN_vcvtpd2udqy 0x5029
#define MN_rmpquery 0x5035
#define MN_vcvtph2bf8sy 0x503e
#define MN_vcvtps2bf8sy 0x504b
#define MN_vcvtph2hf8sy 0x5058
#define MN_vcvtrops2hf8sy 0x5065
#define MN_vcvtps2hf8sy 0x5074
#define MN_clrssbsy 0x5081
#define MN_setssbsy 0x508a
#define MN_vcvtpd2psy 0x5093
#define MN_vcvtqq2psy 0x509e
#define MN_vcvtuqq2psy 0x50a9
#define MN_vfpclasspsy 0x50b5
#define MN_vcvttpd2dqsy 0x50c1
#define MN_vcvttpd2udqsy 0x50ce
#define MN_rex64xy 0x50dc
#define MN_rexy 0x50e4
#define MN_vcvtps2phxy 0x50e9
#define MN_rexxy 0x50f5
#define MN_rex64z 0x50fb
#define MN_vfpclassbf16z 0x5102
#define MN_vcvtps2bf8z 0x5110
#define MN_vcvtrops2hf8z 0x511c
#define MN_vcvtps2hf8z 0x512a
#define MN_fldz 0x5136
#define MN_vfpclasspdz 0x513b
#define MN_vcvtpd2phz 0x5147
#define MN_vcvtqq2phz 0x5152
#define MN_vcvtuqq2phz 0x515d
#define MN_vfpclassphz 0x5169
#define MN_jz 0x5175
#define MN_jnz 0x5178
#define MN_repnz 0x517c
#define MN_ccmpnz 0x5182
#define MN_loopnz 0x5189
#define MN_setnz 0x5190
#define MN_ctestnz 0x5196
#define MN_setzunz 0x519e
#define MN_cmovnz (MN_cfcmovnz + 2)
#define MN_cfcmovnz 0x51a6
#define MN_repz 0x51af
#define MN_ccmpz 0x51b4
#define MN_loopz 0x51ba
#define MN_vcvtps2bf8sz 0x51c0
#define MN_vcvtrops2hf8sz 0x51cd
#define MN_vcvtps2hf8sz 0x51dc
#define MN_vfpclasspsz 0x51e9
#define MN_setz 0x51f5
#define MN_ctestz 0x51fa
#define MN_setzuz 0x5201
#define MN_cmovz (MN_cfcmovz + 2)
#define MN_cfcmovz 0x5208
#define MN_rex64xz 0x5210
#define MN_jecxz 0x5218
#define MN_jcxz 0x521e
#define MN_jrcxz 0x5223
#define MN_rexz 0x5229
#define MN_rexxz 0x522e
#define MN_rex64yz 0x5234
#define MN_rex64xyz 0x523c
#define MN_rexyz 0x5245
#define MN_rexxyz 0x524b
#define MN__disp32_ 0x5252
#define MN__rex2_ 0x525b
#define MN__vex2_ 0x5262
#define MN__vex3_ 0x5269
#define MN__disp16_ 0x5270
#define MN__disp8_ 0x5279
#define MN__load_ 0x5281
#define MN__store_ 0x5288
#define MN__nooptimize_ 0x5290
#define MN__nf_ 0x529d
#define MN__noimm8s_ 0x52a2
#define MN__rex_ 0x52ac
#define MN__evex_ 0x52b2
#define MN__vex_ 0x52b9
#define MN__insn 0x52bf

#define OPREF_4_0 10
#define OPREF_4_4 14
#define OPREF_4_8 18
#define OPREF_4_12 1
#define OPREF_4_16 5
#define OPREF_4_20 22
#define OPREF_4_24 26
#define OPREF_4_28 30
#define OPREF_4_32 34
#define OPREF_4_36 38
#define OPREF_4_40 42
#define OPREF_4_44 46
#define OPREF_4_48 50
#define OPREF_4_52 54
#define OPREF_4_56 58
#define OPREF_4_60 62
#define OPREF_4_64 66
#define OPREF_4_68 70
#define OPREF_4_72 74
#define OPREF_4_76 78
#define OPREF_4_80 82
#define OPREF_4_84 86
#define OPREF_4_88 90
#define OPREF_4_92 94
#define OPREF_4_96 6
#define OPREF_4_100 98
#define OPREF_4_104 102
#define OPREF_4_108 106
#define OPREF_4_112 110
#define OPREF_4_116 114
#define OPREF_4_120 118
#define OPREF_4_124 122
#define OPREF_4_128 126
#define OPREF_4_132 130
#define OPREF_4_136 134
#define OPREF_4_140 138
#define OPREF_4_144 142
#define OPREF_4_148 146
#define OPREF_4_152 150
#define OPREF_4_156 154
#define OPREF_4_160 158
#define OPREF_4_164 162
#define OPREF_3_0 166
#define OPREF_3_3 169
#define OPREF_3_6 172
#define OPREF_3_9 175
#define OPREF_3_12 178
#define OPREF_3_15 181
#define OPREF_3_18 184
#define OPREF_3_21 187
#define OPREF_3_24 190
#define OPREF_3_27 193
#define OPREF_3_30 196
#define OPREF_3_33 199
#define OPREF_3_36 202
#define OPREF_3_39 205
#define OPREF_3_42 10
#define OPREF_3_45 208
#define OPREF_3_48 14
#define OPREF_3_51 106
#define OPREF_3_54 30
#define OPREF_3_57 211
#define OPREF_3_60 214
#define OPREF_3_63 217
#define OPREF_3_66 62
#define OPREF_3_69 78
#define OPREF_3_72 220
#define OPREF_3_75 223
#define OPREF_3_78 226
#define OPREF_3_81 46
#define OPREF_3_84 38
#define OPREF_3_87 229
#define OPREF_3_90 232
#define OPREF_3_93 235
#define OPREF_3_96 238
#define OPREF_3_99 241
#define OPREF_3_102 244
#define OPREF_3_105 247
#define OPREF_3_108 250
#define OPREF_3_111 66
#define OPREF_3_114 70
#define OPREF_3_117 74
#define OPREF_3_120 253
#define OPREF_3_123 2
#define OPREF_3_126 83
#define OPREF_3_129 87
#define OPREF_3_132 31
#define OPREF_3_135 39
#define OPREF_3_138 23
#define OPREF_3_141 27
#define OPREF_3_144 35
#define OPREF_3_147 43
#define OPREF_3_150 256
#define OPREF_3_153 71
#define OPREF_3_156 259
#define OPREF_3_159 262
#define OPREF_3_162 265
#define OPREF_3_165 268
#define OPREF_3_168 99
#define OPREF_3_171 271
#define OPREF_3_174 55
#define OPREF_3_177 151
#define OPREF_3_180 82
#define OPREF_3_183 18
#define OPREF_3_186 86
#define OPREF_3_189 90
#define OPREF_3_192 274
#define OPREF_3_195 264
#define OPREF_3_198 277
#define OPREF_3_201 22
#define OPREF_3_204 26
#define OPREF_3_207 54
#define OPREF_3_210 5
#define OPREF_3_213 143
#define OPREF_3_216 146
#define OPREF_3_219 147
#define OPREF_3_222 280
#define OPREF_3_225 283
#define OPREF_3_228 286
#define OPREF_3_231 289
#define OPREF_3_234 292
#define OPREF_3_237 47
#define OPREF_3_240 295
#define OPREF_3_243 298
#define OPREF_3_246 163
#define OPREF_3_249 131
#define OPREF_3_252 301
#define OPREF_3_255 304
#define OPREF_3_258 307
#define OPREF_3_261 110
#define OPREF_3_264 310
#define OPREF_3_267 313
#define OPREF_3_270 114
#define OPREF_3_273 316
#define OPREF_3_276 319
#define OPREF_3_279 322
#define OPREF_3_282 325
#define OPREF_3_285 328
#define OPREF_3_288 154
#define OPREF_3_291 331
#define OPREF_3_294 334
#define OPREF_3_297 337
#define OPREF_3_300 340
#define OPREF_3_303 343
#define OPREF_3_306 346
#define OPREF_3_309 349
#define OPREF_3_312 352
#define OPREF_3_315 355
#define OPREF_3_318 358
#define OPREF_3_321 361
#define OPREF_3_324 364
#define OPREF_3_327 367
#define OPREF_3_330 370
#define OPREF_3_333 373
#define OPREF_3_336 376
#define OPREF_3_339 379
#define OPREF_3_342 382
#define OPREF_3_345 385
#define OPREF_3_348 155
#define OPREF_3_351 159
#define OPREF_3_354 388
#define OPREF_3_357 391
#define OPREF_3_360 394
#define OPREF_3_363 397
#define OPREF_3_366 400
#define OPREF_3_369 403
#define OPREF_3_372 406
#define OPREF_3_375 409
#define OPREF_3_378 412
#define OPREF_3_381 415
#define OPREF_3_384 418
#define OPREF_3_387 421
#define OPREF_2_0 424
#define OPREF_2_2 426
#define OPREF_2_4 428
#define OPREF_2_6 430
#define OPREF_2_8 432
#define OPREF_2_10 434
#define OPREF_2_12 436
#define OPREF_2_14 438
#define OPREF_2_16 437
#define OPREF_2_18 440
#define OPREF_2_20 442
#define OPREF_2_22 444
#define OPREF_2_24 446
#define OPREF_2_26 448
#define OPREF_2_28 450
#define OPREF_2_30 12
#define OPREF_2_32 452
#define OPREF_2_34 454
#define OPREF_2_36 456
#define OPREF_2_38 458
#define OPREF_2_40 460
#define OPREF_2_42 462
#define OPREF_2_44 188
#define OPREF_2_46 464
#define OPREF_2_48 466
#define OPREF_2_50 468
#define OPREF_2_52 467
#define OPREF_2_54 470
#define OPREF_2_56 472
#define OPREF_2_58 474
#define OPREF_2_60 166
#define OPREF_2_62 178
#define OPREF_2_64 169
#define OPREF_2_66 476
#define OPREF_2_68 172
#define OPREF_2_70 167
#define OPREF_2_72 179
#define OPREF_2_74 478
#define OPREF_2_76 480
#define OPREF_2_78 482
#define OPREF_2_80 484
#define OPREF_2_82 486
#define OPREF_2_84 488
#define OPREF_2_86 490
#define OPREF_2_88 193
#define OPREF_2_90 492
#define OPREF_2_92 196
#define OPREF_2_94 494
#define OPREF_2_96 199
#define OPREF_2_98 496
#define OPREF_2_100 202
#define OPREF_2_102 206
#define OPREF_2_104 498
#define OPREF_2_106 500
#define OPREF_2_108 502
#define OPREF_2_110 504
#define OPREF_2_112 506
#define OPREF_2_114 508
#define OPREF_2_116 510
#define OPREF_2_118 509
#define OPREF_2_120 512
#define OPREF_2_122 514
#define OPREF_2_124 516
#define OPREF_2_126 518
#define OPREF_2_128 176
#define OPREF_2_130 520
#define OPREF_2_132 522
#define OPREF_2_134 524
#define OPREF_2_136 526
#define OPREF_2_138 528
#define OPREF_2_140 71
#define OPREF_2_142 530
#define OPREF_2_144 532
#define OPREF_2_146 534
#define OPREF_2_148 39
#define OPREF_2_150 101
#define OPREF_2_152 75
#define OPREF_2_154 227
#define OPREF_2_156 536
#define OPREF_2_158 47
#define OPREF_2_160 115
#define OPREF_2_162 214
#define OPREF_2_164 538
#define OPREF_2_166 31
#define OPREF_2_168 540
#define OPREF_2_170 542
#define OPREF_2_172 544
#define OPREF_2_174 546
#define OPREF_2_176 548
#define OPREF_2_178 32
#define OPREF_2_180 271
#define OPREF_2_182 289
#define OPREF_2_184 212
#define OPREF_2_186 550
#define OPREF_2_188 552
#define OPREF_2_190 284
#define OPREF_2_192 215
#define OPREF_2_194 549
#define OPREF_2_196 554
#define OPREF_2_198 556
#define OPREF_2_200 558
#define OPREF_2_202 367
#define OPREF_2_204 370
#define OPREF_2_206 560
#define OPREF_2_208 562
#define OPREF_2_210 564
#define OPREF_2_212 566
#define OPREF_2_214 568
#define OPREF_2_216 570
#define OPREF_2_218 131
#define OPREF_2_220 572
#define OPREF_2_222 574
#define OPREF_2_224 576
#define OPREF_2_226 578
#define OPREF_2_228 293
#define OPREF_2_230 285
#define OPREF_2_232 580
#define OPREF_2_234 582
#define OPREF_2_236 584
#define OPREF_2_238 51
#define OPREF_2_240 586
#define OPREF_2_242 588
#define OPREF_2_244 590
#define OPREF_2_246 2
#define OPREF_2_248 23
#define OPREF_2_250 592
#define OPREF_2_252 282
#define OPREF_2_254 594
#define OPREF_2_256 596
#define OPREF_2_258 598
#define OPREF_2_260 600
#define OPREF_2_262 602
#define OPREF_2_264 268
#define OPREF_2_266 55
#define OPREF_2_268 245
#define OPREF_2_270 545
#define OPREF_2_272 59
#define OPREF_2_274 376
#define OPREF_2_276 604
#define OPREF_2_278 266
#define OPREF_2_280 606
#define OPREF_2_282 608
#define OPREF_2_284 610
#define OPREF_2_286 612
#define OPREF_2_288 614
#define OPREF_2_290 139
#define OPREF_2_292 27
#define OPREF_2_294 616
#define OPREF_2_296 618
#define OPREF_2_298 620
#define OPREF_2_300 622
#define OPREF_2_302 624
#define OPREF_2_304 626
#define OPREF_2_306 628
#define OPREF_2_308 630
#define OPREF_2_310 632
#define OPREF_2_312 281
#define OPREF_2_314 634
#define OPREF_2_316 287
#define OPREF_2_318 302
#define OPREF_2_320 229
#define OPREF_2_322 283
#define OPREF_2_324 316
#define OPREF_2_326 636
#define OPREF_2_328 638
#define OPREF_2_330 640
#define OPREF_2_332 642
#define OPREF_2_334 644
#define OPREF_2_336 52
#define OPREF_2_338 646
#define OPREF_2_340 648
#define OPREF_2_342 650
#define OPREF_2_344 652
#define OPREF_2_346 654
#define OPREF_2_348 322
#define OPREF_2_350 155
#define OPREF_2_352 656
#define OPREF_2_354 658
#define OPREF_2_356 660
#define OPREF_2_358 633
#define OPREF_2_360 286
#define OPREF_2_362 662
#define OPREF_2_364 270
#define OPREF_2_366 292
#define OPREF_2_368 664
#define OPREF_2_370 79
#define OPREF_2_372 666
#define OPREF_2_374 579
#define OPREF_2_376 299
#define OPREF_2_378 263
#define OPREF_2_380 613
#define OPREF_2_382 668
#define OPREF_2_384 670
#define OPREF_2_386 672
#define OPREF_2_388 674
#define OPREF_2_390 676
#define OPREF_2_392 678
#define OPREF_2_394 680
#define OPREF_2_396 682
#define OPREF_2_398 684
#define OPREF_2_400 686
#define OPREF_2_402 24
#define OPREF_2_404 688
#define OPREF_2_406 690
#define OPREF_2_408 692
#define OPREF_2_410 401
#define OPREF_2_412 694
#define OPREF_2_414 696
#define OPREF_2_416 698
#define OPREF_2_418 700
#define OPREF_2_420 702
#define OPREF_2_422 704
#define OPREF_2_424 706
#define OPREF_2_426 232
#define OPREF_2_428 708
#define OPREF_2_430 710
#define OPREF_2_432 712
#define OPREF_2_434 714
#define OPREF_2_436 379
#define OPREF_2_438 716
#define OPREF_2_440 718
#define OPREF_2_442 720
#define OPREF_2_444 722
#define OPREF_2_446 724
#define OPREF_2_448 726
#define OPREF_2_450 669
#define OPREF_2_452 728
#define OPREF_2_454 730
#define OPREF_2_456 732
#define OPREF_2_458 734
#define OPREF_2_460 736
#define OPREF_2_462 738
#define OPREF_2_464 740
#define OPREF_2_466 742
#define OPREF_2_468 744
#define OPREF_2_470 746
#define OPREF_2_472 748
#define OPREF_2_474 750
#define OPREF_2_476 752
#define OPREF_2_478 56
#define OPREF_2_480 754
#define OPREF_2_482 756
#define OPREF_1_0 63
#define OPREF_1_1 473
#define OPREF_1_2 758
#define OPREF_1_3 169
#define OPREF_1_4 499
#define OPREF_1_5 436
#define OPREF_1_6 759
#define OPREF_1_7 760
#define OPREF_1_8 761
#define OPREF_1_9 246
#define OPREF_1_10 0
#define OPREF_1_11 468
#define OPREF_1_12 166
#define OPREF_1_13 429
#define OPREF_1_14 167
#define OPREF_1_15 762
#define OPREF_1_16 763
#define OPREF_1_17 75
#define OPREF_1_18 764
#define OPREF_1_19 765
#define OPREF_1_20 694
#define OPREF_1_21 696
#define OPREF_1_22 766
#define OPREF_1_23 767
#define OPREF_1_24 434
#define OPREF_1_25 768
#define OPREF_1_26 190
#define OPREF_1_27 769
#define OPREF_1_28 452
#define OPREF_1_29 770
#define OPREF_1_30 771
#define OPREF_1_31 508
#define OPREF_1_32 502
#define OPREF_1_33 772
#define OPREF_1_34 179
#define OPREF_1_35 773
#define OPREF_1_36 774
#define OPREF_1_37 11
#define OPREF_1_38 79
#define OPREF_1_39 454
#define OPREF_1_40 522
#define OPREF_1_41 515
#define OPREF_1_42 775
#define OPREF_1_43 776
#define OPREF_1_44 271
#define OPREF_1_45 777
#define OPREF_1_46 470
#define OPREF_1_47 284
#define OPREF_1_48 570
#define OPREF_1_49 375
#define OPREF_1_50 229
#define OPREF_1_51 373
#define OPREF_1_52 71
#define OPREF_1_53 316
#define OPREF_1_54 232
#define OPREF_1_55 379
#define OPREF_1_56 636
#define OPREF_1_57 778
