# Copyright 2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test reading/writing pointers to address spaces.

load_lib rocm.exp

require allow_hip_tests

standard_testfile .cpp

if {[prepare_for_testing "failed to prepare" $testfile $srcfile {debug hip}]} {
    return
}

with_rocm_gpu_lock {
    if {![runto_main]} {
	return
    }

    set bp_line [gdb_get_line_number "break-here"]
    gdb_breakpoint $bp_line -allow-pending -temporary
    gdb_continue_to_breakpoint "bp"

    with_test_prefix "dereference" {
	gdb_test "print *generic_ptr1" "= 1234"
	gdb_test "print *generic_ptr2" "= 101"
	gdb_test "print *generic_ptr3" "= 41"
	gdb_test "print *local_ptr1" "= 102"
	gdb_test "print *local_ptr2" "= 101"
	gdb_test "print *priv_ptr1" "= 42"
	gdb_test "print *priv_ptr2" "= 41"

	gdb_test "print *generic_ptr0" "Cannot access memory.*"
	gdb_test "print *local_ptr0" "Cannot access memory.*"
	gdb_test "print *priv_ptr0" "Cannot access memory.*"
    }

    with_test_prefix "sizeof" {
	gdb_test "print sizeof_generic_ptr == sizeof(generic_ptr0)" "= true"
	gdb_test "print sizeof_local_ptr == sizeof(local_ptr0)" "= true"
	gdb_test "print sizeof_priv_ptr == sizeof(priv_ptr0)" "= true"
    }

    with_test_prefix "illegal assignment" {
	gdb_test "print local_ptr0 = &global_var" \
	    "Cannot convert pointer-to-'global' to a pointer-to-'local'"
	gdb_test "print local_ptr0 = &priv_var1" \
	    "Cannot convert pointer-to-'private_lane' to a pointer-to-'local'"
	gdb_test "print local_ptr0 = generic_ptr1" \
	    "Cannot convert pointer-to-'generic' to a pointer-to-'local'"
	gdb_test "print priv_ptr0 = &global_var" \
	    "Cannot convert pointer-to-'global' to a pointer-to-'private_lane'"
	gdb_test "print priv_ptr0 = &local_var1" \
	    "Cannot convert pointer-to-'local' to a pointer-to-'private_lane'"
	gdb_test "print priv_ptr0 = generic_ptr1" \
	    "Cannot convert pointer-to-'generic' to a pointer-to-'private_lane'"
    }

    with_test_prefix "legal assignment" {
	gdb_test "print generic_ptr0 = &local_var1" "generic#0x.*"
	gdb_test "print *generic_ptr0" "= 101" "after generic <- local"
	gdb_test "print generic_ptr0 = &priv_var1" "generic#0x.*"
	gdb_test "print *generic_ptr0" "= 41" "after generic <- priv"

	gdb_test "print local_ptr0 = &local_var2" "local#0x.*"
	gdb_test "print *local_ptr0" "= 102"
	gdb_test "print local_ptr0 == local_ptr1" "= true"

	gdb_test "print priv_ptr0 = &priv_var2" "private_lane#0x.*"
	gdb_test "print *priv_ptr0" "= 42"
	gdb_test "print priv_ptr0 == priv_ptr1" "= true"

	gdb_test "print generic_ptr0 = local_ptr0" "generic#0x.*"
	gdb_test "print *generic_ptr0 == *local_ptr0" "= true"
	gdb_test "print generic_ptr0 = priv_ptr0" "generic#0x.*"
	gdb_test "print *generic_ptr0 == *priv_ptr0" "= true"
    }
}
