# Copyright (C) 2026 Free Software Foundation, Inc.
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.

# This file is part of GDB.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test accessing memory through nullptr for various address spaces.

load_lib rocm.exp

require allow_hip_tests

standard_testfile .cpp

if {[prepare_for_testing "failed to prepare ${testfile}" $testfile $srcfile \
	 {debug hip}]} {
    return
}

clean_restart $::testfile

with_rocm_gpu_lock {
    if {![runto_main]} {
	return
    }
    set bp_line [gdb_get_line_number "Break here"]
    gdb_breakpoint $bp_line -allow-pending -temporary
    gdb_continue_to_breakpoint "kernel bp"

    # Access nullptr in several address spaces.
    foreach_with_prefix addr {0x0 generic#0x0 private_lane#0xffffffff \
			      private_wave#0xffffffff local#0xffffffff} {
	gdb_test "print {int}$addr" \
	    "Cannot access memory at address $addr"
    }
}
