# Copyright (C) 2026 Free Software Foundation, Inc.
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.

# This file is part of GDB.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test the maint info amdgpu address-aliases command.

load_lib rocm.exp

standard_testfile .cpp

require allow_hip_tests

if {[prepare_for_testing "failed to prepare ${testfile}" $testfile $srcfile {debug hip}]} {
    return -1
}

with_rocm_gpu_lock {

    if {![runto_main]} {
	return -1
    }

    gdb_breakpoint [gdb_get_line_number "Break here"] -allow-pending
    gdb_continue_to_breakpoint "kern"

    set seen_header 0
    set seen_address 0

    # The actual output can vary, we want to verify if GDB doesn't
    # have any latent error.
    gdb_test_multiple "maint info amdgpu address-aliases &idx" "" -lbl {
	-re "Address space\[ \t\]*Address\[ \t\]*Valid for\[^\r\n\]*(?=\r\n)" {
	    # Match the header.
	    incr seen_header
	    exp_continue
	}

	-re "^\r\n\[a-z_\]+\[ \t\]+\[a-z_<>\]*\#*$::hex\[ \t\]*($::hex|<null>)\[^\r\n\]*(?=\r\n)" {
	    # Match address space.
	    incr seen_address
	    exp_continue
	}

	-re "^\r\n\[a-z_\]+\[ \t\]+<not reachable>\[ \t\]*($::hex|<null>)\[^\r\n\]*(?=\r\n)" {
	    # Match <not reachable> addresses.
	    incr seen_address
	    exp_continue
	}

	-re -wrap "" {
	    # Done.
	    gdb_assert { $seen_header == 1 && $seen_address > 0 } $gdb_test_name
	}
    }
}
