# Copyright (C) 2026 Free Software Foundation, Inc.
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.

# This file is part of GDB.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test the maint info amdgpu address-aliases command.

load_lib rocm.exp

standard_testfile .cpp

require allow_hip_tests

if {[prepare_for_testing "failed to prepare ${testfile}" $testfile $srcfile {debug hip}]} {
    return -1
}

with_rocm_gpu_lock {

    # Test: command before any inferior is running (no thread selected).
    gdb_test "maint info amdgpu address-aliases &main" \
	"Current architecture is not AMDGPU\\." \
	"address-aliases with no thread selected"

    if {![runto_main]} {
	return -1
    }

    # Test: command when focused on a host (CPU) thread, right after
    # reaching main.
    gdb_test "maint info amdgpu address-aliases &main" \
	"Current architecture is not AMDGPU\\." \
	"address-aliases on host thread"

    gdb_breakpoint [gdb_get_line_number "Break here"] -allow-pending
    gdb_continue_to_breakpoint "kern"

    set asname "\[^ \t\r\n\]+"
    set trailer "\[^\r\n\]*(?=\r\n)"

    # Count address spaces known to the architecture.
    set aspaces 0
    gdb_test_multiple "maint print address-spaces" "" -lbl {
	-re "\r\n${asname}\[ \t\]+$::decimal\[ \t\]+" {
	    incr aspaces
	    exp_continue
	}
	-re -wrap "" {
	    # Done collecting.
	}
    }

    set seen_header 0
    set seen_address 0

    # The actual output can vary, we want to verify if GDB doesn't
    # have any latent error.
    gdb_test_multiple "maint info amdgpu address-aliases &idx" "" -lbl {
	-re "Address space\[ \t\]+Address\[ \t\]+Valid for${trailer}" {
	    # Match the header.
	    incr seen_header
	    exp_continue
	}

	-re "^\r\n${asname}\[ \t\]+$::hex\[ \t\]+$::hex${trailer}" {
	    # Match global address space.
	    incr seen_address
	    exp_continue
	}

	-re "^\r\n${asname}\[ \t\]+${asname}#$::hex\[ \t\]+($::hex|<null>)${trailer}" {
	    # Match address space.
	    incr seen_address
	    exp_continue
	}

	-re "^\r\n${asname}\[ \t\]+<not reachable>\[ \t\]+($::hex|<null>)${trailer}" {
	    # Match <not reachable> addresses.
	    incr seen_address
	    exp_continue
	}

	-re -wrap "" {
	    # Done.  Every address space should have exactly one row.
	    gdb_assert { $seen_header == 1 } "$gdb_test_name: seen header"
	    gdb_assert { $seen_address == $aspaces } \
		"$gdb_test_name: seen address space"
	}
    }
}
