# Copyright 2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This test ensures that we receive SIGABRT when we step over an abort
# instruction.

load_lib rocm.exp

standard_testfile .cpp

require allow_hip_tests

# We want to have a small kernel as we are going to single step all the way
# to our abort instruction (s_trap 2).  Using -O1 allows the compiler to inline
# the sleep and abort instructions.
if {[build_executable "failed to prepare" $testfile $srcfile {hip additional_flags=-O1}]} {
    return
}

proc do_test {} {
    clean_restart $::testfile

    with_rocm_gpu_lock {
	if {![runto_main]} {
	    return
	}

	gdb_test "with breakpoint pending on -- break kern" \
	    "Breakpoint $::decimal \\(kern\\) pending."

	gdb_test "continue" \
	    "Thread $::decimal hit Breakpoint $::decimal.* kern.*"

	set remaining_steps 60
	gdb_test_multiple "si" "step until SIGABRT" {
	    -re -wrap ".*SIGABRT.*" {
		pass $gdb_test_name
	    }
	    -re -wrap ".*" {
		incr remaining_steps -1
		verbose -log "remaining steps: $remaining_steps"
		if {$remaining_steps == 0} {
		    fail $gdb_test_name
		} else {
		    send_gdb "si\n"
		    exp_continue
		}
	    }
	}

	# We have received the SIGABRT.  If we continue from here, the
	# exception is passed to the inferior, i.e. GDB forwards it to the
	# ROCr runtime, which can detect the shader error.
	gdb_test "continue" "Queue error: HSA_STATUS_ERROR_EXCEPTION.*" \
	    "send exception to the runtime"
    }
}

do_test
