#!/usr/bin/env python3

# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.

# This file is part of GDB.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Refresh rocm-theme.css's generated token block from the live ROCm docs.

The ROCm theme stylesheet (rocm-theme.css) defines a block of
--toc-sidebar-* custom properties so that the manual matches the ROCm
documentation site.  Those values are the light-mode design tokens of
the pydata-sphinx-theme the ROCm site is built with -- the color
palette, the heading font-size ramp and weight, and the base and
monospace font stacks.  ROCm leaves the pydata defaults in place
except for a couple of overrides shipped in rocm_custom.css.

This script fetches the live site's CSS, reads those source variables,
and rewrites the generated :root block of the sibling stylesheet in
place.  The file is only touched when a value actually changed, to
avoid bumping the css's modification time unnecessarily.

Only the tokens pydata exposes as --pst-* custom properties are
synced.  The rest of the theme's metrics (the body and heading
line-heights, the heading margins, the pre and inline-code box) live
in pydata's rule bodies rather than in custom properties, i.e., they
are maintained by hand in the stylesheet, which is why they are not
touched here.

Needs network access to https://rocm.docs.amd.com.

"""

import argparse
import os
import re
import sys
import urllib.request

BASE = "https://rocm.docs.amd.com/en/latest/_static"

# The pydata theme stylesheet (which carries the --pst-* defaults) and
# the ROCm custom stylesheet (carries the site's own overrides).
PYDATA_CSS = f"{BASE}/styles/pydata-sphinx-theme.css"
ROCM_CSS = f"{BASE}/rocm_custom.css"

# The committed theme file, a sibling of this script.
THEME_CSS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rocm-theme.css")

# The first line inside the generated :root block.  It both labels the
# block as machine-generated and is the anchor that update_css() keys
# on to find the block to replace.  Emitter and matcher share this one
# constant.
MARKER = "/* generated by rocm-theme-sync.py */"

# Each mapping row is a tuple of:
#
#  - our property (--toc-sidebar-* or --rocm-*)
#  - the pydata/ROCm source variable whose light-mode value we copy
#
# pydata has no variable literally named for links: the site paints
# links with --pst-color-primary and link-hover with
# --pst-color-secondary, which is why those feed our two accents (and
# why the hover accent comes out purple).  Every value is a stock
# pydata light-mode default except the row-hover background, which
# ROCm overrides in rocm_custom.css.
#
# The --toc-sidebar-* properties come first: those are the contract
# that toc-sidebar.css reads.  The --rocm-* properties follow; they are
# used only within rocm-theme.css.  Some of both groups happen to share
# a source token (e.g. --toc-sidebar-bg and --rocm-code-bg are both
# --pst-color-surface), which the trailing source comments record.
PALETTE = [
    # contract: read by toc-sidebar.css
    ("--toc-sidebar-accent", "--pst-color-primary"),  # site link color
    ("--toc-sidebar-text", "--pst-color-text-base"),
    ("--toc-sidebar-muted", "--pst-color-text-muted"),
    ("--toc-sidebar-border", "--pst-color-border"),
    ("--toc-sidebar-bg", "--pst-color-surface"),
    ("--toc-sidebar-hover-bg", "--pst-color-table-row-hover-bg"),  # rocm override
    ("--toc-sidebar-search-bg", "--pst-color-background"),
    ("--toc-sidebar-on-accent", "--pst-color-primary-text"),
    # internal: used only within rocm-theme.css
    ("--rocm-accent-dark", "--pst-color-secondary"),  # site link-hover color
    ("--rocm-code-bg", "--pst-color-surface"),
    ("--rocm-inline-code", "--pst-color-inline-code"),
]

# The heading font-size ramp and the heading weight.  pydata's
# headings are set in the site's light weight, not bold.
TYPE_SCALE = [
    ("--rocm-font-size-h1", "--pst-font-size-h1"),
    ("--rocm-font-size-h2", "--pst-font-size-h2"),
    ("--rocm-font-size-h3", "--pst-font-size-h3"),
    ("--rocm-font-size-h4", "--pst-font-size-h4"),
    ("--rocm-font-size-h5", "--pst-font-size-h5"),
    ("--rocm-font-size-h6", "--pst-font-size-h6"),
    ("--rocm-heading-weight", "--pst-font-weight-heading"),
]

# The UI and monospace font stacks.  We copy the *-system variables,
# which hold the literal stacks; the plain --pst-font-family-* names
# are just var() aliases of these.
FONT_STACKS = [
    ("--rocm-font-base", "--pst-font-family-base-system"),
    ("--rocm-font-mono", "--pst-font-family-monospace-system"),
]

# The groups emitted into the block, in order.  The third element says
# whether to pad the rows so the trailing /* source */ comments line
# up.  The font stacks are long enough that aligning their comments
# would push them far off to the right, so that group is left
# unaligned.
GROUPS = [
    ("palette", PALETTE, True),
    ("type scale", TYPE_SCALE, True),
    ("font stacks", FONT_STACKS, False),
]


def fetch(url):
    """Return the text of URL, decoded as UTF-8."""
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def light_values(css):
    """Map every --pst-* name to its light-mode value.

    pydata defines the light palette under the html:not([data-theme])
    rule and the dark palette under html[data-theme=dark].  ROCm's
    overrides sit under html[data-theme='light'].  We want the
    light-mode value, so we skip any definition that falls inside a
    dark-theme block and keep the rest; a later light definition (an
    override) wins over an earlier default, which is the cascade order
    on the page too.
    """
    values = {}
    # Walk the stylesheet in source order, tracking nothing more than
    # whether the current selector is a dark-theme block.
    for sel, body in re.findall(r"([^{}]*)\{([^{}]*)\}", css):
        flat = sel.replace(" ", "").replace('"', "").replace("'", "")
        if "data-theme=dark" in flat:
            continue
        for name, val in re.findall(r"(--pst-[a-z0-9-]+)\s*:\s*([^;]+)", body):
            values[name] = val.strip()
    return values


def format_value(val, *, is_font_stack):
    """Normalize a source value for emission into the stylesheet."""
    # Lowercase hex colors; the source mixes cases and the committed
    # file keeps them lowercase.
    val = re.sub(r"#[0-9a-fA-F]+", lambda m: m.group().lower(), val)
    # The site ships the font stacks comma-packed.  Space them out so
    # that the committed value reads like regular CSS.
    if is_font_stack:
        val = re.sub(r",\s*", ", ", val)
    return val


def build_root():
    """Return the full generated :root block as a string of CSS.

    Fetch the live stylesheets, look up each mapped source variable's
    light-mode value, and lay the --toc-sidebar-* properties out group
    by group, each group introduced by a comment and (when aligned)
    padded so its trailing /* source */ comments line up.  Exit if a
    mapped source variable is missing, which means the upstream theme
    changed too much to handle here.
    """
    pyd = light_values(fetch(PYDATA_CSS))
    rocm = light_values(fetch(ROCM_CSS))
    # ROCm overrides take precedence over the pydata defaults.
    src = {**pyd, **rocm}

    wanted = [theirs for _, group, _ in GROUPS for _, theirs in group]
    missing = [v for v in wanted if v not in src]
    if missing:
        sys.exit(
            f"source variables not found (theme changed?): "
            f"{', '.join(sorted(set(missing)))}"
        )

    lines = [f"    {MARKER}"]
    for label, group, align in GROUPS:
        # Build each "  --toc-sidebar-x: value;" prefix, then (for aligned
        # groups) pad them to a common width so the trailing comments
        # line up.
        rows = []
        for ours, theirs in group:
            val = format_value(src[theirs], is_font_stack=(label == "font stacks"))
            rows.append((f"    {ours}: {val};", theirs.replace("--", "")))
        width = max(len(prefix) for prefix, _ in rows) if align else 0
        lines.append("")
        lines.append(f"    /* {label} */")
        for prefix, comment in rows:
            lines.append(f"{prefix.ljust(width)}  /* {comment} */")
    return ":root {\n" + "\n".join(lines) + "\n}"


def update_css(root):
    """Replace the generated :root block of the theme file with ROOT.

    Rewrite the file only when the block changes, so that an unchanged
    refresh leaves the mtime untouched.  Return True if it was
    rewritten.
    """
    with open(THEME_CSS) as f:
        old = f.read()
    # Anchor on a column-0 ":root {" whose first inner line is MARKER,
    # then run to the next line that is just "}".
    pattern = r"^:root \{\n    " + re.escape(MARKER) + r"\n.*?\n\}"
    new, n = re.subn(
        pattern, lambda m: root, old, count=1, flags=re.DOTALL | re.MULTILINE
    )
    if n == 0:
        sys.exit(f"no generated :root block found in {THEME_CSS}")
    if new == old:
        return False
    with open(THEME_CSS, "w") as f:
        f.write(new)
    return True


def main():
    """Rewrite the generated block in place and report what happened."""
    argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    ).parse_args()

    name = os.path.basename(THEME_CSS)
    if update_css(build_root()):
        print(f"updated {name}; review the change with git diff")
    else:
        print(f"{name} already matches the live ROCm docs site")


if __name__ == "__main__":
    main()
