.*: Assembler messages:
.*:2: Error: .seh_endprologue used outside of .seh_proc block
.*:3: Error: SEH entry has not been found \(missing .seh_proc\)
.*:4: Error: SEH entry has not been found \(missing .seh_proc\)
.*:5: Error: SEH entry has not been found \(missing .seh_proc\)
.*:6: Error: SEH entry has not been found \(missing .seh_proc\)
.*:7: Error: SEH entry has not been found \(missing .seh_proc\)
.*:8: Error: SEH entry has not been found \(missing .seh_proc\)
.*:9: Error: SEH entry has not been found \(missing .seh_proc\)
.*:10: Error: SEH entry has not been found \(missing .seh_proc\)
.*:11: Error: SEH entry has not been found \(missing .seh_proc\)
.*:12: Error: SEH entry has not been found \(missing .seh_proc\)
.*:13: Error: SEH entry has not been found \(missing .seh_proc\)
.*:14: Error: SEH entry has not been found \(missing .seh_proc\)
.*:15: Error: SEH entry has not been found \(missing .seh_proc\)
.*:16: Error: SEH entry has not been found \(missing .seh_proc\)
.*:17: Error: SEH entry has not been found \(missing .seh_proc\)
.*:18: Error: SEH entry has not been found \(missing .seh_proc\)
.*:19: Error: SEH entry has not been found \(missing .seh_proc\)
.*:20: Error: SEH entry has not been found \(missing .seh_proc\)
.*:21: Error: .seh_endproc used without .seh_proc
.*:23: Error: .seh_proc requires function label name
.*:24: Error: previous SEH entry not closed \(missing .seh_endproc\)
.*:29: Error: offset overflows expected range
.*:30: Error: offset should be a multiple of 16
.*:31: Error: .seh_stackalloc offset is out of range
.*:33: Error: unexpected register number
.*:34: Error: unexpected register number
.*:35: Error: unexpected register name
.*:36: Error: offset is negative
.*:36: Error: offset overflows expected range
.*:38: Error: offset should be a multiple of 8
.*:39: Error: offset overflows expected range
.*:41: Error: unexpected register number
.*:42: Error: unexpected register number
.*:43: Error: unexpected register name
.*:44: Error: offset is negative
.*:44: Error: offset overflows expected range
.*:46: Error: offset should be a multiple of 8
.*:47: Error: offset overflows expected range
.*:49: Error: unexpected register number
.*:50: Error: unexpected register number
.*:51: Error: unexpected register name
.*:52: Error: unexpected register number
.*:53: Error: offset is negative
.*:53: Error: offset overflows expected range
.*:55: Error: offset should be a multiple of 8
.*:56: Error: offset overflows expected range
.*:58: Error: unexpected register number
.*:59: Error: unexpected register number
.*:60: Error: unexpected register name
.*:61: Error: unexpected register number
.*:62: Error: offset is negative
.*:62: Error: offset overflows expected range
.*:64: Error: offset should be a multiple of 8
.*:65: Error: offset overflows expected range
.*:67: Error: unexpected register number
.*:67: Error: unexpected register number
.*:68: Error: unexpected register number
.*:69: Error: unexpected register name
.*:70: Error: unexpected register number
.*:71: Error: offset is negative
.*:71: Error: offset overflows expected range
.*:73: Error: offset should be a multiple of 8
.*:74: Error: offset overflows expected range
.*:76: Error: unexpected register number
.*:77: Error: unexpected register number
.*:78: Error: unexpected register name
.*:79: Error: offset is negative
.*:79: Error: offset overflows expected range
.*:81: Error: offset should be a multiple of 8
.*:82: Error: offset overflows expected range
.*:84: Error: unexpected register number
.*:85: Error: unexpected register number
.*:86: Error: unexpected register name
.*:87: Error: offset is negative
.*:87: Error: offset overflows expected range
.*:89: Error: offset should be a multiple of 8
.*:90: Error: offset overflows expected range
.*:92: Error: unexpected register number
.*:93: Error: unexpected register number
.*:94: Error: unexpected register name
.*:95: Error: offset is negative
.*:95: Error: offset overflows expected range
.*:97: Error: offset should be a multiple of 8
.*:98: Error: offset overflows expected range
.*:100: Error: unexpected register number
.*:101: Error: unexpected register number
.*:102: Error: unexpected register name
.*:103: Error: offset is negative
.*:103: Error: offset overflows expected range
.*:105: Error: offset should be a multiple of 8
.*:106: Error: offset overflows expected range
.*:108: Error: offset is negative
.*:108: Error: offset overflows expected range
.*:110: Error: offset should be a multiple of 8
.*:111: Error: offset overflows expected range
.*:113: Error: offset is negative
.*:113: Error: offset overflows expected range
.*:115: Error: offset should be a multiple of 8
.*:116: Error: offset overflows expected range
.*:118: Error: offset is negative
.*:118: Error: offset overflows expected range
.*:120: Error: offset should be a multiple of 8
.*:121: Error: offset overflows expected range
.*:123: Error: offset is negative
.*:123: Error: offset overflows expected range
.*:125: Error: offset should be a multiple of 8
.*:126: Error: offset overflows expected range
.*: Error: open SEH entry at end of file \(missing .seh_endproc\)
