# Copyright 2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile prog

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable debug] != ""} {
    return
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "STOP" ${testdir}/prog.adb]
runto "prog.adb:$bp_location"

for {set num 0} {$num <= 300} {incr num} {
    gdb_test "print Value_$num" " = value_$num"
    gdb_test "print Unsigned_Enumeration'Val($num)" " = value_$num"
    gdb_test "print/d Unsigned_Enumeration'Val($num)" " = $num"
}

foreach {name dec} {se_a -1 se_b 0 se_c 1 se_d 2 se_e 128 se_f 255} {
    gdb_test "print $name" " = $name"
    gdb_test "print/d $name" " = $dec"
}

gdb_test "ptype signed_enumeration" \
    [string_to_regexp \
	 "type = (se_a => -1, se_b, se_c, se_d, se_e => 128, se_f => 255)"]

set names {}
for {set num 0} {$num <= 300} {incr num} {
    lappend names value_$num
}
gdb_test "ptype unsigned_enumeration" \
    [string_to_regexp "type = ([join $names ", "])"]
