# Copyright 2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test that a value can be passed to a function expecting a padded
# type.

load_lib "ada.exp"

require allow_ada_tests

# This is written in C because actually constructing such a test case
# is difficult or maybe even impossible with recent versions of GNAT.
# Originally padding was used when passing Long_Long_Float types; see
# commit 8344af1e ("[Ada] error trying to call function when parameter
# is aligner type."), but this no longer happens.
standard_testfile

if {[prepare_for_testing "failed to prepare" $testfile $srcfile debug]} {
    return
}

if {![runto_main]} {
    return
}

gdb_test "set language ada" \
    [quotemeta {Warning: the current language does not match this frame.}]

gdb_test "print call(value)" [quotemeta {@DECIMAL = 23}]
gdb_test "print call(pdv)" [quotemeta {@DECIMAL = 23}]
