[^:]*: Assembler messages:
[^:]*:4: Warning: visibility of .gd. is already .internal.
[^:]*:5: Warning: visibility of .gd. is already .internal.
[^:]*:21: Warning: visibility of .ge. is already .hidden.
[^:]*:26: Warning: visibility of .we. is already .hidden.
[^:]*: Warning: local symbol .li. has non-default visibility
[^:]*: Warning: local symbol .lh. has non-default visibility
[^:]*: Warning: local symbol .lp. has non-default visibility
