# Copyright 2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test that GDB refuses to produce a .gdb_index when skeletonless type units
# are present.  A skeletonless type unit is a type unit in a .dwo file that
# doesn't have a corresponding skeleton in the main file.  The .gdb_index
# format cannot represent these, so GDB must refuse to produce one rather than
# produce a bogus index.

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

# Can't produce an index with readnow.
require !readnow

standard_testfile .c -dw.S

set asm_file [standard_output_file $srcfile2]

Dwarf::assemble $asm_file {
    # In the main file: a skeleton CU pointing to the .dwo file.
    cu {
	version 5
	dwo_id 0xF00D
    } {
	compile_unit {
	    DW_AT_dwo_name ${::gdb_test_file_name}-dw.dwo DW_FORM_strp
	} {}
    }

    # In the .dwo file: a type unit (skeletonless, no corresponding skeleton
    # in main file).
    tu {
	fission 1
	version 5
    } 0xCAFE "the_type" {
	type_unit {} {
	    the_type: base_type {
		DW_AT_byte_size 4 DW_FORM_sdata
		DW_AT_encoding  @DW_ATE_signed
		DW_AT_name      int
	    }
	}
    }

    # In the .dwo file: the split compile unit.
    cu {
	fission 1
	version 5
	dwo_id 0xF00D
    } {
	compile_unit {} {
	    DW_TAG_variable {
		DW_AT_name global_var
		DW_AT_type 0xCAFE DW_FORM_ref_sig8
		DW_AT_location {
		    DW_OP_const1u 12
		    DW_OP_stack_value
		} SPECIAL_expr
	    }
	}
    }
}

set obj [standard_output_file "${testfile}-dw.o"]
if {[build_executable_and_dwo_files "$testfile.exp" "${binfile}" {} \
	 [list $asm_file {nodebug split-dwo} $obj] \
	 [list $srcfile  {nodebug}]]} {
    return
}

clean_restart ${testfile}

# Sanity check, verify that the executable works correctly.
gdb_test "print global_var" " = 12"

# Verify that saving a .gdb_index index fails.
set output_dir [standard_output_file ""]
gdb_test "save gdb-index ${output_dir}" \
    "Found foreign \\(skeletonless\\) type unit, unable to produce \\.gdb_index\\.  Consider using \\.debug_names instead\\." \
    "save gdb-index fails"

# Verify that saving a .debug_names index works.
gdb_test_no_output "save gdb-index -dwarf-5 ${output_dir}" \
    "save gdb-index -dwarf-5 succeeds"

# Verify that the .debug_names file was created.
set debug_names_file "${output_dir}/${testfile}.debug_names"
gdb_assert {[file exists $debug_names_file]} ".debug_names file exists"
