# Copyright 2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# The test sets up a type DIE without a DW_AT_name, the type DIE links
# to a type within a TU via DW_AT_signature.  Normally GDB would
# use the DW_AT_signature to find the name of the type DIE.
#
# However, in this test there is no type DIE with the specified
# signature!
#
# This test checks that GDB can emit a complaint when this situation is
# encountered.  The test also checks that trying to find a method
# within the type using the qualified name will fail.

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

standard_testfile main-foo.c .S

# Build the test program using VERSION for the CU/TU DWARF version.
proc run_test { version } {
    # Create the DWARF.
    set asm_file [standard_output_file $::srcfile2]
    Dwarf::assemble {
	filename $asm_file
	add_dummy_cus 0
    } {
	upvar version version

	get_func_info foo
	get_func_info main

	declare_labels method_decl

	tu { version $version } 0xdeadbeefdeadbeef the_type {
	    DW_TAG_type_unit {
		DW_AT_language @DW_LANG_C_plus_plus
	    } {
		the_type: DW_TAG_class_type {
		    DW_AT_name the_type
		    DW_AT_byte_size 1 sdata
		}
	    }
	}

	cu { version $version } {
	    compile_unit {
		DW_AT_language @DW_LANG_C_plus_plus
	    } {
		DW_TAG_class_type {
		    DW_AT_declaration 1 flag
		    DW_AT_signature 0xdeadbeef01234567 ref_sig8
		} {
		    method_decl: DW_TAG_subprogram {
			DW_AT_name method
			DW_AT_linkage_name _ZN8the_type6methodEv
			DW_AT_declaration 1 flag
		    }
		}

		DW_TAG_subprogram {
		    DW_AT_specification %$method_decl
		    DW_AT_low_pc $foo_start DW_FORM_addr
		    DW_AT_high_pc $foo_end DW_FORM_addr
		}

		DW_TAG_subprogram {
		    DW_AT_name main
		    DW_AT_low_pc $main_start DW_FORM_addr
		    DW_AT_high_pc $main_end DW_FORM_addr
		}
	    }
	}
    }

    set testfile_name ${::testfile}-${version}
    set binfile_name [standard_output_file $testfile_name]
    if { [build_executable "failed to build" $testfile_name \
	      [list $asm_file $::srcfile] {nodebug}] } {
	return
    }

    clean_restart $testfile_name

    set expect_complaint true
    # If we have a .gdb_index already then the part of this test that
    # checks for a warning when loading the executable is not going to
    # work as the warning will have already been generated when the
    # index was added.
    if {[get_index_type $testfile_name] == "gdb"} {
	set expect_complaint false
    }

    clean_restart

    set host_binfile [gdb_remote_download host $binfile_name]
    if { [is_remote host] } {
	# For some remote host boards gdb_remote_download returns an
	# absolute path, but for others it returns a relative path.
	# The path reported in the complaint message is always
	# absolute.  Handle this with an optional prefix pattern.
	set binfile_re "\[^\r\n\]*[string_to_regexp $host_binfile]"
    } elseif {[section_get $binfile_name ".gnu_debuglink"] ne ""} {
	set binfile_re "\[^\r\n\]+[string_to_regexp ${testfile_name}.debug]"
    } else {
	set binfile_re [string_to_regexp $binfile_name]
    }

    # Load the executable and check we see the expected complaint from
    # the DWARF indexer.
    gdb_test_no_output "maint set dwarf synchronous on"
    gdb_test_no_output "set complaints 100"
    set saw_complaint false
    gdb_test_multiple "file $host_binfile" "file command" -lbl {
	-re "^\r\nDuring symbol reading: DWARF Error: Cannot find signatured DIE 0xdeadbeef01234567 referenced from DIE at $::hex \\\[in module $binfile_re\\\](?=\r\n)" {
	    set saw_complaint true
	    exp_continue
	}
	-re "^\r\n$::gdb_prompt $" {
	    gdb_assert { $saw_complaint == $expect_complaint } $gdb_test_name
	}
    }

    if { ![readnow] } {
	# Check that GDB is unable to find this via the index.  If we
	# load the full symbols then GDB is able to resolve this print
	# via the linkage name.
	#
	# It is unfortunate that there is a difference in behaviour
	# depending on whether GDB is using the index or not, but
	# remember, the DWARF is corrupted at this point, so it's
	# probably OK if things don't fully work, so long as GDB
	# doesn't crash.
	gdb_test "print the_type::method" \
	    "^There is no field named method"
    }
}

foreach_with_prefix version { 4 5 } {
    run_test $version
}
