# Copyright 2020-2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Check various cases of typed enums.

require allow_cplus_tests

standard_testfile .cc

set opts {}
lappend opts debug
lappend opts c++
lappend opts additional_flags=-std=c++11

if {[prepare_for_testing "failed to prepare" $testfile $srcfile $opts]} {
    return
}

gdb_test "print (int)byte_val" "= 128"
gdb_test "print (int)uchar_val" "= 128"

# int_enum
gdb_test "print (int)int_val" "= 128"
gdb_test "print int_val" "= int_val"
gdb_test "ptype int_enum" \
    [multi_line \
	 "type = enum int_enum : int \{" \
	 "    int_three = 3," \
	 "    int_val = 128" \
	 "\}"]

# schar_enum
gdb_test "print (int)schar_neg" "= -128"
gdb_test "print schar_neg" "= schar_neg"
gdb_test "ptype schar_enum" \
    [multi_line \
	 "type = enum schar_enum : signed char \{" \
	 "    schar_neg = -128," \
	 "    schar_val = 127" \
	 "\}"]
