/* PDB debugging format support for GDB.

   Copyright (C) 1994-2026 Free Software Foundation, Inc.
   Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.

   This file is part of GDB.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>

   This file implements reading of Microsoft PDB debug information format.
   PDB (Program Database) is the native debug format for Microsoft compilers.
   PDB is a multi-stream file container.  All the data is stored in various
   streams while the streams are composed of blocks which don't have to be
   consecutive.  References:
   - microsoft-pdb: https://github.com/microsoft/microsoft-pdb.
   - LLVM docs: https://llvm.org/docs/PDB/.  */

#include "pdb/pdb.h"

#include "gdbtypes.h"
#include "objfiles.h"
#include "buildsym.h"
#include "complaints.h"
#include "source.h"
#include "block.h"
#include "filenames.h"
#include "symfile.h"
#include "pdb/pdb-internal.h"
#include "gdbsupport/rsp-low.h"
#include "cli/cli-cmds.h"
#include "gdbsupport/common-utils.h"

#include <string.h>
#include <algorithm>
#include <vector>
#include <optional>
#include <chrono>

#ifdef _WIN32
/* Define NOMINMAX so <windows.h> does not clobber std::min / std::max.  */
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <io.h>
#else
#include <sys/mman.h>
#include <unistd.h>
#endif

#ifndef PDB_FORMAT_AVAILABLE

/* This configuration has no PDB reader, but coff_symfile_read calls in
   unconditionally.  Report "no PDB here" so it falls through to DWARF.
   The rest of the reader lives in PDB_SRCS, which is not linked either.  */

namespace pdb
{

bool
pdb_initialize_objfile (struct objfile *)
{
  return false;
}

} /* namespace pdb */

/* init.c is generated by scanning the sources for INIT_GDB_FILE, and
   pdb.c is scanned whether or not the reader is configured in.  */

INIT_GDB_FILE (pdb_read)
{
}

#else

namespace pdb
{

/* PDB read debug statements.  */
unsigned int pdb_read_debug = 0;
/* PDB quick functions debug statements.  */
unsigned int pdb_qf_debug = 0;
/* PDB path conversion debug statements.  */
unsigned int pdb_convert_debug = 0;

/* Quick functions debug statements.  */
#define pdb_qf_printf(fmt, ...) \
  debug_prefixed_printf_cond (pdb_qf_debug >= 1, "pdb qf", fmt, ##__VA_ARGS__)

/* Path conversion debug statements.  */
#define pdb_cvt_printf(fmt, ...)                                      \
  debug_prefixed_printf_cond (pdb_convert_debug >= 1, "pdb cvt", fmt, \
			      ##__VA_ARGS__)

/* One PDB loaded per object file.  */
static const registry<objfile>::key<pdb_per_objfile> pdb_objfile_data_key;

/* Convert Unix-style paths to Windows paths as GDB has problems with MSVC
   compiled PDBs that may contain paths like /home/rocm/... when built under
   MSYS2.  This conversion is used before storing the file paths to lineinfo.
   When path is converted we check for the presence of the converted path and if
   it doesn't exist we return the original path.  Path issues to solve:
   1. Under MSYS2, the linker prepends the work dir to the file path.  E.g.
      /home/user/test/C:\Program Files\...\include/__msvc_ostream.hpp*
      We strip the work dir: E.g. /<WHATEVER>/<DRIVE>:\ -> <DRIVE>:\
   2. The pure unix style path - e.g. /home/user/test/file.cpp
      Here we need to find the MSYS2 Windows root and prepend it to the path.
      E.g. C:/msys2/home/user/test/file.cpp.
      The MSYS2 root is not derivable: neither the configure-time gdbdir nor
      the gdb executable dir gives it for every layout.
      For example:
	C:/msys2/mingw64/WHATEVER/gdb -> Root is C:/msys2/mingw64
	C:/msys2/WHATEVER/gdb -> Root is C:/msys2
      but C:/mypath/share/gdb yields nothing.  MSYS2_ROOT must therefore be
      set when a pure unix path is found.
      If path under MSYS2_ROOT or MSYS2_ROOT is not set we will try some well
      known paths:
       a) E.g. <DRIVE>/WHATEVER - search for <DRIVE>:/WHATEVER
       b) Assume MSYS2_ROOT is <DRIVE>:/msys64/mingw64 or <DRIVE>:/msys2  */

static std::string
pdb_resolve_path (const char *path)
{
  if (path == nullptr || path[0] == '\0')
    return std::string ();

  /* Non-Unix paths are returned as-is.  */
  if (path[0] != '/')
    return std::string (path);

  pdb_cvt_printf ("converting path: '%s'", path);

  /* Case 1: Embedded Windows path in a Unix prefix.
     E.g. /home/user/test/C:\Program Files\...\include/file.c
     Search for ':' to find a drive letter pattern /X:\ or /X:/ and strip
     everything before the drive letter.  */
  std::string spath (path);
  if (size_t pos = spath.find (':'); pos != std::string::npos && pos >= 2)
    {
      if (spath[pos - 2] == '/' && isalpha ((unsigned char) spath[pos - 1])
	  && pos + 1 < spath.size ()
	  && (spath[pos + 1] == '\\' || spath[pos + 1] == '/'))
	{
	  std::string result = spath.substr (pos - 1);
	  if (access (result.c_str (), F_OK) == 0)
	    {
	      pdb_cvt_printf ("Converted: '%s' -> '%s'", path,
			      result.c_str ());
	      return result;
	    }
	}

      /* If file is not found return the original string.
	 TODO: decide whether the later schemes should still be tried
	 once a drive letter was found.  */
      if (pos != std::string::npos)
	return spath;
    }

  /* Case 2: Unix-style path.  */

  /* First, try the MSYS2_ROOT environment variable.  */
  const char *env_root = getenv ("MSYS2_ROOT");
  if (env_root != nullptr && env_root[0] != '\0')
    {
      std::string result = std::string (env_root) + path;
      /* Not clear if we need to replace anything but maybe root and path
	 have different dir. separators so make them all the same.  */
      std::replace (result.begin (), result.end (), '\\', '/');
      if (access (result.c_str (), F_OK) == 0)
	{
	  pdb_cvt_printf ("MSYS2_ROOT convert: '%s' -> '%s'", path,
			  result.c_str ());
	  return result;
	}
    }

  /* Fallback (a): Drive-letter mount /c/foo -> C:/foo.  */
  if (isalpha ((unsigned char) path[1]) && (path[2] == '/' || path[2] == '\0'))
    {
      std::string result;
      result += (char) toupper ((unsigned char) path[1]);
      result += ':';
      result += (path[2] == '/') ? &path[2] : "/";
      if (access (result.c_str (), F_OK) == 0)
	{
	  pdb_cvt_printf ("fallback (a) drive mount: '%s' -> '%s'", path,
			  result.c_str ());
	  return result;
	}
    }

  /* Fallback (b): Try well-known MSYS2 installation roots on all
     drive letters.  */
  static constexpr std::array<std::string_view, 4> known_suffixes
    = { ":/msys64/mingw64", ":/msys64", ":/msys2/mingw64", ":/msys2" };

  for (char drive = 'A'; drive <= 'Z'; drive++)
    {
      for (const auto &suffix : known_suffixes)
	{
	  std::string full_path = std::string (1, drive) + std::string (suffix)
				  + path;
	  if (access (full_path.c_str (), F_OK) == 0)
	    {
	      pdb_cvt_printf ("fallback (b) known root: '%s' -> '%s'", path,
			      full_path.c_str ());
	      return full_path;
	    }
	}
    }

  /* Nothing resolved; return the original path unchanged.  */
  return std::string (path);
}

/* See pdb-internal.h.  */

std::string
pdb_convert_path (const char *path)
{
  /* Non-DOS hosts do not treat '\' as a separator; Windows takes both.  */
  std::string result = pdb_resolve_path (path);
  std::replace (result.begin (), result.end (), '\\', '/');
  return result;
}

/* See pdb-internal.h.  */

pdb_per_objfile *
get_pdb_per_objfile (objfile *objfile)
{
  return pdb_objfile_data_key.get (objfile);
}

/* Get the pdb_per_objfile associated with OBJFILE, creating and registering
   a new one if none exists yet.  */

static pdb_per_objfile *
get_or_create_pdb_per_objfile (objfile *objfile)
{
  return &pdb_objfile_data_key.try_emplace (objfile, objfile);
}

/* Read SIZE bytes from the PDB file at OFFSET into BUF.
   Uses the persistent file handle (pdb->pdb_file) for repeated access.  */

static bool
pdb_read_file_bytes (const pdb_per_objfile *pdb, uint64_t offset,
		     gdb_byte *buf, size_t size)
{
  if (pdb->pdb_file == nullptr)
    return false;

  if (fseek (pdb->pdb_file.get (), (long) offset, SEEK_SET) != 0)
    return false;

  size_t nr = fread (buf, 1, size, pdb->pdb_file.get ());
  return nr == size;
}

/* Number of MSF blocks needed to hold SIZE bytes.  */

static inline uint32_t
pdb_blocks_for_size (uint32_t size, uint32_t block_size)
{
  gdb_assert (is_power_of_2 (block_size));
  return (uint32_t) (align_up ((ULONGEST) size, (int) block_size)
		     / block_size);
}

/* Read MSF SuperBlock header.
   https://llvm.org/docs/PDB/MsfFile.html#the-superblock  */

static bool
pdb_read_msf_header (pdb_per_objfile *pdb)
{
  /* Read the SuperBlock from the file and get the block size
     information in order to be able to read streams.  */
  gdb_byte header[MSF_HEADER_SIZE];
  if (!pdb_read_file_bytes (pdb, 0, header, sizeof (header)))
    pdb_error ("Failed to read MSF SuperBlock");

  pdb->block_size = read_u32 (header + MSF_BLOCK_SIZE_OFFS);
  pdb->num_blocks = read_u32 (header + MSF_NUM_BLOCKS_OFFS);
  pdb->num_dir_bytes = read_u32 (header + MSF_NUM_DIRECTORY_BYTES_OFFS);
  pdb->block_map_addr = read_u32 (header + MSF_BLOCK_MAP_ADDR_OFFS);

  pdb_dbg_printf ("SuperBlock: block Size=%" PRIu32 ", No.blocks=%" PRIu32
		  ", Num Dir Bytes=%" PRIu32 ", Block Map Addr=%" PRIu32,
		  pdb->block_size, pdb->num_blocks, pdb->num_dir_bytes,
		  pdb->block_map_addr);

  /* Validate block size.  Microsoft's MSF implementation (microsoft-pdb
     msf.cpp, validCbPg) accepts [512, 1024, 2048, 4096].  We arbitrarily
     extend the range to [256, 8192] to support possible future expansion.  */
  if (pdb->block_size < 256 || pdb->block_size > 8192
      || !is_power_of_2 (pdb->block_size))
    pdb_error ("Invalid PDB block size: %u", pdb->block_size);

  /* Validate the file is large enough for the number of blocks specified.  */
  if (uint64_t expected_file_size = (uint64_t) pdb->num_blocks * pdb->block_size;
      expected_file_size > pdb->msf_size)
    pdb_error ("PDB file too small: expected at least %" PRIu64 " bytes "
	       "for %u blocks of %u bytes each, but file is only %zu bytes",
	       expected_file_size, pdb->num_blocks, pdb->block_size,
	       pdb->msf_size);

  return true;
}

/* Read a uint32_t block number from BUF and validate it against
   pdb->num_blocks.  Throws via pdb_error if out of range; on return the
   returned block number is guaranteed to be < pdb->num_blocks.  CONTEXT
   is included in the error message to identify the call site.  */

static uint32_t
pdb_read_block_number (const pdb_per_objfile *pdb, const gdb_byte *buf,
		       const char *context)
{
  uint32_t block_idx = read_u32 (buf);
  if (block_idx >= pdb->num_blocks)
    pdb_error ("%s: block index %u out of range (max %u)", context, block_idx,
	       pdb->num_blocks);
  return block_idx;
}

/* Read one block from the PDB file.  BLOCK_NUM must be a valid
   block index (caller validates).  */

static gdb::byte_vector
pdb_read_one_block (const pdb_per_objfile *pdb, uint32_t block_num,
		    const char *context)
{
  gdb::byte_vector buf (pdb->block_size);
  if (!pdb_read_file_bytes (pdb, (uint64_t) block_num * pdb->block_size,
			    buf.data (), pdb->block_size))
    pdb_error ("Failed to read %s block %u", context, block_num);
  return buf;
}

/* Given an array of NUM_BLOCKS block numbers, read each referenced block
   from the file and concatenate them into a single buffer.  The last block
   contributes only the remaining bytes (TOTAL_SIZE may not be a multiple of
   block_size).  CONTEXT identifies the call site in error messages.  */

static gdb::byte_vector
pdb_stitch_blocks (const pdb_per_objfile *pdb, const uint32_t *block_nums,
		   uint32_t total_size, const char *context)
{
  uint32_t num_blocks = pdb_blocks_for_size (total_size, pdb->block_size);
  /* Allocate to a whole-block multiple so every read is full-block
     sized; trim down to TOTAL_SIZE at the end.  */
  gdb::byte_vector out ((size_t) num_blocks * pdb->block_size);
  for (uint32_t i = 0; i < num_blocks; i++)
    {
      uint32_t block_idx = block_nums[i];
      gdb_assert (block_idx < pdb->num_blocks);
      if (!pdb_read_file_bytes (pdb, (uint64_t) block_idx * pdb->block_size,
				out.data () + (size_t) i * pdb->block_size,
				pdb->block_size))
	pdb_error ("Failed to read %s block %u/%u (file block %u)", context, i,
		   num_blocks, block_idx);
    }
  out.resize (total_size);
  return out;
}

/* Read stream directory in order to get the blocks for each stream.
   See pdb.h & https://llvm.org/docs/PDB/MsfFile.html#the-stream-directory.  */

static bool
pdb_read_stream_directory (pdb_per_objfile *pdb)
{
  /* The stream directory specifies the number of streams, the size of each
     stream and the blocks that belong to each stream.  To access the directory
     we first need to assemble it as it might be split across multiple blocks.
     The block map in the MSF SuperBlock header is an array of uint32_t block
     numbers that belong to the directory.  We need to read these blocks to
     assemble the complete directory.  We read each block by simply reading
     uint32_t values, one after another.  The number of directory bytes is in
     the MSF header.  Layout:
       struct StreamDirectory {
	 ulittle32_t NumStreams;
	 ulittle32_t StreamSizes[NumStreams];
	 ulittle32_t StreamBlocks[NumStreams][];
       };
     Directory blocks example:
       If the block map contains:
	 Entry 0 = block 12 (first block of directory)
	 Entry 1 = block 47 (second block of directory)
	 Entry 2 = block 89 (third block of directory)
	 Entry 3 = block 156 (fourth block of directory)
       If block_size = 4096 and entries_per_block = 1024:
	 Block 12 holds entries 0-1023
	 Block 47 holds entries 1024-2047
	 Block 89 holds entries 2048-3071
	 Block 156 holds entries 3072-4095   */

  /* Buffer containing the complete stream directory from MSF blocks.  */
  uint32_t num_dir_blocks = pdb_blocks_for_size (pdb->num_dir_bytes,
						 pdb->block_size);

  uint32_t entries_per_block = pdb->block_size / sizeof (uint32_t);

  /* MSF 7.00: block_map_addr is the block number of a single stream
     directory block-map block.  That block holds up to entries_per_block
     uint32_t entries, each being a stream directory block number.  */
  if (num_dir_blocks > entries_per_block)
    pdb_error ("stream directory too large for MSF 7.00 single stream "
	       "directory block-map block (%u > %u)",
	       num_dir_blocks, entries_per_block);

  if (pdb->block_map_addr >= pdb->num_blocks)
    pdb_error ("Block map address out of range: %u (max %u)",
	       pdb->block_map_addr, pdb->num_blocks);

  /* Read the single block-map block.  */
  auto block_map = pdb_read_one_block (pdb, pdb->block_map_addr, "block map");

  /* Collect (and validate) directory block numbers from the block map.  */
  std::vector<uint32_t> dir_block_nums (num_dir_blocks);
  for (uint32_t i = 0; i < num_dir_blocks; i++)
    dir_block_nums[i]
      = pdb_read_block_number (pdb, block_map.data () + i * sizeof (uint32_t),
			       "stream directory");

  /* Stitch directory blocks into a contiguous StreamDirectory.  */
  auto dir = pdb_stitch_blocks (pdb, dir_block_nums.data (),
				pdb->num_dir_bytes, "stream directory");

  /* Finally we got the stream directory.  Parse it to fill the streams
     vector in pdb_per_objfile.  Walk a cursor through the
     directory: NumStreams, then StreamSizes[NumStreams], then
     StreamBlocks[NumStreams][].  */
  const gdb_byte *cursor = dir.data ();
  const gdb_byte *dir_end = dir.data () + dir.size ();

  /* Every directory field is a uint32_t; stop at the directory's end.  */
  auto next_u32 = [&] (const char *what)
    {
      if (dir_end - cursor < (ptrdiff_t) sizeof (uint32_t))
	pdb_error ("stream directory truncated in %s", what);
      const gdb_byte *field = cursor;
      cursor += sizeof (uint32_t);
      return field;
    };

  uint32_t num_streams = read_u32 (next_u32 ("stream count"));
  if (num_streams > (uint64_t) (dir_end - cursor) / sizeof (uint32_t))
    pdb_error ("stream directory too small for %u streams", num_streams);

  pdb->streams.resize (num_streams);
  for (uint32_t i = 0; i < num_streams; i++)
    pdb->streams[i].size = read_u32 (next_u32 ("stream sizes"));

  for (uint32_t i = 0; i < num_streams; i++)
    {
      uint32_t stream_size = pdb->streams[i].size;
      if (stream_size == PDB_NO_STREAM)
	{
	  pdb->streams[i].size = 0;
	  continue;
	}

      uint32_t num_blocks = pdb_blocks_for_size (stream_size, pdb->block_size);
      if (num_blocks > (uint64_t) (dir_end - cursor) / sizeof (uint32_t))
	pdb_error ("stream directory too small for stream %u", i);
      pdb->streams[i].block_nums.reserve (num_blocks);
      for (uint32_t j = 0; j < num_blocks; j++)
	pdb->streams[i].block_nums.push_back (
	  pdb_read_block_number (pdb, next_u32 ("stream block list"),
				 "stream block list"));
    }

  /* Print stream count and each stream size at verbose debug level.  */
  pdb_dbg_printf_v ("stream directory: %zu streams", pdb->streams.size ());
  for (uint32_t i = 0; i < pdb->streams.size (); i++)
    {
      uint32_t sz = pdb->streams[i].size;
      if (sz == 0)
	{
	  pdb_dbg_printf_v ("  stream %u: <unused>", i);
	  continue;
	}

      pdb_dbg_printf_v ("  stream %u: %u bytes", i, sz);

      if (pdb_read_debug >= 3 && !pdb->streams[i].block_nums.empty ())
	{
	  /* Print block numbers per stream only at trace level to avoid
	     large debug output on PDBs with many streams.  */
	  std::string blks;
	  for (uint32_t block_idx = 0;
	       block_idx < pdb->streams[i].block_nums.size (); block_idx++)
	    {
	      if (block_idx > 0)
		blks += ", ";
	      blks += std::to_string (pdb->streams[i].block_nums[block_idx]);
	    }

	  pdb_dbg_printf_t ("    blocks: [%s]", blks.c_str ());
	}
    }

  return true;
}

/* See pdb-internal.h.  */

gdb::byte_vector
pdb_per_objfile::read_stream (uint32_t stream_idx) const
{
  if (stream_idx >= streams.size ())
    return {};

  const msf_stream &stream = streams[stream_idx];
  if (stream.size == 0)
    return {};

  return pdb_stitch_blocks (this, stream.block_nums.data (), stream.size,
			    "stream");
}

pdb_file_mapping::~pdb_file_mapping ()
{
  if (base == nullptr)
    return;
#ifdef _WIN32
  UnmapViewOfFile ((void *) base);
  if (map_handle != nullptr)
    CloseHandle ((HANDLE) map_handle);
#else
  munmap ((void *) base, size);
#endif
}

/* See pdb-internal.h.  */

bool
pdb_map_file (pdb_per_objfile *pdb)
{
  if (pdb->file_mapping.ok ())
    return true;
  if (pdb->pdb_file == nullptr)
    return false;

  uint64_t size = pdb->msf_size != 0
		    ? pdb->msf_size
		    : (uint64_t) pdb->num_blocks * pdb->block_size;
  if (size == 0)
    return false;

  int fd = fileno (pdb->pdb_file.get ());
  if (fd < 0)
    return false;

#ifdef _WIN32
  HANDLE fh = (HANDLE) _get_osfhandle (fd);
  if (fh == INVALID_HANDLE_VALUE)
    return false;
  HANDLE mh = CreateFileMapping (fh, nullptr, PAGE_READONLY, 0, 0, nullptr);
  if (mh == nullptr)
    return false;
  void *base = MapViewOfFile (mh, FILE_MAP_READ, 0, 0, 0);
  if (base == nullptr)
    {
      CloseHandle (mh);
      return false;
    }
  pdb->file_mapping.map_handle = mh;
#else
  void *base = mmap (nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0);
  if (base == MAP_FAILED)
    return false;
#endif
  pdb->file_mapping.base = (const gdb_byte *) base;
  pdb->file_mapping.size = size;
  return true;
}

/* See pdb-internal.h.  */

const gdb_byte *
pdb_stream_bytes (pdb_per_objfile *pdb, uint32_t stream_idx, uint32_t off,
		  uint32_t len, gdb::byte_vector &scratch)
{
  const pdb_file_mapping &map = pdb->file_mapping;
  gdb_assert (map.ok ());
  gdb_assert (stream_idx < pdb->streams.size ());

  const msf_stream &stream = pdb->streams[stream_idx];
  uint32_t bs = pdb->block_size;

  if ((uint64_t) off + len > stream.size)
    pdb_error ("stream %u: read of %u bytes at offset %u exceeds its %u"
	       " bytes", stream_idx, len, off, stream.size);

  /* block_size is a power of two (validated at load). Calculate a shift
     and a mask instead of using divide and a modulo.  */
  uint32_t block_shift = 0;

  while ((bs >> block_shift) > 1)
    block_shift++;

  uint32_t block_mask = bs - 1;
  uint32_t b = off >> block_shift;
  uint32_t in_block = off & block_mask;

  gdb_assert (b < stream.block_nums.size ());

  uint32_t phys_block = stream.block_nums[b];
  gdb_assert (phys_block < pdb->num_blocks);

  if (in_block + len <= bs)
    return map.base + (uint64_t) phys_block * bs + in_block;

  /* The range spans a block boundary.  Gather it block by block: each
     step starts at the current offset inside its block (cur_in) and
     copies up to that block's end, so a mid-block start and a span over
     more than two blocks are both handled.  */
  scratch.resize (len);
  uint32_t copied = 0;
  while (copied < len)
    {
      uint32_t cur_b = (off + copied) >> block_shift;
      uint32_t cur_in = (off + copied) & block_mask;
      gdb_assert (cur_b < stream.block_nums.size ());
      uint32_t cur_phys = stream.block_nums[cur_b];
      gdb_assert (cur_phys < pdb->num_blocks);
      uint32_t chunk = std::min (len - copied, bs - cur_in);
      memcpy (scratch.data () + copied,
	      map.base + (uint64_t) cur_phys * bs + cur_in, chunk);
      copied += chunk;
    }
  return scratch.data ();
}

/* See pdb-internal.h.  */

std::string
pdb_format_guid (const gdb_byte *g)
{
  return string_printf ("%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X",
			read_u32 (g), read_u16 (g + 4), read_u16 (g + 6), g[8],
			g[9], g[10], g[11], g[12], g[13], g[14], g[15]);
}

/* Pointers reference bytes inside pdb->info_data, the cached copy of the
   Info stream populated by pdb_read_info_stream.  */
struct pdb_info_stream
{
  uint32_t version;
  uint32_t signature;
  uint32_t age;
  /* 16 bytes.  */
  const gdb_byte *guid;
  /* Named stream map start.  */
  const gdb_byte *map;
  /* Named stream map size.  */
  uint32_t map_size;
};

/* Read the PDB Info stream (stream 1) and decode its fixed header
   (version, signature, age, GUID) into the returned pdb_info_stream.
   The raw bytes are cached on pdb->info_data so subsequent calls reuse
   the cached copy.  map/map_size are set to the bytes that follow the
   fixed header so the caller can hand them to
   pdb_parse_named_stream_map.  The returned struct holds pointers into
   the cached bytes, not copies.  */

static pdb_info_stream
pdb_read_info_stream (pdb_per_objfile *pdb)
{
  if (pdb->info_data.empty ())
    {
      pdb->info_data = pdb->read_stream (PDB_STREAM_PDB);
      if (pdb->info_data.empty ())
	pdb_error ("Failed to read PDB info stream (stream 1)");
    }

  gdb_byte *data = pdb->info_data.data ();
  size_t size = pdb->info_data.size ();
  if (size < INFO_STREAM_MIN_SIZE)
    pdb_error ("PDB info stream too small (%zu bytes)", size);

  pdb_info_stream info;
  info.version = read_u32 (&data[0]);
  info.signature = read_u32 (&data[4]);
  info.age = read_u32 (&data[8]);
  info.guid = &data[12];
  info.map = &data[INFO_STREAM_HASH_MAP_OFFS];
  info.map_size = size - INFO_STREAM_HASH_MAP_OFFS;
  return info;
}

/* Validate that the PDB info stream's GUID/age match the EXE's CodeView
   RSDS record.  Returns true on match, false on mismatch.  On false, the
   caller MUST drop this PDB file: symbol offsets, line tables and type
   indices are all keyed to the exact build that produced the EXE, so a
   mismatched PDB cannot be safely used.  Mirrors the build-id check
   GDB performs for separate debug files (see build_id_verify).

   TODO: Implement logic that will skip wrong candidates and keep searching
   other locations for the PDB with matching GUID/age.  */

static bool
pdb_validate_guid (pdb_per_objfile *pdb, const pdb_rsds_info &rsds,
		   const pdb_info_stream &info)
{
  if (memcmp (info.guid, rsds.guid.data (), 16) == 0 && info.age == rsds.age)
    return true;

  pdb_load_diagnostic (pdb->objfile,
		       "PDB '%s' has a different GUID/age, file skipped:\n"
		       "  EXE expects GUID=%s age=%u\n"
		       "  PDB provides GUID=%s age=%u",
		       pdb->pdb_file_path.c_str (),
		       pdb_format_guid (rsds.guid.data ()).c_str (), rsds.age,
		       pdb_format_guid (info.guid).c_str (), info.age);
  return false;
}

/* One entry in the Named Stream Map: stream name -> stream index.
   NAME points into the cached PDB info stream StringBuffer, so it
   stays valid for the lifetime of the pdb_per_objfile.  */
struct pdb_named_stream
{
  const char *name;
  uint32_t stream_idx;
};

/* Decoded Named Stream Map from the PDB info stream.  An empty `entries`
   vector means the map was missing or corrupt; callers can treat that the
   same as "name not found" via lookup().  */
struct pdb_named_stream_map
{
  std::vector<pdb_named_stream> entries;

  /* Return the stream index registered for NAME, or PDB_NO_STREAM if
     NAME is not present in the map.  */
  uint32_t lookup (const char *name) const
  {
    for (const auto &e : entries)
      if (strcmp (e.name, name) == 0)
	return e.stream_idx;
    return PDB_NO_STREAM;
  }
};

/* One present bucket of a serialized PDB hash table: the raw uint32 key and
   value, interpreted by the caller.  */
struct pdb_hash_bucket
{
  uint32_t key;
  uint32_t value;
};

/* Decode the serialized hash table beginning at HT, bounded by END.
   On-disk layout (microsoft-pdb HashTable):
     uint32_t Size;
     uint32_t Capacity;
     uint32_t PresentWordCount;  uint32_t Present[PresentWordCount];
     uint32_t DeletedWordCount;  uint32_t Deleted[DeletedWordCount];
     { uint32_t Key; uint32_t Value; } Buckets[popcount (Present)];
   One bucket is stored per set bit in the Present bit-vector.  On corruption
   emits a warning and returns std::nullopt.  */

static std::optional<std::vector<pdb_hash_bucket>>
pdb_decode_hash_table (const gdb_byte *ht, const gdb_byte *end)
{
  if (ht + HASH_TABLE_PRESENT_WORD_OFFS > end)
    {
      pdb_warning ("PDB hash table too small for header");
      return {};
    }

  uint32_t size = read_u32 (ht + HASH_TABLE_SIZE_OFFS);
  uint32_t capacity = read_u32 (ht + HASH_TABLE_CAPACITY_OFFS);
  uint32_t present_words = read_u32 (ht + HASH_TABLE_PRESENT_CNT_OFFS);
  const gdb_byte *present_bits = ht + HASH_TABLE_PRESENT_WORD_OFFS;

  pdb_dbg_printf ("Hash table: size=%u, capacity=%u, present_words=%u", size,
		  capacity, present_words);

  /* Header + present bit-vector + the DeletedWordCount field must fit.  */
  const gdb_byte *deleted_cnt_ptr
    = present_bits + present_words * HASH_TABLE_BYTES_PER_WORD;
  if (deleted_cnt_ptr + HASH_TABLE_BYTES_PER_WORD > end)
    {
      pdb_warning ("PDB hash table too small for header "
		   "and present bit vector");
      return {};
    }

  uint32_t deleted_words = read_u32 (deleted_cnt_ptr);

  const gdb_byte *table = deleted_cnt_ptr + HASH_TABLE_BYTES_PER_WORD
			  + deleted_words * HASH_TABLE_BYTES_PER_WORD;

  std::vector<pdb_hash_bucket> buckets;
  buckets.reserve (size);

  for (uint32_t i = 0; i < capacity; i++)
    {
      /* The bucket array holds only present entries and the on-disk table may
	 end right after the last one, so bound-check each step instead of
	 assuming CAPACITY entries.  */
      if (table + HASH_TABLE_ENTRY_SIZE > end)
	{
	  pdb_warning ("PDB hash table truncated past the %uth entry", i);
	  break;
	}

      uint32_t word_idx = i / HASH_TABLE_BIT_WORD_SIZE;
      uint32_t bit_idx = i % HASH_TABLE_BIT_WORD_SIZE;
      if (word_idx >= present_words
	  || !(read_u32 (present_bits + word_idx * sizeof (uint32_t))
	       & (1 << bit_idx)))
	continue;

      uint32_t key = read_u32 (table + 0);
      uint32_t value = read_u32 (table + HASH_TABLE_KEY_SIZE);
      table += HASH_TABLE_ENTRY_SIZE;

      buckets.push_back ({ key, value });
    }

  return buckets;
}

/* Parse the Named Stream Map embedded in the PDB info stream and return
   it as a flat list of (name, stream_idx) pairs.  See LLVM "PDB Info
   Stream" docs for the on-disk layout.  On corruption, emits a warning
   and returns an empty map.  */

static pdb_named_stream_map
pdb_parse_named_stream_map (const pdb_info_stream &info)
{
  pdb_named_stream_map result;

  const gdb_byte *map = info.map;
  uint32_t map_size = info.map_size;
  const gdb_byte *map_end = map + map_size;

  /* Check that there is at least one entry: 4 bytes each for StringBuffer
     Size, HashTable Size/Capacity, PresentWordCount and DeletedWordCount,
     20 bytes total.  */
  if (map_size < NAMES_MAP_STRBUF_SIZE_OFFS + 5 * NAMES_MAP_UINT32_SIZE)
    {
      /* TODO: distinguish an absent named stream map (map_size == 0) from
	 a corrupt one.  */
      pdb_warning ("PDB info stream too small for named stream map header");
      return result;
    }

  /* Get pointer to StringBuffer and its size.  */
  const gdb_byte *strbuf = map + NAMES_MAP_STRBUF_OFFS;
  uint32_t strbuf_size = read_u32 (map + NAMES_MAP_STRBUF_SIZE_OFFS);
  if (strbuf_size > map_size - NAMES_MAP_STRBUF_OFFS)
    {
      pdb_warning ("PDB named stream map string buffer overflows its stream");
      return result;
    }
  const gdb_byte *strbuf_end = strbuf + strbuf_size;

  /* Print String Buffer content.  */
  pdb_dbg_printf_v ("  StringBuffer contents:");
  for (uint32_t i = 0; i < strbuf_size;)
    {
      const char *name = pdb_extract_string (strbuf + i, strbuf_end);
      if (name == nullptr)
	break;
      pdb_dbg_printf_v ("    [%u] '%s'", i, name);
      i += strlen (name) + 1;
    }

  /* The serialized hash table follows the StringBuffer; each bucket key is
     an offset into that buffer and each value a stream index.  */
  auto buckets = pdb_decode_hash_table (strbuf_end, map_end);
  if (!buckets)
    return result;

  result.entries.reserve (buckets->size ());
  for (const auto &b : *buckets)
    {
      if (b.key >= strbuf_size)
	continue;

      const char *name = pdb_extract_string (strbuf + b.key, strbuf_end);
      if (name == nullptr)
	continue;
      pdb_dbg_printf_v (" Named stream: '%s' -> stream %u", name, b.value);
      result.entries.push_back ({ name, b.value });
    }

  return result;
}

/* Read the /names stream and fill the global string table.
   INFO is the already-decoded PDB info stream header; we reuse it for
   the named-stream map.  */

static bool
pdb_read_names_stream (pdb_per_objfile *pdb, const pdb_info_stream &info)
{
  pdb->string_table = nullptr;
  pdb->string_table_size = 0;

  pdb_dbg_printf ("PDB Info Stream: version:%u, signature:0x%08X, age=%u",
		  info.version, info.signature, info.age);

  /* Decode the Named Stream Map and look up "/names".  */
  auto nsm = pdb_parse_named_stream_map (info);
  uint32_t names_stream = nsm.lookup ("/names");

  if (names_stream == PDB_NO_STREAM || names_stream >= pdb->streams.size ())
    {
      pdb_warning ("/names stream not found");
      return false;
    }

  pdb_dbg_printf ("  Found /names stream at index %u", names_stream);

  /* Read the /names stream and fill the global string table.
     Move into pdb->names_data — string_table points into it for
     the objfile lifetime.  */

  pdb->names_data = pdb->read_stream (names_stream);
  if (pdb->names_data.empty ())
    {
      pdb_warning ("No data in /names stream");
      return false;
    }

  gdb_byte *names_p = pdb->names_data.data ();
  size_t names_size = pdb->names_data.size ();

  if (names_size < NAMES_STREAM_MIN_SIZE)
    {
      pdb_warning ("/names stream too small (%zu bytes)", names_size);
      return false;
    }

  uint32_t names_sig = read_u32 (names_p + NAMES_STREAM_SIGNATURE_OFFS);
  uint32_t data_sz = read_u32 (names_p + NAMES_STREAM_DATA_SIZE_OFFS);

  if (names_sig != NAMES_STREAM_SIGNATURE_VAL)
    pdb_error ("unexpected /names signature");

  if (NAMES_STREAM_MIN_SIZE + data_sz > names_size)
    pdb_error ("/names string data extends beyond stream");

  pdb->string_table = names_p + NAMES_STREAM_MIN_SIZE;
  pdb->string_table_size = data_sz;

  /* Global string table loaded.  */

  /* Print all strings at debug level 2.  */
  if (pdb_read_debug >= 2)
    {
      const gdb_byte *st = pdb->string_table;
      const gdb_byte *st_end = st + data_sz;
      for (const gdb_byte *s = st; s < st_end; s++)
	{
	  if (*s != '\0' && (s == st || *(s - 1) == '\0'))
	    {
	      debug_prefixed_printf_cond (true, "pdb",
					  "  String table[offset=%u]: %s",
					  (uint32_t) (s - st), CSTR (s));
	    }
	}
    }

  return true;
}

/* Find the end of a null-terminated string at P within [P, END).  Returns a
   pointer past the null terminator.  Calls pdb_error with MSG if no null
   byte is found within bounds.  */

static const gdb_byte *
pdb_skip_cstring (const gdb_byte *p, const gdb_byte *end, const char *msg)
{
  auto nul = (const gdb_byte *) memchr (p, 0, end - p);
  if (nul == nullptr)
    pdb_error ("Truncated %s in module info", msg);

  return nul + 1;
}

/* Read the code entries of the Section Contribution substream, which
   follows the MOD_INFO_SIZE bytes of Module Info, into
   pdb->code_contribs.  A module header names only one contribution; a
   module compiled with a section per function has one per function.  An
   absent or malformed substream leaves the list empty.  */

static void
pdb_read_code_contribs (pdb_per_objfile *pdb, uint32_t mod_info_size)
{
  const gdb_byte *dbi = pdb->dbi_data.data ();
  uint64_t offset = (uint64_t) DBI_HDR_SIZE + mod_info_size;
  uint32_t size = read_u32 (dbi + DBI_HDR_SECT_CONTRIB_OFFS);
  if (size < 4 || offset > pdb->dbi_data.size ()
      || size > pdb->dbi_data.size () - offset)
    return;

  const gdb_byte *p = dbi + offset;
  uint32_t version = read_u32 (p);
  size_t entry_size;
  if (version == DBI_SC_VER_60)
    entry_size = DBI_SC_ENTRY_SIZE;
  else if (version == DBI_SC_VER_2)
    entry_size = DBI_SC2_ENTRY_SIZE;
  else
    {
      pdb_warning ("unknown section contribution version 0x%x", version);
      return;
    }

  size_t count = (size - 4) / entry_size;
  p += 4;
  for (size_t i = 0; i < count; i++, p += entry_size)
    {
      uint32_t characteristics = read_u32 (p + DBI_SC_CHARACTERISTICS_OFFS);
      uint32_t contrib_size = read_u32 (p + DBI_SC_SIZE_OFFS);
      uint16_t imod = read_u16 (p + DBI_SC_IMOD_OFFS);
      if ((characteristics & (PDB_SCN_CODE | PDB_SCN_EXECUTE)) == 0
	  || contrib_size == 0 || imod >= pdb->modules.size ())
	continue;

      pdb->code_contribs.push_back ({ read_u16 (p + DBI_SC_ISECT_OFFS), imod,
				     read_u32 (p + DBI_SC_OFFSET_OFFS),
				     contrib_size });
    }

  pdb_dbg_printf ("DBI section contributions: %zu code of %zu",
		  pdb->code_contribs.size (), count);
}

/* Read DBI (Debug Info) stream.  Reads headers and Module Info Records in order
   to obtain the sizes and stream numbers of the debug information for each
   module (object file).  The sizes are used to allocate enough space needed to
   hold the debug information for each module.  Throws via pdb_error on
   failure.  */

static void
pdb_read_dbi_stream (pdb_per_objfile *pdb)
{
  /* Read DBI stream into the owned buffer — module names and
     file_info_names_buffer point into it.  */
  pdb->dbi_data = pdb->read_stream (PDB_STREAM_DBI);
  if (pdb->dbi_data.empty ())
    pdb_error ("Failed to read DBI stream");
  if (pdb->dbi_data.size () < DBI_HDR_MODULE_INFO_OFFS)
    pdb_error ("DBI stream too small for its header (%zu bytes)",
	       pdb->dbi_data.size ());

  /* Parse DBI header.  */

  gdb_byte *dbi_hdr = pdb->dbi_data.data ();
  uint32_t signature = read_u32 (dbi_hdr + DBI_HDR_SIGNATURE_OFFS);

  if (signature != DBI_HDR_SIGNATURE_VAL)
    pdb_error ("Invalid DBI signature: 0x%x", signature);

  /* Read sizes from DBI header.  */

  uint32_t mod_info_size = read_u32 (dbi_hdr + DBI_HDR_MODULE_SIZE_OFFS);
  if (mod_info_size > pdb->dbi_data.size () - DBI_HDR_MODULE_INFO_OFFS)
    pdb_error ("DBI module info (%u bytes) overflows the stream",
	       mod_info_size);
  pdb->gsi_stream = read_u16 (dbi_hdr + DBI_HDR_GSI_STREAM_OFFS);
  pdb->psgsi_stream = read_u16 (dbi_hdr + DBI_HDR_PSGSI_STREAM_OFFS);
  pdb->sym_record_stream = read_u16 (dbi_hdr + DBI_HDR_SYM_RECORD_STREAM_OFFS);

  pdb_dbg_printf ("DBI header: signature=0x%08x module_info_size=%u"
		  " gsi=%u psgsi=%u sym_record_stream=%u",
		  signature, mod_info_size, pdb->gsi_stream, pdb->psgsi_stream,
		  pdb->sym_record_stream);

  /* Module info starts right after the DBI header.  */
  gdb_byte *mod_info = dbi_hdr + DBI_HDR_MODULE_INFO_OFFS;
  const gdb_byte *mod_info_end = mod_info + mod_info_size;

  if (mod_info_size == 0)
    {
      pdb_warning ("Module info empty, no modules to parse");
      return;
    }

  /* Two-pass: first count modules so we can size the vector exactly,
     then parse each MODI record into its slot.  */
  uint32_t num_modules = 0;
  const gdb_byte *cp = mod_info;

  while (cp + MODI_FIXED_SIZE < mod_info_end)
    {
      /* Skip 64-byte fixed header to get to module names.  */
      cp += MODI_FIXED_SIZE;

      /* Module name (null-terminated).  */
      cp = pdb_skip_cstring (cp, mod_info_end, "module name");

      /* Object file name (null-terminated).  */
      cp = pdb_skip_cstring (cp, mod_info_end, "obj file name");

      /* Align to 4 bytes.  */
      cp = align_up (cp, 4);

      num_modules++;

      /* Safety limit.  */
      if (num_modules > 10000)
	pdb_error ("Too many modules: %u", num_modules);
    }

  pdb_dbg_printf ("Found %u modules", num_modules);

  pdb->modules.resize (num_modules);

  /* Parse module info records.  */
  gdb_byte *p = mod_info;
  for (uint32_t i = 0; i < num_modules; i++)
    {
      pdb_module_info *module = &pdb->modules[i];

      /* MODI fixed header fields (0x40 bytes per LLVM/MS spec).  */
      module->stream_number = read_u16 (p + MODI_STREAM_NUM_OFFS);
      module->flags = read_u16 (p + MODI_FLAGS_OFFS);
      module->sym_byte_size = read_u32 (p + MODI_SYM_BYTES_OFFS);
      module->c11_byte_size = read_u32 (p + MODI_C11_BYTES_OFFS);
      module->c13_byte_size = read_u32 (p + MODI_C13_BYTES_OFFS);

      /* Section contribution.  */
      module->sc_section = read_u16 (p + MODI_SC_ISECT_OFFS);
      module->sc_offset = read_u32 (p + MODI_SC_OFFSET_OFFS);
      module->sc_size = read_u32 (p + MODI_SC_SIZE_OFFS);

      /* Module name starts at offset 0x40.  */
      p += MODI_FIXED_SIZE;

      module->module_name = (char *) p;
      p = (gdb_byte *) pdb_skip_cstring (p, mod_info_end, "module name");

      /* Read object file name.  */
      module->obj_file_name = (char *) p;
      p = (gdb_byte *) pdb_skip_cstring (p, mod_info_end, "obj file name");

      /* Align to 4-byte boundary for next MODI record.  */
      p = align_up (p, 4);

      pdb_dbg_printf_v ("  Module %u: stream=%u %s"
			" (sym=%u, c11=%u, c13=%u)",
			i, module->stream_number,
			module->module_name ? module->module_name : "<empty>",
			module->sym_byte_size, module->c11_byte_size,
			module->c13_byte_size);
    }

  pdb_dbg_printf ("Finished parsing all modules");

  pdb_read_code_contribs (pdb, mod_info_size);
}

/* Read section addresses from BFD.  */

static bool
pdb_read_section_addresses (pdb_per_objfile *pdb)
{
  if (pdb->objfile->obfd == nullptr)
    {
      pdb_warning ("No BFD available for section mapping");
      return false;
    }

  for (asection *sect : gdb_bfd_sections (pdb->objfile->obfd))
    pdb->section_addresses.push_back (bfd_section_vma (sect));

  if (pdb->section_addresses.empty ())
    {
      pdb_warning ("No sections found in BFD");
      return false;
    }

  return true;
}

/* See pdb-internal.h.  */

CORE_ADDR
pdb_per_objfile::map_section_offset_to_pc (uint16_t section, uint32_t offset)
{
  if (section == 0 || section > section_addresses.size ())
    {
      pdb_complaint ("Invalid section number %u (max %zu)", section,
		     section_addresses.size ());
      return 0;
    }

  /* Get section base address (VMA from PE header).  */
  CORE_ADDR section_base = section_addresses[section - 1];

  /* Apply relocation offset (difference between linked and loaded address).  */
  CORE_ADDR reloc_offset = objfile->section_offsets[section - 1];

  /* Calculate final address: section VMA + relocation + offset.  */
  CORE_ADDR result = section_base + reloc_offset + offset;

  return result;
}

/* See pdb-internal.h.  */

CORE_ADDR
pdb_per_objfile::map_section_offset_unrelocated (uint16_t section,
						 uint32_t offset)
{
  if (section == 0 || section > section_addresses.size ())
    {
      pdb_complaint ("Invalid section number %u (max %zu)", section,
		     section_addresses.size ());
      return 0;
    }

  return section_addresses[section - 1] + offset;
}

/* See pdb-internal.h.  */

CORE_ADDR
pdb_per_objfile::section_reloc (uint16_t section) const
{
  if (section == 0 || section > section_addresses.size ())
    return 0;

  return objfile->section_offsets[section - 1];
}

/* Read a module stream and extract C13 file checksums.  Returns an owned
   buffer containing the stream data; the caller keeps it alive as long as
   the data is needed (for symbol parsing, line walking, etc.).
   File checksums are copied onto the objfile obstack so they survive
   after the buffer is freed.  */

gdb::byte_vector
pdb_read_module_stream (pdb_per_objfile *pdb, pdb_module_info *module)
{
  if (module->stream_number == 0xFFFF)
    return {};

  auto buf = pdb->read_stream (module->stream_number);
  if (buf.empty ())
    return {};

  gdb_byte *stream = buf.data ();
  uint32_t stream_size = pdb->streams[module->stream_number].size;

  /* Validate that sym + c11 + c13 sizes fit within the stream.  */
  uint64_t fixed_part_size = (uint64_t) module->sym_byte_size
			     + (uint64_t) module->c11_byte_size;

  if (fixed_part_size > stream_size)
    pdb_error ("Module %u: sym+c11 sizes exceed stream size",
	       module->stream_number);

  if (module->c13_byte_size > stream_size - fixed_part_size)
    pdb_error ("Module %u: c13 size exceeds stream size",
	       module->stream_number);

  if (module->c13_byte_size == 0)
    return buf;

  gdb_byte *c13_start = stream + module->sym_byte_size + module->c11_byte_size;
  uint32_t c13_size = module->c13_byte_size;

  /* Parse C13 subsections.  */
  gdb_byte *p = c13_start;
  const gdb_byte *c13_end = c13_start + c13_size;

  /* Skip CV signature if present.  */
  if (p + CV_SIGNATURE_SIZE <= c13_end
      && read_cv_signature (p) == CV_SIGNATURE_C13)
    p += CV_SIGNATURE_SIZE;

  /* Parse subsections.  */
  while (p + C13_SUBSECT_HEADER_SIZE <= c13_end)
    {
      uint32_t subsect_type = read_u32 (p);
      uint32_t subsect_size = read_u32 (p + 4);
      p += C13_SUBSECT_HEADER_SIZE;

      if (subsect_size > (size_t) (c13_end - p))
	pdb_error ("C13 subsection extends beyond stream");

      switch (subsect_type)
	{
	case DEBUG_S_LINES:
	  /* Processed on demand by pdb_walk_c13_line_blocks when
	     pdb_build_module expands this module.  */
	  break;

	case DEBUG_S_FILECHKSMS:
	  /* Copy the checksums block onto the objfile obstack so it
	     survives after the module stream is freed.  Keep the first copy:
	     already-resolved file entries point into it.  */
	  if (module->file_checksums == nullptr)
	    {
	      auto copy = (gdb_byte *)
		obstack_alloc (&pdb->objfile->objfile_obstack, subsect_size);
	      memcpy (copy, p, subsect_size);
	      module->file_checksums = copy;
	      module->file_checksums_size = subsect_size;
	    }

	  break;

	case DEBUG_S_INLINEELINES:
	  /* Copy the inlinee-line table onto the objfile obstack; it maps each
	     inlined function's IPI id to its base source file/line and is read
	     while parsing S_INLINESITE records.  */
	  if (module->inlinee_lines == nullptr)
	    {
	      auto copy = (gdb_byte *)
		obstack_alloc (&pdb->objfile->objfile_obstack, subsect_size);
	      memcpy (copy, p, subsect_size);
	      module->inlinee_lines = copy;
	      module->inlinee_lines_size = subsect_size;
	    }

	  break;

	default:
	  break;
	}

      p += subsect_size;

      /* Align to 4-byte boundary.  */
      p = align_up (p, 4);
    }

  return buf;
}

/* Get string from the global string table (/names stream) at given offset.  */

static const char *
pdb_string_table_get (const gdb_byte *string_table, uint32_t table_size,
		      uint32_t offset)
{
  if (string_table == nullptr || offset >= table_size)
    return nullptr;

  return pdb_extract_string (string_table + offset, string_table + table_size);
}

/* See pdb-internal.h.  */

const char *
pdb_get_filename_from_file_id (const pdb_per_objfile *pdb,
			       pdb_module_info *module, uint32_t file_id)
{
  if (module->file_checksums == nullptr)
    {
      printf_unfiltered ("  file_checksums is nullptr");
      return nullptr;
    }

  /* Access filename through the global string table from /names stream.  */
  if (pdb->string_table == nullptr)
    return nullptr;

  /* Parse file checksums to find the entry for this file_id.  */
  gdb_byte *p = module->file_checksums;
  const gdb_byte *end = p + module->file_checksums_size;

  /* file_id is a byte offset into the DEBUG_S_FILECHKSMS subsection so it
     cannot exceed the checksums size.  */
  if (file_id >= module->file_checksums_size)
    pdb_error ("file_id %u beyond file checksums size %u", file_id,
	       module->file_checksums_size);

  /* Move pointer to the start of file checksums.  */
  p += file_id;

  /* Check that the file checksum record header fits within the buffer.  */
  if (p + CV_FileChecksum::HDR_SIZE > end)
    pdb_error ("file checksum record truncated at offset %u", file_id);

  CV_FileChecksum checksum (p);

  auto filename = pdb_string_table_get (pdb->string_table,
					pdb->string_table_size,
					checksum.file_name_offs);

  /* Return filename, fall back to module name, then "<unknown>".  */
  if (filename != nullptr)
    return filename;

  if (module->module_name != nullptr)
    return module->module_name;

  return "<unknown>";
}

/* Walk all DEBUG_S_LINES subsections in a module's C13 data.  For each file
   block, invokes CALLBACK with the resolved filename and the raw line array
   view.  MODULE_STREAM is the raw module stream data.  */

void
pdb_walk_c13_line_blocks (const pdb_per_objfile *pdb, pdb_module_info *module,
			  gdb_byte *module_stream, pdb_line_block_fn callback)
{
  /* Callers must verify there is C13 data before calling.  */
  gdb_assert (module->c13_byte_size > 0);

  gdb_byte *c13_start = module_stream + module->sym_byte_size
			+ module->c11_byte_size;
  const gdb_byte *c13_end = c13_start + module->c13_byte_size;
  gdb_byte *p = c13_start;

  /* Skip CV signature if present.  */
  if (p + CV_SIGNATURE_SIZE <= c13_end
      && read_cv_signature (p) == CV_SIGNATURE_C13)
    p += CV_SIGNATURE_SIZE;

  /* See pdb.h for C13 block layout.  */

  /* Do not access past the end of the C13.  */
  while (p + C13_SUBSECT_HEADER_SIZE <= c13_end)
    {
      /* Read subsection header.  */
      uint32_t subsect_type = read_u32 (p);
      uint32_t subsect_size = read_u32 (p + 4);
      p += C13_SUBSECT_HEADER_SIZE;

      if (subsect_size > (size_t) (c13_end - p))
	pdb_error ("C13 subsection type 0x%x size %u overflows stream",
		   subsect_type, subsect_size);

      if (subsect_type != DEBUG_S_LINES)
	{
	  p += subsect_size;
	  /* Align to 4-byte boundary.  */
	  p = align_up (p, 4);
	  continue;
	}

      gdb_byte *sp = p;
      const gdb_byte *sp_end = p + subsect_size;

      /* Ensure there's enough space for the header.  */
      if (sp + CV_LineSection::SIZE > sp_end)
	pdb_error ("DEBUG_S_LINES subsection too small for header"
		   " (%u bytes)",
		   subsect_size);

      CV_LineSection ls (sp);
      sp += CV_LineSection::SIZE;

      /* Each line has a CV_Line and, with CV_LINES_HAVE_COLUMNS, a 4-byte
	 column record.  */
      uint64_t entry_size
	= CV_Line::SIZE + ((ls.flags & CV_LINES_HAVE_COLUMNS) != 0 ? 4 : 0);

      /* Iterate file blocks within this subsection.  */
      while (sp + CV_FileBlock::SIZE <= sp_end)
	{
	  CV_FileBlock fb (sp);
	  uint32_t file_id = fb.file_id;
	  uint32_t num_lines = fb.num_lines;
	  uint32_t block_size = fb.block_size;

	  if (block_size < CV_FileBlock::SIZE
	      || block_size > (size_t) (sp_end - sp))
	    break;

	  gdb_byte *line_data = sp + CV_FileBlock::SIZE;
	  if (num_lines * entry_size > block_size - CV_FileBlock::SIZE)
	    break;

	  /* Resolve filename from file checksums + string table.  */
	  auto fname = pdb_get_filename_from_file_id (pdb, module, file_id);
	  if (fname == nullptr)
	    fname = "<unknown>";

	  pdb_dbg_printf_v ("Line block: file=%s, section=%u, offset=%u, "
			    "size=%u, num_lines=%u",
			    fname, ls.seci, ls.offs, ls.code_sz, num_lines);

	  callback (fname, ls, line_data, num_lines);

	  sp += block_size;
	}

      /* Advance past this subsection and align to 4-byte boundary.  */
      p += subsect_size;
      p = align_up (p, 4);
    }
}

/* Callback body for pdb_walk_c13_line_blocks: emit one file's line table
   into CU.  Converts the file path for display, opens a subfile, then
   resolves each CV_Line to an unrelocated PC via the section map and
   records it.  Lines that don't map to any PC (pc == 0) are skipped.
   All PDB line entries are marked LEF_IS_STMT.

   Each DEBUG_S_LINES subsection covers one contiguous code range
   (CV_LineSection.code_sz bytes from sect:offs).  We close it with an
   end-of-sequence marker (line 0) at its end PC so the last line does not
   extend into whatever code follows the range.  */

/* True when one of the NUM_LINES entries of LINE_SECT already sits at PC.  */

static bool
pdb_block_has_line_at (pdb_per_objfile *pdb, CV_LineSection line_sect,
		       const gdb_byte *lines, uint32_t num_lines, CORE_ADDR pc)
{
  for (uint32_t i = 0; i < num_lines; i++)
    {
      CV_Line line (lines + i * CV_Line::SIZE);
      if (pdb->map_section_offset_to_pc (line_sect.seci,
					 line_sect.offs + line.offs) == pc)
	return true;
    }

  return false;
}

static void
pdb_record_line_block (pdb_per_objfile *pdb, buildsym_compunit *cu,
		       const char *filename, CV_LineSection line_sect,
		       const gdb_byte *lines, uint32_t num_lines,
		       const std::unordered_map<CORE_ADDR, pdb_prologue_end> &prologue_ends,
		       pdb_symbol_lines *sym_lines)
{
  uint16_t sect = line_sect.seci;
  uint32_t sect_offs = line_sect.offs;

  /* Convert MSYS2/Unix paths to Windows paths for source display.  */
  std::string path = pdb_convert_path (filename);

  pdb_dbg_printf_v ("add linetable: file='%s', lines=%u, section=%u,"
		    " offs=0x%x",
		    path.c_str (), num_lines, sect, sect_offs);

  subfile *current_subfile = cu->start_subfile (path.c_str (), path.c_str ());

  for (uint32_t i = 0; i < num_lines; i++)
    {
      CV_Line line (lines + i * CV_Line::SIZE);
      uint32_t offs = line.offs;
      uint32_t line_num = line.line_start;

      CORE_ADDR pc = pdb->map_section_offset_to_pc (sect, sect_offs + offs);
      if (pc == 0)
	{
	  pdb_dbg_printf_v ("line %u: skipped (PC=0)", line_num);
	  continue;
	}

      CORE_ADDR unrelocated = pc - pdb->objfile->text_section_offset ();

      /* 0xfeefee and 0xf00f00 mark code that belongs to no source line,
	 such as compiler-generated code; end the previous line there.  */
      if (line_num == 0xfeefee || line_num == 0xf00f00)
	{
	  sym_lines->rows.push_back ({ pc, 0, current_subfile, LEF_IS_STMT });
	  continue;
	}

      /* Always mark PDB line entries as statements.
	 FIXME: Check how reliably this flag is set by compiler and
	 verify if GDB regularly skips non-statement entries.  */
      linetable_entry_flags flags = LEF_IS_STMT;

      auto pe = prologue_ends.find (pc);

      /* A procedure that sets up nothing has no prologue to skip, and GDB
	 must not treat its first statement as one.  */
      if (pe != prologue_ends.end () && pe->second.pc == pc)
	flags |= LEF_PROLOGUE_END;

      sym_lines->rows.push_back ({ pc, (int) line_num, current_subfile,
				   flags });

      /* Remember the file this line counts within; a procedure's entry PC
	 is where its symbol takes its line from.  First entry wins.  */
      sym_lines->at_pc.emplace (pc,
				pdb_symbol_lines::site { (int) line_num,
							 current_subfile });

      /* CodeView gives a procedure one line entry at its entry point, so
	 GDB would fall back to scanning instructions to find the prologue
	 end and can stop before the parameters are stored.  Mark the end
	 the way DWARF does.  An inferred end is only a guess about code the
	 line table did not describe, so leave any real entry there alone.  */
      if (pe != prologue_ends.end () && pe->second.pc > pc
	  && !(pe->second.inferred
	       && pdb_block_has_line_at (pdb, line_sect, lines, num_lines,
					 pe->second.pc)))
	sym_lines->rows.push_back ({ pe->second.pc, (int) line_num,
				     current_subfile,
				     LEF_IS_STMT | LEF_PROLOGUE_END });

      pdb_dbg_printf_v ("line %u: unrelocated_pc=%s added", line_num,
			paddress (pdb->objfile->arch (), unrelocated));
    }

  /* Close the contribution with an end-of-sequence marker at its end PC, so
     the last line stops here instead of extending into the following code.  */
  if (line_sect.code_sz != 0)
    {
      CORE_ADDR end_pc
	= pdb->map_section_offset_to_pc (sect, sect_offs + line_sect.code_sz);
      if (end_pc != 0)
	sym_lines->rows.push_back ({ end_pc, 0, current_subfile, LEF_IS_STMT });
    }

  pdb_dbg_printf_v ("recorded %u lines", num_lines);
}

/* Hand the module's collected rows to buildsym in address order, closing a
   file's run wherever the next code belongs to a different file.

   CodeView gives each file its own line blocks, and their address ranges
   interleave when one function's code comes from several files (#line
   directives, inlining).  Each file's table alone would then show a line
   running over the other file's code, and GDB takes a line's extent from the
   next entry in the same table -- so `next` would step straight past the
   other file's statement.

   A DWARF line program is already one address-ordered stream, so
   lnp_state_machine just watches for the file to change and closes the
   previous run (gdb/dwarf2/line-program.c).  Sorting is what CodeView needs
   extra; the loop below is that same rule.  */

static void
pdb_emit_lines (pdb_per_objfile *pdb, buildsym_compunit *cu,
		pdb_symbol_lines *sym_lines)
{
  auto &rows = sym_lines->rows;

  std::stable_sort (rows.begin (), rows.end (),
		    [] (const pdb_symbol_lines::row &a,
			const pdb_symbol_lines::row &b)
		    { return a.pc < b.pc; });

  CORE_ADDR text_off = pdb->objfile->text_section_offset ();
  subfile *last_subfile = nullptr;

  for (const auto &r : rows)
    {
      unrelocated_addr addr { r.pc - text_off };

      if (r.line == 0)
	{
	  cu->record_line (r.subfile, 0, addr, LEF_IS_STMT);
	  last_subfile = nullptr;
	  continue;
	}

      if (last_subfile != nullptr && last_subfile != r.subfile)
	cu->record_line (last_subfile, 0, addr, LEF_IS_STMT);

      cu->record_line (r.subfile, r.line, addr, r.flags);
      last_subfile = r.subfile;
    }
}

/* See pdb.h.  */

compunit_symtab *
pdb_build_module (pdb_per_objfile *pdb, pdb_module_info *module)
{
  if (module->expanded)
    return module->cu;

  module->expanded = true;

  /* Symbol lookups issued from inside symtab construction (e.g. from
     check_typedef) would re-enter the reader; the flag makes them bail
     out instead.  */
  scoped_restore decrementer = increment_reading_symtab ();

  /* Read module stream — owned locally, auto-freed at scope exit.  */
  auto stream_buf = pdb_read_module_stream (pdb, module);

  /* Cache file list by reading File Info substream.  */
  pdb_read_module_files (pdb, module);

  /* Skip modules with no code contribution (e.g.  linker-generated,
     resource modules, import libs) or an invalid section number.  */
  if (!pdb->section_valid (module->sc_section))
    return nullptr;

  /* Compute module address range based on section contribution from DBI.  */
  CORE_ADDR low_pc = pdb->map_section_offset_to_pc (module->sc_section,
						    module->sc_offset);
  CORE_ADDR high_pc = low_pc + module->sc_size;
  if (high_pc <= low_pc)
    high_pc = low_pc + 1;

  /* CU name from module_name (always set by pdb_read_dbi_stream).  Naming
     it after the module's primary source file instead reads better in
     "info functions", but makes that file the compunit's main subfile
     rather than one created by start_subfile, which changes the subfile
     layout and broke "break file:line" fall-forward for a function inlined
     across files.  */
  const char *cu_name = module->module_name;

  /* Read the language flag for the module (S_COMPILE2/S_COMPILE3).
     Fall back to C++.  */
  enum language lang = language_cplus;
  if (!stream_buf.empty ())
    lang = pdb_module_language (pdb, module, stream_buf.data ());

  buildsym_compunit cu (pdb->objfile, cu_name, "", lang, low_pc);
  cu.record_debugformat ("CodeView");

  const char *producer = pdb_module_producer (pdb, module,
					      stream_buf.empty ()
					      ? nullptr : stream_buf.data ());
  if (producer != nullptr)
    cu.record_producer (producer);

  /* Record line tables (only if C13 data exists).  */
  pdb_symbol_lines sym_lines;
  if (module->c13_byte_size > 0 && !stream_buf.empty ())
    {
      std::unordered_map<CORE_ADDR, pdb_prologue_end> prologue_ends;
      pdb_collect_prologue_ends (pdb, module, stream_buf.data (),
				 &prologue_ends);

      pdb_walk_c13_line_blocks (
	pdb, module, stream_buf.data (),
	[pdb, &cu, &prologue_ends, &sym_lines] (const char *filename,
						CV_LineSection line_sect,
						const gdb_byte *lines,
						uint32_t num_lines)
	  {
	    pdb_record_line_block (pdb, &cu, filename, line_sect, lines,
				   num_lines, prologue_ends, &sym_lines);
	  });

      pdb_emit_lines (pdb, &cu, &sym_lines);

      pdb_dbg_printf ("C13 line processing complete.");
    }

  /* Parse CodeView symbol records and collect function ranges.  */
  pdb_range_pair_vec func_ranges;
  if (!stream_buf.empty ())
    pdb_parse_symbols (pdb, module, stream_buf.data (), &cu, 0, &func_ranges,
		       lang, &sym_lines);

  /* The DBI module info records a single section contribution
     (sc_offset/sc_size), so high_pc above covers only that one fragment.
     Whenever a function gets its own section, that single contribution covers
     only the first function.  So we extend high_pc to the end of the highest
     function so the global block spans them all.  */
  for (const auto &range : func_ranges)
    high_pc = std::max (high_pc, range.second);

  /* Register function ranges on the static block so the CU-level scope
     covers all functions even when they are scattered at non-contiguous
     addresses.  */
  block *static_block = cu.end_compunit_symtab_get_static_block (high_pc,
								 false, true);

  std::vector<blockrange> rangevec;
  rangevec.reserve (func_ranges.size ());
  for (auto &range : func_ranges)
    rangevec.emplace_back (range.first, range.second);
  if (!rangevec.empty ())
    static_block->set_ranges (make_blockranges (pdb->objfile, rangevec));

  module->cu = cu.end_compunit_symtab_from_static_block (static_block, false);

  /* The subfiles now have symtabs, so each queued function can be filed
     under the source file its code actually came from.

     Its line is deliberately not set.  CodeView records no declaration
     line, and the only candidate, the first line-table entry at the entry
     PC, is the first executable line rather than the declaration.  Giving
     a function a line later than its declaration stops GDB advancing
     "break FILE:LINE" from a line with no code to the next one that has
     some (gdb.pdb/pdb-yaml-inline-xfile.exp).  */
  for (const auto &p : sym_lines.to_apply)
    if (p.subfile != nullptr && p.subfile->symtab != nullptr)
      {
	p.sym->set_symtab (p.subfile->symtab);
	if (p.with_line)
	  p.sym->set_line (p.line);
      }

  /* Print the finalized linetable.  */
  if (module->cu != nullptr)
    {
      for (const auto *stab : module->cu->filetabs ())
	{
	  const linetable *lt = stab->linetable ();
	  pdb_dbg_printf_v ("  symtab '%s': %d line entries",
			    stab->filename (), lt ? lt->nitems : 0);
	  if (lt != nullptr)
	    {
	      for (int i = 0; i < lt->nitems; i++)
		pdb_dbg_printf_v (
		  "    [%d] line=%d, pc=%s", i, lt->item[i].line,
		  paddress (pdb->objfile->arch (),
			    (CORE_ADDR) lt->item[i].unrelocated_pc ()));
	    }
	}
    }

  pdb_dbg_printf_v ("Module '%s' expanded: low_pc=%s high_pc=%s"
		    " sym size=%u c11 size=%u c13 size=%u",
		    cu_name, paddress (pdb->objfile->arch (), low_pc),
		    paddress (pdb->objfile->arch (), high_pc),
		    module->sym_byte_size, module->c11_byte_size,
		    module->c13_byte_size);

  return module->cu;
}

/* Expand all modules.  Called during initial PDB load in case lazy loading
   is not requested.  */

static void
pdb_expand_all_modules (pdb_per_objfile *pdb)
{
  using clock = std::chrono::steady_clock;
  auto start = clock::now ();

  /* Load global symbols from the SymRecordStream into a dedicated
     <pdb-globals> CU.  */
  pdb_load_global_syms_cu (pdb);

  unsigned int expanded = 0;
  for (auto &module : pdb->modules)
    {
      if (module.expanded)
	continue;
      pdb_build_module (pdb, &module);
      expanded++;
    }

  /* Register named TPI compound types as typedef symbols so that
     ptype/whatis can find them by name.  MSVC does not always emit
     S_UDT records for user-defined types.  Iterates every TPI record,
     resolves each compound type and creates a LOC_TYPEDEF/STRUCT_DOMAIN
     symbol.  */
  pdb_register_tpi_typedefs (pdb);

  double ms = std::chrono::duration<double, std::milli> (
		clock::now () - start).count ();
  pdb_dbg_printf ("expanded all %u/%zu modules in %.2f ms", expanded,
		  pdb->modules.size (), ms);
}

/* Load the PDB file for the given pdb context.  Validates the MSF magic, stores
   the file size in pdb->msf_size, saves the path, and opens a file handle for
   subsequent block reads.  The file handle is stored in pdb->pdb_file and
   remains open for the lifetime of the pdb_per_objfile.  */

static bool
pdb_load_pdb_file (pdb_per_objfile *pdb, const pdb_rsds_info &rsds)
{
  /* Find the PDB file on disk.  */
  std::string pdb_path = pdb_find_pdb_file (pdb->objfile, rsds);
  if (pdb_path.empty ())
    return false;

  /* Open the file.  Kept in a local until we've validated it; only then
     do we move ownership into pdb->pdb_file so failure paths don't need
     to manually reset the handle.  */
  gdb_file_up file = gdb_fopen_cloexec (pdb_path.c_str (), "rb");
  if (file == nullptr)
    return false;

  /* Validate magic.  */
  gdb_byte magic[PDB_MSF_MAGIC_SIZE];
  size_t nr = fread (magic, 1, PDB_MSF_MAGIC_SIZE, file.get ());
  if (nr < PDB_MSF_MAGIC_SIZE
      || memcmp (magic, PDB_MSF_MAGIC.data (), PDB_MSF_MAGIC_SIZE) != 0)
    pdb_error ("Bad MSF signature: %s", pdb_path.c_str ());

  /* Get file size.  */
  fseek (file.get (), 0, SEEK_END);
  long file_size = ftell (file.get ());

  if (file_size <= 0)
    {
      pdb_warning ("PDB file is empty: %s", pdb_path.c_str ());
      return false;
    }

  pdb_dbg_printf ("PDB file validated: %s (%lu bytes)", pdb_path.c_str (),
		  (unsigned long) file_size);

  pdb->pdb_file = std::move (file);
  pdb->pdb_file_path = std::move (pdb_path);
  pdb->msf_size = file_size;
  return true;
}

/* Process the File Info substream from the DBI stream.
   Create the Names Buffer and precompute module pointers into the Names Buffer.
   Layout:
     uint16_t  NumModules;
     uint16_t  NumSourceFiles;
     uint16_t  ModFileCounts[NumModules];             file count per module
     uint32_t  FileNameOffsets[Sum(ModFileCounts)];   offsets into NamesBuffer
     char      NamesBuffer[];                         filename strings.  */

static void
pdb_read_file_info_substream (pdb_per_objfile *pdb)
{
  if (pdb->dbi_data.empty ())
    pdb_error ("Can't read file info: DBI stream not loaded");

  gdb_byte *dbi = pdb->dbi_data.data ();

  uint32_t mod_info_size = read_u32 (dbi + DBI_HDR_MODULE_SIZE_OFFS);
  uint32_t sect_contrib_size = read_u32 (dbi + DBI_HDR_SECT_CONTRIB_OFFS);
  uint32_t sect_map_size = read_u32 (dbi + DBI_HDR_SECT_MAP_OFFS);
  uint32_t source_info_size = read_u32 (dbi + DBI_HDR_SOURCE_INFO_OFFS);

  uint32_t offset = DBI_HDR_SIZE + mod_info_size + sect_contrib_size
		    + sect_map_size;

  if (offset + source_info_size > pdb->dbi_data.size ())
    pdb_error ("File Info substream out of bounds");

  if (source_info_size < 4)
    pdb_error ("File Info substream too small");

  gdb_byte *fi = dbi + offset;
  const gdb_byte *fi_end = fi + source_info_size;

  /* Avoid repeated summation in each module by precomputing per-module
     file_name_offsets for each module.  */
  uint16_t fi_num_mods = read_u16 (fi + FILE_INFO_HDR_NUM_MODULES_OFFS);

  if (fi_num_mods != pdb->modules.size ())
    pdb_error ("File Info module count (%u), expected %zu", fi_num_mods,
	       pdb->modules.size ());

  gdb_byte *mod_file_counts = fi + FILE_INFO_MOD_INDICES_OFFS
			      + fi_num_mods * FILE_INFO_ELEMENT_SIZE;

  /* File count array must fit within the substream.  */
  if (mod_file_counts + fi_num_mods * FILE_INFO_ELEMENT_SIZE > fi_end)
    pdb_error ("File info substream too small");

  /* FileNameOffsets array starts after ModFileCounts.  */
  gdb_byte *offsets_base = mod_file_counts
			   + fi_num_mods * FILE_INFO_ELEMENT_SIZE;

  /* FileNameOffsets array doesn't have module boundaries explicitly marked.
     Thus, we iterate over the array based on ModFileCounts, find the boundaries
     and record the file name offsets for all the modules.  */
  uint32_t sum = 0;

  for (uint16_t i = 0; i < fi_num_mods; i++)
    {
      pdb->modules[i].file_name_offsets = offsets_base + sum * 4;
      uint16_t fc = read_u16 (mod_file_counts + i * FILE_INFO_ELEMENT_SIZE);
      pdb->modules[i].num_files = fc;
      /* Skip past this module's offsets.  */
      sum += fc;
    }

  /* Names Buffer follows FileNameOffsets and contains null-terminated
     filename strings.  A module naming no source file leaves the buffer
     empty, so it may start exactly at the end of the substream.  */
  gdb_byte *names_buf = offsets_base + sum * 4;
  if (names_buf > fi_end)
    pdb_error ("File info names buffer out of bounds");

  pdb->file_info_names_buffer = names_buf;
  pdb->file_info_names_buffer_size = static_cast<uint32_t> (fi_end
							    - names_buf);
}

/* Main entry point: PDB parsing starts by reading the MSF SuperBlock, which
   contains basic info about the file and location of the stream directory.
   Each stream spans multiple blocks that are not necessarily contiguous and the
   layout of every single stream is described in the  stream directory.
   Next, we parse the /names stream which contains the global string table.
   Then we continue with the DBI stream which contains the main debug info.
   From the DBI stream we get the list of modules and their associated source
   files, including the size of various debug information for each module.
   The actual debug info for a module is read on demand.  */

static pdb_per_objfile *
pdb_read_pdb_file (objfile *objfile, const pdb_rsds_info &rsds)
{
  if (objfile->flags & OBJF_READNEVER)
    {
      pdb_dbg_printf ("OBJF_READNEVER set");
      return nullptr;
    }

  gdb_assert (objfile->obfd != nullptr);

  /* Initialize PDB reader — create and register per_objfile.  */
  pdb_per_objfile *pdb = get_or_create_pdb_per_objfile (objfile);

  /* Validate PDB magic and record file size.  */
  if (!pdb_load_pdb_file (pdb, rsds))
    {
      pdb_load_diagnostic (objfile, "PDB file not loaded for %s",
			   bfd_get_filename (objfile->obfd.get ()));
      return nullptr;
    }

  /* Read MSF structure.  */
  if (!pdb_read_msf_header (pdb))
    pdb_error ("Failed to read MSF header");

  pdb_dbg_printf ("MSF header processing complete");

  if (!pdb_read_stream_directory (pdb))
    pdb_error ("Failed to read stream directory");

  pdb_dbg_printf ("Stream directory processing complete");

  /* Map the whole PDB read-only.  */
  if (!pdb_map_file (pdb))
    pdb_error ("Failed to map PDB file");

  /* Read & decode the PDB Info stream once; both GUID validation and the
     /names lookup consume it.  */
  pdb_info_stream info = pdb_read_info_stream (pdb);

  /* Validate PDB GUID/age against the EXE's RSDS record.  A mismatch means
     this PDB belongs to a different build, so loading is aborted.  */
  if (!pdb_validate_guid (pdb, rsds, info))
    return nullptr;

  /* Read the /names stream for global string table.  */
  if (!pdb_read_names_stream (pdb, info))
    pdb_warning ("/names stream not available. filenames may be incomplete. ");

  pdb_dbg_printf ("Names stream processing complete");

  /* Read DBI stream (contains modules and line info).  */
  pdb_read_dbi_stream (pdb);

  pdb_dbg_printf ("DBI stream processing complete");

  pdb_read_file_info_substream (pdb);

  pdb_dbg_printf ("File Info substream processing complete");

  /* Read and parse the TPI type stream — each type gets stored in the pdb
     but is not yet processed - its index is recorded so it'll be expanded
     and cached as soon as the symbol references it.  A missing or malformed
     TPI is fatal (pdb_error).  */
  pdb_read_tpi_stream (pdb);

  /* Read the IPI (id) stream.  Optional; provides inlinee names for
     S_INLINESITE.  Absence only disables inline-function naming.  */
  pdb_read_ipi_stream (pdb);

  /* Read section addresses from BFD for (section, offset) -> PC mapping.  */
  if (!pdb_read_section_addresses (pdb))
    {
      pdb_warning ("Failed to read sections from BFD");
      return nullptr;
    }

  pdb_dbg_printf ("BFD sections processing complete");

  /* Read and cache the symbol record stream.  */
  pdb_read_sym_record_stream (pdb);

  /* Build minimal symbols from S_PUB32 records in the public symbol stream.  */
  pdb_build_minsyms (pdb);

  printf_unfiltered ("\nUsing PDB file: %s\n", pdb->pdb_file_path.c_str ());
  return pdb;
}

/* With OBJF_READNOW the PDB reader expands all modules immediately.
   Below are minimal quick functions to support this use model.  */
struct pdb_readnow_functions : public quick_symbol_functions
{
  bool has_symbols (objfile *objfile) override
  {
    pdb_qf_printf ("has_symbols called");
    return true;
  }

  bool has_unexpanded_symtabs (objfile *objfile) override
  {
    pdb_qf_printf ("has_unexpanded_symtabs called");
    return false;
  }

  symtab *find_last_source_symtab (objfile *objfile) override
  {
    pdb_qf_printf ("find_last_source_symtab called");
    return nullptr;
  }

  void forget_cached_source_info (objfile *objfile) override
  {
    /* PDB has no internal file name cache.  Symtab fullname cleanup is handled
       by GDB generically.  */
  }

  enum language lookup_global_symbol_language (objfile *objfile,
					       const char *name,
					       domain_search_flags domain,
					       bool *symbol_found_p) override
  {
    pdb_qf_printf ("lookup_global_symbol_language called for '%s'", name);
    *symbol_found_p = false;
    return language_unknown;
  }

  void print_stats (objfile *objfile, bool print_bcache) override
  {
  }

  void dump (objfile *objfile) override
  {
  }

  void expand_all_symtabs (objfile *objfile) override
  {
    pdb_qf_printf ("expand_all_symtabs called");
  }

  iteration_status
  search (objfile *objfile, search_symtabs_file_matcher file_matcher,
	  const lookup_name_info *lookup_name,
	  search_symtabs_symbol_matcher symbol_matcher,
	  compunit_symtab_iteration_callback compunit_callback,
	  block_search_flags search_flags, domain_search_flags domain,
	  search_symtabs_lang_matcher lang_matcher = nullptr) override
  {
    (void) lookup_name;
    (void) symbol_matcher;
    (void) search_flags;
    (void) domain;
    (void) lang_matcher;

    if (compunit_callback == nullptr)
      return iteration_status::keep_going;

    for (compunit_symtab &cu : objfile->compunits ())
      {
	/* If a file matcher is supplied, check whether any filetab
	   in this compunit matches.  */
	if (file_matcher != nullptr)
	  {
	    bool match = false;
	    for (const symtab *s : cu.filetabs ())
	      {
		if (file_matcher (s->filename (), false)
		    || file_matcher (lbasename (s->filename ()), true))
		  {
		    match = true;
		    break;
		  }
	      }

	    if (!match)
	      continue;
	  }

	if (compunit_callback (&cu) == iteration_status::stop)
	  return iteration_status::stop;
      }

    return iteration_status::keep_going;
  }

  compunit_symtab *find_pc_sect_compunit_symtab (objfile *objfile,
						 bound_minimal_symbol msymbol,
						 CORE_ADDR pc,
						 obj_section *section,
						 int warn_if_readin) override
  {
    (void) msymbol;
    (void) section;
    (void) warn_if_readin;
    pdb_qf_printf ("find_pc_sect called for %s",
		   paddress (objfile->arch (), pc));

    /* Iterate PDB modules directly to find matching PC.  */
    pdb_per_objfile *pdb = pdb_objfile_data_key.get (objfile);
    if (pdb == nullptr)
      return nullptr;

    for (uint32_t i = 0; i < pdb->modules.size (); i++)
      {
	pdb_module_info *module = &pdb->modules[i];

	/* Skip unexpanded modules.  */
	if (module->cu == nullptr)
	  continue;

	const blockvector *bv = module->cu->blockvector ();
	if (bv == nullptr)
	  {
	    pdb_qf_printf ("find_pc_sect: module %d bv is null", i);
	    continue;
	  }

	const block *b = bv->global_block ();
	if (b != nullptr && b->start () <= pc && pc < b->end ())
	  {
	    pdb_qf_printf ("find_pc_sect: module %d matched [%s-%s]", i,
			   paddress (objfile->arch (), b->start ()),
			   paddress (objfile->arch (), b->end ()));
	    return module->cu;
	  }
      }

    pdb_qf_printf ("find_pc_sect: no match");
    return nullptr;
  }

  symbol *find_symbol_by_address (objfile *objfile, CORE_ADDR address) override
  {
    pdb_qf_printf ("find_symbol_by_address called for %s",
		   paddress (objfile->arch (), address));

    /* Readnow has expanded every module, so the built compunits hold the
       answer.  */
    for (compunit_symtab &cu : objfile->compunits ())
      {
	if (symbol *sym = cu.symbol_at_address (address))
	  return sym;
      }
    return nullptr;
  }

  void map_symbol_filenames (objfile *objfile, symbol_filename_listener fun,
			     bool need_fullname) override
  {
    pdb_qf_printf ("map_symbol_filenames called");
  }
};

/* See pdb.h.  */

bool
pdb_initialize_objfile (objfile *objfile)
{
  /* Only called for PE/COFF binaries from coffread.c  */
  gdb_assert (bfd_get_flavour (objfile->obfd.get ())
	      == bfd_target_coff_flavour);

  /* Check for RSDS (CodeView/PDB7) record.  */
  auto rsds = pdb_read_rsds_info (objfile->obfd.get (), objfile);
  if (!rsds)
    return false;

  pdb_per_objfile *pdb = pdb_read_pdb_file (objfile, *rsds);
  if (pdb == nullptr)
    {
      /* Drop the half-built reader state.  pdb_read_pdb_file registers the
	 pdb_per_objfile and records the candidate path before it can tell
	 whether the file is usable, so a rejected PDB would otherwise stay
	 attached to the objfile and be reported as loaded by
	 'maint info pdb-loaded-files' and the other maintenance commands --
	 naming the very file that was refused.  */
      pdb_objfile_data_key.clear (objfile);

      /* The RSDS named a PDB we could not use.  Report failure so
	 coff_symfile_read can fall back to DWARF, which a PE may carry
	 alongside the CodeView reference.  */
      return false;
    }

  /* Expand all modules eagerly.  */
  if (objfile->flags & OBJF_READNOW)
    {
      pdb_dbg_printf ("readnow requested");

      pdb_expand_all_modules (pdb);
      objfile->qf.emplace_front (new pdb_readnow_functions);
    }
  else
    {
      pdb_qf_printf ("lazy cooked-index requested");
      pdb_install_cooked_index (objfile, pdb);
    }

  return true;
}

/* Get module's file names from its precomputed file_name_offsets[] pointers
   into the global Names Buffer.  */

void
pdb_read_module_files (pdb_per_objfile *pdb, pdb_module_info *module)
{
  /* Already populated.  */
  if (module->files != nullptr)
    return;

  if (module->file_name_offsets == nullptr
      || pdb->file_info_names_buffer == nullptr)
    return;

  uint16_t file_count = module->num_files;
  if (file_count == 0)
    return;

  const gdb_byte *my_offsets = module->file_name_offsets;
  const gdb_byte *nb = pdb->file_info_names_buffer;
  uint32_t nb_size = pdb->file_info_names_buffer_size;

  module->files = OBSTACK_CALLOC (&pdb->objfile->objfile_obstack, file_count,
				  const char *);
  for (uint16_t i = 0; i < file_count; i++)
    {
      uint32_t name_offset = read_u32 (my_offsets + i * sizeof (uint32_t));
      if (name_offset < nb_size)
	module->files[i] = CSTR (nb + name_offset);
      else
	module->files[i] = nullptr;
    }
}

/* Resolve the i-th filename for a module from the cached files[] array.
   Returns nullptr if index is out of range or files not yet loaded.
   Caller must call pdb_read_module_files first.  */

const char *
pdb_module_file_name (pdb_per_objfile *pdb, const pdb_module_info *module,
		      uint32_t index)
{
  if (index >= module->num_files || module->files == nullptr)
    return nullptr;

  return module->files[index];
}

/* Parse module's DEBUG_S_FILECHKSMS.  Populates module->files_c13[] with
   filename pointers into the /names stream.  */

void
pdb_read_module_files_c13 (pdb_per_objfile *pdb, pdb_module_info *module)
{
  if (module->file_checksums == nullptr || module->file_checksums_size == 0)
    return;

  /* Skip if files already read.  */
  if (module->files_c13_read)
    return;
  module->files_c13_read = true;

  gdb_byte *p = module->file_checksums;
  const gdb_byte *end = p + module->file_checksums_size;

  /* Count the number of files.  */
  uint32_t count = 0;
  while (p + CV_FileChecksum::HDR_SIZE <= end)
    {
      uint8_t ck_size = CV_FileChecksum (p).checksum_size;
      p += CV_FileChecksum::HDR_SIZE + ck_size;
      p = align_up (p, 4);
      count++;
    }

  if (count == 0)
    return;

  /* Allocate file pointers.  */
  module->files_c13 = OBSTACK_CALLOC (&pdb->objfile->objfile_obstack, count,
				      pdb_file_info);

  p = module->file_checksums;
  while (p + CV_FileChecksum::HDR_SIZE <= end && module->num_files_c13 < count)
    {
      CV_FileChecksum ck (p);
      uint8_t ck_size = ck.checksum_size;

      auto fname = pdb_string_table_get (pdb->string_table,
					 pdb->string_table_size,
					 ck.file_name_offs);

      pdb_file_info *fi = &module->files_c13[module->num_files_c13++];
      fi->filename = fname;
      fi->checksum_type = ck.checksum_type;

      if (ck_size > 0 && p + CV_FileChecksum::HDR_SIZE + ck_size <= end)
	{
	  fi->checksum_size = ck_size;
	  fi->checksum = ck.checksum;
	}

      p += CV_FileChecksum::HDR_SIZE + ck_size;
      p = align_up (p, 4);
    }
}
} /* namespace pdb */

INIT_GDB_FILE (pdb_read)
{
  using namespace pdb;

  add_setshow_zuinteger_cmd (
    "pdb-read", no_class, &pdb_read_debug,
    _ ("Set debugging of the PDB reader."),
    _ ("Show debugging of the PDB reader."),
    _ ("When enabled (non-zero), debugging messages are printed during PDB "
       "reading and symtab expansion.  A value of 1 (one) provides basic "
       "information.  A value greater than 1 provides more verbose "
       "information."),
    nullptr, nullptr, &setdebuglist, &showdebuglist);

  add_setshow_zuinteger_cmd ("pdb-convert", no_class, &pdb_convert_debug, _ ("\
Set debugging of the PDB file name converter."),
			     _ ("\
Show debugging of the PDB file name converter."),
			     _ ("\
When enabled (non-zero), debugging messages are printed during PDB\n\
file name conversion.  A value of 1 (one) provides basic\n\
information.  A value greater than 1 provides more verbose information."),
			     nullptr, nullptr, &setdebuglist, &showdebuglist);

  add_setshow_zuinteger_cmd ("pdb-qf", no_class, &pdb_qf_debug, _ ("\
Set debugging of the PDB quick functions."),
			     _ ("\
Show debugging of the PDB quick functions."),
			     _ ("\
When enabled (non-zero), debugging messages are printed during PDB\n\
quick function processing.  A value of 1 (one) provides basic\n\
information.  A value greater than 1 provides more verbose information."),
			     nullptr, nullptr, &setdebuglist, &showdebuglist);

  /* Symbol name filter for targeted diagnostics in pdb_parse_symbols.  */
  static std::string pdb_sym_debug_name;
  add_setshow_string_noescape_cmd ("pdb-sym-name", no_class,
				   &pdb_sym_debug_name, _ ("\
Set symbol name filter for PDB symbol parsing diagnostics."),
				   _ ("\
Show symbol name filter for PDB symbol parsing diagnostics."),
				   _ ("\
When set, pdb_parse_symbols prints detailed info only for records\n\
whose name matches this string.  Example: set debug pdb-sym-name myglobalvar"),
				   nullptr, nullptr, &setdebuglist,
				   &showdebuglist);
}


#endif /* PDB_FORMAT_AVAILABLE */
