name: TheRock CI for rocgdb

on:
  push:
    branches:
      - amd-staging
      - amd-staging-rocgdb-*
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - amd-staging
      - amd-staging-rocgdb-*
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      BASE_REF: HEAD^
    outputs:
      enable_therock_ci: ${{ steps.configure.outputs.enable_therock_ci }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - name: "Configuring CI options"
        id: configure
        run: python .github/scripts/therock_configure_ci.py

  therock-ci-linux:
    name: TheRock CI Linux
    needs: setup
    if: ${{ needs.setup.outputs.enable_therock_ci == 'true' }}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        amdgpu_family: [gfx94X-dcgpu]
    uses: ./.github/workflows/therock-ci-linux.yml
    secrets: inherit
    with:
      amdgpu_families: ${{ matrix.amdgpu_family }}
      artifact_group: ${{ matrix.amdgpu_family }}
      extra_cmake_options: >
        -DTHEROCK_ENABLE_ALL=OFF 
        -DTHEROCK_BUILD_TESTING=ON 
        -DTHEROCK_ENABLE_DEBUG_TOOLS=ON
        -DTHEROCK_SHARED_PYTHON_EXECUTABLES=/opt/python-shared/cp310-cp310/bin/python3;/opt/python-shared/cp311-cp311/bin/python3;/opt/python-shared/cp312-cp312/bin/python3;/opt/python-shared/cp313-cp313/bin/python3;/opt/python-shared/cp314-cp314/bin/python3
        -DTHEROCK_DIST_PYTHON_EXECUTABLES=/opt/python/cp310-cp310/bin/python;/opt/python/cp311-cp311/bin/python;/opt/python/cp312-cp312/bin/python;/opt/python/cp313-cp313/bin/python
        -DTHEROCK_USE_EXTERNAL_ROCGDB=ON
        -DTHEROCK_ROCGDB_SOURCE_DIR=./rocgdb_under_test

  extended-test-check-read1:
    name: "--check-type check-read1"
    if: (success() || failure()) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'testing:extended')
    needs: extended-test-optimization
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/therock-test-packages.yml
    secrets: inherit
    with:
      amdgpu_families: gfx94X-dcgpu
      artifact_group: gfx94X-dcgpu
      test_runs_on: linux-gfx942-1gpu-ossci-rocm
      artifact_run_id: ${{ github.run_id }}
      test_options: "--check-type check-read1 --parallel"

  extended-test-check-readmore:
    name: "--check-type check-readmore"
    if: (success() || failure()) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'testing:extended')
    needs: extended-test-check-read1
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/therock-test-packages.yml
    secrets: inherit
    with:
      amdgpu_families: gfx94X-dcgpu
      artifact_group: gfx94X-dcgpu
      test_runs_on: linux-gfx942-1gpu-ossci-rocm
      artifact_run_id: ${{ github.run_id }}
      test_options: "--check-type check-readmore --parallel"

  extended-test-parallel:
    name: "--parallel"
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'testing:extended')
    needs: therock-ci-linux
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/therock-test-packages.yml
    secrets: inherit
    with:
      amdgpu_families: gfx94X-dcgpu
      artifact_group: gfx94X-dcgpu
      test_runs_on: linux-gfx942-1gpu-ossci-rocm
      artifact_run_id: ${{ github.run_id }}
      test_options: "--parallel"

  extended-test-hip-board:
    name: "hip board gdb.base/break.exp"
    if: (success() || failure()) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'testing:extended')
    needs: extended-test-check-readmore
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/therock-test-packages.yml
    secrets: inherit
    with:
      amdgpu_families: gfx94X-dcgpu
      artifact_group: gfx94X-dcgpu
      test_runs_on: linux-gfx942-1gpu-ossci-rocm
      artifact_run_id: ${{ github.run_id }}
      test_options: "--runtestflags=--target_board=hip --tests gdb.base/break.exp"

  extended-test-optimization:
    name: "--optimization=-O3"
    if: (success() || failure()) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'testing:extended')
    needs: extended-test-parallel
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/therock-test-packages.yml
    secrets: inherit
    with:
      amdgpu_families: gfx94X-dcgpu
      artifact_group: gfx94X-dcgpu
      test_runs_on: linux-gfx942-1gpu-ossci-rocm
      artifact_run_id: ${{ github.run_id }}
      test_options: "--optimization=-O3 --max-failed-retries=0 --parallel"

  therock_ci_summary:
    name: TheRock CI Summary
    if: always()
    needs:
      - setup
      - therock-ci-linux
      - extended-test-check-read1
      - extended-test-check-readmore
      - extended-test-parallel
      - extended-test-hip-board
      - extended-test-optimization
    runs-on: ubuntu-24.04
    steps:
      - name: Output failed jobs
        run: |
          echo '${{ toJson(needs) }}'
          FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
            | jq --raw-output \
            'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
          )"
          if [[ "${FAILED_JOBS}" != "" ]]; then
            echo "The following jobs failed: ${FAILED_JOBS}"
            exit 1
          fi
